### ISSUE TITLE
Unhandled exceptions getting User/Client information

### ISSUE THREAD

**Issue by jd2597** [Velocidex/velociraptor#1]
My instance seems to be having problems accessing information about Users/Clients and throws an exception:

C:\Users\Test\Desktop\velociraptor-master\velociraptor-master>velociraptor-v0.2.5-windows-4.0-386.exe artifacts collect Windows.Sys.Users
INFO:2018/11/15 14:19:56 Loaded 38 built in artifacts
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa8 pc=0x8ccaf6]

goroutine 109 [running]:
www.velocidex.com/golang/velociraptor/vendor/golang.org/x/sys/windows.UTF16ToString(0xa8, 0xffff, 0xffff, 0xffffffe1, 0x0)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vendor/golang.org/x/sys/windows/syscall_windows.go:86 +0x26
www.velocidex.com/golang/velociraptor/vql/windows.LPWSTRToString(0xa8, 0x8, 0x8)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vql/windows/win32_windows.go:142 +0x35
www.velocidex.com/golang/velociraptor/vql/windows.ParseUserRecord(0x17e30b8, 0x0)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vql/windows/users.go:46 +0x31
www.velocidex.com/golang/velociraptor/vql/windows.getUsers(0x14327440, 0x1437bb80, 0x1434aec0, 0x0, 0x0)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vql/windows/users.go:105 +0x8b
www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter.GenericListPlugin.Call.func1(0x1434aec0, 0xe2ff7d, 0x5, 0xe5fc48, 0x62, 0xe6b390, 0xe1adc0, 0x13c5e160, 0x0, 0x0, ...)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter/plugins.go:55 +0x52
created by www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter.GenericListPlugin.Call
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter/plugins.go:52 +0x66

C:\Users\Test\Desktop\velociraptor-master\velociraptor-master>velociraptor-v0.2.5-windows-4.0-386.exe --config client.conf.yaml client
INFO:2018/11/15 14:18:47 Starting Crypto for client C.8027220b60356ad8
INFO:2018/11/15 14:18:47 Starting HTTPCommunicator: [http://localhost:8000/]
INFO:2018/11/15 14:18:47 Received PEM for VelociraptorServer from http://localhost:8000/
INFO:2018/11/15 14:18:47 Receiver: Connected to http://localhost:8000/reader
INFO:2018/11/15 14:18:47 Enrolling
INFO:2018/11/15 14:18:48 Sender: Connected to http://localhost:8000/control
INFO:2018/11/15 14:18:48 Receiver: Connected to http://localhost:8000/reader
INFO:2018/11/15 14:18:48 Receiver: sent 706 bytes, response with status: 200 OK
INFO:2018/11/15 14:18:48 Received request: session_id:"aff4:/clients/C.8027220b60356ad8/flows/F.017b6347" request_id:1 name:"VQLClientAction" args:"\022P\nAselect Version.Name, Version.BuildTime, Client.Labels from config\022\013Client Info\022l\n]select Hostname, OS, Architecture, Platform, PlatformVersion, KernelVersion, Fqdn from info()\022\013System Info\022\232\001\n\211\001select ut_type, ut_id, ut_host as Host, ut_user as User, timestamp(epoch=ut_tv.tv_sec) as login_time from users() where ut_type =~ 'USER'\022\014Recent Users" source:"VelociraptorServer" auth_state:AUTHENTICATED args_rdf_name:"VQLCollectorArgs" task_id:1542245328154631 client_type:VELOCIRAPTOR
INFO:2018/11/15 14:18:48 Received request: session_id:"aff4:/clients/C.8027220b60356ad8/flows/F.Monitoring" request_id:1 name:"UpdateEventTable" args:"\n\267\001\022[\nYLET Generic_Client_Stats_0_0 = SELECT UnixNano FROM clock(period=atoi(string=Frequency))\n\022G\n&SELECT * FROM Generic_Client_Stats_0_0\022\035Artifact Generic.Client.Stats\032\017\n\tFrequency\022\00210\020\001" source:"VelociraptorServer" auth_state:AUTHENTICATED args_rdf_name:"VQLEventTable" task_id:1542245328154632 client_type:VELOCIRAPTOR
INFO:2018/11/15 14:18:48 Starting Artifact Generic.Client.Stats
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa8 pc=0x8ccaf6]

goroutine 88 [running]:
www.velocidex.com/golang/velociraptor/vendor/golang.org/x/sys/windows.UTF16ToString(0xa8, 0xffff, 0xffff, 0xffffffe1, 0x0)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vendor/golang.org/x/sys/windows/syscall_windows.go:86 +0x26
www.velocidex.com/golang/velociraptor/vql/windows.LPWSTRToString(0xa8, 0x8, 0x8)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vql/windows/win32_windows.go:142 +0x35
www.velocidex.com/golang/velociraptor/vql/windows.ParseUserRecord(0x1743d08, 0x0)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vql/windows/users.go:46 +0x31
www.velocidex.com/golang/velociraptor/vql/windows.getUsers(0x141d61b0, 0x141c25b0, 0x13c24d00, 0x0, 0x1)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vql/windows/users.go:105 +0x8b
www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter.GenericListPlugin.Call.func1(0x13c24d00, 0xe2ff7d, 0x5, 0xe5fc48, 0x62, 0xe6b390, 0xe1adc0, 0x13c5e160, 0x0, 0x0, ...)
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter/plugins.go:55 +0x52
created by www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter.GenericListPlugin.Call
        /ext-go/1/src/www.velocidex.com/golang/velociraptor/vendor/www.velocidex.com/golang/vfilter/plugins.go:52 +0x66
'

**Comment by scudette** [comment]
According to the api doc https://docs.microsoft.com/en-us/windows/desktop/api/lmaccess/nf-lmaccess-netuserenum the NetUserEnum function can return a null pointer when there is access denied to the user db. This might happen apparently on some AD configurations.

It is possible that the NetUserEnum API is not the best option - I was just going by what GRR uses. 

The other issue here is that the panic results in the client failing to properly communicate with the server and it can not complete enrollment.

**Comment by scudette** [comment]
I added a fix and made a new binary for testing https://github.com/Velocidex/velociraptor/releases/download/0.2.5/velociraptor-v0.2.6rc1-windows-4.0-amd64.exe

you should be able to replicate using the following command:
```
velociraptor.exe query "select * from users()"
```
