### ISSUE TITLE
Set specific output path for triage collection when using Velociraptor for offline collection

### ISSUE THREAD

**Issue by n3x77** [Velocidex/velociraptor#1002]
Hi, 

I'm not sure if this is a bug or if Its not the intended use case. 
We often use velociraptor as an offline collector for doing quick triages from systems, which works really great, thanks for providing this great capability. 

Normally we run the collection from cmd or powershell. In most cases the triage collection (zip-archive) is created in the current working directory. In some cases we want to write the collection to a specific network share or specific path. We tried to to this with the following command:

` .\Collector_velociraptor-v0.5.7-windows-amd64.exe artifacts collect Collector --output="C:\test.zip"`. 

After the collection is finished, the triage collection is stored in the current working directory. When I'm opening the `test.zip` file then I find a `Collector.json` file which holds the name of the triage package but not the actual data that we wanted to collect. 

Is this the intended use or is there another option for changing the output directory of the offline collector?

Cheers,
Sven

**Comment by scudette** [comment]
Currently the offline collector stores in the current directory and there is no way to control the file format. It is really designed to be a single click tool. 

Can you change directory first to where you need the file, then run the collector?

**Comment by n3x77** [comment]
Thanks @scudette for the clarification, that is totally fine, just wanted to know if the output parameter can be used for this. 

Of course changing the current directory can also be done within our scripts.
