### ISSUE TITLE
Consider support for importing password-protected zips from offline collector

### ISSUE THREAD

**Issue by chris-counteractive** [Velocidex/velociraptor#1026]
**Summary:** Currently if you add a password to offline collector zip files, `Server.Utils.ImportCollection` does not support importing those encrypted files directly.

**Details:** The offline collector wizard offers a conspicuous and useful option to provide a password to protect the zipped results.  Unfortunately, one cannot import those using `Server.Utils.ImportCollection` without first manually decrypting them and providing the path to the enclosed `data.zip` file (used as a security measure to prevent listing the files in the encrypted "wrapper" zip).  This workaround is usable, but having the import options symmetrical to the collector options seems like it's worth considering.

I'll follow this with a PR to clarify the language in `Server.Utils.ImportCollection`, which could be easily removed if this were selected for development.

Thanks!

**Comment by scudette** [comment]
When creating a password protected archive, we create a normal zip file and then embed it inside another zip file. So technically to import a password protected zip file all you have to do is extract the data.zip embedded file first, providing the password, then import that using the normal way.

**Comment by scudette** [comment]
This is now done transparently when using X509 based password encryption.
