### ISSUE TITLE
Feature Request: Disk/Free Disk Space on VR Dashboard by Default

### ISSUE THREAD

**Issue by eduardomcm** [Velocidex/velociraptor#1029]
Could we please have the Free Disk Space for the server as a default displaying field on the VR Dashboard? Would help preventing unwanted server crashes due to lack of disk space.

Below are sample implementations on Linux and Windows:

Windows:
![image](https://user-images.githubusercontent.com/49650494/115745620-9c0a2d80-a361-11eb-9a06-f064e453f07e.png)

Linux:
![image](https://user-images.githubusercontent.com/49650494/115745685-a88e8600-a361-11eb-98dd-c1776c2c3aa2.png)

**Comment by eduardomcm** [comment]
Pretty please? @mgreen27 @scudette 
Not sure if there's a way to bring the drive of the datastore automagically to that

**Comment by mgreen27** [comment]
I think this is a good idea. Everyone has hit disk free space issues at some stage. Maybe a cross platform plugin @scudette ?

**Comment by scudette** [comment]
The best approach is to write a cross platform artifact here. One issue is that there is no way for us to know which volume actually contains the file store because there could be symlinks etc. So maybe it's best to have that in the server metadata so users can change it for more complex scenarios.
