### ISSUE TITLE
Typo in Windows.Analysis.EvidenceOfExecution Artifact

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#103]
Noticed a typo in the aforementioned artifact:

`NumeberOfExecutions` => `NumberOfExecutions`

![image](https://user-images.githubusercontent.com/16829864/66173541-b022f880-e61e-11e9-8cec-35c87febd462.png)

**Comment by scudette** [comment]
Thanks for reporting. This should be fixed now.
