### ISSUE TITLE
Future development of the project

### ISSUE THREAD

**Issue by architect00** [Velocidex/velociraptor#1039]
Hi,

I read about the recent acquisition of the project by Rapid7 in the [news](https://www.healthcareinfosecurity.com/rapid7-acquires-open-source-community-project-velociraptor-a-16459).

Can you tell, what is going to change concerning the development and licensing of this project?

**Comment by scudette** [comment]
Nothing will change regarding the development or licensing - Velociraptor will remain an open source project and will remain community driven. The benefit is that it will now be supported by Rapid7 (i.e. promoted/funded etc). This will enable to project to grow and mature more quickly.

I wrote more about it here:

https://velociraptor.velocidex.com/the-next-phase-of-velociraptor-bf696c2c3491

**Comment by architect00** [comment]
Thank you for the rapid answer. I'm glad to hear, that is projects development is now backed by a bigger company without major changes to development or licensing.

I recommend a disclaimer in the README.md that reflects the new state of this project. Keeps people like me from asking about it in the future. 😅
