### ISSUE TITLE
parse_lines() seems to crash on very long lines

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#1051]
Im working on some malware analysis content and when building out some javascript malware detection I have noticed parse_lines() seems to crash on very long lines.

![image](https://user-images.githubusercontent.com/13081800/116938873-eb523700-ac5a-11eb-94cd-cb8926678589.png)

The results are all the lines up to the line in question which is around 80k characters with no further processing occurring.

read_file() allows parsing, it may be worthwhile to expose a max lines paramater inn parse_lines() and allow continued parsing of the file on failure.

**Comment by scudette** [comment]
An easy workaround here is to use parse_records_with_regex() instead. That plugin is also more robust and will skip very long lines (i think the size there is 40kb).

**Comment by mgreen27** [comment]
The workaround seems to work for my test js sample. I wonder if its something we would want to have configurable?
![image](https://user-images.githubusercontent.com/13081800/117253876-40e33b00-ae37-11eb-96db-8f86d394ab60.png)

**Comment by mgreen27** [comment]
Just looping back to this: it looks like large target lines like the one in my screenshot are truncated so my use case of further analysis on large lines is not possible (this sample was around 80k characters). Increasing or enabling configuration of the max lines would be a great feature, I will need to stick to yara for now.
