### ISSUE TITLE
Linux glob() circular symlinks

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#1052]
I have noticed some unexpected results in recursive (**) glob on linux systems.

Targeted glob works as expected but when targeting a recursive search - e.g **/*.ext there maybe an issue with circular symlinks.

**Comment by scudette** [comment]
This is now optional on Linux - we can turn off symlink following as required

```sql
SELECT FullPath FROM glob(globs="/proc/**", nosymlink=TRUE)
```
