### ISSUE TITLE
Windows.Detection.ProcessMemory.CobaltStrike  add c2 IP address column

### ISSUE THREAD

**Issue by 0xpwntester** [Velocidex/velociraptor#1056]
Can we make this Artifact show the C2 the malicious process is talking to if any. 
Thank you for this awesome work guys

**Comment by mgreen27** [comment]
This is kind of a generic yara for process rule so I was considering refactoring and then using the cobalt strike rule as the default. Maybe its worth adding a config extraction and other observables in too for a super cobalt artifact?

**Comment by 0xpwntester** [comment]
Yes that will be super awesome.
Thank you

**Comment by mgreen27** [comment]
I just submitted parser artifact https://github.com/Velocidex/velociraptor/pull/1172
I will create another enrichment artifact looping detection and other enrichment types soon.

**Comment by scudette** [comment]
is this ready to close now?

**Comment by mgreen27** [comment]
i think so.
