### ISSUE TITLE
Suggested updates for Windows.NTFS.I30 artifact

### ISSUE THREAD

**Issue by mpilking** [Velocidex/velociraptor#1069]
Hi, a few ideas for this artifact--

1. I would like to be able to recursively parse the directory structure and recover only the slack entries (IsSlack=True). It would be nice to have a checkbox option for that filter built into the existing artifact. I think most of the time we only care about the slack entries when looking at $I30. I realize this is easily doable with the notebook, but it would be nice to have it filtered from the start for data reduction purposes. (If it is a large directory structure that is parsed recursively, it takes a long time to run and pulls a lot of extraneous data.)
2. Recursing the directory structure is possible by adding `**` after the DirectoryGlobs path. I suggest adding this tip as part of the description for new users' benefit.
3. The description says it optionally collects the $I30 stream. I see that in the VQL, but don't see an option to do that in the artifact collection wizard. Perhaps I'm missing it, but shouldn't there be a checkbox for that?

Thanks!
Mike

**Comment by scudette** [comment]
This is now available in 0.6.0 RC1
