### ISSUE TITLE
API setup issues, required argument 'output' not provided

### ISSUE THREAD

**Issue by flyingmath776** [Velocidex/velociraptor#1074]
Good day, new to velociraptor and trying to setup the API. I am following the article https://velociraptor.velocidex.com/velociraptor-post-processing-with-jupyter-notebook-and-pandas-8a344d05ee8c and I am trying to setup my jupyter notebook to run VQL queries. 

The command:

$ velociraptor --config /etc/velociraptor/server.config.yaml config api_client --name Mathieu > /tmp/mathieu_api_client.yaml
velociraptor.bin: error: required argument 'output' not provided, try --help

I tried using:

$ velociraptor --config /etc/velociraptor/server.config.yaml user add Mathieu --role administrator

instead, but when I run the "SELECT * FROM info()" query as per the blog article, I get a JSONDecodeError: Expecting value: line 1 column 1 (char 0). I believe this is due to nothing being returned to the notebook, likely due to a connection to the server. I am running my notebook on the same ubuntu VM, so I have setup the binding to 0.0.0.0 and localhost.

If I run the client_example.py, it works fine for the same command. Was there a change in how the API is to be installed since the article was published?

Thanks!

Mathieu

**Comment by scudette** [comment]
The command has slightly changed since the blog post came out - you can see help about each command using the --help flag:
```
$ velociraptor config api_client -h
usage: velociraptor config api_client --name=NAME [<flags>] <output>
...
```

So something like this should work
```
$ velociraptor --config /etc/velociraptor/server.config.yaml user add Mathieu --role administrator api_config.yaml
```

**Comment by flyingmath776** [comment]
Great thank you! 

So I did setup my api_config.yaml and added it to the /etc/environment file.
```
velociraptor config api_client --name Mathieu api_config.yaml
velociraptor --config /etc/velociraptor/server.config.yaml user add Mathieu --role administrator api_config.yaml
velociraptor --config /etc/velociraptor/server.config.yaml acl grant Mathieu '{"all_query": true}'
```

Since I am on the same host, I used 127.0.0.1:8001 as the api_connection_string and listening on all interface.
If I run the client_example.py, works fine, but I still get nothing with velo_pandas.py

```JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

I am assuming this is due to the notebook not connecting to the server, but am not sure why client_example.py would work than.

**Comment by scudette** [comment]
When you grant the user a role it already grants the acls - your second statement reset the policy. You can see the policy using acl show command.

It looks like the panda function is trying to decode an empty string - it might be because it is not properly connection to the server. Is it able to access the api_config.yaml file? You can set the path to it in the VELOCIRAPTOR_API_CONFIG env variable which will allow pandas to pick it up.

**Comment by flyingmath776** [comment]
For the api.config.yaml, it can read it. Had to put a copy that was readable by a user other than velociraptor as I was getting permission denied in the /etc/velociraptor folder.

I tried doing curl http://192.168.245.145/server.pem to get the server key, but I am getting connection refused.

Is there a way to test the API connection other than server.pem? GUI is working fine from both computers and can see my 3 clients.
