### ISSUE TITLE
Support multi-tenanted deployments

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#1075]
In the conference last week I chatted with some users who would love to have a multi-tenanted deployment. This means:

1. An overarching GUI which includes access to all the tenants - See all hunts, view all clients from all tenants.
    * Hunts scheduled in the overarching GUI will automatically be scheduled for all the tenants.
    * Post processing on the hunts at the top level GUI will include all sub hunts in the tenants
2. Each tenant is more or less independently managed - add their own users, schedule their own hunts, etc. All without access to other tenants.

The main use case is an MSSP who wants to provide access to customers but still run managed hunts, detections etc.

The tenants need to be handled transparently as much as possible - i.e. if hunts are scheduled across tenants, then the VQL hunt_results() plugins should incorporate results from all tenants.

**Comment by jhjacobs81** [comment]
i agree with this!! :) 

i currently consider deploying a small vps for each client, but one big server would mean less maintenance :)
For us this means less staff costs, means less costs for the end customer :) 


would be even better if this also adds High Availabilty functionality :) just in case this one server goes down ;-)

**Comment by shiftnerd** [comment]
+1 on this

**Comment by scudette** [comment]
We are working on this feature for the next release cycle - probably around 0.6.6

**Comment by scudette** [comment]
This is now supported in head
