### ISSUE TITLE
Authenticode does not verify files signed via a catalog

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#1076]
On Windows many files are signed via a catalog file, this means that we need to verify the catalog file itself in order to verify the signature. This does not appear to be done automatically via the authenticode() function.

To verify this check any signatures of loaded drivers - by definitions they must all be signed but many appear untrusted.

**Comment by clayscode** [comment]
Noticed this a while ago. I could never quite figure out how to use Windows APIs to do this so I just dump the modules to powershell and run Get-AuthenticodeSignature.
