### ISSUE TITLE
Make fails to compile

### ISSUE THREAD

**Issue by mwilco03** [Velocidex/velociraptor#1081]
Make fails during compile looking for /v3. I assume it is in ref to this change possibly? 
https://github.com/gizak/termui/commit/0b52bac91f96c4530401f2882741d05876d3c1bc
Caveat I don't know go. So may be dumb statement.

**Comment by mwilco03** [comment]
Specific "Error: running 'go get github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6'"

**Comment by scudette** [comment]
You need to have go binary in your path. You also need to add the bin directory of the go install to your path (usually ~/go/bin)
