### ISSUE TITLE
Feature Request: Solaris Compiled Binary 

### ISSUE THREAD

**Issue by mwilco03** [Velocidex/velociraptor#1089]
There are options for Darwin, Linux, and Windows. 
Requesting a compiled bin / source option for Solaris compilation.

**Comment by scudette** [comment]
I have personally haven't come across a Solaris machine in almost 15 years.

This https://www.datanyze.com/market-share/operating-systems--443/oracle-solaris-market-share suggests that Solaris market share is 0.04% so it is insignificant.

It looks like golang kind of supports Solaris on an amd64 platform, I guess it could work if you set the GOOS variable to Solaris in makefile.go

https://golang.org/doc/install/source#environment

Realistically we are not going to work on this but I'm happy to accept a PR :-)

**Comment by mwilco03** [comment]
appreciate it if I make head way I'll update tyvm 👍
