### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by jrn77478** [Velocidex/velociraptor#1091]
Trying to test Velociraptor (v0.5.3-linux-amd64) on CentOS 7, using self-signed certs...

I had it working, briefly, including connecting to clients, but now, once past the auth dialog, I get only "404 page not found". 
Any ideas?

**Comment by scudette** [comment]
make sure you are connecting to the GUI port with the browser not the frontend (by default https://XXX:8889/)

**Comment by jrn77478** [comment]
Hmm... Nope. The GUI was binding to 127.0.0.1. Not sure why. I've edited the server.config.yaml and all seems well now.

**Comment by scudette** [comment]
This is the default when using self signed ssl - you dont want to expose an insecure gui to the world. You should use ssh tunneling or whitelist by ip to limit exposure to the browser.

**Comment by jrn77478** [comment]
Agreed. That's a good default state. I just missed it. FWIW, we're running
on an internal network, using a non-publc DNS zone.
