### ISSUE TITLE
support checking for GDPR compliancy (check gdpr artifact built in)

### ISSUE THREAD

**Issue by jhjacobs81** [Velocidex/velociraptor#1093]
Hello,

Based on this YML file from Wazuh we have several reg keys that relate to GDPR "thingy's" if they all pass the endpoint is 100% compliant, if half passes the endpoint is 50% GDPR compliant, etc.

The file sca_win_audit.txt is what we think would be suitable for small clients, the sca_win_audit_full.txt is what Wazuh ships by default 
[sca_win_audit_full.txt](https://github.com/Velocidex/velociraptor/files/6597721/sca_win_audit_full.txt)

[sca_win_audit.txt](https://github.com/Velocidex/velociraptor/files/6597712/sca_win_audit.txt)

**Comment by scudette** [comment]
This issue is now handled in the audit project here
https://github.com/Velocidex/Audit
