### ISSUE TITLE
Notebook Cell Suggestions

### ISSUE THREAD

**Issue by clayscode** [Velocidex/velociraptor#1124]
I think a number of improvements can be made to markdown cells and just the notebook cells in general. 
1) Make it so you can easily read markdown cell output into VQL 

I know that this is possible by just reading the file, but it would be nice for the "create cell from cell" button to support markdown as well instead of just outputting an empty table. There are a number of use cases for this, including filtering hunt results based on lists, writing artifact parameters, parsing copy/pasted data, etc. 

2) Better tab completion/table editing

In Emacs org mode, there are a lot of commands as well as really good autocompletion for doing things like adding table cells, adding rows, re-ordering rows, etc. I'm not suggesting re-implement all of this because I know that's no easy feat, but just better table editing in general would make markdown tables much more useful. Stuff like if you add a column, it automatically fills in the rest of the rows with empty cells. Perhaps there's also an off-the-shelf markdown table editor out there that could aid this.

3) Live updating markdown output

This one isn't super important, but it would be a nice plus to have live updating output to get immediate feedback on whether or not your markdown is correct. 

4) Add Starlark/JS as supported cell types

This one is fairly trivial to implement, but it would be nice to be able to select Python or JS from the dropdown menus for editing code since Velociraptor supports both of these languages. It's already possible to chose Python or JS as a target in the Ace editor settings, but this should be permanent so your settings don't get reset every time you click away from the cell. 

5) Enable fullscreening on notebooks

It would be nice to be able to fullscreen a notebook to move the notebook list, hunt list, etc, out of the way to just focus on the notebook. I've already worked out an implementation for this and will submit a PR whenever I finish cleaning up testing and cleaning up my code.

**Comment by scudette** [comment]
Full screen is not available in 0.6.1

**Comment by scudette** [comment]
Closing this due to in being too old.
