### ISSUE TITLE
Re-Execution of Timed-Out Clients In Hunts

### ISSUE THREAD

**Issue by eduardomcm** [Velocidex/velociraptor#1135]
When running a hunt, if you have **ERROR**'ed clients due to **Time Out**, it would be great to **be able to re-execute just for the error'ed ones**, **under the same HuntID** - **with longer timeout** - so that when manipulating the results in Notebook you can find everything in one place.

**Comment by randomaccess3** [comment]
Ideally there would be a few cells in this tab of the hunt. One for each status so that you can quickly see (and query) which are finished, running, not started, errors/timeout etc

**Comment by scudette** [comment]
This is now possible through the GUI:
1. Find the machine which didnt work
2. Copy the flow in the GUI , edit whatever is needed (including timeout or maybe parameters etc)
3. Click the "add manually to hunt" to add the flow to the hunt manually.
