### ISSUE TITLE
API Client Example Issue

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#114]
Hello,

I was testing communication with the Velociraptor API, and was wondering if the following was deprecated, or required an update?

https://github.com/Velocidex/velociraptor/blob/master/bindings/python/client_example.py

Or is there something I am missing?  I am attempting to test using my client config like so:

`sudo python client_example.py api_client.conf.yaml '" SELECT * from info() "'`

...and get the following error:

````
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed"
        debug_error_string = "{"created":"@1570495928.561686551","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1570495928.561675547","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":263,"referenced_errors":[{"created":"@1570495928.561671582","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":357,"grpc_status":14,"referenced_errors":[{"created":"@1570495928.561497694","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":244,"referenced_errors":[{"created":"@1570495928.561486425","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":244}]}]}]}]}"
````

I've checked my local hosts file, etc, and I can contact the server host and via port (8001) using curl, etc.  Additionally, bindings are for `0.0.0.0` on the server side in the server config.

Any advice would be awesome.  Thanks!

**Comment by weslambert** [comment]
Okay, so looks I missed the `--name` when exporting the client config.  Looks like the example is documented a little bit differently than the README:

https://github.com/Velocidex/velociraptor/blob/master/bindings/python/client_example.py#L45

vs.

https://github.com/Velocidex/velociraptor/blob/master/bindings/python/README.txt#L48

Thanks!

**Comment by scudette** [comment]
Couple of notes:
1. you do not need to run the client program as root - it just connects using the config file.
2. The error you get is DNS resolution failed - this means the client code tried to connect to the endpoint described in the api_config.yaml but could not resolve it - make sure the dns name is unreachable. You can use an ip address only if you are using self signing mode.
3. The --name flag sets the common name in the cert that is generated. We use to log access in the authentication log. It is only used to make sure we can track what each client program is doing by relating the name of the cert with the VQL it ran.  We do not have a way to revoke certs yet so ACLs are pretty rudimentary right now :-(.

**Comment by weslambert** [comment]
Thanks @scudette!  I tried the IP as well, but still received the DNS resolution error, regardless.  It was not until I used the `--name` flag that it worked (even for the IP).

**Comment by weslambert** [comment]
I just compared the two again (with and without `--name`), with direct IP comm, and the one with `--name` works while the other does config not.   Additionally, the one with `--name` works with both hostname and IP.

**Comment by scudette** [comment]
I can not replicate it - the --name flag just set the common name in the cert:
```
$ velociraptor --config ~/server.config.yaml config api_client --name MySpecialName > ~/api_client2.yaml
$ velociraptor --config ~/server.config.yaml config api_client > ~/api_client.yaml
```

Simply changes the name in the config:
```
api_connection_string: 127.0.0.1:8001
name: VelociraptorAPIClient
```

And
```
api_connection_string: 127.0.0.1:8001
name: MySpecialName
```

And both worth

**Comment by weslambert** [comment]
It was an error on my part, in one of the config files.  Thanks again for all your help, and work on Velociraptor!
