### ISSUE TITLE
Force client re enroll

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#1143]
Sometimes during a deployment the write back file is copied into a VM image by accident.

This results in many clients attempting to connect with the same client id. Velociraptor will refuse to connect to more than one client with the same id and will have a conflict message in the log.

We need a way to black list a client id so it can be forced to re enroll and get a new client id.

We also need an artifact that this can be done manually, but a built in method is preferable.

**Comment by 5k33tz** [comment]
Initial tests with the artifact below have desired results:

To-do:
- [ ] Selectively run based on client id

```
required_permissions:
  - EXECVE

precondition:
  SELECT OS From info() where OS = 'windows'

parameters:
  - name: DeleteWriteback
    default: "Remove-Item -Path 'C:/Program Files/Velociraptor/velociraptor.writeback.yaml' -Force"
  - name: RestartService
    default: "Restart-Service -Name velociraptor -Force"

sources:
  - query: |
      SELECT * FROM execve(argv=["powershell",
        "-ExecutionPolicy", "Unrestricted", "-encodedCommand",
        base64encode(string=utf16_encode(string=DeleteWriteback))
      ])
  - query: |
      SELECT * FROM execve(argv=["powershell",
        "-ExecutionPolicy", "Unrestricted", "-encodedCommand",
        base64encode(string=utf16_encode(string=RestartService))
      ])

**Comment by scudette** [comment]
This solution is probably the best we can do. This artifact needs to be run periodically many times since as new clients join, they will receive the artifact and upgrade allowing the next client to join etc.

**Comment by scudette** [comment]
This is now implemented by the `Server.Monitor.ClientConflict` artifact
