### ISSUE TITLE
GROUP BY Case insensitive please

### ISSUE THREAD

**Issue by Purp1eW0lf** [Velocidex/velociraptor#1174]
Would you kindly be able to add case insensitivity to GROUP BY please?

I appreciate that in 'nix systems case is important. However GROUP BY seperates out too much Windows hunts, as even though the same thing is occuring because it has different case, GROUP BY treats them as unique.

I have attached an IRL example:

![image](https://user-images.githubusercontent.com/44196051/128013445-d2266327-8e81-46d2-979e-bcbd0236863d.png)

Take care,
Dray

**Comment by scudette** [comment]
You can easily group by a case insensitive field by simply using the lowcase() function (see https://docs.velociraptor.app/vql_reference/basic/#lowcase) - so:

```sql
SELECT ....
WHERE ....
GROUP BY lowcase(string=FullPath)
```

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/128014931-abfc19a1-c723-4a1a-97a9-c127c7ea4b1a.png)

You can similarly use any expression that you want to form the groups - for example grouping by two fields (GROUP BY A, B) will separate the rows into groups with both fields being the same value.

**Comment by Purp1eW0lf** [comment]
Thanks Dr Cohen, Today I learned.

Closing Issue.
