### ISSUE TITLE
Export plugin for Elasticsearch/Graylog

### ISSUE THREAD

**Issue by ion-storm** [Velocidex/velociraptor#12]
Nice tool! Would love to be able to auto-export artifacts retrieved from hosts via Gelf/Syslog, let me know if you'd be interested in adding this.  It would be badass to be able to show this data up on some fancy dashboards in Graylog or Grafana.

**Comment by scudette** [comment]
Looks doable - there is this library https://github.com/Graylog2/go-gelf but it is not clear to me what the upstream source is (it seemed to be forked from somewhere else).

I think there is natural place to put the row data in the extra field:
https://github.com/Graylog2/go-gelf/blob/v1/gelf/writer.go#L58

**Comment by scudette** [comment]
This is probably best done via the API

**Comment by ion-storm** [comment]
Another idea that some tools use is write to the eventlog that works can utilize, can you output to eventlog via json?

**Comment by ion-storm** [comment]
Even a flat log file written in json per line would work with filebeat for graylog and elasticsearch
