### ISSUE TITLE
Consider adding a --definitions equivalent to the config

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#1201]
For the FileBasedDatastore the `artifact_definitions` are located relative to the `filestore_directory` server config setting. The `filestore_directory` setting is not available when using other datastore types (of which there may be more in future).

When using datastores other than FileBasedDatastore the artifact_definitions folder can still be defined using the command line --definitions switch, but when run as a service that would require editing the service definition file.

Allowing the `artifact_definitions` folder location to be specified in the config would make switching to other non-file-based datastores easier.

**Comment by scudette** [comment]
Fixed in 0.6.1
