### ISSUE TITLE
Feature Request: Hash Collection zip output file from Offline Triage Collector

### ISSUE THREAD

**Issue by CdtDelta** [Velocidex/velociraptor#1208]
For the offline collector, could we add the ability to generate a hash on the output zip file that is created by the Server.Utils.CreateCollector artifact? Then the hash value would be added to the exe.log file that's created when the triage program runs. Ideally if you could choose the hash value to create during the creation process (MD5, SHA1, SHA256, etc) that would be great, but otherwise just create a SHA256 hash.
This way when the output files are transferred to other users/systems/etc there's a method to verify that the zip file is still valid.

**Comment by scudette** [comment]
Implemented in #1458
