### ISSUE TITLE
Server Service privilege reduction

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#124]
As discussed: I would like us to consider running the Velociraptor service with lower privileges from a standard user account.
It was discovered we could still configure TLS binding with the comand: 
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/velociraptor

This enables me to run the server as a specific user:
![image](https://user-images.githubusercontent.com/13081800/66811759-2e39a600-ef21-11e9-8d7f-12a8d0f930bf.png)

**Comment by mgreen27** [comment]
this works but there is still an error reported with setting the file descriptor limit
![image](https://user-images.githubusercontent.com/13081800/66812048-abfdb180-ef21-11e9-8fbc-1254575d8d47.png)

**Comment by scudette** [comment]
This suggest that its just another capability
http://man7.org/linux/man-pages/man7/capabilities.7.html

```
CAP_SYS_RESOURCE
              * Use reserved space on ext2 filesystems;
              * make ioctl(2) calls controlling ext3 journaling;
              * override disk quota limits;
              * increase resource limits (see setrlimit(2));
              * override RLIMIT_NPROC resource limit;
              * override maximum number of consoles on console allocation;
              * override maximum number of keymaps;
              * allow more than 64hz interrupts from the real-time clock;
              * raise msg_qbytes limit for a System V message queue above
                the limit in /proc/sys/kernel/msgmnb (see msgop(2) and
                msgctl(2));
              * allow the RLIMIT_NOFILE resource limit on the number of "in-
                flight" file descriptors to be bypassed when passing file
                descriptors to another process via a UNIX domain socket (see
                unix(7));
              * override the /proc/sys/fs/pipe-size-max limit when setting
                the capacity of a pipe using the F_SETPIPE_SZ fcntl(2)
                command.
              * use F_SETPIPE_SZ to increase the capacity of a pipe above
                the limit specified by /proc/sys/fs/pipe-max-size;
              * override /proc/sys/fs/mqueue/queues_max limit when creating
                POSIX message queues (see mq_overview(7));
              * employ the prctl(2) PR_SET_MM operation;
              * set /proc/[pid]/oom_score_adj to a value lower than the
                value last set by a process with CAP_SYS_RESOURCE.
```

**Comment by mgreen27** [comment]
Looks like setting individual CAPs overwrites the last entry.
We need to run:
_sudo setcap CAP_SYS_RESOURCE,CAP_NET_BIND_SERVICE=+eip /usr/local/bin/velociraptor_

![image](https://user-images.githubusercontent.com/13081800/66813904-30056880-ef25-11e9-979d-f670022ed516.png)

**Comment by scudette** [comment]
Can you please test the PR using the CI build?

**Comment by mgreen27** [comment]
Looks like the deb build is working as expected from version:
name: velociraptor
version: 0.3.5
commit: 018c38f
build_time: "2019-10-17T05:36:44Z"
