### ISSUE TITLE
Add default server monitoring artifacts to the config

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#1246]
The config currently allows us to specify `default_client_monitoring_artifacts`. It would be nice to have a similar setting for `default_server_monitoring_artifacts` so that these do not need to be manually configured via the GUI.

Default server monitoring artifacts would allow us to pre-configure server-side alerting and maintenance artifacts, for example filestore cleanups or scheduled updates of the inventory.

**Comment by scudette** [comment]
Fixed in #1247
