### ISSUE TITLE
Missing ARM builds?

### ISSUE THREAD

**Issue by vysecurity** [Velocidex/velociraptor#1253]
Missing ARM Linux builds? FYI?

**Comment by scudette** [comment]
We dont normally ship linux arm builds in the releases page (but we started to ship M1 arm build now). 

You can build arm binaries from source very easily using:

```
go run make.go -v arm
```

From the top level directory. You do not need to actually build those on an ARM system itself - the binary will be cross compiled for linux arm (e.g. a Raspberry PI). So build on your workstation and just run on the PI.

Currently modules that require a C compiler will not be built in this mode so things like yara and sqlite will not be available. If you want to have those you need to build on an actual PI and change the target is magefile.go to not disable cgo.
