### ISSUE TITLE
Allow directly pivoting from artifact to collection

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#1255]
It would be nice if there was a button/way to go directly from an artifact to the appropriate screen for collection.

For example:

`client artifact` -> Hunt
`client artifact` -> Client-specific collection (if client already selected)
`client monitoring artifact` -> Client monitoring table
`server monitoring artifact` -> Server monitoring table

**Comment by scudette** [comment]
Implemented in #1457
