### ISSUE TITLE
Allow URLs to be clickable in columns for results

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#1256]
It would be nice to have a URL renderer for the GUI to allow results/rows with URLs to be clickable, as opposed to requiring the user to copy/paste URLs.

**Comment by predictiple** [comment]
That could be a security risk though.

**Comment by scudette** [comment]
Yeah we might need to do something like a dialog warning users and open in new tab

**Comment by predictiple** [comment]
Although isn't this rendering hint controllable via the columns key in artifacts in general? So if you write an artifact and you're sure a particular column is going to contain only safe URIs then maybe it is ok to make it clickable via a column spec.

**Comment by scudette** [comment]
Yes perhaps we need two variants one that has a dialog and one that is safe to open. In either case we should open the link in a new tab

**Comment by predictiple** [comment]
And 3rd variant too: one to _not_ hyperlink the URI, although that should remain the default.

**Comment by scudette** [comment]
Well if the Artifact writer does not want to render a column as a url then they don't specify it as a url type :-)

Similarly in the notebook

**Comment by predictiple** [comment]
Yes, that places the risk responsibility on the artifact author rather than Veloci.

**Comment by weslambert** [comment]
Agreed, the intent would basically be choose to format the column as a URL type when you are writing the artifact.  This would help for things like reference URLs or lookup results, as opposed to results of an artifact gathering potentially unsafe URLs and allowing them to be clickable.

**Comment by weslambert** [comment]
🥳
