### ISSUE TITLE
SFTP offline collector

### ISSUE THREAD

**Issue by lordrgie** [Velocidex/velociraptor#1267]
I'm trying to use the sftp upload option of the offline collector, but I can't get it to work. When I run the .exe, I always get this error: "upload_SFTP: ssh: no key found".
When I create the binary, in the private key field, I use rsa private key from the server. 
I tried to look for an example of usage in the documentation but I can't find anything. 

Context:
Server : ubuntu 18.04
Machine where I run the ".exe": Windows 10

**Comment by scudette** [comment]
This is now extensively documented here https://docs.velociraptor.app/blog/2021/2021-12-11-sftp-in-aws/
