### ISSUE TITLE
Velociraptor Systemd service hits open file limits

### ISSUE THREAD

**Issue by fbausch** [Velocidex/velociraptor#1273]
Recently, I deployed Velociraptor for a larger number of clients. On the Ubuntu Velociraptor server, I created a Systemd service to start/stop Velo automatically on startup/shutdown.

I came across the following behavior: When a certain number of clients connected to the server, the Velo process could not open any new files because the open file limit was hit. By changing `sysctl.conf` or `limits.conf`, this behavior could not be changed. However, by setting the `DefaultLimitNOFILE` value in `/etc/systemd/system.conf` I could resolve the issue, e.g.:

`DefaultLimitNOFILE=524288:1048576`

I know, that this is not an issue with Velociraptor itself, but I wanted to mention it here so that others may find the solution if they experience the same issue.

Another solution is, obviously, not to use the file based datastore for larger number of clients.

**Comment by scudette** [comment]
Velociraptor actually increases its own file limit here https://github.com/Velocidex/velociraptor/blob/20a9e63876712a27e876d47cf51ee699832608d1/server/limits_linux.go#L54

You should see a log message to this effect when it starts up. Normally when we install as a deb we run as a non root user so the deb needs to give the binary the right capability so it may increase its limit 

https://github.com/Velocidex/velociraptor/blob/20a9e63876712a27e876d47cf51ee699832608d1/bin/debian.go#L215

It may be that your system as a very low hard limit which means even root can not increase past it so the limit is not ending up being properly increased.

**Comment by fbausch** [comment]
Thank you for the info about the capabilities. I think, I found a nice solution.
The thing is, we let the velo server run under a non-root user via systemd. In systemd you can control the capabilities that the systemd service is able to get:

```ini
[Unit]
Description=Velociraptor Server

[Service]
Type=simple
User=velociraptor
Group=velociraptor
ExecStart=/usr/local/bin/velociraptor --config <pathtoconfig> frontend -v
CapabilityBoundingSet=CAP_SYS_RESOURCE CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_SYS_RESOURCE CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```
Afterwards, the velo binary is able to set the limits itself (according to the log file).
`CapabilityBoundingSet` lists the caps that may be used by the binary, no other caps can be used by the binary.
`AmbientCapabilities` lists the caps that are given to the binary.

**Comment by scudette** [comment]
Nice! this way is probably easier than setting the capabilities on the binary itself. We should include it in the standard deb builder.
