### ISSUE TITLE
GUI: Server Events page only shows Raw Data after artifact reload

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#1276]
With custom server event artifacts the Raw Data screen is blank until the relevant artifact is removed from the server monitoring table and then re-added. The initial adding to the server monitoring table was done in the normal way through the GUI (i.e. not loaded via the server config).

The Logs screen shows data without any intervention, and this shows that the loaded artifact is working as expected. It's just that the GUI is not displaying the "raw data".

Reliably reproducible on my system:

version: 0.6.1
commit: 20a9e63
build_time: "2021-09-14T12:44:17Z"

**Comment by scudette** [comment]
Is this just a GUI issue? If you navigate away from the client events screen and navigate back do you see the new events?

**Comment by predictiple** [comment]
Well it's an issue that affects the GUI. No amount of clicking and navigating back and forth will get it to show the data. Only removing the artifact and re-adding it to the monitoring table works.

**Comment by predictiple** [comment]
It might have something to do with the length of the result set. My monitoring artifact produces result sets with only 1 or 2 rows. So maybe there's a minimum length for auto-showing the data. But again the remove/re-add gets it to show the 1 or 2 record result sets.

**Comment by scudette** [comment]
It might also have to do with the fact that the client buffers rows to send for 100 sec by default. 

If you reissue the artifact it forces the buffer to be flushed immediately when the Artifacts are refreshed.

If you wait a few minutes do you get some more events?

**Comment by predictiple** [comment]
I think that might be it. Once or twice events did appear unexpectedly after I had been distracted for a few minutes. I wasn't sure if I was imagining it.

I will test further once the competition is over and report back.

**Comment by scudette** [comment]
Certainly if you can see log messages appear immediately then the query is actually started on the client. Log messages are not buffered.

**Comment by predictiple** [comment]
Yeah the moitoring artifact is working. But it's hard to distinguish between a blank page and a zero result set. Eventually I put the results into the logging and then I realised it was working all along :sweat:

**Comment by scudette** [comment]
I guess as a habit it is always worth checking the query logs and they should show the artifact is started. 

Just checked the code and the buffering is for 120 sec +/- 20 sec (we need a bit of jitter so the clients don't synchronise and overload the server).

https://github.com/Velocidex/velociraptor/blob/686a2a6833ffafb242f744d890c48fdc8ab0969a/services/client_monitoring/client_monitoring.go#L287-L292

I originally planned to have this setting in the resource control but i think a lot of people would set it to be really low (say 1 sec) because they want to see events immediately, not realising this has a huge negative effect on performance. So it is actually not settable at the moment.

**Comment by predictiple** [comment]
I've tried waiting about 10 minutes and still nothing shows up. Using the top dropdowns to switch between mode and artifacts does not cause the data to show. Even navigating navigating to a different part of the GUI and coming back makes no difference.

Doing an update on the monitoring table seems to be the only way to get the data to show up.

You should be able to reproduce this with my competition artifacts. The `DispatchTriage` one should show a 1 row result after you run `Custom.Client.FindByMagics` and point it to a folder containing some evtx.
![Screenshot from 2021-09-21 13-57-09](https://user-images.githubusercontent.com/9843422/134166650-cb22da02-8603-41a9-8381-4d69c7d9e42b.png)

It's strange that the default monitoring artifacts show their data right away.

**Comment by scudette** [comment]
I think this should be fixed in 0.6.4 - the server monitoring table was not reloaded whan an artifact was modified.
