### ISSUE TITLE
Timestamp picker shuffles input

### ISSUE THREAD

**Issue by architect00** [Velocidex/velociraptor#1291]
Hi,

Velociraptor 0.6.1
Windows 2012 R2
Chrome 93.0.4577.82

**Actual Behavior**
On configuration of an artifact and using the timestamp picker (e.g. on Windows.Timeline.MFT - DateBefore, DateAfter) the selected input gets reset / jumps to random selections. This seems to happen if we manually change the time. The input is somehow shuffled. To get 23:00 we need to type "12:00".

This problem is experienced on all artifacts with a timestamp picker GUI.

![Screen Recording 2021-09-28 at 10 55 37](https://user-images.githubusercontent.com/50401024/135056769-60b7c00c-8794-4881-b77f-b9ec91ba6d2b.gif)

This problem exists after the switch from 0.6.0 to 0.6.0.

**Expected Behavior**

Timestamp picker reflects the selected date and time.

**Comment by mgreen27** [comment]
Thank you for reporting.

This issue appears to be related to local time and UTC. Changing time view of the selector to local, then changing the time things appear to work as expected.

**Comment by architect00** [comment]
Yes, this is correct. I was not aware that the timezone could be changed by clicking on it.

We can confirm:

 - Changing the timezone to local time in the GUI fixes the problem.
 - Changing the computers timezone to UTC without changing the GUI timezone also fixes the problem.

Thanks for the fast resolution.

**Comment by mgreen27** [comment]
I still think this is worthwhile raising as you would expect to select time in UTC too. Most of my analysis is in UTC so I think its important.

**Comment by Zawadidone** [comment]
Can this issue be reopened this is still an issue in version 0.6.1? If a fix is possible I would like to contribute.
