### ISSUE TITLE
Windows.Collectors.VSS artifact error

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#130]
Version 0.3.5

Creating a collection with the abovementioned artifact using default or any other settings results in the GUI error:
```While parsing source query 3: adowCopy' |AND : <source>:4:36: unexpected token "AND"```

Flows log reports:

```
"vql: scope.go:315: Artifact Windows.Collectors.VSS invalid: While parsing source query 3: adowCopy' |AND
-      : <source>:4:36: unexpected token ""AND""
```

This affects other artifacts such as KapeFiles when VSS is selected.

**Comment by scudette** [comment]
Hmm this seems to be a problem with the VQL parser not liking the linebreak after the AND keyword. I will look into it.

Thanks for reporting!

**Comment by predictiple** [comment]
Yes, I created a copy with the line breaks on L64 removed and it's happy with that. Just doesn't look so cool with 1 long line :-)

**Comment by predictiple** [comment]
brackets around the WHERE expression solves the problem too.
