### ISSUE TITLE
$MFT does not show up in VFS view for mounted NTFS drives on Linux

### ISSUE THREAD

**Issue by lucebac** [Velocidex/velociraptor#1317]
While trying out the predictiple's recommendation in #888 regarding mounted NTFS drives, we experienced the error that `$MFT` was not showing up in the VFS view for the mount folder.  Everything else appeared as expected, just `$MFT` was missing.  We triaged the situation and found out that the error is caused by a combination of the NTFS driver and the standard library:

It seems that both NTFS driver we tested ([ntfs-3g](https://github.com/tuxera/ntfs-3g/) and [ufsd](https://www.paragon-software.com/home/ntfs-linux-professional/)) assign the inode numbers based on the id of the entry in the MFT.  So `$MFT` is assigned `0`, `$MFTMirr` is assigned `1`, and so on:

```
velo@veloubuntu:~$ ./syscall /mnt/windows_mount/
--------------- nread=824 ---------------
inode#    file type  d_reclen  d_off   d_name
       5  directory    24         32  .
       5  directory    24         64  ..
       4  regular      32         96  $AttrDef
       8  regular      32        128  $BadClus
       6  regular      32        160  $Bitmap
       7  regular      32        192  $Boot
      11  directory    32        224  $Extend
       2  regular      32        256  $LogFile
       0  regular      24        288  $MFT
       1  regular      32        320  $MFTMirr
      58  directory    32        360  $Recycle.Bin
       9  regular      32        392  $Secure
[...]
```

However, this poses an issue with at least [glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/readdir.c;h=b4801351645d1236086d24fa025419417b2747d3;hb=HEAD#l71) and the [Golang standard library](https://github.com/golang/go/blob/e74db46519a7cbed16a7f14932da2ef93d647ece/src/os/dir_unix.go#L89): both `readdir` implementations filter out inodes which have assigned the number `0`. And since Velociraptor uses the standard library in its `glob` implementation, `$MFT` will never show up in directory listings or can be grabbed in collections because it is treated as a deleted file.

I attached the artifacts I used for collecting files from a NTFS mount so that you can reproduce the issue. Please use the [KapeFiles artifact](https://gist.github.com/lucebac/110ed2fde6a47fe2504ad95fd9b34169) to request files (it needs this [Collector](https://gist.github.com/lucebac/143bb0c9a36fc608f3a881b8458c05ee) to function).

The question I have is: is that something that should be fixed in Velociraptor?

I came up with two solutions which might work if the anwer to the question is "yes":
 * explicitly collect `$MFT` from target directories (as long as `glob` is not involved, this works fine)
 * allow the NTFS parser and the `ntfs` accessor to work on Linux and use the device in `/dev/sd*`
 
However, I think the second solution can be quite tedious to implement or test and I, personally, am probably not able to contribute that on my own.

**Comment by scudette** [comment]
If you are mounting the NTFS drive then Velociraptor just sees a directory with files in it. So Velociraptor can only use the "file" accessor to access those files. We do not use the standard library version of readdir due to bugs so we actually have our own version

https://github.com/Velocidex/velociraptor/blob/c9a24c82e5e87e1d72cbb484a9e3d1325c4148ff/utils/file_linux.go#L34

I am happy to hoist other standard library functions into our codebase if we need to fix bugs in them if you can figure out where the inode = 0 check is happening.

There is an issue #888 that asks for adding support for managing images like dead disk forensics which might solve the problem in a nicer way.
