### ISSUE TITLE
Issue with setting hunt expiry in 0.6.1

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#1323]
It appears there is a bug in the hunt expiry in the hunt() function in 0.6.1.
![image](https://user-images.githubusercontent.com/13081800/136868409-56e4117c-f574-4f3f-874e-fffdd4dea268.png)

Changing the chosen epoch time doesn't appear to change the error.

**Comment by mgreen27** [comment]
closing - seems to be working as expected (type issue)

**Comment by scudette** [comment]
Fixed in #1325
