### ISSUE TITLE
Add Resources Section to PARSE_PE() function

### ISSUE THREAD

**Issue by eduardomcm** [Velocidex/velociraptor#1332]
Malware can hide its configuration or another PE inside the resources section. 

Having the parse_pe() function return those sections will help future malware config parser artifacts and could be used in conjunction with the upcoming file magic VQL function to identify whether or not there is a specific file type (like a PE or a Zip archive) within the resources of a PE.

Example from Qbot which contains its C2 config and Bot ID in separate resources, in encrypted form:
![image](https://user-images.githubusercontent.com/49650494/137378508-fed7e9ed-69ff-4623-99d4-4b94c14b0f85.png)

**Comment by scudette** [comment]
The parse_pe() function already returns all sections - is there any more specific parsing of the resource section needed?

![Windows_5](https://user-images.githubusercontent.com/3856546/137412129-44e126f8-2128-4f95-a598-6cfc158c7d57.png)
