### ISSUE TITLE
startFrontend fails - file does not exist

### ISSUE THREAD

**Issue by litemanawake** [Velocidex/velociraptor#1333]
Commit: 57e33bf25f3b8289f082c08e825537d214957782

Compiled on Ubuntu 20.04, go version go1.17.1 linux/amd64

After generating a basic config, self-signed cert, all defaults, and one user defined

`
(*errors.errorString)(0xc00004a110)(file does not exist)
velociraptor-v0.6.1-linux-amd64: error: startFrontend file does not existv: file does not exist
`

Full verbose output
`
sudo ./velociraptor-v0.6.1-linux-amd64 frontend -c server.config.yaml -v

[INFO] 2021-10-15T02:46:32Z Loading config from file server.config.yaml
(string) ""
[INFO] 2021-10-15T02:46:32Z Starting Frontend. {"build_time":"2021-10-15T02:45:46Z","commit":"57e33bf2","version":"0.6.1"}
[INFO] 2021-10-15T02:46:32Z Increased open file limit to 999999
[INFO] 2021-10-15T02:46:32Z Frontend: Server will be master.
[INFO] 2021-10-15T02:46:32Z Starting Journal service.
[INFO] 2021-10-15T02:46:32Z Starting the notification service.
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.Ping
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.Notifications
[INFO] 2021-10-15T02:46:32Z Starting Inventory Service
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.FrontendMetrics
[INFO] 2021-10-15T02:46:32Z Loaded 360 built in artifacts in 165.884405ms
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.Label
[INFO] 2021-10-15T02:46:32Z Starting Client Info service.
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.ClientDelete
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.Interrogation
[INFO] 2021-10-15T02:46:32Z Starting Client Monitoring Service
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.ArtifactModification
[INFO] 2021-10-15T02:46:32Z Reloading client monitoring tables from datastore
[INFO] 2021-10-15T02:46:32Z Starting Label service.
[INFO] 2021-10-15T02:46:32Z Converting legacy client index to new format
[INFO] 2021-10-15T02:46:32Z Starting Hunt Dispatcher Service.
[INFO] 2021-10-15T02:46:32Z Starting the hunt manager service with rate limit 30/s.
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.HuntModification
[INFO] 2021-10-15T02:46:32Z Watching for events from System.Hunt.Participation
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.Label
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.Interrogation
[INFO] 2021-10-15T02:46:32Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T02:46:32Z Starting Enrollment service.
[INFO] 2021-10-15T02:46:32Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.Enrollment
[INFO] 2021-10-15T02:46:32Z server_monitoring: Starting Server Monitoring Service
[INFO] 2021-10-15T02:46:32Z Closing Server Monitoring Event table
[INFO] 2021-10-15T02:46:32Z server_monitoring: Updating monitoring table
[INFO] 2021-10-15T02:46:32Z Starting VFS writing service.
[INFO] 2021-10-15T02:46:32Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T02:46:32Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T02:46:32Z Starting Server Artifact Runner Service
[INFO] 2021-10-15T02:46:32Z Watching for events from Server.Internal.ClientDelete
[INFO] 2021-10-15T02:46:32Z Throttling connections to 100 QPS
[INFO] 2021-10-15T02:46:32Z Starting gRPC API server on 127.0.0.1:8001
[INFO] 2021-10-15T02:46:32Z Launched Prometheus monitoring server on 127.0.0.1:8003
(*errors.errorString)(0xc00004a110)(file does not exist)
velociraptor-v0.6.1-linux-amd64: error: startFrontend file does not existv: file does not exist
`

**Comment by scudette** [comment]
Looks like it can't start the server monitoring service. Can you try to move the file <filestore>/config/server_monitoring.yaml out of the way.

Sometimes a server monitoring Artifact was removed and it can't start collecting it.

If this doesn't not work then try to move the client one as well

**Comment by litemanawake** [comment]
I'm not sure I understand.  I don't know where to find the server_monitoring.yaml file. 

I renamed the `/opt/velociraptor/server_monitoring.json.db` and `client_monitoring.json.db`  and re-ran the binary but got the same result. 

Next, I cleared the /opt/velociraptor directory and tried again.  I got more output, but failed in the same place. 

```  
sudo -u velociraptor ./velociraptor-v0.6.1-linux-amd64 -c server.config.yaml frontend -v
[INFO] 2021-10-15T03:09:58Z Loading config from file server.config.yaml
(string) ""
[INFO] 2021-10-15T03:09:58Z Starting Frontend. {"build_time":"2021-10-15T02:45:46Z","commit":"57e33bf2","version":"0.6.1"}
[INFO] 2021-10-15T03:09:58Z Increased open file limit to 999999
[INFO] 2021-10-15T03:09:58Z Frontend: Server will be master.
[INFO] 2021-10-15T03:09:58Z Starting Journal service.
[INFO] 2021-10-15T03:09:58Z Starting the notification service.
[INFO] 2021-10-15T03:09:58Z Watching for events from Server.Internal.FrontendMetrics
[INFO] 2021-10-15T03:09:58Z Watching for events from Server.Internal.Ping
[INFO] 2021-10-15T03:09:58Z Watching for events from Server.Internal.Notifications
[INFO] 2021-10-15T03:09:58Z Starting Inventory Service
[INFO] 2021-10-15T03:09:59Z Loaded 360 built in artifacts in 207.154404ms
[INFO] 2021-10-15T03:09:59Z Watching for events from Server.Internal.Label
[INFO] 2021-10-15T03:09:59Z Starting Client Info service.
[INFO] 2021-10-15T03:09:59Z Watching for events from Server.Internal.ClientDelete
[INFO] 2021-10-15T03:09:59Z Watching for events from Server.Internal.Interrogation
[INFO] 2021-10-15T03:09:59Z Starting Client Monitoring Service
[INFO] 2021-10-15T03:09:59Z Watching for events from Server.Internal.ArtifactModification
[INFO] 2021-10-15T03:09:59Z Reloading client monitoring tables from datastore
[INFO] 2021-10-15T03:09:59Z Creating default Client Monitoring Service
[INFO] 2021-10-15T03:09:59Z Starting Label service.
[INFO] 2021-10-15T03:09:59Z Initial user test not present, creating
[INFO] 2021-10-15T03:09:59Z Converting legacy client index to new format
[INFO] 2021-10-15T03:09:59Z Server upgrade detected  -> 0.6.1... running upgrades.
[INFO] 2021-10-15T03:09:59Z Updating Client Event Table because ClientEventTable was updated
[INFO] 2021-10-15T03:09:59Z Upgrading tool WinPmem64 {"Tool":{"name":"WinPmem64","github_project":"Velocidex/WinPmem","github_asset_regex":"winpmem_mini_x64.+exe","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool OSQueryLinux {"Tool":{"name":"OSQueryLinux","github_project":"Velocidex/OSQuery-Releases","github_asset_regex":"linux-amd64"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool OSQueryDarwin {"Tool":{"name":"OSQueryDarwin","github_project":"Velocidex/OSQuery-Releases","github_asset_regex":"darwin-amd64"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool VelociraptorWindows {"Tool":{"name":"VelociraptorWindows","github_project":"Velocidex/velociraptor","github_asset_regex":"windows-amd64.exe","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool VelociraptorWindows_x86 {"Tool":{"name":"VelociraptorWindows_x86","github_project":"Velocidex/velociraptor","github_asset_regex":"windows-386.exe","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool VelociraptorLinux {"Tool":{"name":"VelociraptorLinux","github_project":"Velocidex/velociraptor","github_asset_regex":"linux-amd64","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool VelociraptorDarwin {"Tool":{"name":"VelociraptorDarwin","github_project":"Velocidex/velociraptor","github_asset_regex":"darwin-amd64","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool SharpHound {"Tool":{"name":"SharpHound","url":"https://github.com/BloodHoundAD/BloodHound/raw/master/Collectors/SharpHound.exe"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool NirsoftBrowsingHistoryView64 {"Tool":{"name":"NirsoftBrowsingHistoryView64","url":"https://github.com/Velocidex/Tools/raw/main/BrowsingHistoryView/BrowsingHistoryView-amd64.exe","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool SBECmd {"Tool":{"name":"SBECmd","url":"https://github.com/Velocidex/Tools/raw/main/SBECmd/ShellBagsExplorer/SBECmd.exe"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool Bulk_Extractor {"Tool":{"name":"Bulk_Extractor","url":"https://github.com/4n6ist/bulk_extractor-rec/releases/download/rec03/bulk_extractor-rec03_x64.zip"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool SunburstYARARules {"Tool":{"name":"SunburstYARARules","url":"https://raw.githubusercontent.com/fireeye/sunburst_countermeasures/main/all-yara.yar"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool Intezer {"Tool":{"name":"Intezer","url":"https://analyze.intezer.com/api/scans/download"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool etl2pcapng {"Tool":{"name":"etl2pcapng","url":"https://github.com/microsoft/etl2pcapng/releases/download/v1.4.0/etl2pcapng.zip"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool OSQueryWindows {"Tool":{"name":"OSQueryWindows","github_project":"Velocidex/OSQuery-Releases","github_asset_regex":"windows-amd64.exe"}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool Autorun_x86 {"Tool":{"name":"Autorun_x86","url":"https://live.sysinternals.com/tools/autorunsc.exe","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool Autorun_amd64 {"Tool":{"name":"Autorun_amd64","url":"https://live.sysinternals.com/tools/autorunsc64.exe","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool SysmonBinary {"Tool":{"name":"SysmonBinary","url":"https://live.sysinternals.com/tools/sysmon64.exe","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Upgrading tool SysmonConfig {"Tool":{"name":"SysmonConfig","url":"https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml","serve_locally":true}}
[INFO] 2021-10-15T03:09:59Z Compiled all artifacts.
[INFO] 2021-10-15T03:09:59Z Starting Hunt Dispatcher Service.
[INFO] 2021-10-15T03:10:00Z Starting the hunt manager service with rate limit 30/s.
[INFO] 2021-10-15T03:10:00Z Watching for events from Server.Internal.HuntModification
[INFO] 2021-10-15T03:10:00Z Watching for events from System.Hunt.Participation
[INFO] 2021-10-15T03:10:00Z Watching for events from Server.Internal.Label
[INFO] 2021-10-15T03:10:00Z Watching for events from Server.Internal.Interrogation
[INFO] 2021-10-15T03:10:00Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T03:10:00Z Starting Enrollment service.
[INFO] 2021-10-15T03:10:00Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T03:10:00Z Watching for events from Server.Internal.Enrollment
[INFO] 2021-10-15T03:10:00Z server_monitoring: Starting Server Monitoring Service
[INFO] 2021-10-15T03:10:00Z Closing Server Monitoring Event table
[INFO] 2021-10-15T03:10:00Z server_monitoring: Updating monitoring table
[INFO] 2021-10-15T03:10:00Z Starting VFS writing service.
[INFO] 2021-10-15T03:10:00Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T03:10:00Z Watching for events from System.Flow.Completion
[INFO] 2021-10-15T03:10:00Z Starting Server Artifact Runner Service
[INFO] 2021-10-15T03:10:00Z Watching for events from Server.Internal.ClientDelete
[INFO] 2021-10-15T03:10:00Z Throttling connections to 100 QPS
[INFO] 2021-10-15T03:10:00Z Starting gRPC API server on 127.0.0.1:8001
[INFO] 2021-10-15T03:10:00Z Launched Prometheus monitoring server on 127.0.0.1:8003
(*errors.errorString)(0xc00004c110)(file does not exist)
velociraptor-v0.6.1-linux-amd64: error: startFrontend file does not existv: file does not exist
```

**Comment by scudette** [comment]
Is this an autocert deployment? does it use self signed certs?

Is the directory specified in the config as  autocert_cert_cache there?

**Comment by litemanawake** [comment]
Looks like `/opt/velociraptor/clients/server/tasks`
Output starting from Prometheus: 

```
68571 openat(AT_FDCWD, "/opt/velociraptor/server_artifact_logs/Server.Monitor.Health/Prometheus/2021-10-15.json", O_RDWR|O_CREAT|O_CLOEXEC, 0700) = 22
68571 openat(AT_FDCWD, "/opt/velociraptor/server_artifact_logs/Server.Monitor.Health/Prometheus/2021-10-15.json.tidx", O_RDWR|O_CREAT|O_CLOEXEC, 0700) = 23
68571 openat(AT_FDCWD, "/tmp/journal2474620684", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 22
68571 openat(AT_FDCWD, "/tmp/journal3055499744", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 23
68571 openat(AT_FDCWD, "/tmp/journal2347740400", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 24
68571 openat(AT_FDCWD, "/proc/sys/net/core/somaxconn", O_RDONLY|O_CLOEXEC) = 26
68561 openat(AT_FDCWD, "/opt/velociraptor/clients/server/tasks", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
68561 openat(AT_FDCWD, "/etc/lsb-release", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/proc/modules", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/proc/cpuinfo", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/proc/bus/pci/devices", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/proc/self/status", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/proc/1/environ", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
68561 openat(AT_FDCWD, "/proc/self/cgroup", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/etc/os-release", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/proc/stat", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/proc", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/sys/class/dmi/id/product_uuid", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
68561 openat(AT_FDCWD, "/etc/machine-id", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 28
68561 openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 28
```

**Comment by scudette** [comment]
Looks like this directory  is missing `/opt/velociraptor/clients/server/tasks` which is strange because it is supposed to create it and its parents.  Is it there? If you remove it does it recreate it again?

Can you please verify that clients/server is a directory ?

**Comment by scudette** [comment]
Oh sorry just to confirm - are you running the CI binary or did you compile it yourself?

If you compiled it yourself did you remember to build the website using `npm install` and type `make build` in gui/velociraptor?

**Comment by scudette** [comment]
Maybe we should just put up a blank "This binary was not built with the GUI app" empty page instead of failing to start

**Comment by litemanawake** [comment]
Yep - that is exactly what I was missing. 

Thank you! I definitely appreciate the quick and thorough response

**Comment by scudette** [comment]
Thank you! and sorry to go off on a tangent debugging this thing :-).
