### ISSUE TITLE
testing velociraptor server in AWS

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#134]
client does not prompt me for auth & throws `404 page not found`

On the console I see this => 
`[INFO] 2019-10-21T05:29:42Z http: TLS handshake error from 127.0.0.1:49693: remote error: tls: unknown certificate`

**Comment by scudette** [comment]
When you say client - do you mean Velociraptor client? How did you install the server? Is it self signed deployment? 

You error message is quite normal for self signed deployment - it just means the browser rejected the self signed cert.

**Comment by siftuser** [comment]
Thanks for swift response. sorry, by client I meant the browser accessing server GUI.

I followed [quick start](https://github.com/Velocidex/velociraptor) guide until step 3 ... at step 4, getting above error

**Comment by scudette** [comment]
Did you select the self signed deployment option?  Are you getting a cert warning from the browser?

**Comment by siftuser** [comment]
@scudette apologies to bother ... my bad, I was expecting velociraptor console/gui on the initially configured frontend port, but it wasn't accurate understanding. When I tried accurate port 8999, it worked like a charm! Sorry again :(

**Comment by scudette** [comment]
Wonderful! Glad you got it working :+1:
