### ISSUE TITLE
Feature request: Support multiple login providers concurrently

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#1349]
My understanding is currently you can only configure login from one provider (for ex Okta, or Gsuite, or Local)
Would be super useful to allow a method that lets us allow authorised emails and their relevant auth

For ex
abc@xyz, Okta
def@123, Gsuite
Administrator, Local

This would allow us to let people outside of the organisation in as Guests without having to give them accounts under our Okta for ex.

**Comment by randomaccess3** [comment]
@scudette did this get completed for this release?  I didnt see it in the release notes/closed issues.

**Comment by scudette** [comment]
nope if it is still open then it is not done. 

It is a pretty significant amount of code and it is not clear that it would be useful so at the moment low priority

**Comment by scudette** [comment]
Implemented by #1644
