### ISSUE TITLE
Large logs when errors in regex

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#1356]
Had an interesting one where an error in a regex put the following into the logs:
![image](https://user-images.githubusercontent.com/1241363/139423929-f754e44f-3b96-4f2c-8e3c-f0c779362a0a.png)

Granted we're going to delete it because it didnt work to begin with but it may be beneficial to not write the same log entry multiple times and instead condense them?
Either with a helper function that runs daily and condenses them (any repeated rows can be compressed and replaced with a single line?) or maybe just as they're written?

Not 100% sure this is required, but it filled up our server pretty quickly because 10k hosts, 100-800mb of logs per host, and was not super easy to troubleshoot.

**Comment by scudette** [comment]
Log dedup is fixed in 0.6.2 and regex editor is in head.
