### ISSUE TITLE
Offline collector inconsistency in file names when special chars are present

### ISSUE THREAD

**Issue by ydkhatri** [Velocidex/velociraptor#1359]
Uploaded file names (in zip) from the offline collector do not match the ones from normal collection, due to inconsistent behaviour when encoding special characters. 

Example, in the KAPE collection zip for event logs for a file which has `%` in the file name. The file name in zip is:
`Microsoft-Windows-Dhcpv6-Client%254Admin.evtx`
Offline collector zip collecting same file will have this name:
`Microsoft-Windows-Dhcpv6-Client%4Admin.evtx`

Original file name is `Microsoft-Windows-Dhcpv6-Client%4Admin.evtx` 

Expected behaviour is to have the same format in both outputs, so it can be post processed via code without hiccups.

**Comment by scudette** [comment]
Should be fixed by #2185 since now both the offline collector and the export use the same container format.
