### ISSUE TITLE
Allow setting env vars via execve

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#1360]
There may be certain times where we need to set env vars prior to running particular commands.  As previously discussed, we should look into allowing them to be set when using `execve`.

Ex. `var1=blah var2=blahblah`

Ref:

https://pkg.go.dev/os/exec#example-Command-Environment
https://github.com/Velocidex/velociraptor/blob/89008362b5c16ecc98be9490712b1a9ef807a300/vql/common/shell.go#L103

**Comment by scudette** [comment]
Fixed by #1453
