### ISSUE TITLE
MFT-related artifacts

### ISSUE THREAD

**Issue by gdms04** [Velocidex/velociraptor#1371]
May I know what's the difference between Windows.NTFS.MFT & Windows.Timeline.MFT? Thanks!

**Comment by mgreen27** [comment]
The goal of the timeline artifact was to show how we may process timeline like artifacts but I exclusively use Windows.NTFS.MFT in feild now days, mainly for live investigation and targeted hunting. It also has some performance optimisations.

 Windows.NTFS.MFT. Windows.Timeline.MFT is similar but flatterns each file entry into row per timestamp similar to processing with Plaso. We are planning on consolidating artifacts and this question is a great reminder. I think it would be best to add a timeline option to Windows.NTFS.MFT. What do you think?

**Comment by scudette** [comment]
Timeline is a something that should be done post collection if needed - the number of rows explodes when each is repeated 16 times and there is no need to transfer so many rows to the server. It probably makes more sense to build the timelines in the collection notebook. Maybe we should add some custom notebook cells to that artifact?

**Comment by gdms04** [comment]
yea, it will help thxthx!

**Comment by scudette** [comment]
Maybe this is something that should be deferred to the knowledge base as building a timeline is a rather general task (could apply for non mft artifacts).
