### ISSUE TITLE
Add an upload file parameter for VQLs 

### ISSUE THREAD

**Issue by Cr-ChenErlich** [Velocidex/velociraptor#1374]
As sometimes you want to hunt/collect data from an external resource such as a .txt or .csv file, adding a parameter for uploading a file that can change for execution can be great.
Also, it will be nice to make this parameter available for an optional fill - to give the user the ability to choose if he/she wants to use this uploaded file or to skip it and use a different option in the configuration (same goes for using a "tool" in a VQL)

**Comment by scudette** [comment]
Implemented in #1455
