### ISSUE TITLE
Search across previous collections

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#1376]
A user might want to search across previous collections for a keyword as part of scoping in an investigation.

For example say in an investigation a tool was discovered. Searching across all previous client collections for relevant strings may be beneficial.

An easy solution may be to leverage our yara.Glob capability as a SERVER artefact and point it at client data to find relevant flow results of interest. Consideration on how to present these results to the user is needed.

**Comment by weslambert** [comment]
Love this idea!

**Comment by eduardomcm** [comment]
love it too! I normally do these keyword searches with Yara when I need to find any files containing that keyword, which takes a long time. Being able to query already collected data for a keyword would be amazing

**Comment by mgreen27** [comment]
Still a bit to finish off, I'll likely add Hostname etc but I have keywords populating and a link to the relevant flow being generated. 
![image](https://user-images.githubusercontent.com/13081800/142004186-16a66e07-1743-4f83-9848-2251e3e2ec45.png)

**Comment by mgreen27** [comment]
I have just added an updated version to the artifact exchange for anyone who wants to test this out.
https://docs.velociraptor.app/exchange/artifacts/pages/findflows/

Modified to use a dynamically created regex yara so the user can enter a regex at the artifact configuration and have it work as expected.

Future update will be to look at making the fs not hardcoded in future.

![image](https://user-images.githubusercontent.com/13081800/143038896-0f217810-c46e-48aa-8228-74d25ff88895.png)
![image](https://user-images.githubusercontent.com/13081800/143038812-64aef17d-d8cc-4ec0-9f3f-b66ae00712d4.png)

**Comment by weslambert** [comment]
Nice job! Looking forward to testing this out!

**Comment by scudette** [comment]
This is done now right? Did you want it to go into the built in set or keep it in the exchange?

**Comment by mgreen27** [comment]
It works pretty welll but I think we leave it in the exchange because its targeting the filestore and not compatible for non filestore deployments. Im happy to lose this off.
