### ISSUE TITLE
fix yamllint errors on autogenerated config files

### ISSUE THREAD

**Issue by juju4** [Velocidex/velociraptor#1378]
Configuration files generated by velociraptor (config generate) are not passing yamllint

```
# yamllint files/*.yaml
files/client.config.yaml
  1:1       warning  missing document start "---"  (document-start)
  8:3       error    wrong indentation: expected 4 but found 2  (indentation)

files/server.config.yaml
  1:1       warning  missing document start "---"  (document-start)
  9:3       error    wrong indentation: expected 4 but found 2  (indentation)
  200:3     error    wrong indentation: expected 4 but found 2  (indentation)

```

**Comment by scudette** [comment]
We use the regular yaml library to produce the yaml files which is can read without any problem. 

Looks like you can tweak yamllint to fix its indentation level etc

https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.indentation
