### ISSUE TITLE
GUI sometimes does not show collected files

### ISSUE THREAD

**Issue by ydkhatri** [Velocidex/velociraptor#1379]
Sometimes the web gui in VFS is unable to fetch small files when "Collect from the client" is clicked. It spins, but then goes back to the same. The behaviour is the same on both NTFS and FILE accessors.

Using cmd, one could view the file by issuing the `type C:\path\file.ext` command.

This is on version 0.6.2

The file path in question here is `C:\Windows\System32\config\systemprofile\AppData\Local\xx\yy\something.txt` 
No long file path issues, illegal chars or other weirdness. File size was 24 bytes.

**Comment by scudette** [comment]
When you click the button in the vfs GUI it just schedules a new artifact collection.

Can you check if the file is properly collected by looking at the collected artifacts screen for that client and selecting the uploaded files tab?

**Comment by ydkhatri** [comment]
Checked, the file is downloaded. Seems to be just a gui bug not reflecting there. 
Thanks for the quick response!

**Comment by scudette** [comment]
Can we replicate this? Please reopen if it is reproducible
