### ISSUE TITLE
Windows.NTFS.MFT AllDrives Option

### ISSUE THREAD

**Issue by gdms04** [Velocidex/velociraptor#1380]
Regarding the artifact [Windows.NTFS.MFT], when you select the AllDrives option, velociraptor will search for C:\$MFT, D:\MFT,etc. After a few testing, i found that it does know to find all the MFT record (i.e. C & D in the Ref 1) in all drives from the log. However, the subsequent steps will only process the MFT record set in MFTFilename (i.e. C in Ref 2). May I ask if I set any parameter wrong? I set [star]:/$MFT], [star]:/$MFT, and .[star]:/$MFT. seems it doesnt work haha 
Thanks!

**Ref 1**
![image](https://user-images.githubusercontent.com/47113752/141959498-a10575f7-aa69-4ffb-b8d5-a99f811331d2.png)
**Ref 2**
![image](https://user-images.githubusercontent.com/47113752/141959656-3829fd07-3bc2-4271-8527-9fd6ecf3a437.png)

**Comment by scudette** [comment]
You are right- there is a bug in that artifact - it should be

```sql
      LET all_drives = SELECT * FROM foreach(row=ntfs_drives,
        query={
             SELECT * FROM mftsearch(MFTPath=MFTFilename)
        })
```

Instead of 
```sql
      LET all_drives = SELECT * FROM foreach(row=ntfs_drives,
        query=mftsearch(MFTPath=MFTFilename))
```

Just customize the artifact with the above change and go again.

**Comment by gdms04** [comment]
Thanks for the prompt reply. It works! but the MFTPath in the result cannot update accordingly. The highlighted entries should be from D:/$MFT. thx!
![image](https://user-images.githubusercontent.com/47113752/141967034-50176171-1aaf-4839-9c94-f9758953d901.png)

**Comment by scudette** [comment]
Yes correct - the value of MFTFilename is not being properly propagated

```sql
      LET all_drives = SELECT * FROM foreach(row=ntfs_drives,
        query={
          SELECT *, MFTFilename FROM mftsearch(MFTPath=MFTFilename)
        })
```

Perhaps the main issue here is redefining the same variable name as a parameter makes it pretty fragile. I think the artifact needs a bit of refactoring.

**Comment by gdms04** [comment]
the fix does work now! thanks so much for your support!

**Comment by scudette** [comment]
Thank you for reporting it! I will reopen so we can fix upstream ....

**Comment by scudette** [comment]
Fixed in head
