### ISSUE TITLE
Add Search for Exchange Artifacts to the /app/index.html?#/artifacts page

### ISSUE THREAD

**Issue by eduardomcm** [Velocidex/velociraptor#1390]
It would be great to be able to query the same **https://docs.velociraptor.app/exchange/** page directly from the **/artifacts** page within a Velociraptor Server - provided your Server has internet access.

Or maybe a new tab entry for Artifact Exchange.

Either way, having the capability to **import an artifact from the Artifact Exchange directly on the server** would be super helpful.

**Comment by mgreen27** [comment]
@eduardomcm take a look at Server.Import.ArtifactExchange it should be in the current version by default.

**Comment by eduardomcm** [comment]
That works great! thanks @mgreen27 ! closing this issue
