### ISSUE TITLE
Allow support for Elastic Selfsign certificate

### ISSUE THREAD

**Issue by mgdevsoft** [Velocidex/velociraptor#1395]
When using server artifact for elastic_upload using https URL for the elasticsearch the SSL handshake foes not complete. This is because when using selfsigned certificates on the elastic side velociraptor cannot connect. 
I did not see any option to add the elastic certificate to the velociraptor trusted certificates.
Is there a possibility to add a flag in the elastic_upload function for it? So, the SSL handshake will be completed.
Or adding an option to add trusted certificates on the server side only?
Kind regards,
Gal

**Comment by scudette** [comment]
Looks like we have a similar arg for splunk but not for Elastic - thanks for reporting :-)

**Comment by scudette** [comment]
Fixed by #1456
