### ISSUE TITLE
Improve Shimcache/appcompat artifact

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#1401]
Ensure we have appropriate output for legacy Shimcache. Looks like we need to add execution flag for older version OSes.

**Comment by mgreen27** [comment]
Need to refactor the appcompat artifact. Currently use Velociraptor regparser which is incomplete.
Probably best to refactor and implement a binary_parse for this feature. 

https://github.com/mandiant/ShimCacheParser/blob/master/ShimCacheParser.py

**Comment by mgreen27** [comment]
Added better formatting output - https://github.com/Velocidex/velociraptor/pull/1892

**Comment by scudette** [comment]
#2628 Added better support for appcompat cache.
