### ISSUE TITLE
Add the ability to pass custom column fields to parse_csv()

### ISSUE THREAD

**Issue by cr-matthewhart** [Velocidex/velociraptor#1405]
Similar to `split_records` it would be nice to pass customized columns to parse CSV. This helps with dealing with unconventional CSV files like Exchange and IIS logs where Microsoft Prepends the log chunks with `#` variables. An example from the Exchange Message Tracking Log can be seen below.

```
#Software: Microsoft Exchange Server
#Version: 15.01.2176.009
#Log-type: Message Tracking Log
#Date: 2021-11-03T08:00:32.100Z
#Fields: date-time,client-ip,client-hostname,server-ip,server-hostname,source-context
2021-11-03T08:00:32.100Z,1.1.1.1,SERVER01,,,"MDB:GUID, Mailbox:GUID, Event:81929817, MessageClass:IPM.TYPE.",(...)
2021-11-03T08:00:32.147Z,1.1.1.1,SERVER01.EXAMPLE.COM,2.2.2.2,SERVER01.EXAMPLE.COM,"MDB:GUID, Mailbox:GUID, Event:81929817, MessageClass:IPM.TYPE.",(...)
```

**Comment by scudette** [comment]
Could we please get a sample log file (anonymised if you wish - just edit out the PII but keep the general structure the same) to include in the CI testing for this feature? We only need a couple of lines and the header.

**Comment by cr-matthewhart** [comment]
Files can be found attached. iis is space delimited and exchange is comma delimited.

[exchange.csv](https://github.com/Velocidex/velociraptor/files/7638133/exchange.csv)
[iis.csv](https://github.com/Velocidex/velociraptor/files/7638134/iis.csv)

**Comment by scudette** [comment]
This is now available in head
