### ISSUE TITLE
Usn-related artifacts (i.e. Windows.Forensics.Usn & Windows.Carving.USN)

### ISSUE THREAD

**Issue by gdms04** [Velocidex/velociraptor#1406]
In theory, every NTFS drive will have its own usn journal. In other words, the USN-related artifact can be run on all NTFS drives. In my case, my C & D Drive are NTFS drives (Please refer to Screenshot 1). I created a file called try.txt and deleted it (Please refer to Screenshot 2 & 3). After running Windows.Forensics.Usn on Drive, there is no result returned (Please refer to Screenshot 4 & 5). I simulated this in C drive and the expected result is returned (Please refer to Screenshot 6). May I ask if I set any parameter wrong? Thanks!

**_Screenshot 1_**
![image](https://user-images.githubusercontent.com/47113752/144298243-107fa703-7404-4637-a0c3-ac95326df33f.png)

**_Screenshot 2_**
![image](https://user-images.githubusercontent.com/47113752/144297682-a381f6bb-995e-48c3-afc2-41e5b55d1264.png)

**_Screenshot 3_**
![image](https://user-images.githubusercontent.com/47113752/144297728-a0e1973d-0e66-4156-8663-ba6f534bdba9.png)

**_Screenshot 4_**
![image](https://user-images.githubusercontent.com/47113752/144298562-e007a5bf-eae9-4426-ae5a-bd6e395d6d57.png)

**_Screenshot 5_**
![image](https://user-images.githubusercontent.com/47113752/144298632-c68738a9-6e6a-494c-95d5-123ef63ab987.png)

**_Screenshot 6_**
![image](https://user-images.githubusercontent.com/47113752/144299003-b1bab306-317d-4353-a512-5f8fcf9f72c1.png)

**Comment by scudette** [comment]
This is quite interesting - I tried to recreate by making another ntfs disk on this VM and formatting it. While the main drive has an USN journal as you can see here
![Windows_Active](https://user-images.githubusercontent.com/3856546/144412686-a77b3075-47ab-4a1a-8206-83f2df213f98.png)

The second disk has no USN file at all by default

![Windows_Active](https://user-images.githubusercontent.com/3856546/144412755-e4c269d7-2c03-4a90-ab6c-75769721acf7.png)

But I can create a journal file for this drive using 

```
fsutil usn createjournal e:
```

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-usn

and now it has a journal
![Windows_Active](https://user-images.githubusercontent.com/3856546/144413192-bb4eeb62-f09b-45ef-b98b-7723665752d1.png)

and everything works as expected :-).

Similarly the above command is often used to remove the journal or to set the size to really small by malware so this is a very common way for interfering with the USN journal.

**Comment by gdms04** [comment]
inspiring, thx so much for your help!
