### ISSUE TITLE
Feature Request: Multiple cells within the 'clients' tab of a hunt

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#1410]
Would be great to have multiple cells in the clients tab with a filter on the "state" column for "running/finished/error".
Then periodically you can refresh all three and easily see where things are at in a hunt.

**Comment by scudette** [comment]
How is that any different from a notebook cell with the appropriate query?

**Comment by randomaccess3** [comment]
Because the clients tab is the right place for it
It would just be there notebook cells with the same query, different filter values. 

Lower barrier for entry for those that would otherwise need to know what query to write to get that data. 

It's absolutely not something everyone will be checking when it comes to the "quality of their output" when it comes to errors/hosts that are stuck still running

**Comment by scudette** [comment]
This needs to be a lot more intelligent than just showing finished/failed

There are many cases when the query did not go so well but the collection is actually marked as finished. For example a vql typo or version mismatch would show as finished because as far as the server is concerned it sent the query and got a response.

We need to collate this information from the query logs and surface it in the GUI somehow as a possible problem.

Maybe the solution is some kind of server built in artifact that analyzes the query logs in hunts to determine if there possibly are some issues that require user attention.

**Comment by randomaccess3** [comment]
![image](https://user-images.githubusercontent.com/1241363/157602264-e22b0a1e-5e1f-4024-bfc1-afc2f0c48bf4.png)

`# ERROR
{{ Query "SELECT ClientId, FlowId, Flow.start_time As StartedTime, Flow.state AS FlowState, Flow.status as FlowStatus, Flow.execution_duration as Duration, Flow.total_collected_bytes as TotalBytes, Flow.total_collected_rows as TotalRows from hunt_flows(hunt_id='H.C7SVOLOCB4GBC') where FlowState = 'ERROR'" | Table}}

## RUNNING
{{ Query "SELECT ClientId, FlowId, Flow.start_time As StartedTime, Flow.state AS FlowState, Flow.status as FlowStatus, Flow.execution_duration as Duration, Flow.total_collected_bytes as TotalBytes, Flow.total_collected_rows as TotalRows from hunt_flows(hunt_id='H.C7SVOLOCB4GBC') where FlowState = 'RUNNING'" | Table}}

## FINISHED
{{ Query "SELECT ClientId, FlowId, Flow.start_time As StartedTime, Flow.state AS FlowState, Flow.status as FlowStatus, Flow.execution_duration as Duration, Flow.total_collected_bytes as TotalBytes, Flow.total_collected_rows as TotalRows from hunt_flows(hunt_id='H.C7SVOLOCB4GBC') where FlowState = 'FINISHED'" | Table}}`

This would suffice for now
Where hunt_id would be whatever the hunt is that you've selected.

And i haven't gotten it to work the exact same way because youll likely improve it significantly with less effort. 

It currently doesnt lookup the hostname against the clientid, and the total collected bytes was showing blank when it should have shown 0.

Next step from this would be if you could click on the "errored" items and have it seemlessly and temporarily tag them, rerun the hunt against the tag, and merge the results in so that queries can be run again the one huntid even though it is made up of two seperate hunts

**Comment by scudette** [comment]
This now solved by a new notebook feature: Suggestions. This is a way for notebooks to offer quick pre-templated cells for doing specific post processing analysis at a click of the mouse. For hunts a suggestion is always added to basically construct the VQL @randomaccess3 added above:

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/158320911-2576ab5d-073b-4d8d-aecd-8a05258438e5.png)

![Velociraptor_Response_and_Monitoring](https://user-images.githubusercontent.com/3856546/158320965-b3668353-75c9-426a-b9cb-1f69cebf7af6.png)

The advantage of doing this is that it can be recalculated at any time to bring fresh data.
