### ISSUE TITLE
Look into Atera

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#1422]
Seen several engagements with AteraAgent.
Look into a series of artifacts.

**Comment by eduardomcm** [comment]
https://github.com/eduardomcm/VelociraptorCompetition/blob/main/Windows.Registry.AteraNetworks.yaml
This one is simple and helps. 
Another one would be a simple log parser

**Comment by mgreen27** [comment]
@eduardomcm  thank you! 
Another good one is probably yara the MFT for Atera (Windows.Forensics.FilenameSearch). I dont imagine that to be too common but need to test it.

**Comment by mgreen27** [comment]
@eduardomcm just modded your artefact to return config nicely
![image](https://user-images.githubusercontent.com/13081800/148177061-eb132843-8c66-4169-9419-8f5be704a253.png)

Also lots of hits in MFT hunting on the string "Atera" that hang around for a while after removal.
I couldn't find any interesting logs in my default install and messing around. The platform seems lax in logging. Do you have any examples you can share?

**Comment by eduardomcm** [comment]
Thanks for the update, looking nice :)

Unfortunately I don't have any examples to share. 

In my experience logging is very limited, like you said, and as far as remember the logs are in C:/Program Files (x86)/ATERA Networks/AteraAgent/*

**Comment by mgreen27** [comment]
Added - https://docs.velociraptor.app/exchange/artifacts/pages/ateranetworks/
closing this issue
