### ISSUE TITLE
Unable to build velociraptor on ppc64le

### ISSUE THREAD

**Issue by helix-loop** [Velocidex/velociraptor#1442]
**OS / arch**
Debian Bullseye ppc64le

**Version**
v0.6.2

Trying to build velociraptor on ppc64le with `make linux` I get the following error:

```
exec: go build -o output/velociraptor-v0.6.2-linux-amd64 -tags  server_vql extras  release yara  -ldflags=-s -w -X "www.velocidex.com/golang/velociraptor/config.build_time=2021-12-21T12:20:22+01:00" -X "www.velocidex.com/golang/velociraptor/config.commit_hash=" ./bin/
# runtime/cgo
gcc_amd64.S: Assembler messages:
gcc_amd64.S:25: Error: unrecognized opcode: `pushq'
gcc_amd64.S:26: Error: unrecognized opcode: `pushq'
gcc_amd64.S:27: Error: unrecognized opcode: `pushq'
gcc_amd64.S:28: Error: unrecognized opcode: `pushq'
gcc_amd64.S:29: Error: unrecognized opcode: `pushq'
gcc_amd64.S:30: Error: unrecognized opcode: `pushq'
gcc_amd64.S:37: Error: unrecognized opcode: `movq'
gcc_amd64.S:38: Error: unrecognized opcode: `movq'
gcc_amd64.S:39: Error: unrecognized opcode: `call'
gcc_amd64.S:40: Error: unrecognized opcode: `call'
gcc_amd64.S:43: Error: unrecognized opcode: `popq'
gcc_amd64.S:44: Error: unrecognized opcode: `popq'
gcc_amd64.S:45: Error: unrecognized opcode: `popq'
gcc_amd64.S:46: Error: unrecognized opcode: `popq'
gcc_amd64.S:47: Error: unrecognized opcode: `popq'
gcc_amd64.S:48: Error: unrecognized opcode: `popq'
gcc_amd64.S:49: Error: unrecognized opcode: `ret'
Error: running "go build -o output/velociraptor-v0.6.2-linux-amd64 -tags  server_vql extras  release yara  -ldflags=-s -w -X "www.velocidex.com/golang/velociraptor/config.build_time=2021-12-21T12:20:22+01:00" -X "www.velocidex.com/golang/velociraptor/config.commit_hash=" ./bin/" failed with exit code 2
exit status 2
make: *** [Makefile:31: linux] error 1
```

**Comment by scudette** [comment]
To support a new architecture you first need to add a build target in magefile.go

https://github.com/Velocidex/velociraptor/blob/461909bd6b65056fb763b02d53790488c93fda34/magefile.go#L245

For example this
```go
func PPCLinux() error {
    return Builder{
        extra_tags:  " release yara ",
        goos:        "linux",
        disable_cgo: true,
        arch:        "ppc64",
    }.Run()
}
```

But it looks like it does not work because gopsutil does not support that architecture:
```
exec: go build -o output/velociraptor-v0.6.3-dev-linux-ppc64-nocgo -tags  server_vql extras  release yara  -ldflags=-s -w -X "www.velocidex.com/golang/velociraptor/config.build_time=2021-12-21T05:38:17+10:00" -X "www.velocidex.com/golang/velociraptor/config.commit_hash=461909bd" ./bin/
# github.com/shirou/gopsutil/v3/host
../../go/pkg/mod/github.com/shirou/gopsutil@v3.21.11/host/host_linux.go:98:22: undefined: sizeOfUtmp
../../go/pkg/mod/github.com/shirou/gopsutil@v3.21.11/host/host_linux.go:103:14: undefined: sizeOfUtmp
../../go/pkg/mod/github.com/shirou/gopsutil@v3.21.11/host/host_linux.go:105:9: undefined: utmp
```

We did want to deprecate the gopsutil dependency anyway so maybe this is the way to go.

I dont know if there are other dependencies that do not support that architecture - i guess we need to go through them one at the time :-).

**Comment by scudette** [comment]
Sorry I think the arch is actually called ppc64le which is supported by gopsutil - this build correctly

```go
func PPCLinux() error {
    return Builder{
        extra_tags:  " release yara ",
        goos:        "linux",
        disable_cgo: true,
        arch:        "ppc64le",
    }.Run()
}
```

the build with 
```sh
$ go run make.go -v PPCLinux
Running target: PPCLinux
exec: fileb0x artifacts/b0x.yaml
2021/12/21 06:15:56 fileb0x: took [657ms] to write [artifacts/assets/ab0x.go] from config file [b0x.yaml] at [2021-12-21 06:15:56.68614507 +1000 AEST m=+0.674718610]
exec: fileb0x config/b0x.yaml
2021/12/21 06:15:56 fileb0x: took [9ms] to write [config/ab0x.go] from config file [b0x.yaml] at [2021-12-21 06:15:56.73248768 +1000 AEST m=+0.012667786]
exec: fileb0x gui/velociraptor/b0x.yaml
2021/12/21 06:15:57 fileb0x: took [644ms] to write [gui/velociraptor/ab0x.go] from config file [b0x.yaml] at [2021-12-21 06:15:57.393550283 +1000 AEST m=+0.646702492]
exec: git rev-parse --short HEAD
exec: go build -o output/velociraptor-v0.6.3-dev-linux-ppc64le-nocgo -tags  server_vql extras  release yara  -ldflags=-s -w -X "www.velocidex.com/golang/velociraptor/config.build_time=2021-12-21T06:15:57+10:00" -X "www.velocidex.com/golang/velociraptor/config.commit_hash=461909bd" ./bin/
```

**Comment by scudette** [comment]
If you have c compilers installed you can try to enable cgo - without cgo it will leave out modules that depend on the c compiler so for example, libmagic, yara, sqlite etc

**Comment by helix-loop** [comment]
Thank you, I was able to build with the suggested change. I am able to get the .deb-package via `./velociraptor-v0.6.2-linux-ppc64le-nocgo --config server.config.yaml debian server`, however I am not able to install it with dpkg complaining about the architecture (amd64) not fitting the system architecture (ppc64el). I am able to generate a config for the server (`./velociraptor-v0.6.2-linux-ppc64le-nocgo config generate -i`) and test it and the web gui with `./velociraptor-v0.6.2-linux-ppc64le-nocgo gui` just fine. I looked for arch specific commands in the debian directory of the source and only found an "amd64" in the description of the systemd config file. Is there another command to change?

The built binary also suggests that it was build without cgo (nocgo). Is there a specific argument or config change for the build to enable cgo? I have c compilers (gcc) installed so far.

**Comment by scudette** [comment]
Maybe you need to change the architecture here
https://github.com/Velocidex/velociraptor/blob/a45997641651bbc7b54c9706d2dbb08b82d326be/bin/debian.go#L180

We can add a flag to make it easier to change by users

**Comment by helix-loop** [comment]
Thanks again! Changing the architecture in the mentioned lines (180 and 306) worked. I was able to build a .deb for the server and for clients.

I also successfully built with cgo enabled. From changing options in magefile.go, would it be feasible to use something like this 

`disable_cgo: runtime.GOOS != "freebsd"`

based on the linux architecture the build is running on?

```
func PPCLinux() error {
       return Builder{
          extra_tags:  " release yara ",
          goos:        "linux",
          disable_cgo: runtime.GOARCH !="ppc64le",
          arch:        "ppc64le"}.Run()
}
```
Is it possible to cross-compile with cgo enabled? Trying to do so, I got a gcc error, although I should have installed the proper packages for cross compiling the other architecture. If this would be possible, that would be an argument against the suggested switch with cgo based on the runtime arch?

**Comment by scudette** [comment]
It really depends on the presence of cross compilers on the build system. The best option is to just create different targets and let the user decide what they wanted to build. For our release pipeline we actually use native build vms for the different targets instead of rely on cross compilers - i find that a bit easier to manage.

**Comment by scudette** [comment]
I added the --arch flag now to control the type of deb produced.
