### ISSUE TITLE
First Seen At time isn't fetched when using `clients()` in VQL

### ISSUE THREAD

**Issue by Satharus** [Velocidex/velociraptor#1448]
# Reproducing the issue

Create a new notebook and run the VQL Query `SELECT * FROM clients()`

- Expected output: first_seen_at field is populated for each client.
- Actual output: first_seen_at field is zero for each client.
![image](https://user-images.githubusercontent.com/29730368/147263183-ce183fa7-9e1b-499f-a941-452fa456470c.png)

## Current workaround
Run this query instead: `SELECT client_info(client_id=client_id) AS ClientInfo FROM clients()` this fetches the first_seen_at field properly for each client.

**Comment by scudette** [comment]
Fixed in head
