### ISSUE TITLE
Windows.Applications.NirsoftBrowserViewer does not collect all available history (missing switch)

### ISSUE THREAD

**Issue by chris-coalitionir** [Velocidex/velociraptor#1472]
**summary:** `Windows.Applications.NirsoftBrowserViewer` does not collect all available history; that is, it doesn't collect from all dates/times.  We think the expected behavior would be to get all dates by default, but in any case it's better to be fully explicit about the arguments passed to the external binary, to avoid default behaviors since they may change or be counter-intuitive.

**environment:** velociraptor v0.6.2-1, win 10, Nirsoft Browsing History View v2.50

**steps to reproduce:**

```powershell
PS C:\> .\BrowsingHistoryView.exe /HistorySource 1 /LoadIE 1 /LoadFirefox 1 /LoadChrome 1 /LoadSafari 1 /scomma ./test.csv /SaveDirect
PS C:\> .\BrowsingHistoryView.exe /VisitTimeFilterType 1 /HistorySource 1 /LoadIE 1 /LoadFirefox 1 /LoadChrome 1 /LoadSafari 1 /scomma ./testfix.csv /SaveDirect
```

then compare test.csv and testfix.csv.

**fix:**

Add the explicit `VisitTimeFilterType 1` argument to the execve call at https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/Applications/NirsoftBrowserViewer.yaml#L60-L65:

```sql     
-- snip
FROM execve(argv=[
             BinPath,
             "/VisitTimeFilterType", "1",
             "/HistorySource", HistorySource, "/LoadIE", "1",
             "/LoadFirefox", "1", "/LoadChrome", "1",
             "/LoadSafari", "1",
             "/scomma",  CSVFile, "/SaveDirect"])
--snip
```

Thanks to @brianvilnrotter and @megan-coalitionir for noticing this and implementing the fix.

**Comment by scudette** [comment]
This should be fixed in 0.6.4
