### ISSUE TITLE
imports scope breaks when called from another artifact

### ISSUE THREAD

**Issue by cr-matthewhart** [Velocidex/velociraptor#1477]
When attempting to run an artifact within an artifact collection, I believe that the imports: field is not being evaluated.

For example when calling `Artifact.Windows.Forensics.Shellbags()` we get a scope error for the Profile symbol.

![image](https://user-images.githubusercontent.com/50118581/149189033-293ba554-82e3-475f-a873-c290467ef7a0.png)

![Screen Shot 2022-01-12 at 12 09 32 PM](https://user-images.githubusercontent.com/50118581/149188942-d6eef15c-3ed7-49ec-b0fe-c73aef300dab.png)

However, this does not occur when directly running `Windows.Forensics.Shellbags()`

Is there something I am missing? I'm assuming that the issue is related to the imports section.

**Comment by scudette** [comment]
Can you please check which version you have? Just tried to replicate and it work for me at HEAD.

There was an issue like that some time ago and now we have a test to make sure it works here:

https://github.com/Velocidex/velociraptor/blob/170fe784a797fa06606389f86e4dbb7eee6595c2/services/launcher/launcher_test.go#L243

Looks like that fix went in https://github.com/Velocidex/velociraptor/commit/f5915373e6a049da45f41fbafb0f3485c117cb02

which should be available in 0.6.2 already

**Comment by cr-matthewhart** [comment]
Ah okay, yes, the current client is an older version of 0.6.2. Sorry about that.

Thanks for the response 🙏
