### ISSUE TITLE
cant see client in the server gui

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#149]
I can see the test client running on the server  in the web-gui .. but dont see client running on another machine ... though the client terminal  show the client connected (Receiver: Connected to https://IP:port) ... any clue ? thanks in advance!

**Comment by scudette** [comment]
Can you see the client record in the server data store? You can check the client id in the client's own startup messages.

If you deleted the index it is possible that you can no longer search for the client but it is still communicating normally. Client indexes are updated during interrogation (running the client Generic.Client.Info artifact). You could try to issue that artifact via a hunt or directly to get the index to update.

**Comment by siftuser** [comment]
Many Thanks for the clue @scudette ... it works now. Thanks!
