### ISSUE TITLE
Feature Request: Okta support

### ISSUE THREAD

**Issue by dfirpaul** [Velocidex/velociraptor#150]
Add okta implementation for authentication

https://github.com/okta/okta-sdk-golang

for testing OAUTH for okta we can create a free account https://developer.okta.com/signup/

**Comment by turekt** [comment]
Hi @dfirpaul,

did you try to utilize the existing SAML support in Velociraptor to integrate with Okta? As far as I can see, the crewjam's SAML library does [support Okta integration](https://github.com/crewjam/saml/pull/24).

If I would have to guess, you would need to [configure your Okta to enable SAML support](https://developer.okta.com/docs/guides/saml-application-setup/overview/) and follow the [SAML setup guide inside the docs folder in Velociraptor repository](https://github.com/Velocidex/velociraptor/tree/master/docs/saml). My guess would be that you should set the following values inside `server.config.yaml` under `GUI`:

- `saml_certificate`: your SAML certificate
- `saml_private_key`: your SAML private key
- `saml_idp_metadata_url`: SAML metadata URL pointing to Okta
- `saml_root_url`: URL pointing to your Velociraptor server (https://localhost:8889 when testing locally)
- `saml_user_attribute`: NameID **

** _This was deduced from [official Okta documentation on SAML hooks](https://developer.okta.com/docs/reference/saml-hook/#data-assertion-subject)) additionally confirming this via a pastebin link that I found in the [SAML Go Okta support pull request](https://github.com/crewjam/saml/pull/24). Both resources suggest that NameID should be the tag that contains the user identification._

**Comment by scudette** [comment]
SAML is too complex and probably an overkill for us. We now have a streamlines oauth2 flow and it seems to support all oauth2 providers (Microsoft, Google etc).

If Okta has a specific oauth2 endpoint we may add it but otherwise we are probably not going to officially support it.
