### ISSUE TITLE
Files with different licenses in the repository

### ISSUE THREAD

**Issue by vpereira** [Velocidex/velociraptor#1532]
Hello Velociraptor team!

We at SUSE, are running some experiments with Velociraptor, mainly focused on Linux. Our goal is to upstream everything if possible. One of our PRs however is adding some existing code which uses Apache License https://github.com/SUSE/linux-security-sensor/pull/1/files#diff-37a649608cd6304e89be4223e4319acf185bdb53a608fc819c347819cf842778. 

We would like to know if that's something acceptable or an issue

**Comment by scudette** [comment]
I dont believe this to be an issue at all - AFAIK GPL and Apache code can be freely mixed and the result is GPL licensed so no issue there! We certainly use a ton of Apache dependencies ourselves.

**Comment by vpereira** [comment]
great, thank you @scudette for the fast answer!
