### ISSUE TITLE
Notebook Cell As Source Inconsistent Behaviour

### ISSUE THREAD

**Issue by KostyaIliouk** [Velocidex/velociraptor#1537]
Using a Notebook Cell as source has inconsistent behaviour between a Hunt's Notebook and a created Notebook.
A Hunt's Notebook will output the parent cell's source data, rather than the computed VQL output.
A created Notebook will output the computed VQL query of the parent cell as expected.

Steps to Reproduce:
1. Run a Hunt that generates rows.
2. Filter Hunt Notebook output on a WHERE clause.
3. Click "Add Cell From This Cell"
4. Output will be original parent cell's source data rather than the computer VQL query
5. Copy notebook_id & notebook_cell_id
6. Create or Open a new Notebook in /app/index.html#/notebooks/
7. Add VQL cell
8. Enter query `SELECT * FROM source(notebook_id=<Copied Value>, notebook_cell_id=<Copied Value>)`
9. Output will be the computed VQL query as expected.

**Comment by scudette** [comment]
Fixed in #1844
