### ISSUE TITLE
server crashes during testing kape download

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#154]
Server crashed with following error 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xc0 pc=0xd7e82f]

goroutine 4612 [running]:
www.velocidex.com/golang/velociraptor/api.downloadFlowToZip(0x18d9780, 0xc000080310, 0xc000539140, 0x0, 0x0, 0x0, 0x0, 0xc000c3f360, 0x0, 0x0)
        C:/velociraptor/api/download.go:102 +0x26f
www.velocidex.com/golang/velociraptor/api.createDownloadFile.func1(0x18e3760, 0xc0000ac418, 0xc00083fcd0, 0xf, 0x18d9e00, 0xc0000ac428, 0xc000c3f360, 0xc000539140, 0x0, 0x0, ...)
        C:/velociraptor/api/download.go:188 +0x16d
created by www.velocidex.com/golang/velociraptor/api.createDownloadFile
        C:/velociraptor/api/download.go:183 +0x8fa

**Comment by scudette** [comment]
Hi which version are you testing? I think I just fixed this bug can you try with the latest ci build?

**Comment by scudette** [comment]
Please reopen this if it happens again with the latest release.
