### ISSUE TITLE
"kape_files.py" script registers parameters incompatible with VQL

### ISSUE THREAD

**Issue by jn-a** [Velocidex/velociraptor#1563]
"kape_files.py" registers parameters starting with a digit (e.g. "1Password") that are incompatible with the VQL syntax.

**Comment by scudette** [comment]
Why are these incompatible? Can you explain what is not working?

**Comment by yarox24** [comment]
Hi,

Following VQL query when attempting to save in "View artifacts section" as CLIENT type VWL plugin is generating error.

Query

```
SELECT * FROM Artifact.Windows.KapeFiles.Targets(VSSAnalysis=IncludeVSS,DontBeLazy=true,UseAutoAccessor=true,
        1Password=true)
```

Error
`Error: While parsing source query: 1:148: unexpected token "," (expected ")")`

We suspect that error is related to parameter (1Password or 4KVideoDownloader) passed to function which begins from digit, as for other parametrs which doesn't begin from digit it works perfectly fine.

**Comment by scudette** [comment]
VQL Identifiers have to start with a letter and can not contain characters like space, comma etc. If you have identifiers that use such characters you can just surround them with backticks:

```sql
SELECT * FROM Artifact.Windows.KapeFiles.Targets(VSSAnalysis=IncludeVSS,DontBeLazy=true,UseAutoAccessor=true,
        `1Password`=true)
```

See this relevant doc https://docs.velociraptor.app/docs/vql/#identifiers-with-spaces
