### ISSUE TITLE
Offline collector allow to custom or override Device letter?

### ISSUE THREAD

**Issue by tUn4** [Velocidex/velociraptor#1576]
Hello,
Is there any way to custom the **Device** letter in Windows.KapeFiles.Targets?
Default it should be "C:" letter but sometimes I faced several servers that use another letter (like D, E, F).
I'm trying to look in the training section but found nothing.
Or could Collector automatically get the system driver letter?
Thanks for your help.

**Comment by scudette** [comment]
Are you asking about customizing it **after** creating the offline collector? You can normally change it during the creation process.

The whole idea of the collector is that is is already pre-configured to run without command line args.

**Comment by tUn4** [comment]
> 

Yes, I mean after creating the offline collector?
Because this setting is configured (like C: letter) before but then I faced several servers that use another letter like D, E), therefore the collector could not collect data. At the time, I could not recreate the collector to change the Drive letter.

**Comment by scudette** [comment]
The offline collector is just a pre-configured velociraptor binary - no magic there :-). If you dont provide parameters it will just run what it has been told, but you can always provide any parameters to make it do something else.

If you want to be able to change an already created collector? You can manually dump out the configuration, change it and repack it if you want

1. extract the config from a collector:  `Collector_velociraptor.exe config show > config.yaml`
2. Edit the config: `notepad config.yaml` you will see a section like

```sql
 - name: Collector
    parameters:
    - name: Artifacts
      default: |-
        [
         "Generic.Client.Info", "Windows.System.Pslist"
        ]
      type: json_array
    - name: Parameters
      default: '{}'
      type: json
```

add whatever new artifacts you need to collect here or edit the parameters

3. Now you just repack it into a new collector: Collector_velociraptor.exe config repack config.yaml collector2.exe

But all this is doing is essentially collecting the same artifacts automatically - you can do it manually using the artifact collect command (you can collect any artifact this way not just the one built into the collector)

```
collector.exe -v artifacts collect --output somefile.zip Windows.KapeFiles.Targets --args _BasicCollection=Y --args Device=D:
```

**Comment by tUn4** [comment]
Thank you so much for your help.
By the way, I saw a flag that allows overwriting the config, could I use it to change config without repacking the collector?
```
 -o, --config_override=CONFIG_OVERRIDE
                                A json object to override the config.
```

**Comment by scudette** [comment]
Yeah you can use this to override part of the config or you can load an entirely new config. Also you can override specific items of config with command line flags - to see the list of flags you need to enable debug mode (there are just so many of them):

```
SET DEBUG=1 
velociraptor.exe --help
```

**Comment by drewhjelm** [comment]
Alternatively, you could create a custom KAPE collector artifact that iterates over all the drives and places them into separate folders rather than trying to specify any drives in the command itself. This is not a complete add, but it shows how the collection could look like, where the rule_specs_ntfs is the list of files being gathered. 

`LET wmi_query = SELECT * FROM wmi(query="SELECT * FROM Win32_LogicalDisk)

LET Windows = SELECT DeviceID, Description, VolumeName FROM wmi_query

SELECT * FROM foreach(
  row={
    SELECT DeviceID FROM Windows
  },
  query={
    SELECT * FROM Artifact.Windows.Collectors.File(RootDevice=DeviceID, Accessor="ntfs",collectionSpec=rule_specs_ntfs)
  }
)
)
`

**Comment by scudette** [comment]
I think this issue is probably stale - Kapefiles allows specifying drive letters now
