### ISSUE TITLE
Prefetch collection missing the "Accessed Files" section

### ISSUE THREAD

**Issue by sahar55** [Velocidex/velociraptor#158]
Hey guys, 
First of all, awesome presentation at SANS Summit, and amazing tool, thank you for the contribution!

I noticed the prefetch collection doesn't parse and display the "Accessed files" data of the prefetch, and since the collection doesn't provide with the original file this data is completely missing (Unless I missed something)

Is there any specific reason from omitting this? or is it in the road-map? 
Looking forward to your answer, 
cheers, 
Sahar

**Comment by scudette** [comment]
The Accessed Files column is very verbose. If you want it just add it to the artifact yourself:

Customize the artifact:

![image](https://user-images.githubusercontent.com/3856546/68544093-2fb89a00-040b-11ea-8112-54dd3a70c080.png)

Add the extra column to the query:
![image](https://user-images.githubusercontent.com/3856546/68544091-1ca5ca00-040b-11ea-810c-52204ec84546.png)

Collect the custom version of the prefetch artifact:
![image](https://user-images.githubusercontent.com/3856546/68544110-6393bf80-040b-11ea-8bfe-1bfc4632c4a3.png)

View the results.
![image](https://user-images.githubusercontent.com/3856546/68544124-8cb45000-040b-11ea-9624-e23c5914c0b3.png)


The results are very verbose so you would probably be best to download them first and analyse offline.

**Comment by scudette** [comment]
This is now available as a checkbox in the built in artifact
