### ISSUE TITLE
Enable logging of http 409 errors on server

### ISSUE THREAD

**Issue by PCNZ** [Velocidex/velociraptor#1595]
When the Velociraptor server returns a 409 error to a client is not currently logged.
https://discord.com/channels/624244632552734750/624244632552734752/946064095826837505
https://github.com/Velocidex/velociraptor/blob/b536bf827d1b508b0e831bc2fbbf9df4cde8aa46/server/comms.go#L499

It would be useful to be able to see this 409 response logged in the server logs, along with the client id and IP address. Helping to track down clients with conflicts and giving a view of the extent of the client configuration problems, which cause this error from the servers perspective.

**Comment by scudette** [comment]
This is now possible by simply following the Server.Internal.ClientConflict artifact:
```sql
SELECT * FROM watch_monitoring(artifact='Server.Internal.ClientConflict')
```

But it is not really necessary any more because enabling the `Server.Monitor.ClientConflict` artifact will automatically rekey conflicting clients if this is likely to happen with the deployment.
