### ISSUE TITLE
offline collector - upload_s3 fails with Unable to open / lstat no such file or directory

### ISSUE THREAD

**Issue by litemanawake** [Velocidex/velociraptor#1596]
Observed with the mac and linux offline collector on v0.6.3, and with the Windows offline collector in v0.6.4-dev

Error `lstat ... no such file or directory` even though the file does exist in the local directory

`[INFO] 2022-02-23T22:56:45Z  upload_S3: Unable to open ./test_collection.zip: lstat /test_collection.zip: no such file or directory
[INFO] 2022-02-23T22:56:45Z  Query Stats: {"RowsScanned":3,"PluginsCalled":2,"FunctionsCalled":3,"ProtocolSearch":10,"ScopeCopy":11}
[
 {
  "Uploaded": null
 }
][INFO] 2022-02-23T22:56:45Z Collection completed in 45 Seconds`

File is present:

`-rw------- 1 root   root    2748764 Feb 23 22:56 test_collection.zip`

Linux offline collector version
`name: velociraptor
version: 0.6.3
commit: 69e0fff
build_time: "2022-02-23T22:52:25Z"`

**Comment by scudette** [comment]
It looks like it is trying to open the file with a relative path - Velociraptor does not use the current directory and always opens files using an absolute path (in this case ./test_collection.zip turns into /test_collection.zip).

what is test_collection.zip and how is it generated? it is supposed to be in a temp file? Make sure the temp file is set to a full path and not a relative path (like ".")

**Comment by litemanawake** [comment]
We've been using relative path for ease of use -- so that the zip file is dropped in the same directory as the executable. This has only recently started failing for us during the upload phase. 

This is the relevant selection from our config -- the output parameter for the collect() function works with the relative path -- the zip file does get created in the intended location. 

```
SELECT upload_s3(
                     file=Container,
                     bucket=S3bucket,
                     region=S3region,
                     name=Container,
                     credentialskey=S3Key,
                     credentialssecret=S3Secret) AS Uploaded
                    FROM collect(
                    output=format(format='./%s.%s.%s.%s.level.%d.zip', args=[ClientName, CollectionType, hostname.Fqdn[0],<ARTIFACTSET>, now()]),
                    password="<PASSWORD>",
                    format="json",
                    artifacts=[
                      <ARTIFACTS>
                    ]
```

**Comment by scudette** [comment]
You can find out the path of the velociraptor executable using this vql:
```sql
SELECT dirname(path=Exe) FROM info()
```

You can add it to your artifact like this
```sql
LET CWD <= SELECT dirname(path=Exe) AS CWD FROM info()

SELECT upload_s3(
                     file=Container,
                     bucket=S3bucket,
                     region=S3region,
                     name=Container,
                     credentialskey=S3Key,
                     credentialssecret=S3Secret) AS Uploaded
                    FROM collect(
                    output=format(format='%s/%s.%s.%s.%s.level.%d.zip', args=[
                             CWD[0].CWD,
                             ClientName, CollectionType, hostname.Fqdn[0],<ARTIFACTSET>, now()]),
                    password="<PASSWORD>",
                    format="json",
                    artifacts=[
                      <ARTIFACTS>
                    ]
```

**Comment by litemanawake** [comment]
Ah perfect -- Thank you!
