### ISSUE TITLE
0.3.6 - please include .msi

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#161]
Hi,

can you please Include .msi for v0.3.6 :)

**Comment by dfirpaul** [comment]
In case you want to generate it. grab the executable drop it on the Output folder and build it.

https://github.com/Velocidex/velociraptor/tree/master/docs/wix

**Comment by scudette** [comment]
Sorry I am travelling today :-(. I will get an MSI build this evening :+1:

**Comment by scudette** [comment]
MSI Is build now.
