### ISSUE TITLE
RPM velociraptor_client.service file permission should not be set to executable

### ISSUE THREAD

**Issue by PCNZ** [Velocidex/velociraptor#1612]
RHEL clients are reporting this error message in logs.
"velociraptor_client.service is marked executable. Please remove executable permission bits"

Please change the permissions when this file is created, I believe this is where is needs to be changed.
https://github.com/Velocidex/velociraptor/blob/master/bin/rpm.go so that velociraptor_client.service
Change mode from 0755 to 0644.

**Comment by scudette** [comment]
Fixed by #1647
