### ISSUE TITLE
info() fqdn not reliable

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#164]
info() fqdn is using local resolve from first Network Adapter. 
So, if first network adapter is let's say vEthernet from Hyper-V then your fqdn will be hostname.mshome.net and not your real fqdn. 
Basically it'll use fqdn from adapter with lowest metric.

**Comment by scudette** [comment]
This is the relevant code:

https://github.com/Showmax/go-fqdn/blob/master/fqdn.go#L11

We get the hostname then do a DNS lookup to get the ip addresses. Then we do a reverse dns lookup for each ip address and return the first fqdn.

It is possible for a host to have multiple fqdn and so we might have to present multiple ones.

Perhaps we need to extend the concept of fqdn to multiple?

**Comment by Idriel** [comment]
I am testing on one client workstation. 
net.LookupIP is using Local resolver and if we ping from local PC hostname then we get:
- good fqdn and we get IP from adapter with lowest metrics
- now resolve fqdn from IP for lowest adapter metrics is where issue occurs and we got wrong fqdn - from wrong adapter

**Comment by scudette** [comment]
I think ultimately this information is not super critical and there is not right answer anyway. 

It is intended to help people search for the right machine in the GUI - in some environments a windows AD name is more useful for this (as you say).  In some environments a hostname is not useful either (I often see hostnames set as DHCP leases so they keep changing).

**Comment by Idriel** [comment]
Hi, I agree it's not super critical. It's not critical at all. :)
Just to say, it's the same thing on DevOps computers where they are using Docker for Windows. 
All that workstations are showing as "host.docker.internal" so I need to do some kung-fu to get right client ID.

**Comment by scudette** [comment]
You know you can customize your "Host Information" screen by simply editing the `Generic.Client.Info` artifact. You can add additional sources to have your clients collect more/different info as part of the interrogation workflow. Also by editing the template you can customize the GUI as well.

So you just have to figure out a way to identify these machines that makes sense to you - maybe by username, role name, function name etc then you collect that and render it in the UI. You can then use labels to categorize and group machines.

Not quite as convenient as customizing the search screen though.  Maybe we need to convert the search screen to an artifact so people can customize it as well?
