### ISSUE TITLE
Feature Request: Support SSO via SAML/Shibboleth to authenticate to WebUI

### ISSUE THREAD

**Issue by dwdixon** [Velocidex/velociraptor#165]
Hi there, it would be really amazing if you would be open to considering adding SSO support to authenticate to the WebUI via SAML/Shibboleth, many organizations (especially in Higher Ed) utilize SAML/Shib for their SSO solution, this typically also includes the organizations solution for 2FA on top of SAML/Shib which of course is highly desirable when authenticating to analyze data of this nature for TH/IR purposes etc.

Let me know if you have any follow up questions etc. !

Best,

-Drew

**Comment by scudette** [comment]
Sorry I dont know much about SAML but have you given the instructions here a try:
https://github.com/Velocidex/velociraptor/tree/master/docs/saml

**Comment by dwdixon** [comment]
Hi @scudette thanks for this, I did not see this in the docs on the website or on the Wiki here- I can investigate if this basic SimpleSAML support will work and report back.

**Comment by scudette** [comment]
This is functional right? We can close this?
