### ISSUE TITLE
Client deb install seems to be broken

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#1665]
Client deb created from 0.6.4-dev. On Ubuntu 20.04 after installation, `/usr/local/bin/velociraptor_client` is not set as executable.

After fixing that manually the service then fails to start because: `velociraptor_client: error: unknown long flag '--quiet'`

**Comment by scudette** [comment]
That's weird the --quiet command line option was added here
https://github.com/Velocidex/velociraptor/pull/1604/files#diff-36de6dcf68e9ed070f4eac1fe4a2a1b1e17fb6db3be0ede20ed706de1479e188

When you created the deb did you provide a binary with the --binary flag?

**Comment by predictiple** [comment]
Also confirmed that "./0.6.4-dev debian client --binary 0.6.4-dev" does not produce any issues.
