### ISSUE TITLE
Custom CSV Deliminator (rune)

### ISSUE THREAD

**Issue by chaoticmachinery** [Velocidex/velociraptor#1668]
When outputting CSV files from Raptor, a user defined deliminator is required. For most cases, the comma is fine. However when outputting a field like Cert details, it will hose the fields as the Cert details are comma deliminated too. 

I was thinking in the GUI a field was added next the the "Download CSV" button where you could put in the deliminator (i.e. rune) to use, that would address the issue. The field should accept multiple characters as \t (tab) might be the best deliminator.

**Comment by scudette** [comment]
Velociraptor outputs proper CSV formatted data - this means that it is ok to output fields with commas in them as the field will be properly escaped. If you import the csv into a tool that correctly supports CSV (like Excel or even Python with the csv parser) the data will be correct regardless of the delimiter.

**Comment by chaoticmachinery** [comment]
I get what your saying. However, I run the downloaded CSV through other tools at the command line. In order to process the CSV, I then have to load it up into another tool to read it. Then export it with the tool just so I can remove the commas and use say a | or tab for the fields. 

For example if I want to use the cut command in Linux, I may not get the columns I want due to the issue I described above. Yes I know I could just print out the columns I want with VQL. However, 99% I want all the columns. and I need to parse a few of them to get the data I need. That data I find relevant can be used to get the rest of the information out of the row.

Lastly, the download CSV may end up being too big for Excel to parse. I've seen this numerous times happen with Excel with my forensics datasets. I am more apt to use a tool that can give me some control over the export to feed either another process or tool.

**Comment by scudette** [comment]
If you want to process large csv files you can use an appropriate tool such as Miller 

https://github.com/johnkerl/miller

It works better than cut on structured data. 

The issue for us is that there are many places we produce csv and the benefit of allowing the delimiter to be set in all cases is not worth the effort of all the different ui changes. Maybe we can add a config option that is used globally but we definitely don't want to add a more complex UI for things like table export, offline collector etc.

**Comment by chaoticmachinery** [comment]
Please add a config option to be used globally. Miller isn't quite working out.

**Comment by scudette** [comment]
Should be fixed by 0.6.4 - you can now set a default delimiter for all CSV outputs in the config file. 

https://github.com/Velocidex/velociraptor/blob/523a376bd837d66b4b4565fcea54e56441757b1e/config/proto/config.proto#L803

**Comment by chaoticmachinery** [comment]
Thank you Mike.
