### ISSUE TITLE
Agentless deployment via SSH for Linux

### ISSUE THREAD

**Issue by cr-AustinBollinger** [Velocidex/velociraptor#1669]
At present, Velociraptor appears to support agentless deployment for Windows hosts only.

For various distros of *nix, having capability of an agentless SSH deployment could be useful to forensicate the lesser supported systems.

**Comment by scudette** [comment]
Agentless deployment is generally just running the client without having it installed permanently as a service. Either in a client/server capacity or as an offline collector.

You can do this with SSH easily - simply copy the binary and config files to the endpoint, then just run it. Something like this:

```
$ scp velociraptor client.config.yaml remote:/tmp/
$ ssh remote /tmp/velociraptor --config /tmp/client.config.yaml client -v
```

The agent will stay up as long as the ssh connection is up and when you ctrl-c it then the agent will be killed. Just enough to complete all the hunts.

**Comment by scudette** [comment]
Further information here https://docs.velociraptor.app/knowledge_base/tips/deploying_in_agentless_mode/#linux-environments
