### ISSUE TITLE
Wrong info grom stats.total_clients_with_errors

### ISSUE THREAD

**Issue by chaoticmachinery** [Velocidex/velociraptor#1670]
I was running the following VQL:
SELECT  hunt_id,artifacts, state, stats.total_clients_scheduled, stats.total_clients_with_results, stats.total_clients_without_results, stats.total_clients_with_errors  from hunts()

The column returned for stats.total_clients_with_errors always returns zeros. However, I have a couple of hunts where it shows some clients with ERRORs in the GUI interface. Unless the GUI gets the information differently, the VQL and GUI reporting should match.

**Comment by scudette** [comment]
Thanks for reporting this - it seems that total_clients_with_errors was just not updated at all. 

This should be fixed in #1672
