### ISSUE TITLE
Metadata tagging virtual machines

### ISSUE THREAD

**Issue by cr-AustinBollinger** [Velocidex/velociraptor#1671]
When deploying Velociraptor into virtualized environments, and performing collections - there can be resource spikes.

Is there or can there be some in-built template to flag endpoints checking in by their device model, ex:
`model: 'Parallels ARM Virtual Machine'`

It would be nice to be able to run more constrained hunts on virtual environments, when resources can sometimes be spread thin. Effectively, the capability for Velociraptor to auto-label hosts by their model, and or generically flag machines that are virtual, as such.

Thank you

**Comment by scudette** [comment]
You can include labels built into the config file and use the deployment system to automatically add them.

https://docs.velociraptor.app/docs/gui/clients/#built-in-labels

You can also automatically apply a label to clients based on any condition. For example this artifact applies labels based on if a user exists on the client but you can change it to any other condition:

https://docs.velociraptor.app/exchange/artifacts/pages/exchange.label.user/

You can also extend the Generic.Client.Info artifact by customizing it - Velociraptor will use the custom version when interrogating new clients.

But there may be a race condition when a new asset appears, as labeling may happen after the interrogation step but hunt scheduling may happen before the label is applied. So for example say you have a hunt that excludes all machines with the label "Small" and you use the above method to apply the label "Small" to machines with less than 1 gb ram. It may be that the hunt is schedule *before* the label is applied on a never before seen machine, and therefore it will still run it.

One option is to use a precondition in the artifact itself - the hunt will be scheduled, but the precodition will be applied and essentially skip doing anything if the machine has say < 1gb ram.

Another option is to schedule the hunt for:
1. Include labels of "Classified"
2. Exclude labels of "Small"

Then your classifier artifact as above sets both labels at the same time for small machines, and only the "Classified" label on large machines. This will delay the hunt scheduling until the labels are set and we have certainty about the size of the VM.

**Comment by scudette** [comment]
There is nothing required for this issue
