### ISSUE TITLE
Can't work with '|' (pipe) characters in grok or regex_replace

### ISSUE THREAD

**Issue by jcronenberg** [Velocidex/velociraptor#1686]
When trying to parse something with `|` characters in it, I can't get it to work with grok or regex_replace.
So e.g. if I have to following string `testing|with|pipes` I can't seperate the values with `grok()` or replace the `|`'s with `regex_replace()`

For example the following setup:
```
LET TestLine = "testing|with|pipes"
LET GROK_EXP = "%{DATA:first}\|%{DATA:second}\|%{GREEDYDATA:third}"

SELECT grok(grok=GROK_EXP, data=TestLine) FROM TestLine
SELECT regex_replace(re="\|", replace=" ", source=TestLine) FROM TestLine
```
returns the following:
![image](https://user-images.githubusercontent.com/54934253/161041644-f002526e-316f-4bd1-ad2f-b7a180ad5ad1.png)
![image](https://user-images.githubusercontent.com/54934253/161041716-fca61123-80da-4327-b5ae-ca3f99401f28.png)

I have tried a few online interpreters of grok and regex, like https://grokdebug.herokuapp.com/ or https://www.regextester.com/96554 and from what i found normally both are able to handle pipe characters, but not the velociraptor plugins.

**Comment by scudette** [comment]
https://docs.velociraptor.app/docs/vql/#string-constants

```sql
LET TestLine = "testing|with|pipes"
LET GROK_EXP = '''%{DATA:first}\|%{DATA:second}\|%{GREEDYDATA:third}'''

SELECT grok(grok=GROK_EXP, data=TestLine) FROM TestLine
SELECT regex_replace(re='''\|''', replace=" ", source=TestLine) FROM TestLine
```

**Comment by jcronenberg** [comment]
Ah I see, thank you!
