### ISSUE TITLE
USN Journal on all drives

### ISSUE THREAD

**Issue by gdms04** [Velocidex/velociraptor#1690]
On MFT artifact [Windows.NTFS.MFT], I found that there is an option to select "AllDrives" to search for MFT records in all drives. From the queries in the artifact, i found that there is a function [mftsearch] which helps to look for MFT in drives. May I ask if there is any similar functions I can use to search for USN journals on all drives of a windows host. Ultimately, I want to use artifact [Windows.Forensics.Usn] to parse all available USN journals of all drives on a windows host. Thanks!

**Comment by scudette** [comment]
Yes this makes sense to add this option to the USN artifacts as well.

**Comment by gdms04** [comment]
thx a lot!

**Comment by scudette** [comment]
Fixed by #1699 should be available in 0.6.4-rc3
