### ISSUE TITLE
Artifact Windows.System.Services doesn't collect all services

### ISSUE THREAD

**Issue by certrik** [Velocidex/velociraptor#1692]
When running Windows.System.Services on two Windows Server 2016 and two Windows 10 only some services are collected (TotalRows 3).
Using Velociraptor 0.6.3 .

**Comment by scudette** [comment]
This artifact is just an enriched version of the wmi. Did you specify any filtering to the artifact?

What does the following query give - more than 3 rows? (for example in the VQL shell feature):

```sql
SELECT * FROM wmi(query="SELECT * From Win32_service")
```

**Comment by certrik** [comment]
This query returns everything right it seems. But I didn't set any filters. I didn't change anything.

**Comment by scudette** [comment]
Ah excellent - this was already fixed for 0.6.4 👍🏽
