### ISSUE TITLE
Notebook issue with multiple artifacts in a single collection with v0.6.4-rc2

### ISSUE THREAD

**Issue by teddy-ROxPin** [Velocidex/velociraptor#1707]
Using 'velociraptor-v0.6.4-rc2-windows-amd64.exe gui', if I run a collection with multiple artifacts, only the first artifact that returns results will have a cell in that collection's notebook. I've tried deleting the notebook but the issue persists.

If I run the same artifacts against the same data using 'velociraptor-v0.6.3-windows-amd64.exe gui', each artifact that returns results will have its own cell in the collection's notebook.

**Comment by scudette** [comment]
Thanks for reporting this! It was a regression introduced by added the custom notebook per artifact feature.
