### ISSUE TITLE
Feature Request: S3 Bucket and/or SFTP Support

### ISSUE THREAD

**Issue by prolsen** [Velocidex/velociraptor#171]
In the example here, https://medium.com/velociraptor-ir/triage-with-velociraptor-pt-3-d6f63215f579 you use Google Buckets. 

Do you have plans to support any of the following:

- AWS S3 Bucket uploads
- SFTP

**Comment by scudette** [comment]
I think S3 buckets should be easy to support as well. SFTP might be more complex but should be doable - the challenge with SFTP is setting up the correct security model so you can safely upload your evidence to it (and someone can't just download it off the server again).  I think this is possible with SFTP but it might require some instructions to help people set it up correctly.

With GCS and AWS you can set up bucket credentials for write only i.e. the credentials are not allowed to download the data once it is up there nor can they list the content of the bucket (which would reveal other uploads).

I don't have any immediate plans to support S3 right now though but will happily accept PRs of course :-).

**Comment by prolsen** [comment]
@scudette can you point me to the specific code that implements the GCP bucket upload and ill give it a shot for S3. New to Go, but a good excuse to start learning it.

**Comment by scudette** [comment]
GCS uploader is implemented as a VQL function. Here is the code:
https://github.com/Velocidex/velociraptor/blob/master/vql/tools/gcs_upload.go

You can trigger the upload by calling the function from VQL:
```
SELECT upload_gcp(file=... ) FROM scope()
```

It would be awesome to have an `upload_s3()` function!

**Comment by hacktobeer** [comment]
@prolsen Submitted a PR for this [here](https://github.com/Velocidex/velociraptor/pull/199), feel free to clone and test.

**Comment by scudette** [comment]
This adds about 5mb to binary size - we will need to optimize it a little I think.

**Comment by hacktobeer** [comment]
That's not good, I'll have a look later this week if I can get rid of some imports by using AWS PutObject instead of the Upload library function. No idea if that helps but will try.

**Comment by scudette** [comment]
We had a similar experience with the elastic library. The library includes
objects with function pointers to their entire API so the compiler just
can't get rid of any unused functions. So important a single function
increased our size by 6mb. I ended up forking it and fixing their code a
bit.

Maybe there is a similar thing going on here. I need to take a look later.

Thanks
Mike

**Comment by scudette** [comment]
We had s3 support for a while so I am closing this. I think we can work on replacing with a lighter library as a separate issue.
