### ISSUE TITLE
Feature-Request: Mass import of collections done by the offline collector via GUI

### ISSUE THREAD

**Issue by certrik** [Velocidex/velociraptor#1748]
It would be a very useful feature to be able to mass import collections done via the offline collector. At the moment every ZIP archive has to be imported manually one at a time or be scripted via VQL in connection with a e.g. CSV making the process a bit cumbersome.
This probably could be done by making the Generic.Client.Info artifact mandatory for offline collection and make Velociraptor extract host info from this information to be able to bulk ingest collected ZIP archives from a provided path via Server.Utils.ImportCollection.
This could provide a valuable alternative to the "agentless" method making Velociraptor even more flexible. 
@scudette

**Comment by scudette** [comment]
With the introduction of the import_collection() VQL function it should be trivial to import many files using a quick notebook in VQL. See 

https://docs.velociraptor.app/vql_reference/server/import_collection/

Simply glob for the collection files and call import_collection() on each of them.
