### ISSUE TITLE
search specific event ID or files on a target host or set of hosts

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#175]
Is there a sample collector or hunt to 

a) search for specific event ID across fleet or a specific target host 
b) search / hunt for the presence of specific file or folder (by name) across target set of hosts ? 

Thanks

**Comment by scudette** [comment]
For a take a look at the Windows. EventLog.DHCP artifact.

For b you can use the standard filefinder artifact or modify it.

**Comment by siftuser** [comment]
Thanks @scudette !

How do I configure it to hunt for a known set of target hosts ?

**Comment by scudette** [comment]
When you set up your hunt you can specify a label to hunt on - just label your clients in a sensible way and only they will pick up the hunt.  You can label clients using the GUI or the label() vql function (if there are too many clients to do manually)

https://www.velocidex.com/docs/vql_reference/functions/#label

**Comment by siftuser** [comment]
Thanks! Super useful indeed!

Great tool & [documentation](https://www.velocidex.com/docs/user-interface/investigating_clients/searching_clients/)  Thank YOU!
