### ISSUE TITLE
Bug: GLIBC_2.28 not found when running v0.3.6

### ISSUE THREAD

**Issue by prolsen** [Velocidex/velociraptor#177]
Ran into this on both GCP and AWS Ubuntu 18.04 builds today. Worked fine last week so not sure if some updates by the cloud providers caused the below issue. Looking at the build date of the images, "amd64 bionic image built on 2019-11-13" it's possible this broke it.

**$ ./velociraptor-v0.3.6-linux-amd64**
./velociraptor-v0.3.6-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./velociraptor-v0.3.6-linux-amd64)

**$ uname -a**
Linux testing 5.0.0-1025-gcp #26~18.04.1-Ubuntu SMP Mon Nov 11 13:09:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**sudo apt-get install --only-upgrade libc6**
Reading package lists... Done
Building dependency tree
Reading state information... Done
**libc6 is already the newest version (2.27-3ubuntu1)**

**sudo dpkg -i libc6_2.28-0ubuntu1_amd64.deb**
dpkg: regarding libc6_2.28-0ubuntu1_amd64.deb containing libc6:amd64:
 libc6:amd64 breaks locales (<< 2.28)
  locales (version 2.27-3ubuntu1) is present and installed.

dpkg: error processing archive libc6_2.28-0ubuntu1_amd64.deb (--install):
 installing libc6:amd64 would break locales, and
 deconfiguration is not permitted (--auto-deconfigure might help)
Errors were encountered while processing:
 libc6_2.28-0ubuntu1_amd64.deb

**Version 0.3.5 works fine:**
./velociraptor-v0.3.5-linux-amd64
usage: velociraptor [<flags>] <command> [<args> ...]

An advanced incident response and monitoring agent.
<snip>

This (0.3.6) worked fine last week; so figured I would bring it up. I tried 16.04 and the same issues for 0.3.6

I decided to use, Debian 10 and it works. This seems like a good reference - https://pkgs.org/download/libc6-amd64

**Comment by scudette** [comment]
Yeah sorry - the previous release was built accidentally on ubuntu 19.10 which seems to be incompatible with older versions. 

I have re-uploaded a new linux build velociraptor-v0.3.6-linux-amd64.1 which was built on ubuntu 18.04.
