### ISSUE TITLE
Windows.Events.Trackaccount artifact not collecting all 4624 events

### ISSUE THREAD

**Issue by SDHDOCS** [Velocidex/velociraptor#1789]
When using the artifact Windows.Events.Trackaccount to monitor the client for logon events (event id 4624), only events from some users are recorded and some are not recorded. When I checked the Security.evtx log of the client for 4624 events, all logon events are recorded. But velociraptor is not fetching all the events.Please give a solution or steps to troubleshoot the issue.

**Comment by scudette** [comment]
Did you update the user regex parameter to include the users you wanted to see? The default regex is `admin|user` - what was the user you were expecting to alert on?

**Comment by scudette** [comment]
If this is still an issue for 0.6.7-4 please reopen
