### ISSUE TITLE
Feature Request: Configurable Quarantine Button

### ISSUE THREAD

**Issue by kingaling** [Velocidex/velociraptor#1796]
Would it be possible to have the quarantine button be configurable? Right now it triggers the Windows.Remediation.Quarantine artifact. It would be beneficial to have the quarantine artifact be configurable as most environments (I would imagine) have more than one endpoint security solution that require more than just the Velociraptor executable to be allow through the firewall. You can make changes to it but it will be saved as Custom.Windows.Remediation.Quarantine which the button doesn't point to.

**Comment by scudette** [comment]
Fixed by https://github.com/Velocidex/velociraptor/pull/1810 where users can now create a custom version of the different artifact definitions that will be launched instead of the built in version when the button is clicked.
