### ISSUE TITLE
Feature-Request: Add possibility to calculate Trend-Micro Locality Sensitive Hash (TLSH)

### ISSUE THREAD

**Issue by certrik** [Velocidex/velociraptor#1799]
Including Trend-Micro Locality Sensitive Hash (TLSH) as plugin for VQL to Velociraptor via e.g. https://github.com/glaslos/tlsh would allow to generate fuzzy-hashes of files on clients to be able query the hashes via a server artifact on VirusTotal or abuse.ch MalwareBazaar (https://bazaar.abuse.ch/). This could allow enriching data with possible malware similarities based on TLSH further easing triage using Velociraptor.

**Comment by certrik** [comment]
@scudette Is this request something to be considered?

**Comment by certrik** [comment]
@scudette Would you consider this for 0.6.7?

**Comment by weslambert** [comment]
Here is a quick artifact to compute this hash from a file:

https://gist.github.com/weslambert/ab98195cec7575a29d4013948acad05a
