### ISSUE TITLE
404 page not found when user logs off 

### ISSUE THREAD

**Issue by LPT6166676c** [Velocidex/velociraptor#1806]
When a user logs off the server a '404 page not found' page is presented. Server version 0.6.4-2
![Screenshot 2022-05-25 115551](https://user-images.githubusercontent.com/78862024/170246865-0b946f9a-ed1f-481c-8d4d-4170073806e0.png)

**Comment by scudette** [comment]
This only happens when using the Basic authenticator.

Fixed in https://github.com/Velocidex/velociraptor/pull/1835
