### ISSUE TITLE
Bug: When using || with null value, "" evaluates to false

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#1812]
When using `||`, `""`  (Ex. `NULL  | | ""`)currently evaluates to `false`. Using `" "` works, but is not the expected behavior.

Ex.

```
SELECT "X" = (NULL || "X"), "" = (NULL || "")
FROM scope()
```

Results in:

`true, false` 

instead of 

`true, true`

**Comment by scudette** [comment]
Fixed by https://github.com/Velocidex/vfilter/pull/61
