### ISSUE TITLE
Feature Question: Zircolite

### ISSUE THREAD

**Issue by Salva2000HD** [Velocidex/velociraptor#1822]
Good Morning.
In Zircolite page (on Artifact Exchange) you said "This artifact currently supports usage of the built-in rulesets. Support for custom ruleset usage will be added in the future.".
Can you tell me the estimated time for this feature add? 
Thanks in advance.

**Comment by weslambert** [comment]
I'll see if I can get it added in the next week or so. 😄

**Comment by FrancescoFaenzi** [comment]
This is super-intersting. It would be awesome to launch specific SIGMA-based Zircolite rules as Velociraptor hunts. @weslambert have you got news about this? Besides that, do you need any help in this effort. I have a pretty huge lab to roll out new experimental features and test them... just let me know?

**Comment by weslambert** [comment]
Sorry, this slipped off my radar. Should have it updated very soon!

**Comment by FrancescoFaenzi** [comment]
> Sorry, this slipped off my radar. Should have it updated very soon!

Awesome! Let me repeat : should you think having a second huge lab could be useful, don't hesitate to ask.

**Comment by weslambert** [comment]
I made a quick change here: https://github.com/Velocidex/velociraptor-docs/pull/312. Let me know if that performs as you would expect.

**Comment by scudette** [comment]
If this is still an issue for 0.6.7-4 please reopen
