### ISSUE TITLE
Error when using logical volume with BulkExtractor

### ISSUE THREAD

**Issue by mpilking** [Velocidex/velociraptor#1828]
An error occurs when trying to search the logical volume using `Windows.Forensics.BulkExtractor`. For example, changing the target from `\\.\PhysicalDrive0` to `\\.\C:`. This is because a temp directory gets created based on the name of this target path, but Windows can't create a directory with a colon `:` in it. So an error like the following shows up:

`Could not make directory C:\Users\MPILKI~1\AppData\Local\Temp\temp\tmp430626\C:`

If I copy the built-in artifact and adjust line 80 from:

```
FROM execve(argv=cmdline[0].CMD + (tempfolder + '\\' + base, DeviceID)
```

to:

```
FROM execve(argv=cmdline[0].CMD + (tempfolder + '\\' + 'C', DeviceID)
```

it works as expected.

Searching the logical volume is a useful capability to be able to search after decryption of bitlocker drives (I did some testing to verify this). In fact, I wonder if it should be the default? Or at least make a note of it as a reminder to analysts.

**Comment by scudette** [comment]
Fixed in #1844
