### ISSUE TITLE
Feature request: netstat to show application that's using a port

### ISSUE THREAD

**Issue by shakarama** [Velocidex/velociraptor#184]
Hello, I think that it would be very useful to have netstat plugin to show application that's using the port, like netstat switches "-b" on windows or  "-p" on linux.
Not sure about dependencies and libraries that enable this plugin so I hope it's possible.

**Comment by scudette** [comment]
Do you mean this https://www.velocidex.com/docs/vql_reference/plugins/#netstat 

You can collect it with the Windows.Network.Netstat artifact. That artifact currently just shows the Pid which is not ideal - you can modify it by adding additional fields to it - for example:
```
sources:
- precondition: SELECT OS From info() where OS = 'windows'
  queries:
  - LET processes <= SELECT Name, Pid AS ProcPid FROM pslist()
  - SELECT Pid, { 
              SELECT Name from processes 
              WHERE Pid = ProcPid
           } AS Name, FamilyString as Family,
           TypeString as Type,
           Status,
           Laddr.IP, Laddr.Port,
           Raddr.IP, Raddr.Port,
           Timestamp
           FROM netstat()
```

The first query does a process listing and then we can call a sub query for each row to enrich with the name of the process matched by the PID.

I will add this field to the artifact :-).

**Comment by shakarama** [comment]
Oh, sry I didn't realize the Pid in netstat() before opening this request...  thanks for upgrading the Windows artifact!
