### ISSUE TITLE
Check over German translation file

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#1864]
We need a native speaker to check over the German translation file 

https://github.com/Velocidex/velociraptor/blob/master/gui/velociraptor/src/components/i8n/de.js

This file was automatically generated by Google Translate and may have subtle issues.

If you are a native level speaker and would like to help can you please comment on this issue or reassign the issue to you? This way we can know that someone has it covered and avoid replicating work.

**Comment by sch-raub** [comment]
hi, I'm a German native speaker and can review the Google translation. How would you like me to provide my corrections?

**Comment by scudette** [comment]
Thank you kindly 😊 really appreciated 👍

you can simply click the link above then select edit in the GUI and edit directly in the GUI.

 Then click save to prepare a PR.

 Otherwise you can simply edit the de.js file and attach to this issue if that's easier.

**Comment by scudette** [comment]
@deetl is this PR #1872 ok to merge?

**Comment by deetl** [comment]
I think it is not necessary to merge #1872 as #1875 also covers all changes. At least, the master brach looks good.

**Comment by scudette** [comment]
Ahh thanks 👍 I didn't realize it was merged. Thanks again!

We can close this issue.
