### ISSUE TITLE
Check over Spanish translation

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#1865]
We need a native speaker to check over the Spanish translation file 

https://github.com/Velocidex/velociraptor/blob/master/gui/velociraptor/src/components/i8n/es.js

This file was automatically generated by Google Translate and may have subtle issues.

If you are a native level speaker and would like to help can you please comment on this issue or reassign the issue to you? This way we can know that someone has it covered and avoid replicating work.

**Comment by fhidalgo** [comment]
Hi there, I'm a Spanish native speaker and I'd love to help with this issue.

**Comment by scudette** [comment]
Thank you @fhidalgo much appreciated!

**Comment by fhidalgo** [comment]
[es.zip](https://github.com/Velocidex/velociraptor/files/8975526/es.zip)

Hello,

Here is the reviewed version. Sorry for the delay. Feel free to reach me back if there is something wrong with the translation (maybe some word will need tweaking due to lack of context).

Regards,
Fernando

**Comment by scudette** [comment]
Thanks for this - we can close the issue as it is in the current release. Thanks again!
