### ISSUE TITLE
Check over Portuguese translations

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#1866]
We need a native speaker to check over the Portuguese translation file 

https://github.com/Velocidex/velociraptor/blob/master/gui/velociraptor/src/components/i8n/por.js

This file was automatically generated by Google Translate and may have subtle issues.

@eduardomcm can you please take a look ?

**Comment by eduardomcm** [comment]
Working on it!

**Comment by scudette** [comment]
Fixed by #1876
