### ISSUE TITLE
Persistence artifacts parsing binaries inside of launch string

### ISSUE THREAD

**Issue by ecapuano** [Velocidex/velociraptor#1885]
Per this [conversation](https://discord.com/channels/624244632552734750/624244632552734752/988460906591715419) in Discord, I wanted to call attention to this undesired behavior of a couple persistence artifacts. 

The results of certain artifacts like `Windows.Sys.StartupItems` tend to bring back results that are difficult to manage due to massive blocks of non-printable characters getting pulled into the CSV for things like binaries... It's not only messy ,but makes the results very difficult to sort through, and even causes lag in the UI at times.

See the following results from `Windows.Sys.StartupItems`, the "Command" (aka LaunchString) contains non-printable chars for things like EXEs or HTAs, etc.

![image](https://user-images.githubusercontent.com/4219694/174639063-fa26ec2c-3953-431c-816a-d31141311e5f.png)

In the event of an EXE, this block of non-printable chars could be massive which makes these results incredibly difficult to deal with.

Where this behavior could be detrimental to a hunter is that LNK files are not being parsed to show their true destination.

For example, here is a the same entry from both `Windows.Sys.StartupItems` and `Windows.Sysinternals.Autoruns`

![image](https://user-images.githubusercontent.com/4219694/174639463-0089c9d2-0cf4-48c8-bb24-c5ca6f84fea0.png)

Notice the `ImagePath` extracted by `Autorunsc` reveals the true destination of the LNK file, which is a very suspicious `svchost.exe`

![image](https://user-images.githubusercontent.com/4219694/174639823-3b71b567-5daf-448a-92c7-f4cffeb36f06.png)

Now it may or may not be useful to teach `Windows.Sys.StartupItems` to parse LNK files, but at the very least, we should refrain from bringing contents of binaries back in the results of these hunts.

**Comment by ecapuano** [comment]
As @scudette brought up in Discord, seems to be caused by how the file is being read in by this artifact. https://github.com/Velocidex/velociraptor/blob/592506360be1741b23e87627e8c30411dfd75039/artifacts/definitions/Windows/Sys/StartupItems.yaml#L58

**Comment by scudette** [comment]
Windows.Sys.StartupItems now has per type display and can parse lnk files automatically

![image](https://user-images.githubusercontent.com/3856546/175245311-0c316f99-4978-44d8-8e29-025af31382e3.png)
