### ISSUE TITLE
Windows.KapeFiles.Targets inconsistent results

### ISSUE THREAD

**Issue by do-not-look** [Velocidex/velociraptor#1905]
Hello,
I've done some comparison between using Kape by itself vs Kape via Velociraptor.
Shockingly I've noticed that the results differ by a lot. The uncompressed evidence size is less than 50%. First I thought that some evidence simply just have not been extracted. But when I further looked into it, I noticed that the extracted files have different hashsum (filesize) from the original.

I've tried this in Velociraptor V0.6.3-1 and the latest release V0.6.5.
The Hunt was done with following parameters:

```
...
  "artifacts": [
    "Windows.KapeFiles.Targets"
  ],
  "specs": [
    {
      "artifact": "Windows.KapeFiles.Targets",
      "parameters": {
        "env": [
          {
            "key": "VSSAnalysis",
            "value": "Y"
          },
          {
            "key": "_SANS_Triage",
            "value": "Y"
          },
          {
            "key": "DontBeLazy",
            "value": "Y"
          }
        ]
      }
    }
  ],
  "timeout": "99999",
  "max_upload_bytes": "10485760000",
....
```

The Kape image was created on a 1TB drive. And only the SANS_Triage Target was selected. I've also tried to play around with the settings: "DontBeLazy" and "UseAutoAccessor", but the results stayed the same.

The uploaded PNG shows the difference between each setup. Left side was created by the latest Kape version, right side the image was created via Windows.KapeFiles.Targets.
![velo-kape-tshoot](https://user-images.githubusercontent.com/108124141/175506017-ab726e2f-3e46-4761-8392-65dfb24a7006.PNG)

**Comment by scudette** [comment]
It is hard to know what the differences are - can you please attach a recursive directory listing of the two acquisitions?

One potential different is that Velociraptor handles sparse files a bit differently (e.g the $J file is usually very sparse). Velociraptor only stores the non sparse regions of the file and adds an idx file which describes the sparse layout.

**Comment by do-not-look** [comment]
Reviewing this issue with the knowledge how Velociraptor handles sparse files makes much more sense. This will result in different filesize & hashes, but the actual data of the file stays the same.
Best example for this would be the file C:\ProgramData\Microsoft\search\data\applications\windows\Windows.edb file. On the Kape image it has the size of ~4,7GB and on the Velociraptor side it has a size of ~0,7GB + 50KB of an .idx file

The major difference, which propably causes the different packed (compressed) file size is that Velociraptor did not extract the $MFT file from all VSS "folders". These files have a packed size of ~107MB.

The zipped Kape image has a size of ~991 MB and the Velociraptor zipped Kape image has a size of ~661 MB. Since 3 VSS $MFT files are missing they are almost equal in size, which is the expected result for me.

Initially I thought that both solutions, raw kape vs Kape via Velociraptor would be identical, since I expected Velo to simply execute the Kape executable. But that is not the case, they do the imaging on their own manner.
Since this is not an issue I'll close this. 
Thanks for the explanation and help!
