### ISSUE TITLE
Velociraptor client on Windows keeps bloating in memory usage

### ISSUE THREAD

**Issue by shakarama** [Velocidex/velociraptor#192]
Hello, we configured several Windows clients to test constant shipping of some security and sysmon events to Velociraptor server and we noticed that the client often bloats in memory usage until it's restarted.
We can't check all of the clients but on test machines the behaviour is consistent.
Clients are the latest version 0.3.6.
Example screenshots of process RAM usage and uptime are attached.

Is this expected behaviour or should Velociraptor be able to continuously ship logs from clients?

![Velociraptor_RAM_1](https://user-images.githubusercontent.com/31079715/70225245-f3990080-174e-11ea-83fb-0fe77edbf070.png)
![Velociraptor_RAM_2](https://user-images.githubusercontent.com/31079715/70225246-f4319700-174e-11ea-80ce-3741a4b9c660.png)
![Velociraptor_RAM_3](https://user-images.githubusercontent.com/31079715/70225248-f4319700-174e-11ea-9870-621963db4e3c.png)

**Comment by scudette** [comment]
No this is not expected. Typically memory use is 30-50mb. What event queries (client monitoring queries) are you running?  It is possible that there is a memory leak so we need to chase it down.

If you start the client with debug flag (i.e. --debug) you can then connect to the debug server and get an idea of what is using the memory up

![image](https://user-images.githubusercontent.com/3856546/70225658-2d8ff400-179b-11ea-9c52-e220c039dd58.png)

Can you please attach the output from the heaps view:
![image](https://user-images.githubusercontent.com/3856546/70225821-8069ab80-179b-11ea-8ede-83e8ce2568a0.png)

**Comment by scudette** [comment]
Thanks for reporting! I think I tracked it down to a go routine leak. Looking at the go routine profile in the debug server shows an increasing number of goroutines:

![image](https://user-images.githubusercontent.com/3856546/70236601-f9273280-17b0-11ea-9f17-c82d347920bf.png)

This is created by the following backtrace:

![image](https://user-images.githubusercontent.com/3856546/70236668-1fe56900-17b1-11ea-965b-837c7d620089.png)

So what is happening is that the event log watcher tries to open the file every few seconds and each time it is leaking a go routine. Over time this will lead to a memory leak.

**Comment by scudette** [comment]
Really appreciate this report!! Just in time for the next 0.3.7 release :-).

**Comment by shakarama** [comment]
> 
> 
> Really appreciate this report!! Just in time for the next 0.3.7 release :-).

Thanks for the fast response, I didn't even upload my heaps, looking forward to 0.3.7. :)
