### ISSUE TITLE
Incorrect math with an integer and a float

### ISSUE THREAD

**Issue by crford** [Velocidex/velociraptor#1928]
When doing subtraction or division on an integer and a float, where the float is not the first factor in the equation, the float is handled incorrectly resulting in incorrect results.  I ran into this when walking through the Slack notification for a client coming online example, when I was getting negative "lastseen" times.

For example:
Subtracting a float from an integer results in the inverse of the correct answer, ie. `4 - 2.0 = -2`
When dividing an integer by a float, the decimal point is removed from the float and it's treated like an integer, ie 2.0 becomes 20.  `4 / 2.0 = 0.5`

I was originally on 0.6.4-2 on Ubuntu 22.04, I upgraded to 0.6.5 and the behavior stayed.
Built a new box on Ubuntu 20.04 and 0.6.5 and behavior was there in a default Self-Signed SSL configuration.
Tried the same math in a generic go script on Go version 1.18.1 and the behavior was not present.

Screenshot with additional tests as run in a VQL notebook:
![velo-bug](https://user-images.githubusercontent.com/34066604/177681947-eb946efc-aff1-42b7-9dcf-56cf7e745e55.png)

**Comment by scudette** [comment]
This fix should be in head now.

**Comment by crford** [comment]
Confirming the fix resolved my issue.  Thanks for the fast turnaround!
