### ISSUE TITLE
Unable to Download Hunting Tools

### ISSUE THREAD

**Issue by Cyopeng** [Velocidex/velociraptor#1929]
I have been having issues trying to run certain hunts as it requires the download of tools. For example, when trying to run the Windows.Applications.NirsoftBrowserViewer hunt, I need to download NirsoftBrowsingHistoryView64.

When trying to launch the hunt it shows "Checking NirsoftBrowsingHistoryView64"

[INFO] 2022-07-07T16:24:17-04:00 Downloading tool NirsoftBrowsingHistoryView64 FROM https://github.com/Velocidex/Tools/raw/main/BrowsingHistoryView/BrowsingHistoryView-amd64.exe
[ERROR] 2022-07-07T16:24:17-04:00  {"error":"{\"code\":2, \"message\":\"Get [\\\"https://github.com/Velocidex/Tools/raw/main/BrowsingHistoryView/BrowsingHistoryView-amd64.exe\\\](file:///%22https:/github.com/Velocidex/Tools/raw/main/BrowsingHistoryView/BrowsingHistoryView-amd64.exe/)": Bad Request\"}","method":

Wasn't sure where to start with this. Do I need to make a configuration change for a corporate Proxy?

**Comment by mgreen27** [comment]
The tool component will try to download the tool from the url provided. Sometimes we see issues with github blocking connections.

Can you try to upload and serve it locally from your Velociraptor server?

![image](https://user-images.githubusercontent.com/13081800/177913451-e1eb4dad-9a9b-46cf-8e1b-dad5db625828.png)
