### ISSUE TITLE
Feature Request: Multiple Configurable Clocks in bottom of Web GUI

### ISSUE THREAD

**Issue by kiyori-lw** [Velocidex/velociraptor#1932]
Currently using version: 0.6.5

Request to add multiple clocks to the bottom of the web GUI.  Currently, I only see 1 clock in Zulu at bottom right.

It would be super to have multiple clocks that we could choose time zones for across the bottom of the web GUI to account for users & systems that are in different timezones
![clocks request](https://user-images.githubusercontent.com/109005472/178126516-66eba59f-38cc-4d2e-baf8-1f2ea42f2256.PNG)
.

**Comment by scudette** [comment]
That feature was most useful for understanding times in the GUI when times were always presented in utc. Since 0.6.5 presentation times are settable in the GUI the any time zone so this is less important.

Maybe we should change the clock time zone to also be settable by the GUI?

**Comment by kiyori-lw** [comment]
Changing the clock time zone via the GUI would be nice too.  I guess this  is more like a "convenience" feature request.  It would be nice to be like "what time is it in Hawaii?" and then look at the bottom bar and see it quickly; vice using a different app like normal Windows clock or a website.

Kind of something like this
![clocks request2](https://user-images.githubusercontent.com/109005472/178127024-bdc79fcd-bd4a-4d84-856a-297684874015.PNG)
:

**Comment by scudette** [comment]
The clock at the bottom is now aware of the timezone selected in the user preferences and so shows the time in that timezone.
