### ISSUE TITLE
sftp offline collector issue

### ISSUE THREAD

**Issue by crrim** [Velocidex/velociraptor#1947]
I can successfully build an offline collector via the GUI that uploads the collection as expected to the given sftp server.
The endpoint the offline collector runs on is MacOS

When I try build similar via the commandline using a custom .yaml file, I continually get the error:
upload_SFTP: ssh: no key found

build executable:
./velociraptor_client config repack test_vel.yaml test_run

**yaml file:**

autoexec:
  argv: ["artifacts", "collect", "-v", "UploadToSFTP"]
  artifact_definitions:
    - name: UploadToSFTP
      sources:
         - queries:
              # This collects the MacOS.Applications.Chrome.History into
              # a tempfile, then uploads the tempfile to SFTP with the added privatekey
              - SELECT upload_sftp(
                   file=Container,
                   user="REDACTED",
                   endpoint="REDACTED:2022",
                   name=format(format="Collection %s.zip", args=[timestamp(epoch=now())]),
                   privatekey="REDACTED"
                   hostkey="") AS Uploaded
                FROM collect(
                   artifacts="MacOS.Applications.Chrome.History",
                   output=tempfile( extension=".zip"))
                   
**error:**
upload_SFTP: ssh: no key found

I do see it picks up the variable  "endpoint" as expected, but never the "privatekey" string

**Comment by scudette** [comment]
It is likely that you have something wrong with the escaping in the private key block (for example the line breaks) so it is an invalid key

I would suggest to have the key in a parameter just like the GUI does it and then retrieve it from the parameters in the vql. This is much easier than having to escape an inline string properly.

You can always see how the GUI creates the config by running velociraptor config show on the collector exe.

See this for more information

https://docs.velociraptor.app/knowledge_base/tips/reconfigure_offline_collector/

**Comment by crrim** [comment]
Thanks you! Much obliged.

outputting the GUI version of the working collector config was a big help. What worked for me in the end was adding this line to pull in the sftp parameters:
- LET TargetArgs <= SFTPkey 

I'd tried various versions of the privatekey string, with and without line breaks, copying across what was used in GUI config version fixed it.

**adjusted config working**:
`autoexec:
  # These parameters are run when the binary is started without args. 
  # It will just collect our custom artifact and quit.
  argv: ["artifacts", "collect", "-v", "UploadToSFTP"]
  artifact_definitions:
    - name: UploadToSFTP
      parameters:
         - name: SFTPkey
           default: |-
            {
             "bucket": "",
             "GCSKey": "",
             "credentialsKey": "",
             "credentialsSecret": "",
             "region": "",
             "endpoint": "REDACTED",
             "serverSideEncryption": "",
             "privatekey":"REDACTED"
             "user": "veloc"
            }
           type: json
      sources:
         - queries:
              # This collects the WebBrowsers target from KapeFiles into 
              # a tempfile, then uploads the tempfile to SFTP with the 
              # above credentials.
              - LET TargetArgs <= SFTPkey 
              - SELECT upload_sftp(
                   file=Container,
                   user=TargetArgs.user,
                   path=TargetArgs.path,
                   privatekey=TargetArgs.privatekey,
                   name=format(format="Collection %s.zip", args=[timestamp(epoch=now())]),
                   endpoint=TargetArgs.endpoint) AS Uploaded  
                FROM collect(
                   artifacts="MacOS.Applications.Chrome.History",
                   output=tempfile( extension=".zip"))
`

**Comment by scudette** [comment]
You should be able to use the SFTPKey variable directly instead of assigning it first to another variable:
```sql
          SELECT upload_sftp(
                   file=Container,
                   user=SFTPkey.user,
                   path=SFTPkey.path,
                   privatekey=SFTPkey.privatekey,
                   name=format(format="Collection %s.zip", args=[timestamp(epoch=now())]),
                   endpoint=SFTPkey.endpoint) AS Uploaded  
                FROM collect(
                   artifacts="MacOS.Applications.Chrome.History",
                   output=tempfile( extension=".zip"))
```

**Comment by crrim** [comment]
Yes, correct, adjusted and working.
I think I'd ran it like that previously, but had missed out one of the variables, so failed.
**removed LET TargetArgs <= SFTPkey**

thanks!

```autoexec:
  # These parameters are run when the binary is started without args. 
  # It will just collect our custom artifact and quit.
  argv: ["artifacts", "collect", "-v", "UploadToSFTP"]
  artifact_definitions:
    - name: UploadToSFTP
      parameters:
         - name: SFTPkey
           default: |-
            {
             "bucket": "",
             "GCSKey": "",
             "credentialsKey": "",
             "credentialsSecret": "",
             "region": "",
             "endpoint": "REDACTED",
             "serverSideEncryption": "",
             "privatekey": "REDACTED" 
             "user": "veloc"
            }
           type: json
      sources:
         - queries:
              # This collects the WebBrowsers target from KapeFiles into 
              # a tempfile, then uploads the tempfile to SFTP with the 
              # above credentials.
              - SELECT upload_sftp(
                   file=Container,
                   user=SFTPkey.user,
                   path=SFTPkey.path,
                   privatekey=SFTPkey.privatekey,
                   name=format(format="Collection %s.zip", args=[timestamp(epoch=now())]),
                   endpoint=SFTPkey.endpoint) AS Uploaded  
                FROM collect(
                   artifacts="MacOS.Applications.Chrome.History",
                   output=tempfile( extension=".zip"))```

**Comment by scudette** [comment]
This is resolved.
