### ISSUE TITLE
I am getting a This site can’t provide a secure connection after enabling SSO 

### ISSUE THREAD

**Issue by dgilmore82** [Velocidex/velociraptor#1954]
Hello 

After working with our SSO team I was able to get Velociraptor to talking to Azura but, there seemed to be an issue with my account on their side. Once this was resolved I enabled SSO again and got the following message. 

![image](https://user-images.githubusercontent.com/104925486/180492936-c30e6d1c-2d39-4ba0-be62-d4364c015ab5.png)

I was able to talk to the authenticator at first but now i can not, is there something I need to adjust in the server.config file to resolve this?

**Comment by scudette** [comment]
It looks like some of the urls are using plain http. Maybe the redirect url in the oauth config ?

Or maybe the server is configured to use plain http instead of tls?

**Comment by dgilmore82** [comment]
I saw the following read.me file:
https://github.com/Velocidex/velociraptor/tree/master/docs/saml

Do I need to set up my server config file to resemble what is in the link?

**Comment by scudette** [comment]
It depends what authentication method you want to use. I would recommend against saml because it seems a bit more complex to set up. Azure can provide both saml and oauth so I would recommend to just use oauth.

Here is how to enable it in azure

https://docs.velociraptor.app/blog/2020/2020-08-17-velociraptor-sso-authentication-6dd68d46dccf/#microsoft-azure-oauth2-flow

**Comment by dgilmore82** [comment]
Hello @scudette Thank you so much for that information. We followed the steps in that documentation you provided and it looks like everything is set up on the Azure side, just looks like I may be missing something on the Velociraptor side, just not sure what the issue could be at the moment.

**Comment by scudette** [comment]
From velociraptor there are only a couple of steps. First, when you go to the site, velociraptor should redirect to azure. Then after you do the oauth steps on the azure servers, the browser redirects back to velociraptor.

In your case do you get the first redirect? Are you seeing the azure oauth dialog?

You can capture the second redirect in the dev tools and see the url is using tls, then the auth cookies should be present.

**Comment by dgilmore82** [comment]
It looks like it is hitting Azure page then after i enter my credentials it  redirects  to the application. that's when i get the "this site can't provide a secure connection error.

**Comment by scudette** [comment]
It looks like the browser is trying to access an SSL page but the server is not serving over SSL at all. Did you add the use_plain_http option to the config file? Do you have some kind of reverse proxy in front?

Does the redirect URL start with https?

**Comment by dgilmore82** [comment]
I didn't know the use_plain_http option existed so no I did not add it to the config file. Greatly appreciate you bringing that up though. We do have a proxy but it is using https.

**Comment by dgilmore82** [comment]
Hello @scudette it looks like we may have solved the redirect issues but now the application is saying the user we have added to the system already is not registered. 

<img width="918" alt="No user found" src="https://user-images.githubusercontent.com/104925486/184160373-ba1ed3bc-5769-48cc-b548-f854d461fb15.PNG">

Here you can see that account is registered on the system
<img width="956" alt="SAML user" src="https://user-images.githubusercontent.com/104925486/184160555-71fd918d-e207-4d6b-9f3d-7328b125dac9.PNG">


Any idea why we might be getting this error?

**Comment by dgilmore82** [comment]
Its showing that the account has a role of administrator 

![image](https://user-images.githubusercontent.com/104925486/184197643-5288557d-eda6-4080-b66c-1f0a5952e71c.png)

**Comment by scudette** [comment]
I would check the file permissions of the acl files to make sure something didnt go wrong in creating the acl. You need to become the velociraptor user whenever running any commands like above:

```
sudo -u velociraptor bash
velociraptor acl show mic
```

if you do not it is like that the acl files take the wrong permission then the server can not read them.

**Comment by dgilmore82** [comment]
We finally got it to work!!  It looks like it was just a case sensitivity  issue, we needed to make the username exactly as it was in Azura.  I do have one last question, is there away to adjust the session timeout for the GUI of Velociraptor? I have been looking for away to adjust it but I haven't had any luck so far. Would greatly appreciate any insight on this.

**Comment by scudette** [comment]
Sessions are set to 24 hours before a reauth. Do you want to make it less or more?

**Comment by scudette** [comment]
The session length is now configurable in the config file.
