### ISSUE TITLE
Server binary generation: Master/Minon RPM packages

### ISSUE THREAD

**Issue by svch0stz** [Velocidex/velociraptor#1967]
When generating binary packages for the master and minion servers, the rpm command below only generates one .rpm file
``` 
velociraptor --config /etc/velociraptor/server.config.yaml rpm server
```
Expected behaviour is to generate a .rpm per frontend defined in the server config. The equivalent debian command works to produce the multiple server binaries.

**Comment by scudette** [comment]
Fixed by #1991
