### ISSUE TITLE
Additional formatters for reducing the amount of line wrap in certain columns

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#1970]
It would be great to specify additional formatters or CSS to prevent line-wrapping for smaller, but important values like `timestamp` or `ip`, or even if you were able to specify an option to pad/push certain columns or specific the number of characters before the line wrap.

**Comment by scudette** [comment]
This is now fixed in 0.6.9 - define the column type as `nobreak` to attach a no break class to it.

https://github.com/Velocidex/velociraptor/blob/a785b16c6213b791c2c78cf34f913c4e1c94023e/gui/velociraptor/src/components/core/table.jsx#L497
