### ISSUE TITLE
No .msi asset for version v0.6.5-2

### ISSUE THREAD

**Issue by phox142** [Velocidex/velociraptor#1971]
There was no .msi asset for version v0.6.5-2.  
Should it be possible to release it ? We use it for automatic deploy.

**Comment by scudette** [comment]
0.6.5-2 was a server side fix so I didn't bother making an msi. But we can publish an msi just in case anyway.

**Comment by phox142** [comment]
It seems me better and avoid to have multiple "version" on a network. 
Thanks for you answer
