### ISSUE TITLE
Context Menu or Special Handlers for Certain Column Types or Values

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#2026]
It would be great to be able to offer a menu of selections or special handlers for acting on data from certain columns, or of a certain (data) type from the GUI.

For example, user or deployment-configurable URLs or GET/POST requests utilizing data supplied from cells (within the GUI). 

Ex. Click on cell containing binary data , then offer a list of selections of how to act on that particular data.

Also consider functions necessary to perform encoding for URLs, etc.

**Comment by mgreen27** [comment]
@weslambert I ave been adding some decoding functions as I hit a need for them in engagements. Unforuantely they may not all be easy to find!

For URL decoding you can do this: https://docs.velociraptor.app/knowledge_base/tips/urldecode/

**Comment by scudette** [comment]
Sending to cyberchef will cover the easy use cases and make them applicable in the gui - it will also cover off on most use cases we can think of and future proof it. Sure it is more powerful to do it in VQL but sometimes we just need a quick and dirty decode. So I see this feature as orthogonal to the VQL functions which are also important

**Comment by weslambert** [comment]
> @weslambert I ave been adding some decoding functions as I hit a need for them in engagements. Unforuantely they may not all be easy to find!
> 
> For URL decoding you can do this: https://docs.velociraptor.app/knowledge_base/tips/urldecode/

Thanks @mgreen27! In this case, I was just referring to having a way to ensure that URLs defined in the action selection would be able to be encoded appropriately as needed. I will definitely check out what you have referenced!

**Comment by weslambert** [comment]
> Sending to cyberchef will cover the easy use cases and make them applicable in the gui - it will also cover off on most use cases we can think of and future proof it. Sure it is more powerful to do it in VQL but sometimes we just need a quick and dirty decode. So I see this feature as orthogonal to the VQL functions which are also important

Right, CyberChef is a great example.

**Comment by mgreen27** [comment]
> > @weslambert I ave been adding some decoding functions as I hit a need for them in engagements. Unforuantely they may not all be easy to find!
> > For URL decoding you can do this: https://docs.velociraptor.app/knowledge_base/tips/urldecode/
> 
> Thanks @mgreen27! In this case, I was just referring to having a way to ensure that URLs defined in the action selection would be able to be encoded appropriately as needed. I will definitely check out what you have referenced!

Got it. In this case you would do the opposite to URL encode relevant characters.

**Comment by scudette** [comment]
Fixed and added in #2039
