### ISSUE TITLE
watch_evtx overwrites UserData key with Message

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#203]
With 0.3.7 parse_evtx() creates a new Message field for the interpolated message string but watch_evtx() places it in UserData, which would presumably overwrite existing data in that field if it exists.

I couldn't find where this is happening in the code but it seems likely to be a field name misplacement... somewhere.

An obvious temporary workaround is to use UserData AS Message in the VQL, but we could be losing the original UserData contents due to the potential overwrite.

**Comment by scudette** [comment]
This does not appear to be the case in current version

![image](https://user-images.githubusercontent.com/3856546/75612049-d1572900-5b6b-11ea-9a95-914ca870447b.png)

Please re-open if I missed something
