### ISSUE TITLE
Create Pslist artifact for MacOS

### ISSUE THREAD

**Issue by mpilking** [Velocidex/velociraptor#2038]
I'm using 0.6.6rc1 and do not see a `pslist` artifact for MacOS. 

I copied `Linux.Sys.Pslist` and changed the Precondition from `OS = 'linux'` to `OS = 'darwin'` and works well. So I think that's all that's needed.

**Comment by scudette** [comment]
It is now possible to define aliases for artifacts added in #2190 This solves the issue of all the artifacts that work equally well on linux and macos so we do not need to be duplicated.
