### ISSUE TITLE
Password Password Protected Installation

### ISSUE THREAD

**Issue by mgdevsoft** [Velocidex/velociraptor#2043]
Hi,
It will be nice to be able to do a password protected installation.
So, when we install Velociraptor as a service you could not uninstall it without a password.

Thanks in advanced.
Gal Miller

**Comment by scudette** [comment]
This capability is called Elam drivers https://docs.microsoft.com/en-us/windows-hardware/drivers/install/early-launch-antimalware

And they need to be signed with a special certificate. We currently do not have kernel components or a kernel signing cert, and so we can not write such drivers. We need to rely on the normal permission model in windows. A system level service can not generally be installed by low privilege users but can be managed by administrators.

**Comment by mgdevsoft** [comment]
Hi,
Thanks for the update.
My point of view is for an APT that will "fight" back and uninstall
velociraptor even if we changed the parameters to hide it.

**Comment by scudette** [comment]
This is a good idea and definitely needed. There is not much we can do about it though because we rely on the OS permission model to control who has access to uninstall the service. If the user gains admin level access we can not stop it currently without an ELAM driver.
