### ISSUE TITLE
oidc-cognito authenticator - Issue with the log out process when using AWS Cognito

### ISSUE THREAD

**Issue by gdzieleziesz** [Velocidex/velociraptor#2046]
This issue is specific to the Velociraptor deployment in which it uses AWS Cognito for the user management (including authentication and session handling process). 
Here is the scenario in which issue has been noticed: 
When user logs off from the Velociraptor, session cookie is deleted, user is logged off from Velociraptor but AWS Cognito session is not dropped. User is allowed to login again using the same Cognito session to Velociraptor without entering username and password. 

AWS Cognito session is closed once GET request is issued to close Cognito session. Once it's processed, the user is redirected back to the Cognito HostedUI login screen.

https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html 

GET https://mydomain.auth.us-east-1.amazoncognito.com/logout?
client_id=ad398u21ijw3s9w3939&
logout_uri=https://myclient/logout

**Comment by scudette** [comment]
We (the Velociraptor team) are unlikely to support an AWS specific technology like this. You are welcome to implement a PR to handle this case but I will close this issue because it is not actionable from us.
