### ISSUE TITLE
Tabel CSV download not working on other orgs than the root org

### ISSUE THREAD

**Issue by SecMeyo** [Velocidex/velociraptor#2048]
## Issue

Table CSV downloads are not working for other orgs than the root org, because of a missing org id in the HTTP request generated by the frontend. The downloaded file has a total size of 0 bytes in any case.

## Steps to reproduce

Issue a local HTTP request and download an empty file

![image](https://user-images.githubusercontent.com/10670024/188482403-0d50a3a5-90c7-459c-92db-855af1238582.png)

## Proposed fix

add a org id parameter to the download URL and propagate context accordingly

**Comment by Astavinu** [comment]
should be addressed in https://github.com/Velocidex/velociraptor/pull/2047

**Comment by scudette** [comment]
Fixed
