### ISSUE TITLE
build an IBM - AIX architecture binary 

### ISSUE THREAD

**Issue by amarvind** [Velocidex/velociraptor#207]
Hi Velociraptor Team,

Request if you can build a binary for AIX architecture for data extraction. 

Looking forward for your response

Cheers,

**Comment by scudette** [comment]
I seems that the termios package does not work on AIX so i had to disable any velociraptor commands which use the terminal.

Give this binary a try and if it works we can file a bug upstream to support AIX. I dont think any of the terminal commands are that important though so maybe we can live without them

[velociraptor-v0.3.7-aix-ppc64.gz](https://github.com/Velocidex/velociraptor/files/4022954/velociraptor-v0.3.7-aix-ppc64.gz)

**Comment by scudette** [comment]
we are not realistically going to work on this since we have no use case. Closing but would love to accept PRs :-).
