### ISSUE TITLE
 Missing Service Configuration When Installing via Velociraptor.exe service install

### ISSUE THREAD

**Issue by mgdevsoft** [Velocidex/velociraptor#2072]
Hi,
When installing the service via the command line:
velociraptor.exe --config client.config.yaml service install

the service default configuration is installed without the options to handle failure correctly:
![image](https://user-images.githubusercontent.com/5002484/189650808-596259aa-ff56-49c0-b4e1-09def71080d0.png)

while installing the service via the MSI the configuration with the correct options:
![image](https://user-images.githubusercontent.com/5002484/189651488-0c87fb90-99b4-477c-8446-3203499cddf7.png)

Solution:
Implement the configuration change inside the code or via running the following command line as part of the installation of the service:
sc failure [service name] reset=0 actions=restart/0
example:
sc failure Velociraptor reset=0 actions=restart/0

**Comment by scudette** [comment]
Fixed by #2182
