### ISSUE TITLE
Resources Leak

### ISSUE THREAD

**Issue by cmueller-tp** [Velocidex/velociraptor#2080]
Not sure how I can debug this issue but over time memory usage increases further and further.

**Comment by scudette** [comment]
You can collect profiles as described here https://docs.velociraptor.app/knowledge_base/tips/debugging_clients/

https://docs.velociraptor.app/blog/2020/2020-08-16-profiling-the-beast-58913437fd16/

**Comment by scudette** [comment]
It is not necessarily a leak - it might just be that it is building up to its constant memory usage over time (filling caches etc) so unless it is excessive it is not an issue usually

**Comment by cmueller-tp** [comment]
Oh, on the server side. The client looks fine.
without the weird peaks it would be more obvious, but this is the memory usage of the server. With more or less the same amount of clients connected.
![image](https://user-images.githubusercontent.com/64212396/189895696-e5bb4fc7-76a6-4db1-8d02-6953a1698e5d.png)

**Comment by cmueller-tp** [comment]
The peaks in the end are coming from restarting the server, there you can see the memory usage after running a few hours, the line building up in the left is from multiple days.

**Comment by scudette** [comment]
Ok please attach the profile information containing the heap output and metrics

**Comment by scudette** [comment]
If this is still an issue for 0.6.7-4 please reopen
