### ISSUE TITLE
Unable to delete multiple clients as the same time in 0.6.6-1 linux server

### ISSUE THREAD

**Issue by Xboarder56** [Velocidex/velociraptor#2085]
Hi all,

I just updated the server to the latest linux release and after deploying the agents, and attempting to delete them from the GUI they won't successfully remove when you select 2+ agents at the same time. I don't get any error in the browser it just cycles like it's going to delete but then when you refresh the page nothing happens. 

Deleting 1 agent at a time via the GUI works fine however. 

Error inside of the server tab is this `client_delete: Client Id should be of the form C.XXXX`. However, this exactly how the clients show up just comma separated as I'm selected more than 1 at a time.

**Comment by scudette** [comment]
Fixed by #2169
