### ISSUE TITLE
MFT parsing issue when rebuilding paths

### ISSUE THREAD

**Issue by phillmoore-ccx** [Velocidex/velociraptor#2090]
There is a bug in the MFT parsing artifact which may relate to taking into account EntryID + Sequence number when rebuilding the OSPath.
Multiple instances observed where an item is returned as C:\item name, and when reviewing VFS, File Finder, raw powershell the item isnt there.
I haven't validated whether this is occurring in other paths, but it's obvious for the C:\ paths.

Example:
MFT Hunt:
![image](https://user-images.githubusercontent.com/109129708/190167515-4f4c11dd-b02f-46ba-8300-66242230df54.png)

VFS
![image](https://user-images.githubusercontent.com/109129708/190167622-24b050e4-5395-420e-9ca8-e6e751a2c618.png)

**Comment by scudette** [comment]
Duplicate of #2110 Lets move discussion there
