### ISSUE TITLE
Linux & MacOs Mass deployment 

### ISSUE THREAD

**Issue by dfir-noob** [Velocidex/velociraptor#2096]
I am wondering if there is any Administartion Tool  or a way to mass deployment of .deb packages on approx 500 Linux or MacOs endpoints  .

**Comment by scudette** [comment]
On Linux you can use management systems like puppet, Ansible, Chef etc. On MacOS you really need an MDM solution as @mpilking explained in his recent talk https://docs.velociraptor.app/presentations/2022_velocon/#mac-response--the-good-the-bad-and-the-ugly

We consider software management outside of the scope of the project.
