### ISSUE TITLE
Feature request: filtering for unlabeled clients in Admin GUI search bar

### ISSUE THREAD

**Issue by KarelDemeyer** [Velocidex/velociraptor#2099]
Allow to filter out unlabeled clients in the search bar (e.g. with "label:none" or "label:", "label:{}"...).
This would allow to select only those hosts added but not labeled yet.
Would also make a nice shortcut addition next to "Show All" and "Recent Hosts" in the drop down menu next to the search field.

**Comment by scudette** [comment]
Fixed by #2840
