### ISSUE TITLE
Feature Request: MRUList Run Order

### ISSUE THREAD

**Issue by prolsen** [Velocidex/velociraptor#211]
Looking for an artifact or an example that takes an MRUList, reads in the ordering, and then applies a, "run_order": "1" field to the respective entry. Examples for both string and binary data would be helpful.

Example output:
```
 {
  "timestamp": "2020-01-08T15:42:08.8800134Z",
  "reg_value": "MRUList",
  "reg_data": "**ga**fbecd"
 },

 {
  "timestamp": "2020-01-08T15:42:08.8800134Z",
  **"reg_value": "g"**,
  "reg_data": "excel\\1"
  **"run_order": "1"**
 },
 {
  "timestamp": "2020-01-08T15:42:08.8800134Z",
  **"reg_value": "a",**
  "reg_data": "cmd\\1",
  **"run_order": "2"**  
 },

**Comment by scudette** [comment]
Just for background info this is what the MRU list looks like
![image](https://user-images.githubusercontent.com/3856546/72122534-f0c2a880-33a9-11ea-8cec-933ec32a461d.png)

**Comment by scudette** [comment]
The trick here is to find the index of the letter in the MRUList and convert it to a length. You can use a regex to essentially remove the prefix and then len() to find out the length of what is left of the string. 

Previously `len()` only worked on arrays but this needs to also work on strings. Check the latest CI build from the last PR to have that fixed.

The artifact would look something like:

```
name: ....
description: ....
parameters:
  - name: MRUPath
    default: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\RunMRU

sources;
- queries:
   -  LET order <= SELECT MRUList from read_reg_key(globs=MRUPath)
   -  SELECT Data.value AS Command, Name, 
                     len(list=regex_replace(
                               source=order.MRUList[0], 
                               re='^.*' + Name, replace=''))  AS Order
      FROM glob(globs=MRUPath+'\\*', accessor='reg') 
      WHERE Name =~ '^.$'"
```

**Comment by scudette** [comment]
This is now implemented with Windows.Timeline.Registry.RunMRU
