### ISSUE TITLE
Extract the client into a VQL plugin

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#2120]
This allows the client to be started after running arbitrary VQL - this VQL can be used to prepare the machine to the client (e.g. create temp files etc).

**Comment by predictiple** [comment]
This will be awesome to have. A use case I am thinking about would be to bundle the Tailscale client and then have the VR client set that up before enrolling.

**Comment by certrik** [comment]
This really would be an awesome addition to 0.6.8.

**Comment by scudette** [comment]
In 0.6.9 it is now possible to define and add an event artifact to run on the client.

https://github.com/Velocidex/velociraptor/blob/a785b16c6213b791c2c78cf34f913c4e1c94023e/config/proto/config.proto#L290

The additional_event_artifacts will be launched by the client on startup before connecting to the server. They can mention artifacts defined in the autoexec.artifact_definitions section.

These artifacts can access the install time using `config.Version.install_time` and the client start time using the info() plugin so it is possible to define a precondition to control various use cases:

1. Start only at install time: compare install time to now() and run only when it is fairly recent.
2. Start on boot - compare client start time to now()
