### ISSUE TITLE
Feature request: Jumplist parser

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#2131]
Would be great to have a jumplist parser that at the very least parses automaticdestinations files:

Reference files: https://github.com/AndrewRathbun/DFIRArtifactMuseum/tree/main/Windows/JumpLists/Win10/RathbunVM

The automaticdestinatinons jumplist is an OLE2 container containing LNK files as individual streams (can parse with a lnk parser, just wont have the MAC times from the file system). last modified time of the stream is the last time the file was accessed. Theres no time associated with first access.
Each stream is tracked by a destlist entry - https://github.com/EricZimmerman/JumpList/blob/066253bd30a543064768b60c9c2285c8317c3062/JumpList/Automatic/DestList.cs

The filename has an appid in it as well, that can be used to identify the program the jumplist relates to: https://github.com/EricZimmerman/JumpList/blob/a72a510b01922f60ce550c307e5f04131272448f/JumpList/Resources/AppIDs.txt

**Comment by scudette** [comment]
https://docs.velociraptor.app/artifact_references/pages/windows.forensics.jumplists/
