### ISSUE TITLE
Windows.KapeFiles.Targets Does Not Collect $Boot

### ISSUE THREAD

**Issue by iamaleks** [Velocidex/velociraptor#2141]
Hello,

It appears the `Windows.KapeFiles.Targets` artifact does not completely collect the `$Boot` file.

When running `Windows.KapeFiles.Targets` with an Offline Velociraptor Collector I see the following STDOUT message:

```
{"level":"info","msg":"Collecting file \\\\.\\C:\\$Boot into \\\\.\\C:\\$Boot (8192 bytes)\n","time":"2022-10-06T16:39:42-04:00"}
```

However, within the resulting collection the `$Boot` shows up as `0` in size:

![image](https://user-images.githubusercontent.com/52838964/194436617-0eb7a900-4e4d-470e-bc27-f321e90e90af.png)

Would implementing additonal logic to collect the `$Boot` be possible?

Additional Notes:
Version Tested: Velociraptor 0.6.6-2 (commit: ebaf185)

**Comment by scudette** [comment]
Should be fixed by https://github.com/Velocidex/go-ntfs/commit/f91169ef8a39fc5463700f9a1b845f51a2f95b66
