### ISSUE TITLE
Add native kill process

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#2196]
Killing a process has been super handy during ransomware cases but we currently requre to shell out and use taskkill.
We would like to enable a kill process capability natively.

We would need to apply ACL requirements simlar to execve().
We would also need to ensure we cant kill protected processes by checking for protected process flag prior to execution.
https://reverseengineering.stackexchange.com/questions/20932/detecting-protected-processes-and-critical-processes-from-windows-driver

Additional capability we may also want to consider is process/thread control such as suspend/resume or kill.

**Comment by scudette** [comment]
Should be available in 0.6.8 with the pskill VQL function
