### ISSUE TITLE
Feature Request: Expand Windows.KapeFiles.Remapping utility

### ISSUE THREAD

**Issue by bcvilnrotter** [Velocidex/velociraptor#2197]
Is there any plans to expand on the artifact capabilities for Windows.KapeFiles.Remapping()?

Specifically I'm wondering if there is plans to add the ability to use the artifact on multiple import collections at once (rather than just through individual import collections flows notebook), or through hunts.

Also, added functionality to work with more native artifacts:

Some artifacts that appear to **not** work using this method:

    Windows.Applications.Chrome.History
    Windows.Applications.Edge.History
    Windows.Applications.Firefox.History
    Windows.Registry.UserAssist

**Comment by scudette** [comment]
I think those artifacts rely on the users plugin to get a list of users. We probably could mock that and make it sort of work.

But honestly remapping of imported artifacts is a band aid solution in case the user forgot to actually collect the right things in the first place. It's not a recommended workflow and it's not going to be perfect in any case.

You should just collect the right artifacts in the first place during the offline collector construction. Collecting of bulk files is not the best way for doing triage (I know this is all that other tools do so it's hard to break out of the mindset).

**Comment by scudette** [comment]
The latest release has some notebook suggestions in KapeFiles artifact that help with the remapping - you could use those inside a query() plugin to apply to entire hunts or many collections.
