### ISSUE TITLE
Add possibility to remove all roles of a user for specific orgs

### ISSUE THREAD

**Issue by BadBloopZ** [Velocidex/velociraptor#2216]
Currently, there's no clean way of removing user access on a single org only. This should be possible by setting the roles of that user to "" (empty string) in the user_grant function to be consistent with the command line. Afterwards, the user should not see this organization in the user settings any longer.

See conversation on discord: https://discord.com/channels/624244632552734750/624244632552734752/1037783722130419852

**Comment by scudette** [comment]
This should be fixed in 0.6.7 - the `user_delete()` function now takes a list of org in which to delete the user.

https://docs.velociraptor.app/vql_reference/server/user_delete/

**Comment by Felix83000** [comment]
Hi !

Is it possible to delete a user via the GUI?  (Cannot see a button in the list, Velociraptor 0.7.0)
![image](https://github.com/Velocidex/velociraptor/assets/16541780/6ed224dd-bc60-4089-b96c-fd55b7c60a58)

If it is only via an Artifact, do you provide one? (Cannot see one in the list, Velociraptor 0.7.0)

Thanks

**Comment by Felix83000** [comment]
Okay thanks
