### ISSUE TITLE
Feature Request: Add a client_add_metadata function

### ISSUE THREAD

**Issue by BadBloopZ** [Velocidex/velociraptor#2219]
Currently, the client_set_metadata function only allows to set the entire dict but does not allow to simply add a new key value pair. One always has to include another function call which reads the existing metadata and then combine it with the new property. This can easily lead to errors if one forgets to include to read the existing metadata first and simply deletes all existing properties by adding a new one.

Current status to add a new property in addition to existing 'Foo=Bar':
```
SELECT client_set_metadata(client_id=ClientId,
    metadata=client_metadata(client_id=ClientId) + dict(Foo2="Bar2")),
FROM scope()
```
Requested functionality:
```
SELECT client_add_metadata(client_id=ClientId,metadata=dict(Foo2="Bar2")) FROM scope()
```

**Comment by scudette** [comment]
Fixed by #2237
