### ISSUE TITLE
execve is spliting lines

### ISSUE THREAD

**Issue by chaoticmachinery** [Velocidex/velociraptor#2247]
The VQL code I am using is:
SELECT * FROM execve(argv=["rpm", "-Vva"],sep='\n)  

The output uploaded comes up 65% to 80% fine. However, I do get splits in the middle of the line. For example:
.........    /usr/libexec/webmin/jabber/help/modu||0|false|F.CDPR7ENRTIL7M|C.fd17a89a3527bcd0|greybox
  les.fr.auto.html||0|false|F.CDPR7ENRTIL7M|C.fd17a89a3527bcd0|greybox
  
  The line should be:
  .........    /usr/libexec/webmin/jabber/help/modules.fr.auto.html||0|false|F.CDPR7ENRTIL7M|C.fd17a89a3527bcd0|greybox

The "rpm -Vva" command produces ASCII output with a "\n" at the end of the line. 

My guess there is  a threshold in the go code that is causing the line splits. It like the length of the line is not resetting after seeing a "\n".

**Comment by scudette** [comment]
This should be fixed in 0.6.7
