### ISSUE TITLE
Velociraptor GUI not coming up

### ISSUE THREAD

**Issue by moksharthab** [Velocidex/velociraptor#2263]
Hi Team,

Greetings!

We installed Velociraptor as a service in RHEL 8 server. We followed the steps in this article.

We ran some jobs with regards to Kape Target files and we found our jobs to be hanging.

Any job following it was also hanging (simple Server info artifact as well).

Hence we rebooted the server, but we can see the Velociraptor service as in the screenshot attached.
 
BUT the GUI is down. We ran these commands after login to server, but to no success.
 

sudo systemctl daemon-reload

sudo systemctl enable --now velociraptor

sudo systemctl status velociraptor

sudo systemctl restart velocirapto

![MicrosoftTeams-image](https://user-images.githubusercontent.com/37410623/203051458-bc7ae484-0296-4c53-a19d-dcba025e0876.jpg)

Can you please let us know what we did wrong ?

**Comment by scudette** [comment]
Please follow the troubleshooting guide here https://docs.velociraptor.app/docs/deployment/troubleshooting/ and attach any output here

**Comment by scudette** [comment]
Is this issue resolved now?
