### ISSUE TITLE
MacOS Offline Collector using 'localhost' as machine name

### ISSUE THREAD

**Issue by enduirluke** [Velocidex/velociraptor#2266]
"Will collect package Collection-localhost-2022-11-21T16_31_22-06_00" is present in the log file, and the actual machine name (e.g. something like 'John's Macbook Pro') is no where in the log.

This is a problem since after receiving offline collected zip files from Windows machines I programmatically unzip collections and route them based on machine name.  I would like to do the same for MacOs, even if I have to 'hack' the solution and pull the machine name from some other location or file content.

I tried on 0.6.5 and 0.6.7 and both have the same behavior.  

Alternatively, if this field could support a variable like %machinename%, that could also suffice, but I wasn't able to find documentation for that:
![image](https://user-images.githubusercontent.com/109753124/203391400-c3c259a8-a382-4ba1-83bb-3ab470bba23c.png)

**Comment by scudette** [comment]
You can collect any artifact you want so that info will be in the zip. For example generic client info.

**Comment by scudette** [comment]
This has been fixed a while ago with the introduction of the filename template. This expands env variables into the template as well as having the special %FQDN% and %Timestamp% expansions. For example the following filename template inserts the computer name into the filename

![image](https://github.com/Velocidex/velociraptor/assets/3856546/602c2339-212e-492c-b857-4f11c4ec0107)


![image](https://github.com/Velocidex/velociraptor/assets/3856546/ec3c80f1-e080-4197-9b27-a0248dabd258)
