### ISSUE TITLE
Server crashes with segmentation violation

### ISSUE THREAD

**Issue by tbi88** [Velocidex/velociraptor#227]
Hi

I have an issue with my server which crashes few seconds / minutes after startup. I had the issue before and solved it by removing the data and log directory. But few days later it is happening again. Clients are still running 0.3.7, I upgraded the server to 0.3.8 trying to solve the issue but that did not help.

Here is the output I get:

root@raptor:~/velociraptor# /home/tobias/velociraptor/velociraptor-v0.3.8-linux-amd64 --config /home/tobias/velociraptor/server.config.yaml frontend -v
[INFO] 2020-01-20T14:53:09Z Starting Frontend. {"build_time":"2020-01-11T09:26:22Z","commit":"5195c3c","version":"0.3.8"}
[INFO] 2020-01-20T14:53:09Z Loaded 145 built in artifacts
[INFO] 2020-01-20T14:53:09Z Increased open file limit to 999999
[INFO] 2020-01-20T14:53:09Z Launched Prometheus monitoring server on 127.0.0.1:8003
[INFO] 2020-01-20T14:53:09Z Frontend is ready to handle client TLS requests at 0.0.0.0:8000
[INFO] 2020-01-20T14:53:09Z Starting hunt manager.
[INFO] 2020-01-20T14:53:09Z Launched gRPC API server on 0.0.0.0:8001
[INFO] 2020-01-20T14:53:09Z GUI is ready to handle TLS requests {"listenAddr":"0.0.0.0:8889"}
[INFO] 2020-01-20T14:53:09Z Starting Hunt Dispatcher Service.
[INFO] 2020-01-20T14:53:09Z Starting Stats Collector Service.
[INFO] 2020-01-20T14:53:09Z Starting Server Monitoring Service
[INFO] 2020-01-20T14:53:09Z Collecting Server Event Artifact: Server.Monitor.Health/Prometheus
[INFO] 2020-01-20T14:53:09Z Collecting Server Event Artifact: Server.Powershell.EncodedCommand
[INFO] 2020-01-20T14:53:09Z Starting Server Artifact Runner Service
[INFO] 2020-01-20T14:53:09Z Collecting Server Event Artifact: Server.Monitor.Shell
[INFO] 2020-01-20T14:53:09Z Starting Client Monitoring Service
[INFO] 2020-01-20T14:53:09Z Collecting Client Monitoring Artifact: Generic.Client.Stats
[INFO] 2020-01-20T14:53:09Z Collecting Client Monitoring Artifact: Windows.Events.ProcessCreation
[INFO] 2020-01-20T14:53:09Z Collecting Client Monitoring Artifact: Windows.Detection.Service.Upload
[INFO] 2020-01-20T14:53:09Z Collecting Client Monitoring Artifact: Windows.Detection.WMIProcessCreation
[INFO] 2020-01-20T14:53:09Z Collecting Client Monitoring Artifact: Windows.Events.DNSQueries
[INFO] 2020-01-20T14:53:09Z Collecting Client Monitoring Artifact: Windows.Events.Kerbroasting
[INFO] 2020-01-20T14:53:09Z Collecting Client Monitoring Artifact: Windows.Events.ServiceCreation
[INFO] 2020-01-20T14:53:09Z Starting VFS writing service.
[INFO] 2020-01-20T14:53:09Z Starting interrogation service.
[INFO] 2020-01-20T14:57:39Z Fetching http://127.0.0.1:8003/metrics
[DEBUG] 2020-01-20T14:57:45Z Received a post of length 1187 from X.X.98.206:56686 (C.46efe489cef1fd90)
[DEBUG] 2020-01-20T14:57:48Z Received a post of length 3379 from X.X.98.246:51693 (C.836859395761a31f)
[DEBUG] 2020-01-20T14:57:49Z Received a post of length 803 from X.X.4.171:62184 (C.7620dbcbde7978d2)
[DEBUG] 2020-01-20T14:57:51Z Received a post of length 1171 from X.X.1.7:57821 (C.2fb2966e785c6490)
[DEBUG] 2020-01-20T14:57:51Z Received a post of length 23972 from X.X.1.50:58618 (C.1f2e1778097e3941)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc485d6]
 
goroutine 254396 [running]:
www.velocidex.com/golang/velociraptor/flows.appendUploadDataToFile(0xc0005a6300, 0xc001f2e100, 0xc0027ca000, 0x0, 0x0)
        /build/flows/artifacts.go:539 +0xd6
www.velocidex.com/golang/velociraptor/flows.MonitoringProcessMessage(0xc0005a6300, 0xc001f2e100, 0xc0027ca000, 0x0, 0x0)
        /build/flows/monitoring.go:32 +0xc34
www.velocidex.com/golang/velociraptor/flows.(*FlowRunner).ProcessSingleMessage(0xc0014e81a0, 0xc0027ca000)
        /build/flows/artifacts.go:673 +0x1b2
www.velocidex.com/golang/velociraptor/crypto.(*MessageInfo).IterateJobs(0xc00335c0a0, 0x1b3a140, 0xc005532080, 0xc0008a3d70, 0x10, 0x443c0a)
        /build/crypto/transport.go:435 +0x80
www.velocidex.com/golang/velociraptor/flows.(*FlowRunner).ProcessMessages(0xc0014e81a0, 0x1b3a140, 0xc005532080, 0xc00335c0a0, 0x8d9245, 0xc0028d9b30)
        /build/flows/artifacts.go:692 +0x67
www.velocidex.com/golang/velociraptor/server.(*Server).Process(0xc0003d45f0, 0x1b3a140, 0xc005532080, 0xc00335c0a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /build/server/server.go:145 +0x12f
www.velocidex.com/golang/velociraptor/server.control.func1.1(0xc003a9c060, 0xc0003d45f0, 0xc001f2e000, 0xc00335c0a0)
        /build/server/comms.go:392 +0xcc
created by www.velocidex.com/golang/velociraptor/server.control.func1
        /build/server/comms.go:390 +0x8a8

Any ideas on that?

**Comment by tbi88** [comment]
The system is an Ubuntu 18.04.03.

**Comment by scudette** [comment]
Thanks for the detailed bug report! It looks like an issue where a client event monitoring artifact is trying to upload a file to the server. What event monitoring artifacts do you have configured?

**Comment by scudette** [comment]
Ah sorry - I did not see it up in the logs above :-).  You have set Windows.Detection.Service.Upload and this is what is causing the crash. 

This is obviously a bug though so we do need to fix it :-).

**Comment by scudette** [comment]
Can you please test with the latest CI build?

**Comment by tbi88** [comment]
Hi Mike

I have run the CI build. So far it is running fine for the last 15 minutes. I will check later again and see if I get all the artifacts. I let you know then.

Thanks & Regards
Tobias

**Comment by tbi88** [comment]
Hi Mike

Still looks good. Also I am receiving data from the clients. Thanks for the help.

Best regards Tobias
