### ISSUE TITLE
 Intervention during updates needed due inconsinstant package name change in RPMs

### ISSUE THREAD

**Issue by disasmwinnie** [Velocidex/velociraptor#2272]
Between the update 0.6.5 and 0.6.7 the package name (meta-field in RPM) has changed. It went from velociraptor, to velociraptor-client. In packages generated for SysV, it is the other way around.

The DEB packages don't introduce the described change, it's still "velociraptor-client". 

------

This change will result in failed updates, since package managers assume that the current package is trying to overwrite a file provided by another package. In some sense it's not an update but another package install is happening.

SystemD Update (rhel9):

```
Error: Transaction test error:
  file /etc/velociraptor/client.config.yaml from install of velociraptor-client-0:0.6.7-A.x86_64 conflicts with file from package velociraptor-0:0.6.5-A.x86_64
```

SysV Update (amazon linux 2018, rhel6-based):

```
Transaction check error:
  file /etc/velociraptor/client.config.yaml from install of velociraptor-0:0.6.7-A.x86_64 conflicts with file from package velociraptor-client-0:0.6.5-A.x86_64
```

------

If the bug is not too obvious, I will have some time during the next weeks to dig through the source myself, and will try to provide a PR.

**Comment by scudette** [comment]
This seems to be a conflict between two packages "velociraptor" and "velociraptor_client". 

https://github.com/Velocidex/velociraptor/blob/03e3e2cab6cac3a9ab04c5d11571512fbc27dfd0/bin/rpm.go#L275

https://github.com/Velocidex/velociraptor/blob/03e3e2cab6cac3a9ab04c5d11571512fbc27dfd0/bin/rpm.go#L544

One is set by the sysv rpm and one by the systemd rpm. Looking at the git history those lines have not changed for over a year now.

Could it be that you are trying to install both variants of the client on the same system? It normally makes no sense as the system is either a sysv system (older centos or rh distro) or a modern systemd system.

It might make sense to name these the same for consistency. Or maybe even add a dependency on systemd so it can not even be installed incorrectly on the wrong system.

**Comment by scudette** [comment]
I renamed both packages to velociraptor-client in #2292 . This should fix the issue anyway
