### ISSUE TITLE
Ubuntu arm cannot execute binary file

### ISSUE THREAD

**Issue by hmtkgn** [Velocidex/velociraptor#2279]
### How to solve this error? 

**step 1:** I am running on a linux machine. 
**Command:** uname -a 
**result:** Linux ubuntu-linux-22-04-desktop 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:55:29 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux  

**step 2:** i checked the file type of the "binary file"  
**command:** file velociraptor  
**Result:** velociraptor: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>  

**step 3:** i made the  file executable by changing file permissions.  
**command:** chmod +x /usr/local/bin/velociraptor   

**Step 4:**  To generate server configuration file       
**command:** velociraptor config generate –help 
**result:** bash: /usr/local/bin/velociraptor: cannot execute a binary file: exec format error

**Comment by scudette** [comment]
We currently do not ship Linux arm binaries, those are for Darwin (macos).

You can build Linux arm binaries from source using the Linux arm target.

**Comment by scudette** [comment]
If you are trying to run in docker on mac m1 you will need the linux_m1 target:
```
go run make.go -v LinuxM1
```

If you want to run on raspberry pi you will need the arm target:
```
go run make.go -v arm
```
