### ISSUE TITLE
Offline collector bug

### ISSUE THREAD

**Issue by tuttimann** [Velocidex/velociraptor#2288]
Every time I create an Offline Collector on our server (v0.6.7) and change the default value of max execution time from 600 to another value, than the binary crashes on the client when executing with attached error message.
When I change to default value of max execution time (600 seconds) it runs without any problems.
![Offline_Collector](https://user-images.githubusercontent.com/35948670/204791124-11e87faf-4133-47fa-83f8-75e69d41ca15.png)

**Comment by scudette** [comment]
This was using the timeout in ns accidentally instead of sec. #2297 fixes the issue.
