### ISSUE TITLE
Feature request: improved artefact selection

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#23]
I would like to raise a feature request for artefact selection workflow in the GUI

Im using 0.3.0 and I can currently select artefacts by searching and selecting "Add". I need to highlight and select "add" for each item of interest.

I would love to be able to select multiple artefacts and add all at once as this saves time and ensures my collections are easier to be repeated.

Expected workflow:
1. Open New Artefact Collection - Select Artefacts to collect screen
2. Type in: Windows.Triage to obtain all Windows triage items
3. Select all / items of interest and add in one go.

I know we can technically create a artefact pack but the above workflow is very relevant to how I work an engagement.

**Comment by scudette** [comment]
Probably for more complex collections like this it might be easier to automate using a notebook query?

**Comment by mgreen27** [comment]
Yes that an option but I think of capability in terms of "click click forensics". For those that cant VQL and mainly consumers, we want to be able to quickly whip up appropriate collection in a few clicks without a clunky multi click/hunt workflow or building VQL which requires a level of skill with the platform.

**Comment by scudette** [comment]
The current UI is a bit quicker - you need to highlight the selection not highlight and click add so it is quite a bit faster.
