### ISSUE TITLE
Windows.Events.DNSQueries Template broken

### ISSUE THREAD

**Issue by tbi88** [Velocidex/velociraptor#230]
Hi

I have an issue with the client monitoring artifact "Windows.Events.DNSQueries". When I try to open the artifact in the Web-GUI for a client, the following message is displayed:

Error template: :13: unterminated quoted string

Also the following messages are shown in the logs:

tobias@raptor:~/velociraptor/logs$ tail -f VelociraptorGUI_error.log
{"error":"{\"error\":\"template: :13: unterminated quoted string\",\"code\":2,\"message\":\"template: :13: unterminated quoted string\"}","level":"error","method":"POST","msg":"","remote":"X.X.4.10:39397","status":500,"time":"2020-01-21T08:29:58Z","url":"/api/v1/GetReport","user":"tobias","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.160 Safari/537.36"}
{"error":"{\"error\":\"template: :13: unterminated quoted string\",\"code\":2,\"message\":\"template: :13: unterminated quoted string\"}","level":"error","method":"POST","msg":"","remote":"X.X.4.10:39397","status":500,"time":"2020-01-21T08:32:03Z","url":"/api/v1/GetReport","user":"tobias","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.160 Safari/537.36"}
{"error":"{\"error\":\"template: :13: unterminated quoted string\",\"code\":2,\"message\":\"template: :13: unterminated quoted string\"}","level":"error","method":"POST","msg":"","remote":"X.X.4.10:39397","status":500,"time":"2020-01-21T08:33:21Z","url":"/api/v1/GetReport","user":"tobias","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.160 Safari/537.36"}
{"error":"{\"error\":\"template: :13: unterminated quoted string\",\"code\":2,\"message\":\"template: :13: unterminated quoted string\"}","level":"error","method":"POST","msg":"","remote":"X.X.4.10:39397","status":500,"time":"2020-01-21T08:33:39Z","url":"/api/v1/GetReport","user":"tobias","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.160 Safari/537.36"}

The issue happens at least in 0.3.7, 0.3.8 and the current CI build.

Best regards
Tobias

**Comment by scudette** [comment]
This might be because the files are too large to be rendered in the
browser. Can you check if the files are actually collected correctly on the
server?

You will find the files under the clients/client id/monitoring directory in
the file store separated out by days.

It might be that the report is not limiting the number of rows it's trying
to render in the browser.

**Comment by tbi88** [comment]
Yes the files are actually created and contain the data. I doubt it is an issue with the size. For some clients the files are rather small (20 KB). Also the issue start happening immediately after enabling the DNSQueries monitoring artifact.

**Comment by scudette** [comment]
Sorry you are right- it was a typo in the template.
