### ISSUE TITLE
Tables Contain n+1 Requested Rows

### ISSUE THREAD

**Issue by SBattaglia-R7** [Velocidex/velociraptor#2314]
When viewing a table for a resultset that contains more entries than the currently selected number of rows per page, the table displays _n+1_ rows instead of the requested _n_.  The response json will contain keys numbered _0 through n_ instead of _0 through n-1_.  

I noticed this when browsing the client listing of an instance with 11 registered clients, but was able to replicate this in any table I tried.  In the client listing, instead of the first page containing the first 10 clients and the second page containing the 11th, the first page listed all 11 client.  The second page displayed just the 11th client, again.

To reproduce, find any pageable table for a resultset of more than 10 entries (I tried the client search page, user listing, and hunt flow notebook).  In the UI, the last entry of page 1 will be the first entry of page 2.  Viewing the response json in the browser's dev tools will show that results 0-10 instead of 0-9 are displayed:

![Screen Shot 2022-12-05 at 4 20 30 PM](https://user-images.githubusercontent.com/40576678/205745116-5b1e78c1-3907-4f2b-8896-bcaf2222788f.png)

Alternatively, use Firefox to "Edit and Resend" the request  with the header's _rows_ field  changed to anything smaller than your sample size, such as 5 if the resultset has <10 rows.  The UI will not update, but the response json will still show the extra row returned.

**Comment by scudette** [comment]
![image](https://user-images.githubusercontent.com/3856546/205835881-31b2f02d-c648-4194-a6fc-349092eefedf.png)

**Comment by scudette** [comment]
![Win_Server_2019](https://user-images.githubusercontent.com/3856546/217138849-ac5b9e18-fece-4911-b469-a33efa774e51.png)
