### ISSUE TITLE
Disable compression

### ISSUE THREAD

**Issue by moksharthab** [Velocidex/velociraptor#2322]
When checking the server.config.yaml in the references in Github

Line no - 170

disable_compression: false

Is this a optional setting or setting which comes by default by installing a certain version ?

**Comment by scudette** [comment]
You probably never need to change it. It disables compression of the data in transit.

**Comment by moksharthab** [comment]
But we don't have the setting at all.

So we need to add it manually ?

**Comment by scudette** [comment]
No. The default is false - so if it is missing the setting is false. 

You can see all the config settings including their default values here
https://docs.velociraptor.app/docs/deployment/references/#Client.disable_compression
