### ISSUE TITLE
Rework vfs tree in the GUI

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#2326]
It's really making chrome cry with large directories

**Comment by kingaling** [comment]
Not sure if this was related to chrome or just really big dirs in general but there is this issue from a couple months back: https://github.com/Velocidex/velociraptor/issues/2005

**Comment by scudette** [comment]
Yeah the solution for that issue was to limit the size of the vfs directory by just truncating the list (I think it's 1000) but that's not a great solution because it's missing actually some files.

Maybe we need to replace the file table with a standard pageable table.

**Comment by scudette** [comment]
Fixed by #2343
