### ISSUE TITLE
Generic Collectors File artifact materializes file list into memory - causing excessive memory usage

### ISSUE THREAD

**Issue by yarox24** [Velocidex/velociraptor#2329]
YAML Artifact doesn't support field: progress_timeout

![image](https://user-images.githubusercontent.com/18016218/206722999-2f326efa-dc76-401a-ad0e-ebd7fcd9ea7f.png)

Error:
![image](https://user-images.githubusercontent.com/18016218/206723191-16692d6a-f669-4bb9-8295-6295ce414ef9.png)

**Comment by scudette** [comment]
Currently you can not set the progress timeout default in the artifact definition. 

Can you explain why you would want to? A progress timeout will abort the query if no rows are emitted within the specified time - it is a finer grained version of the timeout. 

You can use the vql query() plugin to run a query with a progress timeout if you needed to. This is more flexible because you can run a number of smaller queries within the same artifact and abort the ones that are taking too long while still doing other ones.

**Comment by yarox24** [comment]
We are trying to create a Profile (which contains 20-50 different sources named as Block, and this number will be increasing) to gather data from various artifacts on demand (Like evtx, MFT files for all partitions etc. all the basic forensics stuff, selectable by parameters).

Example beginning of profile Demo1 (Anonymized):

![image](https://user-images.githubusercontent.com/18016218/206736749-3f814658-94a3-47c1-8dcd-1e890c9d1ece.png)

Example of first sources of the same plugin:
![image](https://user-images.githubusercontent.com/18016218/206737365-4daea7f4-ed4b-432e-9606-c3ff7d0be74a.png)

Main problem which we are struggling is related to "stalling" of executed profile.

This was previously written using "Serial mode" - precondition on the  top, and now I moved precondition to every source to achieve parallel execution (Not mainly due to performance, but to overcome "stalling").

We know that "Serial mode" version was "stalling", but it's still yet not conclusive if "Parallel mode" version will be also "stalling".


What I mean by stalling:
Flow is in RUNNING state, but query is not progressing since for example 15 hours and it seems it will never reach the end of execution (Until it will reach it's timeout which is set to very high value).


That's why the goal to better detect this was to add progress_timeout to YAML.

**Comment by scudette** [comment]
It's important to understand why things are not progressing was they should. Can you collect a client profile from the client while it is working on the query? Include goroutine and query logs.

If no progress is made it is either a bug or maybe the artifact is trying to do something in an inefficient way. If you share you query we can try to replicate the issue.

The parallel execution is still bound by the client concurrency limit which is 2 by default so it will execute 2 queries at the same time.

You can use the query() plugins to have very fine control over how queries are run and their timeout.

**Comment by yarox24** [comment]
We are now executing more tests (Which can take days to finish).

Logs from crash captured when running as client -v (This time on version 0.6.7, next checks will be on version 0.6.7-4):
[Crash1 - Extended_Basic.txt](https://github.com/Velocidex/velociraptor/files/10215679/Crash1.-.Extended_Basic.txt)

**Comment by yarox24** [comment]
Logs + Crashing Yaml + other helpful info
https://velo-crash.s3.eu-central-1.amazonaws.com/crash4.7z


```
...
[INFO] 2022-12-15T15:02:35+01:00 Found C:\Users\live\AppData\Local\Mozilla\Firefox\Profiles\zsk70zrt.default-release\cache2\entries\A742DC9A902B1F5C5A19B9F5BE1BFCE394E958AF 
[INFO] 2022-12-15T15:02:35+01:00 Found C:\Users\live\AppData\Local\Mozilla\Firefox\Profiles\zsk70zrt.default-release\cache2\entries\A74C52604BCC000B604725C4B61F7827CF684795 
runtime: VirtualAlloc of 8192 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x2356d92?, 0xc2b1ebf000?})
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:1047 +0x65 fp=0x5c4bbff718 sp=0x5c4bbff6e8 pc=0x55e885
runtime.sysUsedOS(0xc2b1ebe000, 0x2000)
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/mem_windows.go:83 +0x1c9 fp=0x5c4bbff778 sp=0x5c4bbff718 pc=0x53a4c9
runtime.sysUsed(0x80?, 0x2000?, 0x6956?)
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/mem.go:77 +0x25 fp=0x5c4bbff798 sp=0x5c4bbff778 pc=0x539fc5
runtime.(*mheap).allocSpan(0x3651ac0, 0x1, 0x0, 0x12)
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/mheap.go:1333 +0x615 fp=0x5c4bbff830 sp=0x5c4bbff798 pc=0x54c875
runtime.(*mheap).alloc.func1()
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/mheap.go:910 +0x65 fp=0x5c4bbff878 sp=0x5c4bbff830 pc=0x54be65
runtime.systemstack()
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/asm_amd64.s:492 +0x4e fp=0x5c4bbff880 sp=0x5c4bbff878 pc=0x58eb4e

goroutine 93 [running]:
runtime.systemstack_switch()
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/asm_amd64.s:459 fp=0xc061ca5558 sp=0xc061ca5550 pc=0x58eae0
...
```

**Comment by yarox24** [comment]
OK, we found exact place in which excessive memory consumption occurs (Based on modified version of Generic.Collectors.File
)

The difference in next files is related to line 166: 
In working version this query is not materialized and it only make difference when more rows than 10000.
We assume glob is catching at least 10k files.

Note: During materialization it emits all the rows in never ending loop. On test machine we had 435 iterations per glob.


```
LET all_results <= SELECT Created, LastAccessed,
              Modified, Size, SourceFile
        FROM hits LIMIT 10001
```

Example files:
[NotWorkingConsumingLotRam.txt](https://github.com/Velocidex/velociraptor/files/10245940/NotWorkingConsumingLotRam.txt)
[Working.txt](https://github.com/Velocidex/velociraptor/files/10245941/Working.txt)

**Comment by scudette** [comment]
Yes I see that our artifact materializes into memory here

https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Generic/Collectors/File.yaml#L52

It does it so it can reuse the results in the next source for the actually upload

We don't expect that many files but I guess this is not really safe though so we should probably fix it.

Are you saying that once it gets too 10k it just goes out of control? It should be emitting a warning at 10k files but still continue

**Comment by yarox24** [comment]
Yes,

I had recorded demo of previously attached plugins in terms of their memory consumption (and very long execution up until point of Out Of Memory panic - which is not shown on the movie as longer recording time will be needed). Velociraptor was launched with gui mode on affected Windows 10 machine.

1st execution - proper one
2nd execution- with <= will cause out of memory error (Private bytes in Process Hacker)

GIF:
![crash_demo](https://user-images.githubusercontent.com/18016218/208397747-eb16d0fd-d582-4154-84d4-d70d60ac4ae7.gif)

**Comment by scudette** [comment]
Thank you for the detailed debugging 👍🏽

**Comment by scudette** [comment]
This is no longer an issue due to #2420 which writes the data to a tempfile instead making it safer to run an keeping memory needs low.
