### ISSUE TITLE
Hunt's exported results from Generic.Client.Info has duplicated names

### ISSUE THREAD

**Issue by KKV002** [Velocidex/velociraptor#2336]
When you export the JSON or CSV zipped result from a hunt using artifact Generic.Client.Info, the 3 files share the same name. 
In that case the are all called "All Generic.Client.Info.json" instead of "BasicInformation", "WindowsInfo" and "Users" like before. 
You have to extract and rename 1 file at a time otherwise they simply extract over eachother.

This happens only with artifacts that outputs multiple tables in its result.

**Comment by scudette** [comment]
This should be fixed by #2347
