### ISSUE TITLE
ELF file cannot run 

### ISSUE THREAD

**Issue by mgdevsoft** [Velocidex/velociraptor#2338]
Hi,
The problem:
When executing any version of velociraptor-v0.6.7-*-linux-amd64 an error message of:
 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28` not found (required by [insert name of elf file here])

In other versions, same message only the versioning of the GLIBC is changing. 

OS:
ubuntu 16.04.6 LTS

The last working version of Velociraptor I was able to run on the server is:
velociraptor-v0.6.6-1-linux-amd64

Have any idea about the underline problem and/or fix?

Thanks,
Gal Miller

**Comment by predictiple** [comment]
Ubuntu 16.04 is too old (and end-of-life actually). You can download the build that ends in `-linux-amd64-musl` from the Releases section which has no dependency on GLIBC. Also it would be good to consider upgrading that Ubuntu since it's EOL.

**Comment by scudette** [comment]
We probably need to update the kb item here to cover the musl build

https://docs.velociraptor.app/knowledge_base/tips/glibc_errors/

**Comment by scudette** [comment]
Updated docs to reference the MUSL build
