### ISSUE TITLE
Add time travel tracing for endpoint visibility

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#2344]
We occasionally get reports that collections seem hung or unresponsive. This sometimes happen because the endpoint is rebooted or cpu limits mean the query will not run, but it is very hard to determine what is happening.

We need an easy way to capture periodic snapshots of certain queries when they run so we can go back and see what happened after the fact. Currently we get good information with the Generic.Client.Profile artifact but that requires collecting it deliberately and is manual. A trace setting will essentially do this transparently so it is easier to get the data automatically.

**Comment by randomaccess3** [comment]
+1 - we often see this happening.
It may be that the client never works properly, but sometimes it just doesnt deal with new hunts coming in.
Haven't explored why it happens, but usually the flow is received, and then it sits there with no last active time.
Or there's a last active time from a while ago, and even though the client is reporting in it doesnt continue the collection.

In the past I've had to stop all of the active flows, (occasionally hit killkillkill), then re-add them all back, and add the new flows back to the original hunts. Sometimes nothing new will run until I stop everything first (so adding new things is just adding to a backlog that wont get started).

**Comment by scudette** [comment]
Fixed by #2422
