### ISSUE TITLE
Starting server from server config file, bad username and password

### ISSUE THREAD

**Issue by RSOCKS** [Velocidex/velociraptor#2348]
Thanks for reading

I am a beginner user.  I've followed along with the training and created server and client config files.  However, when I attempt to start the server, I'm getting blocked from logging in.  I have attempted this many times.  I've attempted with no usernames and with several usernames.  Still nothing.  Screenshots are attached.

![Capture](https://user-images.githubusercontent.com/42501298/209130997-66055a36-1441-49bd-937d-9e7785462c79.PNG)
![Capture1](https://user-images.githubusercontent.com/42501298/209131009-df5d1ce2-b43d-4151-be07-a162c35d8dfb.PNG)
![Capture2](https://user-images.githubusercontent.com/42501298/209131019-c40becbd-4d0d-4b06-8934-45bd4579de03.PNG)

**Comment by scudette** [comment]
The `velociraptor gui` command sets up a fresh installation with preselected defaults. In other words it generates its own config file with default admin/password access.

if you generate your own config file you should use the frontend command. `velociraptor --config server.config.yaml frontend -v`

**Comment by RSOCKS** [comment]
That did it!  Thank you.
