### ISSUE TITLE
Hunt manager empties sometimes

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#2350]
Have seen this a couple times where the hunt manager has nothing in it but the /opt/velociraptor/hunts directory is full.
Individual flows are still visible per client.
New hunts get displayed.

![image](https://user-images.githubusercontent.com/1241363/209260551-419c3245-ba02-49bb-84db-f22273b94473.png)

![image](https://user-images.githubusercontent.com/1241363/209260665-255b3cf9-5433-4d4b-aabf-fb134b603b46.png)

Unsure if there's an age out to remove old hunts from being displayed in the UI.

**Comment by randomaccess3** [comment]
Confirmed owner of the folders in /opt/velociraptor/hunts is Velociraptor

**Comment by scudette** [comment]
I just saw something similar that happened after the disk ran out of space. The hunt manager tries to save all hunts but because there is no disk space left they all end up as 0 length files.

```
C:\>dir datastore\hunts\*.db
 Volume in drive C has no label.
 Volume Serial Number is DEE0-D9DE

 Directory of C:\datastore\hunts

01/13/2023  10:20 PM                 0 H.CDJQIKNP54BP0.db
01/13/2023  10:27 PM                 0 H.CDJQV0SLM6T32.db
01/13/2023  10:27 PM                 0 H.CDJR7ECI1GEQI.db
01/13/2023  10:27 PM                 0 H.CDJRM7GT1V3EI.db
01/13/2023  10:27 PM                 0 H.CDJS4J4QKLP3Q.db
01/13/2023  10:27 PM                 0 H.CDKB1QR1HOO8G.db
11/07/2022  12:42 AM                 0 H.CDKBGJRAO635A.db
```

**Comment by randomaccess3** [comment]
Yeah for mine we didn't run out of space. 
And the original hunts were all there. Just not displayed. 
New hunts were created no problem

**Comment by scudette** [comment]
Did you have 0 size files like above?

**Comment by randomaccess3** [comment]
I don't think so. 
From memory the content was there. 

Plus def didn't do anything bulk cleanup to get new hunts working.

**Comment by scudette** [comment]
0.6.8 has a hunts reconstruct command to rebuild the hunt objects which were lost due to 0 length files.

This command replays the hunt log from System.Hunts.Creation to rebuild the lost hunt objects

**Comment by sunnywalia206** [comment]
How do you invoke the hunts reconstruct command?  I've tried and am getting an error "Command not available when running without a frontend service." though I'm running a frontend.
