### ISSUE TITLE
split_records splits on both new lines and provided regexp 

### ISSUE THREAD

**Issue by clayscode** [Velocidex/velociraptor#2368]
https://github.com/Velocidex/velociraptor/blob/21e061d9cea80b7f341c10df0cb8689ed385120b/vql/parsers/splitparser.go#L85 The split_records plugin should split only on provided regexp and not also newline characters

**Comment by clayscode** [comment]
I think this might be the best approach https://go.dev/play/p/1pFFrhYKXW, sourced from this Google Groups thread: https://groups.google.com/g/golang-nuts/c/msMHvOmmzOY/m/LbGWaEqLD-YJ

**Comment by scudette** [comment]
The intention behind this function is to parse CSV like files - so we count on the file being in a kind of tabular format and then split it into columns. For example this function is used in parsing the /proc/mounts file.

So we do count on this behaviour. Perhaps we need both record regex and column regex to allow for both cases.

**Comment by scudette** [comment]
Fixed by #2431
