### ISSUE TITLE
AWS SFTP upload error in 0.6.7

### ISSUE THREAD

**Issue by denizciftci-sec** [Velocidex/velociraptor#2373]
Hi,

I can confirm that we are able to upload files via SFTP to AWS S3 bucket via https://velociraptor.velocidex.com/sftp-in-aws-24a51bebc103 **when we use 0.6.6 release**. 
But using 0.6.7 release - latest, having the following error. Clearly 0.6.7 AWS sftp upload is not working at the moment. 

C:\Users\Lenovo\Downloads>"Collector_velociraptor-v0.6.7-4-windows-amd64 (6).exe"
[INFO] 2023-01-09T12:03:32+01:00 Autoexec with parameters: [artifacts collect Collector --logfile Collector_velociraptor-v0.6.7-4-windows-amd64.exe.log -v --require_admin]
[INFO] 2023-01-09T12:03:32+01:00  _    _     _           _                  __
[INFO] 2023-01-09T12:03:32+01:00 | |  / /_  / /_  __()___ __  / /__  ___
[INFO] 2023-01-09T12:03:32+01:00 | | / / _ \/ / _ \/ _/ / _/ _ `/ _ \/ _/ _ \/ __/
[INFO] 2023-01-09T12:03:32+01:00 | |/ /  _/ / // / /_/ / /  / // / // / // /_/ / /
[INFO] 2023-01-09T12:03:32+01:00 |_/\__//\__/\__///   \,/ ._/\_/\_/_/
[INFO] 2023-01-09T12:03:32+01:00                                   /_/
[INFO] 2023-01-09T12:03:32+01:00 Digging deeper!                  https://www.velocidex.com
[INFO] 2023-01-09T12:03:32+01:00 This is Velociraptor 0.6.7-4 built on 2022-12-06T13:31:56Z (c6f11a7)
[INFO] 2023-01-09T12:03:32+01:00 Loaded embedded config
[INFO] 2023-01-09T12:03:32+01:00 Starting Org Manager service.
[INFO] 2023-01-09T12:03:32+01:00 Starting services for Root Org
[INFO] 2023-01-09T12:03:32+01:00 Starting Journal service for Root Org.
[INFO] 2023-01-09T12:03:32+01:00 Starting the notification service for Root Org.
[INFO] 2023-01-09T12:03:32+01:00 Starting repository manager for Root Org
[INFO] 2023-01-09T12:03:32+01:00 Loaded 347 built in artifacts in 252.8207ms
[INFO] 2023-01-09T12:03:32+01:00 Installing Dummy inventory_service. Will download tools to temp directory.
[INFO] 2023-01-09T12:03:32+01:00 Uploading to Collection-DESKTOP-2ME7QAF_fritz_box-2023-01-09T12_03_32_01_00.log
[INFO] 2023-01-09T12:03:32+01:00 upload_SFTP: Uploading Collection-DESKTOP-2ME7QAF_fritz_box-2023-01-09T12_03_32_01_00.log to s-79f9041cc7c84ad58.server.transfer.eu-central-1.amazonaws.com:22
[INFO] 2023-01-09T12:03:33+01:00 Compiled all artifacts.
[INFO] 2023-01-09T12:03:35+01:00 **upload_SFTP: permission denied**
[INFO] 2023-01-09T12:03:35+01:00 Will collect package Collection-DESKTOP-2ME7QAF_fritz_box-2023-01-09T12_03_32_01_00 and upload to cloud bucket
[INFO] 2023-01-09T12:03:35+01:00 Starting collection of Collector
[INFO] 2023-01-09T12:03:35+01:00 Aborting collection: Failed to upload to cloud bucket!
[DEBUG] 2023-01-09T12:03:35+01:00 Query Stats: {"RowsScanned":4,"PluginsCalled":4,"FunctionsCalled":24,"ProtocolSearch":26,"ScopeCopy":13}
[
 {
  **"log(message=\"Aborting collection: Failed to upload to cloud bucket!\")": true**
 }
][INFO] 2023-01-09T12:03:35+01:00 Collection completed in 3 Seconds
[DEBUG] 2023-01-09T12:03:35+01:00 Query Stats: {"RowsScanned":1,"PluginsCalled":1,"FunctionsCalled":0,"ProtocolSearch":0,"ScopeCopy":3}
[INFO] 2023-01-09T12:03:35+01:00 Exiting notification service for Root Org!

**Comment by scudette** [comment]
Can you please test with the latest CI release? You will need to manually upload the velociraptor.exe to the tool setup screen.

https://github.com/Velocidex/velociraptor#getting-the-latest-version

**Comment by scudette** [comment]
This actually looks like a permission issue on the AWS side. I just tried it and I can certainly upload with sftp without an issue locally.

**Comment by scudette** [comment]
Feel free to reopen if you see this again. BTW I generally dont like to use sftp on aws because it is very expensive relative to s3 upload which is better supported anyway.
