### ISSUE TITLE
Issue while creating offline collector

### ISSUE THREAD

**Issue by ravalpratik5** [Velocidex/velociraptor#2376]
I have downloaded the latest version of Velociraptor on windows and trying to create a offline collector following the steps mentioned in documentation. However in the last stage it is getting failed and I'm getting below error in console.

Note: I have not installed the Velociraptor I am using GUI command to bring up the console and from there creating a offline collector.

Log:-

{"error":"{\"code\":2,\"message\":\"While resolving github release Velocidex/velociraptor: Get \\\"https://api.github.com/repos/Velocidex/velociraptor/releases/latest\\\": dial tcp: lookup api.github.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. \"}","method":"GET","remote":"127.0.0.1:57535","status":500,"url":"/api/v1/GetToolInfo","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44"}

**Comment by scudette** [comment]
It is likely your host is somehow blocked from accessing GitHub to download the release binary.

The collector builder basically gets the release binary and pre-configures it. That is what an offline collector is - a preconfigured velociraptor, so it needs to fetch the binary from the github release page and probably you have some kind of filtering on DNS.

You can install the binaries for the different OS manually:

 just click the tool setup screen and manually upload the binary

![image](https://user-images.githubusercontent.com/3856546/211540915-a6ec7b72-2ad6-4cea-9228-c800645bdf82.png)

![image](https://user-images.githubusercontent.com/3856546/211540957-8d7c72c7-957e-4613-a3f9-d9e157261a9f.png)

You can get the latest windows binary from the GitHub release page.
