### ISSUE TITLE
x86 MSI added to the project Build/Releases 

### ISSUE THREAD

**Issue by nsanity2097** [Velocidex/velociraptor#2386]
Since Issue 2357 has been resolved, VR can re-pack msi's from a linux binary.

However without publishing both x64 and x86 msi files, this would still require the an end user to manually package for a significant  portion of potential clients. Extending the build pipeline to include an x86 msi as well as the x64 msi will better enable this msi-repack feature.

**Comment by scudette** [comment]
WIX XML files and build process added in #2424
