### ISSUE TITLE
Update Nirsoft BrowsingHistoryView

### ISSUE THREAD

**Issue by DavidSanchezGracia** [Velocidex/velociraptor#2395]
Hi everyone, 

I have just realized that the current BrowsingHistoryTool version used by the Artifact "Windows.Applications.NirsoftBrowserViewer" uses an old version of the tool that does not include new features as extract the Brave browsing history. 

It would be nice if the .exe downloaded from "https://github.com/Velocidex/Tools/tree/main/BrowsingHistoryView" was updated. 

Thank you in advance.

**Comment by DavidSanchezGracia** [comment]
Hi again,

Any update on this one?

**Comment by scudette** [comment]
Have you tried to manually override the binary with the latest version?

From memory that binary has some issues with it being a GUI compiled binary so it's not really suitable for command line.

We use the sqlite hunter and want to get it to the same level as that tool. Ideally there will be no advantage in using the nirsoft tool as all it's doing is parse a few sqlite files.

**Comment by scudette** [comment]
This should be done now. You might need to hit - redownload binary in the tool setup page to refetch the tool
