### ISSUE TITLE
Windows.Forensics.SRUM improvement

### ISSUE THREAD

**Issue by DavidSanchezGracia** [Velocidex/velociraptor#2408]
Hi there,

Playing around with "Windows.Forensics.SRUM" I found that the User column contains the SID of the user that executed the program. It would be really useful if the artifact give the possibility of comparing the SID with the results of "Windows.Sys.Users" so it can directly display the username. 

Thank you in advance.

**Comment by scudette** [comment]
Fixed by #2413
