### ISSUE TITLE
Auto Collector (offline collector to velociraptor console)

### ISSUE THREAD

**Issue by Xboarder56** [Velocidex/velociraptor#2414]
Hi All,

After creating a few offline collectors I have come to really love the ability to have it execute a hunt for me straight from the EXE.

is it possible/(potential feature request) to create a 1 click collector that instead of uploads to s3 goes to the velociraptor server?

**Comment by Xboarder56** [comment]
Or even as an alternative, on first client creation/connection with velociraptor. Execute a hunt automatically.

**Comment by predictiple** [comment]
What you've described sounds like a normal (not offline) Velociraptor setup. In order for the client to be able to upload to the server it has to be connected and enrolled already.

On the server you can create a hunt first and then go run the client(s). The new client connects to the server and enrolls. The server then schedules the hunt on that client which then does as specified by the hunt.

If what you mean is that the collection is "uploaded" to the server out-of-band, then there is a server artifact that imports the collection as if it had been done online. That artifact is named `Server.Utils.ImportCollection`.

**Comment by Xboarder56** [comment]
Is it possible to package it up where the client itself when run as:

velo.exe client -v

could enroll and then execute that hunt automatically? Without any intervention

**Comment by predictiple** [comment]
Yes it works exactly like that. A hunt will apply to existing clients _and clients that enroll in future_ (during the time period that the hunt is active).

As long as the hunt applies to the client, which it should since by default hunts apply to all clients. If you want certain hunts to apply only to certain clients then you can target the hunt by label and include the label in the client config.

**Comment by Xboarder56** [comment]
I got it pretty close with just needing to tag the client on connection using a hunt.

**Comment by Xboarder56** [comment]
@predictiple is it possible to auto tag the client via the config.yaml packed into the exe?

**Comment by Xboarder56** [comment]
You rock! Thank you!
