### ISSUE TITLE
Velociraptor SSO behind Reverse proxy

### ISSUE THREAD

**Issue by AnthonyH26** [Velocidex/velociraptor#2443]
I am attempting to setup velociraptor within a homelab environment (limited IPs) and am attempting to use SSO with Azure and a reverse proxy (Does not have to offload SSL, more of a SNI router), however, the issue I am having is similar to that of  #1954 

This was because although it works when connecting through the domain, attempting the IP address of the VM returns nothing, curl shows:
`curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error`

I was wondering if there was some workaround or support for Reverse proxies and SSO someone has managed to figure out or if I need to find another way around this (Most likely just choosing a different NAT port)

**Comment by scudette** [comment]
Using the IP address is unlikely to work as the certificate is issued for a domain usually. What are the issues you are seeing?

If you want to just terminate the TLS on your reverse proxy you can turn it off the Velociraptor server. See this for more info https://docs.velociraptor.app/blog/2020/2020-09-28-velociraptor-network-communications-30568624043a/#ssl-offloading

Otherwise I not aware of any issues with placing Oauth behind a proxy. As long as the redirect URLs are working and configured properly it should just follow the right flow.

**Comment by AnthonyH26** [comment]
My issue was more of this flow: request to site(velociraptor.site.com) > Reverse Proxy > 192.168.1.xxx as I could not then send it to velociraptor.site.com again due to it then looping back to nginx.

For TLS offloading it should be okay to then set all the places where 443 is in use to 80 and set use_plain_http: true on the frontend and GUI (although the GUI is still bound to 127.0.0.1) ?

**Comment by scudette** [comment]
If you want the GUI to be externally accessible you need to bind it to 0.0.0.0 

Do you see nginx making a request to the Velociraptor server? It is often easier to enable debug logs and run interactively as described here https://docs.velociraptor.app/docs/deployment/troubleshooting/

**Comment by AnthonyH26** [comment]
So I managed to fix it with 
` proxy_ssl_name $host; `
` proxy_ssl_server_name on; `
but a query on the Letsencrypt, which verification method does this use?  tls-sni-01 or http-01 ?

**Comment by scudette** [comment]
It uses either depending on the type of challenge:

https://cs.opensource.google/go/x/crypto/+/refs/tags/v0.6.0:acme/autocert/autocert.go;l=807

**Comment by AnthonyH26** [comment]
Many thanks!
Unfortunately I was unable to set it up behind the reverse proxy so had to change which host was exposed over port 443 for 2 minutes but after it got the certbot cert. All is well now.

Thank you for your help!
