### ISSUE TITLE
Support references to files for secrets.

### ISSUE THREAD

**Issue by ch0wm3in** [Velocidex/velociraptor#2452]
It would be a nice feature, to support a file reference for eg. oauth_client_secret used in azure SSO in the server.config.yaml file, this is useful because then you could use stuff like eg. vault agent to automatically template the secret to said file. 

https://github.com/Velocidex/velociraptor/blob/7099393ffae6dfc6d862b2795a319cdba2f02a8a/config/proto/config.proto#L336

**Comment by scudette** [comment]
You can set any config option from the command line - so therefore you can also take that value from a file.

You can see how to update any config option using
```
DEBUG=1 velociraptor --help 2>&1 | grep oauth
      --config.gui-authenticator-oauth-client-id=CONFIG.GUI-AUTHENTICATOR-OAUTH-CLIENT-ID
      --config.gui-authenticator-oauth-client-secret=CONFIG.GUI-AUTHENTICATOR-OAUTH-CLIENT-SECRET
      --config.gui-google-oauth-client-id=CONFIG.GUI-GOOGLE-OAUTH-CLIENT-ID
      --config.gui-google-oauth-client-secret=CONFIG.GUI-GOOGLE-OAUTH-CLIENT-SECRET
```

So all you have to do is to modify the startup script for velociraptor to feed the value from a file. Something like this should work:
```
velociraptor --config /etc/server.config.yaml --config.gui-authenticator-oauth-client-secret "$(<some_file)"
```

**Comment by ch0wm3in** [comment]
Oh nice, that'll work too! 👍
