### ISSUE TITLE
yara: Failed to open /  failed, will use accessor error messages

### ISSUE THREAD

**Issue by WD-ST** [Velocidex/velociraptor#2463]
I have been using the yara scanning collector for about 6 months. Every time we run it with admin privileges but get a constant lines of info errors. I have been asked to explain them.

**Example of errors:**
[INFO] 2023-02-20T14:30:11+10:30 Directly scanning file C:\MMCEx.dll failed, will use accessor
[INFO] 2023-02-20T14:30:11+10:30 yara: Failed to open C:\MMCEx.dll with accessor : open C:\MMCEx.dll: The system cannot find the file specified., unable to fall back to ntfs parsing: Not found
[INFO] 2023-02-20T14:30:13+10:30 Directly scanning file C:\Microsoft.AppV.AppvClientComConsumer.resources.dll failed, will use accessor
[INFO] 2023-02-20T14:30:13+10:30 yara: Failed to open C:\Microsoft.AppV.AppvClientComConsumer.resources.dll with accessor : open C:\Microsoft.AppV.AppvClientComConsumer.resources.dll: The system cannot find the file specified., unable to fall back to ntfs parsing: Not found
[INFO] 2023-02-20T14:30:14+10:30 Directly scanning file C:\PresentationBuildTasks.dll failed, will use accessor
[INFO] 2023-02-20T14:30:14+10:30 yara: Failed to open C:\PresentationBuildTasks.dll with accessor : open C:\PresentationBuildTasks.dll: The system cannot find the file specified., unable to fall back to ntfs parsing: Not found
[INFO] 2023-02-20T14:30:15+10:30 Directly scanning file C:\System.AddIn.dll failed, will use accessor
[INFO] 2023-02-20T14:30:15+10:30 yara: Failed to open C:\System.AddIn.dll with accessor : open C:\System.AddIn.dll: The system cannot find the file specified., unable to fall back to ntfs parsing: Not found
[INFO] 2023-02-20T14:30:29+10:30 Directly scanning file C:\Users\<UserName>\AppData\Local\Microsoft\WindowsApps\Skype.exe failed, will use accessor
[INFO] 2023-02-20T14:30:30+10:30 Directly scanning file C:\Users\<UserName>\AppData\Local\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\DeviceSearchCache\Apps_{16827c38-5fcc-4406-a6d9-2ed0e6444191}\0.2.filtertrie.intermediate.txt failed, will use accessor

![image](https://user-images.githubusercontent.com/94940315/220006121-5842f678-65d5-485c-a86c-6b66a74c5f5f.png)

**Comment by scudette** [comment]
Can you please explain what artifact your are running how are you running it and what the parameters are?

**Comment by mgreen27** [comment]
I think its probably the Yara.ntfs artifact. The yara component doesn't specify ntfs for scan speed so when a file is found, it will try to hit it by the default yara file accessor first.

**Comment by scudette** [comment]
That is expected but it looks like it is interpreting the rest of a path as a linux path so it tries to open the literal file with \ escaped (linux path can have \ in them)

It looks as thought the artifact us using FullPath instead of OSPath and getting confused during serialization/parsing round

**Comment by WD-ST** [comment]
This was using the Windows.Search.Yara artefact with one small modification which allows the addition of the matching file hashes being returned in the resulting json file.

This is a collector being run on a live device (not specific files or dead drive analysis) with the default parameters

**Comment by WD-ST** [comment]
The Artifact code just in case:


name: Custom.Windows.Search.Yara
description: |
  Searches for a specific malicious file or set of files by a Yara rule.
  
  Customised to add:
  - scanning for .ASP and .ASPX files
  - SHA256 and MD5 hashes of discovered files

tools:
  - name: YaraRules

parameters:
    - name: nameRegex
      description: Only file names that match this regular expression will be scanned.
      default: "(exe|txt|dll|php|asp|aspx)$"
    - name: AlsoUpload
      type: bool
      description: Also upload matching files.

precondition:
  SELECT * FROM info() WHERE OS =~ "windows"

sources:
  - query: |
        LET yara_rules <= SELECT read_file(filename=FullPath) AS Rule,
           basename(path=FullPath) AS ToolName
        FROM Artifact.Generic.Utils.FetchBinary(
             ToolName="YaraRules", IsExecutable=FALSE)

        LET fileList = SELECT FullPath
        FROM parse_mft(
            accessor="ntfs",
            filename="C:\\$MFT")
        WHERE InUse
          AND FileName =~ nameRegex
          AND NOT FileName = yara_rules[0].ToolName
          AND NOT FullPath =~ "WinSXS"


        -- These files are typically short - only report a single hit.
        LET search = SELECT Rule, String.Offset AS HitOffset,
             str(str=String.Data) AS HitContext,
             FileName,
             File.Size AS Size,
             File.ModTime AS ModTime,
             hash(path=FileName).SHA256 as sha256,
             hash(path=FileName).MD5 as md5
        FROM yara(
            rules=yara_rules[0].Rule, key="A",
            files="C:/" + FullPath)
        LIMIT 1

        -- Only do something when yara rules are available.
        SELECT * FROM if(condition=yara_rules,
        then={
          SELECT *, if(condition=AlsoUpload, then=upload(file=FileName)) AS Upload
          FROM foreach(row=fileList, query=search)
        })

**Comment by scudette** [comment]
I have a fix to that artifact which I will submit shortly - it is basically a Fullpath vs OSPath issue.

```sql
name: Custom.Windows.Search.Yara
description: |
  Searches for a specific malicious file or set of files by a Yara rule.

parameters:
    - name: nameRegex
      description: Only file names that match this regular expression will be scanned.
      default: "(exe|txt|dll|php)$"
      type: regex
    - name: AlsoUpload
      type: bool
      description: Also upload matching files.
    - name: yaraRule
      type: yara
      description: The Yara Rule to search for.

precondition:
  SELECT * FROM info() WHERE OS =~ "windows"

sources:
  - name: Test
    query: |
        LET Root = pathspec(parse="C:", path_type="ntfs")

        SELECT *, Root + OSPath AS OSPath
        FROM parse_mft(accessor="ntfs",filename=Root+"$MFT")
        WHERE InUse
          AND FileName =~ nameRegex
          AND NOT OSPath =~ "WinSXS"
        LIMIT 1000
        
  - query: |
        LET Root = pathspec(parse="C:", path_type="ntfs")

        LET fileList = SELECT Root + OSPath AS OSPath
        FROM parse_mft(accessor="ntfs",filename=Root+"$MFT")
        WHERE InUse
          AND FileName =~ nameRegex
          AND NOT OSPath =~ "WinSXS"


        -- These files are typically short - only report a single hit.
        LET search = SELECT Rule, String.Offset AS HitOffset,
             str(str=String.Data) AS HitContext,
             FileName,
             File.Size AS Size,
             File.ModTime AS ModTime
        FROM yara(
            rules=yaraRule, key="A",
            files= OSPath)
        LIMIT 1

        SELECT *, if(condition=AlsoUpload, then=upload(file=FileName)) AS Upload
        FROM foreach(row=fileList, query=search)
     ```

**Comment by WD-ST** [comment]
Thank you. I will test it in the next couple of days

**Comment by WD-ST** [comment]
Using the code from above, with the small addition of the SHA256 and MDS, I still get a screen full or errors.
Only done limited testing so far, but wanted to see if I'm doing something wrong

```
name: Custom.Windows.Search.Yara
description: |
  Searches for a specific malicious file or set of files by a Yara rule.
  Customised to add:

    - scanning for .ASP and .ASPX files
    - SHA256 and MD5 hashes of discovered files
    
tools:
  - name: YaraRules

parameters:
    - name: nameRegex
      description: Only file names that match this regular expression will be scanned.
      default: "(exe|txt|dll|php|asp|aspx)$"
      type: regex
    - name: AlsoUpload
      type: bool
      description: Also upload matching files.
    - name: yaraRule
      type: yara
      description: The Yara Rule to search for.

precondition:
  SELECT * FROM info() WHERE OS =~ "windows"

sources:
  - query: |
        LET Root = pathspec(parse="C:", path_type="ntfs")

        LET fileList = SELECT Root + OSPath AS OSPath
        FROM parse_mft(accessor="ntfs",filename=Root+"$MFT")
        WHERE InUse
          AND FileName =~ nameRegex
          AND NOT OSPath =~ "WinSXS"


        -- These files are typically short - only report a single hit.
        LET search = SELECT Rule, String.Offset AS HitOffset,
             str(str=String.Data) AS HitContext,
             FileName,
             File.Size AS Size,
             File.ModTime AS ModTime,
             hash(path=FileName).SHA256 as sha256,
             hash(path=FileName).MD5 as md5
        FROM yara(
            rules=yaraRule, key="A",
            files= OSPath)
        LIMIT 1

        SELECT *, if(condition=AlsoUpload, then=upload(file=FileName)) AS Upload
        FROM foreach(row=fileList, query=search)
```

![image](https://user-images.githubusercontent.com/94940315/220525485-e5c83a43-a489-42e4-aede-220f23f483b9.png)

**Comment by WD-ST** [comment]
When I use a collector with the above code (to scan C drive) and using the same code for separate artifacts to scan the D & E drive, rolled into one collector I don't get those errors

```
INFO] 2023-02-22T15:59:18+10:30 yara: Failed to open \\.\C:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\micaut.dll with accessor : open \\.\C:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\micaut.dll: The system cannot find the file specified., unable to fall back to ntfs parsing: Not found
[INFO] 2023-02-22T15:59:18+10:30 Collected Custom.Windows.Search.Yara
[INFO] 2023-02-22T15:59:18+10:30 Will throttle query to 20 percent of 2 available CPU resources (0.40 cores long term average).
[INFO] 2023-02-22T15:59:18+10:30 Starting collection of Custom.Windows.SearchD.Yara
[INFO] 2023-02-22T15:59:19+10:30 Collected Custom.Windows.SearchD.Yara
[INFO] 2023-02-22T15:59:19+10:30 Will throttle query to 20 percent of 2 available CPU resources (0.40 cores long term average).
[INFO] 2023-02-22T15:59:19+10:30 Starting collection of Custom.Windows.SearchE.Yara
[INFO] 2023-02-22T15:59:31+10:30 Collected Custom.Windows.SearchE.Yara
[INFO] 2023-02-22T15:59:31+10:30 Will throttle query to 20 percent of 2 available CPU resources (0.40 cores long term average).
[INFO] 2023-02-22T15:59:31+10:30 Adding global destructor for C:\Users\winphish\AppData\Local\Temp\tmp1033502055.zip
```

But scanning C, D and E using that new code found no results, when I know I have specific yara rules based on files on this machine.

**Comment by scudette** [comment]
The VQL in the artifact you posted has
```sql
  LET search = SELECT Rule, String.Offset AS HitOffset,
             str(str=String.Data) AS HitContext,
             FileName,
             File.Size AS Size,
             File.ModTime AS ModTime,
             hash(path=FileName).SHA256 as sha256,
             hash(path=FileName).MD5 as md5
        FROM yara(
            rules=yaraRule, key="A",
            files= OSPath)
        LIMIT 1
```

But FileName is only the filename of the file - it is not the full path to the file (which is given by OSPath) so that is why the warning messages are about opening C:\bootres.dll for example because it is trying to open the actual file from the root. You need to replace that FileName with OSPath to open the full file.

Also the VQL will hash the same file twice so it is better to only hash it once and then report both fields later.

**Comment by scudette** [comment]
I think this one is done? Please reopen if there is further action needed.
