### ISSUE TITLE
certain formated input data being shown as "Invalid date"

### ISSUE THREAD

**Issue by Herbert-Karl** [Velocidex/velociraptor#2466]
I stumbled upon strange behaviour in velociraptor, which I see as a bug.

I found that for certain formatted output data from journalctl (collected via execve), the GUI would not show the actual data but rather the string "Invalid date" . This is inconsistent with the output collected on the host itself and the data reported in the json output for such query. Visual representation is at the end of my issue.

Steps to reproduce
+ take Linux host
+ run velo executable as standalone host
+ open velo gui
+ go to the enrolled host
+ switch to "Shell"
+ run following VQL query: `SELECT * FROM execve(argv=["sh", "-c", "journalctl --all --output=short-iso"], sep="\n")`
	+ disclamer: I minimized the query and stripped some elements to hide information; the intent behind the query is to search for certain keywords in the journal logs
+ look at results
	+ instead of the log lines, you should see "Invalid date" in the "Stdout" column
	+ hovering with the mouse over the string "Invalid date" seems to crash the tab (GUI goes blank white; page has to be reloaded)
+ download flow results and compare content with gui results 
	+ flow contains relevant/wanted data, gui doesn't
	+ alternatively compare content in gui with "Inspect Raw JSON" option

tested and reproduced on
+ Ubuntu 16.04. LTS with velo v0.6.7-4 (musl variant)
+ Fedora 37 with velo v0.6.7-5 as well as v0.6.8-rc1

_The problem seems to somehow relate to the iso formated output from journalctl. Running the query with any non-iso output format delivers the expected results. More strangely, if the query is run with iso output format and no seperator in execve, the results are as expected._

![error_gui](https://user-images.githubusercontent.com/34774005/220316909-644a7c62-f114-4f24-97e0-780ce9864351.PNG)
![gui_raw_json](https://user-images.githubusercontent.com/34774005/220316919-5354accf-9066-455f-8182-826dca7dd0b4.PNG)

**Comment by scudette** [comment]
Thanks for reporting this bug!

This happened because the GUI is looking for something that looks like a date so it can format it as a timestamp (adding the tooltip overlay and also converting to the user specified timezone). The regex used previously assumed the entire cell is a timestamp but was confused when the timestamp is part of the larger cell content.

I submitted #2467 that properly breaks up the cell content into timestamps and other text. You can test it with the CI binaries.

**Comment by Herbert-Karl** [comment]
I have tested with the binaries of the PR. The problem is gone.
Thanks for the quick reaction and fix. :)
