### ISSUE TITLE
Artifact Windows.Sysinternals.Autoruns - 32-bit tool (Minor)

### ISSUE THREAD

**Issue by yarox24** [Velocidex/velociraptor#2475]
In following line:
https://github.com/Velocidex/velociraptor/blob/19d84ad127ad4c3919db0c94b3604f793c6a864f/artifacts/definitions/Windows/Sysinternals/Autoruns.yaml#L8

32-bit version of tool is defined as Autorun_**x86**

Error when executing on 32-bit Windows 8:
inventory_get: Tool Autorun_**386** not declared in inventory.

VQL Query on Windows 8 (32-bit):
![image](https://user-images.githubusercontent.com/18016218/221129484-c3fce517-7d45-420a-85dd-3f4aa4bb6801.png)

**Comment by mgreen27** [comment]
@yarox24 I cant recall last time I saw a x86 machine to tell you if this is normal!
Can you try to change the - name: Autorun_x86 to - name: Autorun_386 and test?

If it works we can look at fixing the artifact, I can run some scoping to see if I can find other x86 machines and what they report. We can either just change the definition to 386 or look at adding an additional definition if needed.

**Comment by yarox24** [comment]
I made following change:
![image](https://user-images.githubusercontent.com/18016218/221172470-eb641908-a60a-4b15-a159-7651a382d8f4.png)


And execution on Win8 is now working:
![image](https://user-images.githubusercontent.com/18016218/221172511-07f158dc-fc9b-46b2-96d9-26e10987796f.png)

![image](https://user-images.githubusercontent.com/18016218/221172536-3cb66f51-c476-46e0-a19d-c7a1149de653.png)

**Comment by scudette** [comment]
Thanks for reporting the bug! would you like to send a PR?

**Comment by yarox24** [comment]
Yes
