### ISSUE TITLE
Not able to "add" Linux Client after "Deletion"

### ISSUE THREAD

**Issue by denizciftci-sec** [Velocidex/velociraptor#2476]
Hi!

I have created and installed a linux client on a centos machine as guided (below). I was able to see the client in server but then the status icon turned to "yellow" from "green" and I **deleted** the client on server manually and I stopped/disabled the service (systemctl) on client and deleted dpkg file and re-installed it. I followed below steps but I am not able to see the successful connection of this linux client after re-installation. Could you please assist me related to this issue?

#**./velociraptor-v0.6.7-4-linux-amd64-musl --config velociraptor.config.yaml debian client**
# **dpkg -i velociraptor_0.6.7-4_client.deb**
Selecting previously unselected package velociraptor-client.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack velociraptor_0.6.7-4_client.deb ...
Unpacking velociraptor-client (0.6.7-4) ...
Setting up velociraptor-client (0.6.7-4) ...
Created symlink from /etc/systemd/system/multi-user.target.wants/velociraptor_client.service to /etc/systemd/system/velociraptor_client.service.

**Comment by mgreen27** [comment]
@denizciftci-sec can you run the same command but add the '-v' switch for verbose output?

This should give you an idea of what may be happening.

**Comment by scudette** [comment]
Troubleshooting steps https://docs.velociraptor.app/docs/deployment/troubleshooting/

**Comment by denizciftci-sec** [comment]
Thanks @mgreen27  and @scudette . It seems that it is connected to server which is 10.1.3.222. But I am not able to see the client as listed in server client list. Btw system is working OK on client side - there is no errors. 




[root@t-ifs-wazuh-srv01 opt]# ./velociraptor-v0.6.7-4-linux-amd64-musl  --config velociraptor.config.yaml client -v
[INFO] 2023-02-24T12:41:03+01:00  _    __     __           _                  __ 
[INFO] 2023-02-24T12:41:03+01:00 | |  / /__  / /___  _____(_)________ _____  / /_____  _____ 
[INFO] 2023-02-24T12:41:03+01:00 | | / / _ \/ / __ \/ ___/ / ___/ __ `/ __ \/ __/ __ \/ ___/ 
[INFO] 2023-02-24T12:41:03+01:00 | |/ /  __/ / /_/ / /__/ / /  / /_/ / /_/ / /_/ /_/ / / 
[INFO] 2023-02-24T12:41:03+01:00 |___/\___/_/\____/\___/_/_/   \__,_/ .___/\__/\____/_/ 
[INFO] 2023-02-24T12:41:03+01:00                                   /_/ 
[INFO] 2023-02-24T12:41:03+01:00 Digging deeper!                  https://www.velocidex.com 
[INFO] 2023-02-24T12:41:03+01:00 This is Velociraptor 0.6.7-4 built on 2022-12-06T13:31:44Z (c6f11a7) 
[INFO] 2023-02-24T12:41:03+01:00 Loading config from file velociraptor.config.yaml 
[INFO] 2023-02-24T12:41:03+01:00 Loading writeback from /etc/velociraptor.writeback.yaml 
[INFO] 2023-02-24T12:41:03+01:00 Starting Org Manager service. 
[INFO] 2023-02-24T12:41:03+01:00 Starting nanny with MaxConnectionDelay 10m0s and MaxMemoryHardLimit 0 
[INFO] 2023-02-24T12:41:03+01:00 Starting services for Root Org 
[INFO] 2023-02-24T12:41:03+01:00 Starting Journal service for Root Org. 
[INFO] 2023-02-24T12:41:03+01:00 Starting the notification service for Root Org. 
[INFO] 2023-02-24T12:41:03+01:00 NotificationService: Watching for events from Server.Internal.Ping 
[INFO] 2023-02-24T12:41:03+01:00 NotificationService: Watching for events from Server.Internal.Pong 
[INFO] 2023-02-24T12:41:03+01:00 NotificationService: Watching for events from Server.Internal.Notifications 
[INFO] 2023-02-24T12:41:03+01:00 Starting repository manager for Root Org 
[INFO] 2023-02-24T12:41:03+01:00 RepositoryManager: Watching for events from Server.Internal.ArtifactModification 
[INFO] 2023-02-24T12:41:04+01:00 Loaded 347 built in artifacts in 173.134069ms 
[INFO] 2023-02-24T12:41:04+01:00 Starting Inventory Service for Root Org 
[INFO] 2023-02-24T12:41:04+01:00 Starting Crypto for client C.0c0e173630988839 
[INFO] 2023-02-24T12:41:04+01:00 Expecting self signed certificate for server. 
[INFO] 2023-02-24T12:41:04+01:00 Ring Buffer: Creation {"filename":"/var/tmp/Velociraptor_Buffer.bin","max_size":1073741874}
[INFO] 2023-02-24T12:41:04+01:00 Starting event query service with version 0. 
[INFO] 2023-02-24T12:41:04+01:00 Starting HTTPCommunicator: HTTP Connector to [https://10.1.3.222:8000/] 
[INFO] 2023-02-24T12:41:04+01:00 Closing EventTable 
[INFO] 2023-02-24T12:41:04+01:00 Starting monitoring query $efe2df3bf94e4d1768ca65abc6cd48c39e9e1d3e050937f2fc3024374d9a561e 
[INFO] 2023-02-24T12:41:04+01:00 Starting monitoring query $efe2df3bf94e4d1768ca65abc6cd48c39e9e1d3e050937f2fc3024374d9a561e 
[INFO] 2023-02-24T12:41:04+01:00 Starting query execution. 
[INFO] 2023-02-24T12:41:04+01:00 Starting query execution. 
[INFO] 2023-02-24T12:41:04+01:00 Starting event query service with version 1677230137818762542. 
[INFO] 2023-02-24T12:41:04+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":201,\"MaxSize\":1073741874,\"AvailableBytes\":143,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:04+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":352,\"MaxSize\":1073741874,\"AvailableBytes\":286,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:04+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":393,\"MaxSize\":1073741874,\"AvailableBytes\":319,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:04+01:00 Skipping query due to preconditions 
[INFO] 2023-02-24T12:41:04+01:00 Collection is done after 10.686236ms 
[DEBUG] 2023-02-24T12:41:04+01:00 Query Stats: {"RowsScanned":1,"PluginsCalled":1,"FunctionsCalled":0,"ProtocolSearch":0,"ScopeCopy":4} 
[INFO] 2023-02-24T12:41:04+01:00 Finished monitoring query $efe2df3bf94e4d1768ca65abc6cd48c39e9e1d3e050937f2fc3024374d9a561e 
[INFO] 2023-02-24T12:41:04+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":559,\"MaxSize\":1073741874,\"AvailableBytes\":477,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:04+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":670,\"MaxSize\":1073741874,\"AvailableBytes\":580,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:04+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":834,\"MaxSize\":1073741874,\"AvailableBytes\":736,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:04+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":1065,\"MaxSize\":1073741874,\"AvailableBytes\":959,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:04+01:00 Received PEM for VelociraptorServer from https://10.1.3.222:8000/ 
[INFO] 2023-02-24T12:41:04+01:00 Receiver C.0c0e173630988839: Connected to https://10.1.3.222:8000/reader 
[DEBUG] 2023-02-24T12:41:04+01:00 Connection Info {"IdleTime":2069849,"LocalAddr":{"IP":"10.1.3.200","Port":43992,"Zone":""},"Reused":true,"WasIdle":true}
[INFO] 2023-02-24T12:41:04+01:00 Receiver C.0c0e173630988839: sent 658 bytes, response with status: 406 Not Acceptable 
[INFO] 2023-02-24T12:41:04+01:00 Enrolling 
[INFO] 2023-02-24T12:41:04+01:00 Ring Buffer: Enqueue {"item_len":925,"total_length":925}
[INFO] 2023-02-24T12:41:04+01:00 Compiled all artifacts. 
[INFO] 2023-02-24T12:41:05+01:00 Ring Buffer: Leased {"leased_length":925,"total_length":925}
[INFO] 2023-02-24T12:41:05+01:00 Sender: Connected to https://10.1.3.222:8000/control 
[DEBUG] 2023-02-24T12:41:05+01:00 Connection Info {"IdleTime":0,"LocalAddr":{"IP":"10.1.3.200","Port":43994,"Zone":""},"Reused":false,"WasIdle":false}
[INFO] 2023-02-24T12:41:05+01:00 Sender: sent 1395 bytes, response with status: 406 Not Acceptable 
[INFO] 2023-02-24T12:41:05+01:00 Ring Buffer: Commit {"leased_length":925,"total_length":925}
[INFO] 2023-02-24T12:41:05+01:00 Ring Buffer: Truncate {"total_length":0}
[INFO] 2023-02-24T12:41:05+01:00 Sender: Connected to https://10.1.3.222:8000/control 
[DEBUG] 2023-02-24T12:41:05+01:00 Connection Info {"IdleTime":0,"LocalAddr":{"IP":"10.1.3.200","Port":43996,"Zone":""},"Reused":false,"WasIdle":false}
[INFO] 2023-02-24T12:41:05+01:00 Receiver C.0c0e173630988839: Connected to https://10.1.3.222:8000/reader 
[INFO] 2023-02-24T12:41:05+01:00 Sender: sent 1091 bytes, response with status: 200 OK 
[INFO] 2023-02-24T12:41:05+01:00 Sender: received 626 bytes 
[DEBUG] 2023-02-24T12:41:05+01:00 Connection Info {"IdleTime":0,"LocalAddr":{"IP":"10.1.3.200","Port":43996,"Zone":""},"Reused":true,"WasIdle":false}
[INFO] 2023-02-24T12:41:05+01:00 Receiver C.0c0e173630988839: sent 674 bytes, response with status: 200 OK 
[INFO] 2023-02-24T12:41:05+01:00 Receiver C.0c0e173630988839: received 6387 bytes 
[DEBUG] 2023-02-24T12:41:05+01:00 Received request: session_id:"F.CFSA4KBCUK3TM" request_id:1 source:"VelociraptorServer" auth_state:AUTHENTICATED task_id:1677238865133371419 VQLClientAction:{query_id:1 total_queries:3 Query:{VQL:"LET Interfaces = SELECT format(format='%02x:%02x:%02x:%02x:%02x:%02x', args=HardwareAddr) AS MAC FROM interfaces() WHERE HardwareAddr"} Query:{VQL:"LET Generic_Client_Info_BasicInformation_0_1 = SELECT config.Version.Name AS Name, config.Version.BuildTime AS BuildTime, config.Version.Version AS Version, config.Version.ci_build_url AS build_url, config.Labels AS Labels, Hostname, OS, Architecture, Platform, PlatformVersion, KernelVersion, Fqdn, Interfaces.MAC AS MACAddresses FROM info()"} Query:{Name:"$b09aea1001538b053993b8ff8e29da7761e09ae224a4079635f487ae4f3d73a91c3214ff732b9668b762476c061b35d2" VQL:"SELECT * FROM Generic_Client_Info_BasicInformation_0_1"} max_row:1000} 
[DEBUG] 2023-02-24T12:41:05+01:00 Received request: session_id:"F.CFSA4KBCUK3TM" query_id:1 request_id:1 source:"VelociraptorServer" auth_state:AUTHENTICATED task_id:1677238865133502492 VQLClientAction:{query_id:2 total_queries:3 precondition:"SELECT OS From info() where OS = 'windows'" Query:{VQL:"LET precondition_Generic_Client_Info_WindowsInfo_0 = SELECT OS FROM info() WHERE OS = 'windows'"} Query:{VQL:"LET DomainLookup <= dict(`0`='Standalone Workstation', `1`='Member Workstation', `2`='Standalone Server', `3`='Member Server', `4`='Backup Domain Controller', `5`='Primary Domain Controller')"} Query:{VQL:"LET Generic_Client_Info_WindowsInfo_0_1 = SELECT { SELECT DNSHostName, Name, Domain, TotalPhysicalMemory, get(item=DomainLookup, field=str(str=DomainRole), default=\"Unknown\") AS DomainRole FROM wmi(query='SELECT * FROM win32_computersystem') } AS `Computer Info`, { SELECT Caption, join(array=IPAddress, sep=\", \") AS IPAddresses, join(array=IPSubnet, sep=\", \") AS IPSubnet, MACAddress, join(array=DefaultIPGateway, sep=\", \") AS DefaultIPGateway, DNSHostName, join(array=DNSServerSearchOrder, sep=\", \") AS DNSServerSearchOrder FROM wmi(query=\"SELECT * from Win32_NetworkAdapterConfiguration\") WHERE IPAddress } AS `Network Info` FROM scope()"} Query:{Name:"$b09aea1001538b053993b8ff8e29da778aea1db5052dc7b78956ba6ae0d9cb30" VQL:"SELECT * FROM if(then=Generic_Client_Info_WindowsInfo_0_1, condition=precondition_Generic_Client_Info_WindowsInfo_0, else={ SELECT * FROM scope() WHERE log(message='Query skipped due to precondition')  AND FALSE })"} max_row:1000} 
[DEBUG] 2023-02-24T12:41:05+01:00 Received request: session_id:"F.CFSA4KBCUK3TM" query_id:2 request_id:1 source:"VelociraptorServer" auth_state:AUTHENTICATED task_id:1677238865133568029 VQLClientAction:{query_id:3 total_queries:3 precondition:"SELECT OS From info() where OS = 'windows'" Query:{VQL:"LET precondition_Generic_Client_Info_Users_0 = SELECT OS FROM info() WHERE OS = 'windows'"} Query:{VQL:"LET Generic_Client_Info_Users_0_0 = SELECT Name, Description, Mtime AS LastLogin FROM Artifact.Windows.Sys.Users(OnlyRemote=TRUE)"} Query:{Name:"$b09aea1001538b053993b8ff8e29da777fadc7232b47380727c634049694d3e1" VQL:"SELECT * FROM if(then=Generic_Client_Info_Users_0_0, condition=precondition_Generic_Client_Info_Users_0, else={ SELECT * FROM scope() WHERE log(message='Query skipped due to precondition')  AND FALSE })"} max_row:1000 artifacts:{name:"Windows.Sys.Users" parameters:{name:"remoteRegKey" default:"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\ProfileList\\*"} parameters:{name:"OnlyRemote" type:"bool"} type:"client" sources:{precondition:"SELECT OS FROM info() WHERE OS = 'windows'" queries:"LET GetTimestamp(High, Low) = if(condition=High, then=timestamp(winfiletime=High * 4294967296 + Low))" queries:"LET roaming_users = SELECT split(string=Key.OSPath.Basename, sep=\"-\")[-1] AS Uid, \"\" AS Gid, lookupSID(sid=Key.OSPath.Basename) || \"\" AS Name, Key.OSPath AS Description, ProfileImagePath AS Directory, Key.OSPath.Basename AS UUID, Key.Mtime AS Mtime, { SELECT Mtime FROM stat(filename=expand(path=ProfileImagePath)) } AS HomedirMtime, \"roaming\" AS Type, dict(ProfileLoadTime=GetTimestamp(High=LocalProfileLoadTimeHigh, Low=LocalProfileLoadTimeLow), ProfileUnloadTime=GetTimestamp(High=LocalProfileUnloadTimeHigh, Low=LocalProfileUnloadTimeLow)) AS Data FROM read_reg_key(globs=remoteRegKey, accessor=\"registry\")" queries:"LET local_users = SELECT User_id AS Uid, Primary_group_id AS Gid, Name, Comment AS Description, { SELECT * FROM roaming_users WHERE User_sid = UUID } AS RoamingData, User_sid AS UUID, \"local\" AS Type FROM users() LIMIT 1000 " queries:"LET local_users_with_mtime = SELECT Uid, Gid, Name, Description, RoamingData.Directory AS Directory, UUID, RoamingData.Mtime AS Mtime, RoamingData.HomedirMtime AS HomedirMtime, Type, RoamingData.Data || dict() AS Data FROM local_users" queries:"LET combined = SELECT * FROM chain(q1=local_users_with_mtime, q2=roaming_users) ORDER BY Gid DESC " queries:"SELECT * FROM if(condition=OnlyRemote, then=roaming_users, else={ SELECT * FROM combined GROUP BY UUID, Name })"}}} 
[DEBUG] 2023-02-24T12:41:05+01:00 Received request: session_id:"F.Monitoring" source:"VelociraptorServer" auth_state:AUTHENTICATED task_id:1677238865142677534 UpdateEventTable:{event:{query_id:1 total_queries:2 precondition:"SELECT OS From info() where OS = 'windows'" env:{key:"Frequency" value:"10"} Query:{VQL:"LET Frequency <= int(int=Frequency)"} Query:{VQL:"LET precondition_Generic_Client_Stats_0 = SELECT OS FROM info() WHERE OS = 'windows'"} Query:{VQL:"LET Generic_Client_Stats_0_0 = SELECT *, rate(x=CPU, y=Timestamp) AS CPUPercent FROM foreach(row={ SELECT UnixNano FROM clock(period=Frequency) }, query={ SELECT UnixNano / 1000000000 AS Timestamp, User + System AS CPU, Memory.WorkingSetSize AS RSS FROM pslist(pid=getpid()) })"} Query:{Name:"$efe2df3bf94e4d1768ca65abc6cd48c39e9e1d3e050937f2fc3024374d9a561e" VQL:"SELECT * FROM if(then=Generic_Client_Stats_0_0, condition=precondition_Generic_Client_Stats_0, else={ SELECT * FROM scope() WHERE log(message='Query skipped due to precondition')  AND FALSE })"} max_row:1000 max_wait:136 timeout:99999999} event:{query_id:2 total_queries:2 precondition:"SELECT OS From info() where OS != 'windows'" env:{key:"Frequency" value:"10"} Query:{VQL:"LET Frequency <= int(int=Frequency)"} Query:{VQL:"LET precondition_Generic_Client_Stats_0 = SELECT OS FROM info() WHERE OS != 'windows'"} Query:{VQL:"LET Generic_Client_Stats_0_0 = SELECT *, rate(x=CPU, y=Timestamp) AS CPUPercent FROM foreach(row={ SELECT UnixNano FROM clock(period=Frequency) }, query={ SELECT UnixNano / 1000000000 AS Timestamp, Times.system + Times.user AS CPU, MemoryInfo.RSS AS RSS FROM pslist(pid=getpid()) })"} Query:{Name:"$efe2df3bf94e4d1768ca65abc6cd48c39e9e1d3e050937f2fc3024374d9a561e" VQL:"SELECT * FROM if(then=Generic_Client_Stats_0_0, condition=precondition_Generic_Client_Stats_0, else={ SELECT * FROM scope() WHERE log(message='Query skipped due to precondition')  AND FALSE })"} max_row:1000 max_wait:137 timeout:99999999} version:1677238865142718839} 
[INFO] 2023-02-24T12:41:05+01:00 Client event query update 1677238865142718839 did not change queries, skipping 
[INFO] 2023-02-24T12:41:05+01:00 Starting query execution. 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":247,\"MaxSize\":1073741874,\"AvailableBytes\":189,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 Starting query execution. 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":414,\"MaxSize\":1073741874,\"AvailableBytes\":348,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":465,\"MaxSize\":1073741874,\"AvailableBytes\":391,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 Skipping query due to preconditions 
[INFO] 2023-02-24T12:41:05+01:00 Collection is done after 8.782582ms 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":647,\"MaxSize\":1073741874,\"AvailableBytes\":565,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":780,\"MaxSize\":1073741874,\"AvailableBytes\":690,\"LeasedBytes\":0}","leased_pointer":50}
[DEBUG] 2023-02-24T12:41:05+01:00 Query Stats: {"RowsScanned":1,"PluginsCalled":1,"FunctionsCalled":0,"ProtocolSearch":0,"ScopeCopy":4} 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":959,\"MaxSize\":1073741874,\"AvailableBytes\":861,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 Collection is done after 10.283019ms 
[DEBUG] 2023-02-24T12:41:05+01:00 Query Stats: {"RowsScanned":4,"PluginsCalled":2,"FunctionsCalled":1,"ProtocolSearch":99,"ScopeCopy":13} 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":1206,\"MaxSize\":1073741874,\"AvailableBytes\":1100,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":1529,\"MaxSize\":1073741874,\"AvailableBytes\":1415,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":2317,\"MaxSize\":1073741874,\"AvailableBytes\":2195,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":2582,\"MaxSize\":1073741874,\"AvailableBytes\":2452,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":2792,\"MaxSize\":1073741874,\"AvailableBytes\":2654,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":3070,\"MaxSize\":1073741874,\"AvailableBytes\":2924,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 Starting query execution. 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":3237,\"MaxSize\":1073741874,\"AvailableBytes\":3083,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 Skipping query due to preconditions 
[INFO] 2023-02-24T12:41:05+01:00 Collection is done after 8.518832ms 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":3419,\"MaxSize\":1073741874,\"AvailableBytes\":3257,\"LeasedBytes\":0}","leased_pointer":50}
[DEBUG] 2023-02-24T12:41:05+01:00 Query Stats: {"RowsScanned":1,"PluginsCalled":1,"FunctionsCalled":0,"ProtocolSearch":0,"ScopeCopy":4} 
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":3552,\"MaxSize\":1073741874,\"AvailableBytes\":3382,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":3731,\"MaxSize\":1073741874,\"AvailableBytes\":3553,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:05+01:00 File Ring Buffer: Enqueue {"header":"{\"ReadPointer\":50,\"WritePointer\":3978,\"MaxSize\":1073741874,\"AvailableBytes\":3792,\"LeasedBytes\":0}","leased_pointer":50}
[INFO] 2023-02-24T12:41:06+01:00 Sender: Connected to https://10.1.3.222:8000/control 
[DEBUG] 2023-02-24T12:41:06+01:00 Connection Info {"IdleTime":993520119,"LocalAddr":{"IP":"10.1.3.200","Port":43996,"Zone":""},"Reused":true,"WasIdle":true}
[INFO] 2023-02-24T12:41:06+01:00 Sender: sent 2003 bytes, response with status: 200 OK 
[INFO] 2023-02-24T12:41:06+01:00 Sender: received 626 bytes 
[INFO] 2023-02-24T12:41:06+01:00 Receiver C.0c0e173630988839: Connected to https://10.1.3.222:8000/reader 
[DEBUG] 2023-02-24T12:41:06+01:00 Connection Info {"IdleTime":3882485,"LocalAddr":{"IP":"10.1.3.200","Port":43996,"Zone":""},"Reused":true,"WasIdle":true}
[INFO] 2023-02-24T12:41:06+01:00 Receiver C.0c0e173630988839: sent 674 bytes, response with status: 200 OK

**Comment by scudette** [comment]
When you say you deleted the client on the server do you mean by deleting it in the GUI or did you remove the files on the system?

You can try to do a Generic.Client.Info hunt to refresh the client index.

**Comment by denizciftci-sec** [comment]
This worked for me, thanks! @scudette
