### ISSUE TITLE
Feature Request: Allow setting hunt expiration date via the GUI

### ISSUE THREAD

**Issue by yampelo** [Velocidex/velociraptor#250]
It would be nice to be able to set the expiry date for a hunt via the GUI when creating a hunt. This will allow the hunt to "auto stop" after a shorter amount of time than a week

**Comment by sjosz** [comment]
And you can allow for it to run longer, which I would find very handy!

**Comment by CR-OmerYampel** [comment]
@scudette  is there any chance this may be able to be added in? we'd like to somehow have a way to have hunts run forever and query new hosts as they log in

**Comment by scudette** [comment]
Available in 0.4.5

**Comment by sjosz** [comment]
Nice, thank you Mike!
