### ISSUE TITLE
velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by velociraptor) 

### ISSUE THREAD

**Issue by branstiveITCOm** [Velocidex/velociraptor#2503]
I am getting this error "velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by velociraptor)" when installing Velociraptor version  0.6.8-rc1 and 0.6.7 on Ubuntu 18.04

**Comment by scudette** [comment]
https://docs.velociraptor.app/knowledge_base/tips/glibc_errors/

**Comment by branstiveITCOm** [comment]
Thank you will try this and share the feedback.
