### ISSUE TITLE
Import / export hunt(s) functionality

### ISSUE THREAD

**Issue by Miesvanderlippe** [Velocidex/velociraptor#2510]
It would be useful to be able to deploy a standard set of hunts for new customers. 

My ideal flow would be: 
- Multi-select for downloading hunts 
- Uploading hunts, possibly in bulk
- Editing imported hunts before starting them

It seems the data in the requests tab is sufficient to do this.

**Comment by mgreen27** [comment]
Does this artifact help your usecase? 
https://github.com/mgreen27/DetectRaptor/blob/master/vql/StartHunts.yaml

**Comment by scudette** [comment]
feel free to reopen this issue if the above link does not do what you need
