### ISSUE TITLE
Global notebook suggestion configuration

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#2511]
The notebook suggestion feature is super useful when leveraging on an artifact. We would like a global notebook suggestion that would enable populating a notebook with suggestions in a similar way.

This could be used for server administration, hunt management or other general analysis tasks. 

The feature would also allow import and export of suggested notebook snippets that should solve some previous requests.

**Comment by scudette** [comment]
What if we had a new artifact type called notebook and reuse the same UI to initialise the notebook from it.

It's generally difficult to export and re import the same notebook because it's hard to get the same state back on a different server

**Comment by mgreen27** [comment]
I think people just want to import basic VQL so they dont need to retype for common tasks (or copy and paste). A suggestion for VQL works here. If it was a notbook artifact type that populated suggestions that would work.

**Comment by scudette** [comment]
We can not include templates for global notebooks which can define any suggestions as well.
