### ISSUE TITLE
Password not accepted during login.

### ISSUE THREAD

**Issue by anish9991** [Velocidex/velociraptor#2513]
I am new to Velociraptor and was trying to setup a server and client for learning purpose.
Post configuration when I try to login to web Gui from a different machine the Gui (browser) asks for password, but would not accept the same. I tried simple and complex passwords, tried different browsers but no result. 

I am using  velociraptor-v0.6.7-4-linux-amd64  on Ubuntu 20-04 server. 
I use Self signed certificate provided by  velociraptor-v0.6.7-4
username admin and password is Password.
I am able to access the gui after accepting the risks.
but when login is attempted, login fails

Can you help me find my error.

**Comment by hiroki-hamasaki** [comment]
Same problem I met.
![image](https://user-images.githubusercontent.com/107527098/224252392-e0c20a12-7ccf-4526-8475-179383438059.png)

**Comment by scudette** [comment]
Be sure that the server is able to write to the data store directory. Sometimes this happens if the directory file permissions are incorrect for example if the server was started as root in there past and now it's trying to run as the low privilege Velociraptor user

**Comment by hiroki-hamasaki** [comment]
Thank you for your resolution. I have had set permission correctly but lack of disk space. Due to this,  failed to create `/opt/velociraptor/users/<username>.db`.

**Comment by scudette** [comment]
Cool - I think this is resolved.

**Comment by anish9991** [comment]
> Be sure that the server is able to write to the data store directory. Sometimes this happens if the directory file permissions are incorrect for example if the server was started as root in there past and now it's trying to run as the low privilege Velociraptor user

Yes this was a permission issue the /opt/velociraptor/users dir and its contents could not be created. 
Now its working fine, and issue is resolved. Thanks for the support.
