### ISSUE TITLE
PsList crashes on linux

### ISSUE THREAD

**Issue by mdenzel** [Velocidex/velociraptor#2517]
Hello,

I think a colleague found a bug. When starting pslist on Linux, velo crashes.

Confirmed on Fedora, Ubuntu and Arch.

Steps to reproduce:

```
> ./velociraptor-v0.6.8-rc1-linux-amd64 -v query "SELECT * FROM pslist(pid=getpid())"
[...]
Job 1, './velociraptor-v0.6.8-rc1-linux…' terminated by signal SIGKILL
```

**Comment by scudette** [comment]
Thanks for reporting this bug...

It should be fixed by #2514
