### ISSUE TITLE
Something completely different - Do you know that your VQL acronym had a synonym in Denodo products ?

### ISSUE THREAD

**Issue by gamgm** [Velocidex/velociraptor#2530]
Hello everyone here !

As a Data Scientist and a Denodo Virtual Data Layer project manager and developer for a European government organization, I had to point out to you the double meaning of VQL :
- You use it as Velociraptor's query language.
- We use it as a virtual query language.
Here I understand that you did not want to change, as well as Denodo.

If you couldn't already, then I advise you to create disambiguation pages, in order to remove the doubt, since you seem to be working on subjects that may be related to both communities.

Good luck for your very interesting project.

Kind regards,
Guinux

**Comment by scudette** [comment]
Haha thanks for pointing it out - there are so many other things that use VQL as an acronym too. People kind of expect acronyms to not be unique

I didn't even know that there are websites to keep track of all the acronyms:

https://www.acronymfinder.com/VQL.html
https://www.allacronyms.com/VQL

A quick google shows even more:

https://developer.veevavault.com/vql/#introduction-to-vault-queries

Maybe if we ever get a Wikipedia article we can disambiguate there?
