### ISSUE TITLE
Missing File Search/Filter in VFS browsing

### ISSUE THREAD

**Issue by mgdevsoft** [Velocidex/velociraptor#2541]
Hi,
In velociraptor version 0.6.8.rc1, The new VFS system with the paging is missing the Filter/Search Option under the Name column in order to get specific file.
In addition, the folders and files are no longer sorted by ABC.

Kind regards,
Gal Miller

**Comment by scudette** [comment]
The new UI table is the same as any other table. This means that you can filter it the same as other table by clicking the filter table button. You can filter on any field now, including the name field.
