### ISSUE TITLE
Cognito authenticator - User rejected by GUI [http: named cookie not present]

### ISSUE THREAD

**Issue by yarox24** [Velocidex/velociraptor#2544]
We upgraded our test Velociraptor instance first to 0.6.8 rc1 then to rc3. 

Upgrade to rc3 break Cognito authentication:

Cognito login screen works as usual but after successful authentication following blank HTML webpage is visible (Source):
![image](https://user-images.githubusercontent.com/18016218/225266532-6ed980e0-2227-4855-9885-4d0db40b1c6f.png)

In this screenshot I also see that src for ICO, JS and CSS starts with double underscore, I doubt if it will work properly.

and in logs/* following line is present:
`[INFO] 2023-03-15T09:00:36Z User rejected by GUI {"err":"http: named cookie not present","method":"GET","principal":"","remote":"<cut>:9908","url":"/app/index.html"}`

Following authenticator is used in server config:
![image](https://user-images.githubusercontent.com/18016218/225269195-9364f5bb-0d91-450c-b364-32249841802e.png)

Maybe it's related to some changes in Go itself?

go1.20.1 (released 2023-02-14) includes security fixes to the crypto/tls, mime/multipart, **net/http**, and path/filepath packages, as well as bug fixes to the compiler

**Comment by scudette** [comment]
Do you have the base path configured in your GUI section? If you are not using base path you should omit that altogether (so it's blank instead of / )

**Comment by yarox24** [comment]
This is the fragment from GUI section:
`public_url: https://<edited>.net:8443/`

I restored binary to version rc1 from rc3 and exactly the same config is working fine.

**Comment by scudette** [comment]
Can you please check if you have the GUI.base_path parameter set in your config at all.

There was a bug fix between rc1 and rc3 that it was ignored and now it is considered. If you are not using it then it should be removed completely

https://docs.velociraptor.app/docs/deployment/references/#Frontend.base_path

And

https://docs.velociraptor.app/docs/deployment/references/#GUI.base_path

**Comment by yarox24** [comment]
```
cat server.config.yaml | grep -i base_path
=> Empty result
```

**Comment by scudette** [comment]
Thanks for testing this. There was a bug with the base path processing. I just submitted a fix in 
#2545 and once the CI pipeline finished building that commit it would be awesome if you could test it again.

https://github.com/Velocidex/velociraptor/actions/runs/4426743706

Thanks again for your help!

**Comment by yarox24** [comment]
So I replaced with the new version from runs and now there is another error:

After successful logon with AWS Cognito it's showing screen:
![image](https://user-images.githubusercontent.com/18016218/225340536-d766471b-89db-4022-b570-1dbe93d651a0.png)

but after clicking on Sign In with Generic OIDC Connector, it's redirecting to the same screen (every time). So no ability to login.

Extra error in console:
`{"err":"http: named cookie not present","level":"info","method":"GET","msg":"User rejected by GUI","principal":"","remote":"<edited>:12808","time":"2023-03-15T14:30:44Z","url":"/app/index.html"}`

Browser inspector:
![image](https://user-images.githubusercontent.com/18016218/225341905-909f0916-8ca9-43a0-aedf-beb6f0e91258.png)

Also as I had valid session from previous rc1 installation, for this existing session (applied to rc3 from runs build) it was working properly.

**Comment by scudette** [comment]
Thanks for testing. This looks like an issue introduced when I tried to fix the base path support. Let me look into it, I will update this issue shortly

Thanks again :-)
