### ISSUE TITLE
PE fixup capability

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#2551]
I often extract PE files from memory and it would be helpful to enable a PE fixup capability

RVA is the in memory address of the PE file and thus extraceted PEs have messed up offsets when parse_pe() tries to analyse them. Now this is expected but causes manual workflow requriements if we want to run additoinal steps on the extracted data. We should have an option to do the offset replacements:  e.g run parse_pe() normally, then Drop the file offsets and replace with the correct RVAs. This could be simply a switch in parse_pe or a seperate function and be best effort only.

An example from pe-sieve (the best example Ive seen):
https://github.com/hasherezade/pe-sieve/blob/8a48c9c52d16b86ed6915df8f49612afc5a43705/postprocessors/pe_reconstructor.cpp

**Comment by scudette** [comment]
Should be fixed in 0.6.8 which added a pedump capability
