### ISSUE TITLE
Indicators on client status use colour which affects colourblind persons

### ISSUE THREAD

**Issue by Firstyear** [Velocidex/velociraptor#2559]
Some ui elements such as the client list use colour for their status. As someone who is colour blind, I can't distinguish these (especially the yellow and green)

What would be good is icons (✅ ⚠️ 🚨) which use colour *and* shape to help people distinguish the difference. 

<img width="442" alt="Screenshot 2023-03-20 at 15 54 33" src="https://user-images.githubusercontent.com/271005/226258565-f7712677-ab6c-4da9-8b51-c7d772d43ba2.png">

**Comment by scudette** [comment]
#2639 added a shape based icons (circle for online, fading circle for recently only and triangle for offline).
