### ISSUE TITLE
Velociraptor agent does not show CommandLine from pslist() on W7

### ISSUE THREAD

**Issue by sjosz** [Velocidex/velociraptor#256]
Hi,

When I was doing an investigation using Velociraptor, I observed that the CommandLine value does not return when running the query pslist() on a Windows 7 system (tested on both x64 and x86):

![RImVNcyi2Z](https://user-images.githubusercontent.com/11965973/75264946-2ca8b480-5816-11ea-9daa-25effb2b1ae3.png)

Is there a way to fix this perhaps?

It's one of these small things :)

**Comment by scudette** [comment]
We used to do the pslist using WMI (e.g. "SELECT * FROM Win32_Process") but now we use some undocumented APIs because they are much faster than WMI. Maybe these APIs dont really work well on Window 7?

It is always possible to fallback to the WMI call with a different artifact.

**Comment by sjosz** [comment]
The following command works for me on Windows 7:

`velociraptor.exe -v query "SELECT * FROM wmi(query='SELECT * from Win32_Process', namespace='ROOT\\CIMV2')"`
