### ISSUE TITLE
Better indication of extra actions

### ISSUE THREAD

**Issue by Firstyear** [Velocidex/velociraptor#2560]
During your EO presentation you demonstrated using the file hash for virus total lookups. This has a custom right click menu, however few other elements have this.

This means that new users can't find or discover this behaviour and feature since they are already taught by other areas that there is no right click context, so they don't try it on things. And there is no visual difference on the hashes to expose this.

Having a different visual indicator on the hashes or an alternative way to trigger the menu would help users discover that this feature exists.

**Comment by scudette** [comment]
#2641 Added a context mouse shape to indicate a context menu is available.
