### ISSUE TITLE
Improve indication of settings behind username

### ISSUE THREAD

**Issue by Firstyear** [Velocidex/velociraptor#2562]
In your demos you showed how a user could access the settings via the username. There is no indication that this is a settings menu because the graphic shows a logout icon next to the username, which can indicate to the user that the logout is the action, and the username is for informational purposes.

It would be better to seperate this to show that there is a settings menu there to allow users to more easily find this.

**Comment by scudette** [comment]
Fixed by #2639 There is now a wrench button to indicate configuration
