### ISSUE TITLE
config repack --msi does not work with v0.6.8

### ISSUE THREAD

**Issue by stucki** [Velocidex/velociraptor#2572]
It looks like the `config repack` command does not work as documented in the v0.6.8 release notes:
https://docs.velociraptor.app/blog/2023/2023-02-13-release-notes-0.6.8/

```
velociraptor-v0.6.8-rc1-linux-amd64 config repack --msi velociraptor-v0.6.8-rc1-windows-amd64.msi client.config.yaml output.msi
```

- It seems like the parameter has changed from `--msi` to `--exe` in 5be0b681e3bacf12412a464d405d1093a6e61da5
- Even worse, the specified file is always searched in the filesystem root (prefixed with `/`) no matter what path I set for the input MSI file. Copying my `velociraptor-v0.6.8-windows-amd64.msi` to `/velociraptor-v0.6.8-windows-amd64.msi`, I am now able to repack the package.

**Comment by stucki** [comment]
Side note: what is the point of such a last-minute change in a production release?

**Comment by scudette** [comment]
Actually the flag was not used at all which is why it was removed to avoid confusion. You should supply the msi to the --exe flag.

**Comment by scudette** [comment]
As for the path it expects a full path to the msi file.

This happens because the repack functionality is now done in vql and vql does not deal in relative paths.

Maybe we should expand the relative path to an absolute path to avoid confusion.

**Comment by scudette** [comment]
This is documented here https://github.com/Velocidex/velociraptor/blob/master/docs/wix/README.md but maybe we should also update the release notes

**Comment by stucki** [comment]
Correct, that's where I found about the switch from `--msi` to `--exe`. However, it's probably the wrong place to document it because the Wix framework is not even involved here, right?

In any case, I would be happy if this is corrected in the release notes. Thank you!

**Comment by scudette** [comment]
I just uploaded 0.6.8-2 which brings back the --msi flag as a synonym for --exe
