### ISSUE TITLE
Sending EventLogs to splunk

### ISSUE THREAD

**Issue by ibyf0r3ns1cs** [Velocidex/velociraptor#2573]
I am attempting to establish a process that will allow me to upload Splunk the logs from Windows servers I pulled with Velociraptor. Despite searching for resources on how to do so, I have not found any comprehensive guides. However, the Client Monitoring page on https://docs.velociraptor.app/docs/client_monitoring/ suggests that this functionality is feasible.

"Collecting real time data such as ETW logs, process executions logs, Sysmon logs etc. These are typically collected by Velociraptor and sent directory to an external system (e.g. Elastic or Splunk). Typically the VQL for such queries contains minimal filtering and simply forwards all events to the server."

Help please.

**Comment by scudette** [comment]
See this and the corresponding artifact

https://github.com/Velocidex/velociraptor-docs/pull/524/files

I dont personally use splunk but you need to pre-define your schema in splunk so it not a simple matter of enabling the artifact like with Elastic.
