### ISSUE TITLE
Feature request: Comments field next to Available Downloads and Hunts

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#258]
It would be great to be able to allow a user to add comments next to available downloads. This way if there's a list of downloads available because the reviews have been conducted whilst the hunt is available then the analyst can easily keep track of whether there are findings or if the task can be marked as completed.

Similarly, having the ability to add a column for comments in the hunt manager would allow analysts to group hunts together, as well as mark as hunt task as completed.

**Comment by scudette** [comment]
I just committed to head the notebook feature. This is not specific to hunts - it is just a way of documenting an entire analysis (and keep track across many hunts). It is similar to Jupyter notebooks but work out of the box in Velociraptor using VQL.

Although it is not exactly what you asked for, I think it solves the general need to keep track of analysis within the application itself.

Can you try it and see if it solves your need? Thanks!

**Comment by scudette** [comment]
We prefer to use notebooks for this instead of making the hunts UI more complex.
