### ISSUE TITLE
Grok doesn't handle named group coalescing properly

### ISSUE THREAD

**Issue by Gr1mR3aver** [Velocidex/velociraptor#2591]
If multiple fields in a grok pattern have the same name, but are mutually exclusive (i.e. only one pattern will ever match), then the grok parser appears to return the value of the last group evaluated with that name, whereas it should coalesce and return the matching group.  The observed behavior is different from online grok evaluators and my own testing/experience with non-velo implementations.  Have seen this with even simple examples like a syslog parsing line: 

(?:%{SYSLOGTIMESTAMP:timestamp}|%{TIMESTAMP_ISO8601:timestamp}) +%{GREEDYDATA:message}

with log message:

Mar 27 10:49:14 Ubuntu-22 gdm-autologin]: gkr-pam: no password is available for user

returns:

{"timestamp":null,"message":"Ubuntu-22 gdm-autologin]: gkr-pam: no password is available for user"}

but should return:

{"timestamp":"Mar 27 10:49:14","message":"Ubuntu-22 gdm-autologin]: gkr-pam: no password is available for user"}

**Comment by scudette** [comment]
Thanks for testing this. This ended up being a bug in the grok library which we were using. I forked it for now (upstream does not seem to be maintained)

If you can further test the grok implementation with more test cases we will be able to get better confidence that it's working as it should.
