### ISSUE TITLE
Missing settings in automatically generated configuration

### ISSUE THREAD

**Issue by 0xThiebaut** [Velocidex/velociraptor#261]
Hi,

As I am looking to perform a mass-deployment of Velociraptor 0.3.9 servers, I have build a Dockerfile which among others executes the following command at run-time should the configuration file not be mapped by a volume:

```bash
velociraptor config generate > /etc/velociraptor/config.yml
```

Sadly, running Velociraptor using the generated file results in the following error:

>  ```
> [INFO] 2020-02-28T10:32:38Z Starting Frontend. {"build_time":"2020-02-10T22:30:07+10:00","commit":"0022e2c","version":"0.3.9"}
> [INFO] 2020-02-28T10:32:38Z Loaded 149 built in artifacts 
> [INFO] 2020-02-28T10:32:38Z Increased open file limit to 999999 
> [INFO] 2020-02-28T10:32:38Z Starting the hunt manager service. 
> [INFO] 2020-02-28T10:32:38Z Starting Hunt Dispatcher Service. 
> [INFO] 2020-02-28T10:32:38Z Starting Stats Collector Service. 
> [INFO] 2020-02-28T10:32:38Z Starting Server Monitoring Service 
> [INFO] 2020-02-28T10:32:38Z Starting Server Artifact Runner Service 
> [INFO] 2020-02-28T10:32:38Z Collecting Server Event Artifact: Server.Monitor.Health/Prometheus 
> [INFO] 2020-02-28T10:32:38Z Starting Client Monitoring Service 
> [INFO] 2020-02-28T10:32:38Z Collecting Client Monitoring Artifact: Generic.Client.Stats 
> [ERROR] 2020-02-28T10:32:38Z Failed starting services: Frontend is missing a public_path setting. This is required to serve third party VQL plugins. 
> velociraptor: error: startFrontend: Frontend is missing a public_path setting. This is required to serve third party VQL plugins.
> ```

By performing a diff between the above generated file and one generated interactively, we notice that some settings are not defined as one would expect.

> ```
> diff --git a/unattended.yml b/interactive.yml
> index 8e9c97e..d5edde1 100644
> --- a/unattended.yml
> +++ b/interactive.yml
> [...]
> @@ -111,93 +111,96 @@ GUI:
> [...]
>      -----END RSA PRIVATE KEY-----
> +  public_path: /tmp/public
>    max_upload_size: 10485760
>    default_client_monitoring_artifacts:
>    - Generic.Client.Stats
>  Datastore:
>    implementation: FileBaseDataStore
> -  location: /tmp/velociraptor
> -  filestore_directory: /tmp/velociraptor
> +  location: /tmp
> +  filestore_directory: /tmp
>  Writeback: {}
>  Mail: {}
> -Logging: {}
> +Logging:
> +  output_directory: /tmp
> +  separate_logs_per_component: true
>  Monitoring:
>    bind_address: 127.0.0.1
>    bind_port: 8003
> ```

More specifically, in an unattended generation, the `public_path` variable is entirely missing while the `Logging` variable is furthermore empty.

Am I missing some required flags?
Thanks in advance!

*PS: I did not manage to identify documentation related to the automated configuration generation, am I missing it?*

**Comment by scudette** [comment]
The automatic generation is not intended to produce a working config without editing. We probably should fill out at least the required settings though.

You are supposed to patch the generated config with your settings using the --patch flag. Just provide a json object with your settings to have it override the generated config.

**Comment by 0xThiebaut** [comment]
Hi @scudette 

Thanks for the pointer regarding `--patch`!

On a side remark, do note that the [current FAQ](https://github.com/Velocidex/velociraptor/wiki/FAQ)'s example will hence probably break too.

> * How do I prepare Velociraptor for deployment?
> 
>   To create a deployment you need to make a deployment configuration:
> 
>   ```
>   $ velociraptor config generate > server.config.yaml
>   $ velociraptor --config server.config.yaml config client > client.config.yaml
>   ```
>   
>   You now can simply install the binary using the client configuration:
>   ```
>   $ velociraptor.exe --config client.config.yaml service install
>   ```
> 
>   You can repack the binary with the config so it is embedded in the binary. This allows you to ship a single binary and have it automatically install itself.
>   ```
>   $ velociraptor config repack --exe velociraptor.exe client.config.yaml my_velociraptor.exe
>   $ my_velociraptor.exe service install
>   ```
>

**Comment by scudette** [comment]
Ah i completely forgot about that FAQ page on the wiki - it is way outdated. I removed it altogether since it is basically the same as the README file. 

Im still not sure what to use the wiki for - it seems to be very primitive to be really useful.
