### ISSUE TITLE
Request to build an IBM Power/AIX architecture binary

### ISSUE THREAD

**Issue by alexistrate87** [Velocidex/velociraptor#2630]
Hi Velociraptor Team,

Could you please help build a binary for AIX architecture too. 

Looking forward for your response.

Thanks a lot !

**Comment by scudette** [comment]
We did try it once but it didnt really work - i think the binary was built but was not able to start without crashing.

I did a quick survey of how prevalent aix was and it was exceedingly rare so we didnt think it was useful.

**Comment by scudette** [comment]
It is also impossible for us to test it because we dont have access to this os and it does not seem to be freely available. Is there a VM or a free install media we can test with?

**Comment by alexistrate87** [comment]
Can you provide some general instructions on how to compile it on IBM Power (AIX) ?

**Comment by scudette** [comment]
Sure - there is still a build target here https://github.com/Velocidex/velociraptor/blob/defdd49452a70794b7a58f481f02bcc10695cf3d/magefile.go#L270 so you should be able to get a binary with ` go run make.go -v aix`

**Comment by scudette** [comment]
If stuff breaks just disable plugins/files that dont compile right by adding `// +build: !aix` like here

https://github.com/Velocidex/velociraptor/blob/defdd49452a70794b7a58f481f02bcc10695cf3d/bin/debian.go#L1

Would be interesting to see if you can get it to work.

**Comment by scudette** [comment]
Closing as not feasible.
