### ISSUE TITLE
Feature Request: Alternative Artifact import method when http_client() plugin is disabled on the Server

### ISSUE THREAD

**Issue by SBattaglia-R7** [Velocidex/velociraptor#2647]
This is mostly relevant to CloudVelo -- When the http_client() plugin is excluded from the server allowlist, we cannot import artifacts from the Exchange.  The IR team told me that this is a regular part of their setup procedure.  Assuming we include the Exchange automatically in hosted instances, it would be difficult to update Artifacts later.

Maybe a plugin that only supports fetching data from the official Exchange?

**Comment by scudette** [comment]
Maybe an allow list of domains ?

**Comment by SBattaglia-R7** [comment]
I'd be happy with that, since Matt's DetectRaptor toolset was also specifically mentioned as a regular inclusion.  On the other hand, maybe we can fold that repo into the Exchange officially, so we only have a single source that needs to be reviewed

**Comment by scudette** [comment]
It is actually possible to manually upload the exchange bundles in the GUI. In 0.6.9 the prefix can be set as well as a filter to only import some of the bundle. There is a link to the exchange bundles in the exchange page https://docs.velociraptor.app/exchange/
