### ISSUE TITLE
Windows.System.HostsFile regex is not matching

### ISSUE THREAD

**Issue by liteman** [Velocidex/velociraptor#2669]
https://github.com/Velocidex/velociraptor/blob/a785b16c6213b791c2c78cf34f913c4e1c94023e/artifacts/definitions/Windows/System/HostsFile.yaml#L40-L42

This regex is not matching on example line
```
1.1.1.1	mytestdomain-velo.com # Hi
```

Recommended change 
```
^\s*(?P<Resolution>[^\\s]+)\s+(?P<Hostname>[^\\#]+)\s*#*\s*(?P<Comment>.*)$
```

![image](https://user-images.githubusercontent.com/6087529/236964804-dd0a5718-8023-4af9-8eb4-d95be872bd0f.png)
![image](https://user-images.githubusercontent.com/6087529/236964817-6727cfc4-58e8-471c-9d1b-e02cd5e11677.png)

**Comment by mgreen27** [comment]
@liteman VQL requires escaping the backslash so in your original test you need to replace all the \\ with \.

**Comment by liteman** [comment]
I see -- thank you for the quick response. 

I was troubleshooting an issue where the Hostname field was not returned (I thought).  Checking again -- this is a problem with forwarded events/logstash.  The artifact results on the server look correct.

**Comment by mgreen27** [comment]
No worries - its not to say its not broken in other ways! 
If you find an exampe reopen/post here and we can modify the regex.

**Comment by liteman** [comment]
The issue was the Elastic.Flow.Upload artifact overriding the Hostname field.

That was an easier fix with a custom server artifact to rename that field.


On May 9, 2023, at 18:18, Matthew Green ***@***.***> wrote:

﻿

No worries - its not to say its not broken in other ways!
If you find an exampe reopen/post here and we can modify the regex.

**Comment by scudette** [comment]
This artifact is tested here https://github.com/Velocidex/velociraptor/blob/a785b16c6213b791c2c78cf34f913c4e1c94023e/artifacts/testdata/server/testcases/hostsfile.in.yaml#L6 

If you find a host definition in the wild that does not match the built in regex, please include it in the test file so we have coverage.
