### ISSUE TITLE
Windows.Applications.FTKImager - A Forbidden Error 

### ISSUE THREAD

**Issue by AvivkCYE** [Velocidex/velociraptor#2670]
Hi, 

While attempting to capture the E01 image, I encountered an issue wherein I had to create a new artifact. I followed the relevant guide page to generate the artifact; however, I received a forbidden (403) error upon running the newly created artifact.

How can I resolve this issue and make the artifact work as intended?
![image_2023-05-10_114601003](https://github.com/Velocidex/velociraptor/assets/127300315/3f5093bb-61ae-4cb6-b186-295ad695c224)

**Comment by AvivkCYE** [comment]
yes, I know the FTK Imager for a while, I wanted to use the Velociraptor query to activate it on a remoted system, can I get this done in a different query?

**Comment by scudette** [comment]
You need to manually upload the zip file to the tools setup menu.

**Comment by AvivkCYE** [comment]
Great, thank you.
Where can I find a guide to this process?

**Comment by scudette** [comment]
https://docs.velociraptor.app/docs/extending_vql/#using-external-tools

**Comment by AvivkCYE** [comment]
Thanks!
