### ISSUE TITLE
Windows.Detection.Usn does not work correctly

### ISSUE THREAD

**Issue by ezpz4n6** [Velocidex/velociraptor#2671]
I try to test client monitoring using Windows.Detection.Usn

first, run Windows.Detection.Usn artifact with parameter `Device=C:\\` , `PathRegex=velo.txt*` , then create C:\velo.txta, C:\velo.txtb, C:\velo.txtc at client

![image](https://github.com/Velocidex/velociraptor/assets/48788455/b6afd6c3-0020-4a5c-904f-ba47d4310e2d)

no results at `Available` tab.

I try debug verbose at local client, but same issue

![image](https://github.com/Velocidex/velociraptor/assets/48788455/74c90bfc-9cf8-4596-b81e-54b4c78bb63b)

![image](https://github.com/Velocidex/velociraptor/assets/48788455/3c8eb63d-d2ec-49fb-88c1-49545a59a92e)

**Comment by scudette** [comment]
Fixed by https://github.com/Velocidex/go-ntfs/commit/d367f954db15f31ca191d628bc582684709e5654
