### ISSUE TITLE
Skipping certificate verifications in http_client not working in 0.6.9-rc1

### ISSUE THREAD

**Issue by BadBloopZ** [Velocidex/velociraptor#2688]
### Summary ### 
In 0.6.9-rc1 the parameter to skip certificate verifications in the http_client plugin changed from disable_ssl_security to skip_verify. However, neither of these parameters achieve the desired effect. The only option for TLS connections using untrusted certificates is to add the root_ca parameter.

### Steps to reproduce ###

1. Deploy a webserver with an untrusted/self-signed certificate.
2. In a notebook on the Velo 0.6.9-rc1 server: Create a simple request to this webserver via http_client plugin and set the skip_verify OR the disable_ssl_security parameter to true.
3. You'll get a x509 error like ``http_client: DisableSSLSecurity is deprecated, please use SkipVerify instead
Fetching <url>
http_client: Error Get "<url>": x509: certificate signed by unknown authority while fetching <url>`` OR when using skip_verify: ``Fetching <url>
http_client: Error Get "<url>": x509: certificate signed by unknown authority while fetching <url>``
4. Try again on a Velo 0.6.8 server and it will work

**Comment by scudette** [comment]
Fixed by #2690
