### ISSUE TITLE
0.4.0 Registry full path output URL encoding

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#270]
I  noticed the FullPath of registry keys now outputs in URL encoding.

Is this expected? This breaks some of my content but thought I would ask before I fix.
![image](https://user-images.githubusercontent.com/13081800/76267230-f6c9ee00-6261-11ea-9bb7-8ea289b5169c.png)

**Comment by scudette** [comment]
This is the correct output for raw registry.  The idea is that you should
be able to take this full path and pass it exactly to any other plugin and
it will be able to open the key, without you needing to do anything special
to encode it. Therefore it needs to encode the name of the reg file to
parse, the accessor to open it with and the key to extract from it in the
full path itself.

If you just want to display the key path you can parse it and extract the
fragment part.

Thanks
Mike
