### ISSUE TITLE
View Artifacts -->  Under notebook( no summary of logs)

### ISSUE THREAD

**Issue by Yashil06** [Velocidex/velociraptor#2705]
Can someone assist with all the artifacts being run that produce no output whatsoever, I have tried on 3 different artifacts and this shows the same result. I have attached some screenshots of each of the artifacts.

![{1ED9151C-76B4-4296-A9E0-35922CB6C5E1}](https://github.com/Velocidex/velociraptor/assets/77737581/82710fc1-f7d8-498c-9b4f-9e05c939ab33)
![{5F9B31AE-C865-4D5B-9879-A6294FFD75E2}](https://github.com/Velocidex/velociraptor/assets/77737581/f32f7d4c-bd74-4108-91d1-fee201021b93)
![{27EB0C76-A5A2-429D-B3B2-8030ED371B88}](https://github.com/Velocidex/velociraptor/assets/77737581/ccd67239-c017-43e2-9ef6-76d5cf2c4b40)

![{6B663086-B60C-4595-BC67-EA4F8BA8DDFE}](https://github.com/V
![{99AD3FF5-A44C-405D-87F0-DD82F57692C2}](https://github.com/Velocidex/velociraptor/assets/77737581/072daae3-3ccc-4d04-b18f-bbb3f8a532d3)
![{7135F888-E7A3-4DF3-B58A-3EBDD5E8DE91}](https://github.com/Velocidex/velociraptor/assets/77737581/034bd8fc-33a1-41a5-816c-d79ad06e0142)
![{E5F1C189-BA5C-4CE7-90C0-4D9232AEDB02}](https://github.com/Velocidex/velociraptor/assets/77737581/69372099-4b59-49cb-b237-3bdedc2aee26)

elocidex/velociraptor/assets/77737581/d07ab898-6007-42f0-a879-f5478a11edbb)

**Comment by scudette** [comment]
Be sure to recalculate the notebook when new results come in.

Also you can see the results from individual collections and look at the kids to make sure it's working

**Comment by scudette** [comment]
In your screenshot of the cmdshell artifact it doesn't look like you specified any command to actually run. You need to configure that artifact to run something.
