### ISSUE TITLE
Overuse of red color when no errors occur

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#2721]
We currently color the console output in inconsistent ways - sometimes red means an error other times it just looks nice:

`"<red>Stopping</> watch for %v for %v (%v)"`
`"Downloading tool <green>%v</> FROM <red>%v</>"`

Red needs to be used consistently to indicate an error condition.

Similarly in the notebook output the query log shows up in red when it does not always indicate an error

This needs to be update to either only show logs at error level in red (or at all) in the query summary.

**Comment by Bloggzy** [comment]
I concur, the overuse of red can be misleading. 
e.g. Red = bad, I see red text, what went wrong? Oh no, everything is fine, false alarm, carry on...
