### ISSUE TITLE
REQUEST: Offline Collector mass ingestion

### ISSUE THREAD

**Issue by nsanity2097** [Velocidex/velociraptor#2726]
Now that VR can configure an offline collector to upload to an S3 bucket, a potential usecase for Incident Recovery post environment wide impact (e.g ransomware) is to be able to collect client machine data prior to reimaging, then mass upload to an S3 Bucket or SFTP site - then have a Hunt collect and ingest these collections automatically.

Ideally making this a "watch folder" style hunt would follow the spirit of VR by continually pulling in client data as it becomes available for the duration of the hunt. 
However this would require the ability for VR to catalogue what it has already ingested (or delete the source file/create a hash or something).

**Comment by bmcder02** [comment]
Hi @nsanity2097 , sorry for the delay getting back to you. 
I've got a pull request in for two new artifacts to be added to the artifact exchange. See this pull request, there's two artifacts, one for local and one for s3. 
Please note that you will need to wait until v7.0.4. We've got an update coming to the import_collection plugin which these two artifacts require. See the following commit to allow the importing of hunt data. (#3005)
