### ISSUE TITLE
Collector - fallback option when upload fails

### ISSUE THREAD

**Issue by Bloggzy** [Velocidex/velociraptor#2729]
Love the collector and it works really well, we did come across one issue, and have a suggestion to deal with it.

Issue: We sent a configured collector to an endpoint, all our tests worked fine, but when it got to the actual target endpoint, it couldn't upload to our prepared Azure container. Not the fault of the collector, and it transpired that the host was isolated from the network. Our failure for not considering that ahead of time, but not ideal either way.

Suggestion: an option to have the collector fallback to creating a local zip collection in the event of the collector's upload test failing.

Reason: it took quite a bit of effort to get the collector binary into the hands of the right people. Eventually we configured and sent a new collector for them to use (not tech savvy) that created the collection locally, but a lot of that could have been avoided if the collector had an option to fall back to a local collection if the upload test fails? What do you think?

**Comment by scudette** [comment]
Yes this is definitely a great suggestion ☺️

**Comment by Bloggzy** [comment]
Awesome, thanks!

**Comment by Bloggzy** [comment]
Awesome, thanks!

**Comment by scudette** [comment]
Fixed by #2834 which does not remove the collection at the end any more - it is now up to the user to remove the collection file once they are sure it was properly uploaded
