### ISSUE TITLE
elastic setup help

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#273]
I admit setting up kibana is new to me. I have used it & big fan. I installed elastic & kibana locally. Enabaled `Elastic.Flows.Upload ` as suggested in your blog. While defining index pattern, I get a message "artifact_*" doesn't match any indices . Do I need to install & configure any other component such as logstash, filebeat etc ? Thanks

**Comment by scudette** [comment]
You don't need to configure logstash just make sure your elastic bulk upload api is exposed and you can push data to it. It might be worth looking at the logs while you are uploading to elastic to make sure there are no connectivity issues.

**Comment by siftuser** [comment]
Thank you! what you mean by `elastic bulk upload` api ? is that different from `Elastic.Flows.Upload` ? appreciate clarification. Could you share logfile to look at for clues ? Regarding connectivity, it's installed locally as on same VR server. Thanks

**Comment by scudette** [comment]
You need to make sure you can talk with the API properly. The Elastic.Flows.Upload artifact will try to talk to the Elastic API to do a bulk upload. 

You can read more about the elastic APIs https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html for example to list all the indexes.

Basically make sure you can copy the curl command and get results from elastic before you try to debug Velociraptor.

**Comment by siftuser** [comment]
Thanks @scudette! This is the list of indices I see 

```
green open .monitoring-es-7-2020
green open .kibana_task_manager_1
green open .apm-agent-configuration
green open .kibana_1
green open .monitoring-kibana-7-2020
```

**Comment by scudette** [comment]
Ok are you getting any errors from collecting the elastic artifacts locally?

```
velociraptor -v artifacts collect Elastic.Flows.Upload 
```
Then try to collect an artifact from the client and see if there are any errors

**Comment by siftuser** [comment]
This is the output from the suggested command:

```
[INFO] 2020-03-15T13:29:11Z Loaded 153 built in artifacts
[INFO] 2020-03-15T13:29:11Z Loaded artifact_definitions/Custom/Linux/Ssh/PrivateKeys.yaml
[][][] 
```
And no change in the indices on kibana console

**Comment by scudette** [comment]
Are you able to see any events generated when you e.g. click the interrogate button on a client?

**Comment by siftuser** [comment]
yes. I can see the results in the gui from artifacts as well as client client events

**Comment by siftuser** [comment]
Hi @scudette any help ? Thanks!

**Comment by scudette** [comment]
Hi @siftuser - just a few pointers

I normally use Security Onion in a VM so I normally tunnel port 9200 on localhost to the SO vm. Make sure that you have connectivity and elastic is actually reachable from the Velociraptor server. 

![image](https://user-images.githubusercontent.com/3856546/77519944-20bf1980-6ecc-11ea-93a1-b0846e515113.png)

After this works make sure the artifact works 
https://github.com/Velocidex/velociraptor/blame/master/artifacts/definitions/Elastic/Flows/Upload.yaml

take a look at that artifact - it was updated recently maybe copy it into a custom artifact if you have an older Velociraptor version installed (or just grab the latest from the CI pipeline).

Add it to the server monitoring GUI
![image](https://user-images.githubusercontent.com/3856546/77520081-5fed6a80-6ecc-11ea-9f11-831d35276a4c.png)

You can also collect this artifact locally on the command line. If you then do anything (like refresh a VFS directory) it should emit the event

![image](https://user-images.githubusercontent.com/3856546/77520388-e144fd00-6ecc-11ea-93cd-88601d1496f6.png)

after a short time you should be able to see the event being pushed to the elastic server
![image](https://user-images.githubusercontent.com/3856546/77520267-ab077d80-6ecc-11ea-92e3-d51ec4a5b558.png)

**Comment by siftuser** [comment]
Thanks @scudette! Apologize in advance for ignorance

FYI - I'm running velo server 0.4

My elastic  & velo server are running on same box. so reachable on port 9200 & matches the output you shared.

Step2. I couldn't find option to modify or add new/custom `Elastic.Flows.Upload` server monitoring artifact

Step3: Are you suggesting to run the `velociraptor artifacts collect Elastic.Flows.Upload` command on the velo raptor correct ? If so, I ran it - but dont see any event upon collecting test artifacts on a connected client using the web ui

**Comment by scudette** [comment]
![image](https://user-images.githubusercontent.com/3856546/77599284-ef882d00-6f4f-11ea-8c10-b24c93f6f9cd.png)

Obviously if you customize it then you need to run the customized version (depending on the name you call it).

You can also just run the latest CI build.

**Comment by siftuser** [comment]
Thank you @scudette ! This worked like a charm :)

PS: Is there a deb file in CI build ? I do see exe though :) Thanks!

**Comment by scudette** [comment]
We only distribute exe files but you can make your own deb file 
https://www.velocidex.com/docs/getting-started/cloud/#deploying-to-the-cloud

**Comment by siftuser** [comment]
Thank you!

**Comment by siftuser** [comment]
appreciate any help to fix the error while creating deb server using CI buld exe : `Binary does not appear to be an ELF binary. Please specify the linux binary using the --binary flag.`

**Comment by scudette** [comment]
If you are building the Deb on Windows you will need to provide the Linux binary with the --binary flag.

**Comment by siftuser** [comment]
Thank you @scudette 

For newbie like me, the steps to generate deb from ci version exe are

- download `velociraptor-linux.elf` as well, along with exe file
- command to generate deb from  `velociraptor --config server.config.yaml debian server --binary=velociraptor-linux.elf`
