### ISSUE TITLE
VFS viewer not updating with scan

### ISSUE THREAD

**Issue by gammore** [Velocidex/velociraptor#2741]
Hi! 

I'm seeing a weird issue since updating to 0.6.8 from 0.6.4, I hope you can help me figure this out.

On 0.6.4 i was able to go to the VFS screen and navigate on the client's filesystem, see the files, etc.  Last week we updated the client and the server to 0.6.8 and recreated the server's certificate (the one in `https://URL/certificate.pem`). The new version works great but the VFS viewer stopped working. 

Now, when i go to a client `view clients -> click client id -> navigate to VFS on the left menu` the view is empty:
![velociraptor1](https://github.com/Velocidex/velociraptor/assets/10826865/117800ff-9523-4dd4-8db8-fd25be29d80d)

If i click on any of the two buttons on the top right to refresh the filesystem, they start collecting and keep spinning indefinetly. If i check the Collected artifacts screen, I can see that the operation succeeded, but the VFS view never updates:
![Screenshot_20230608_170757](https://github.com/Velocidex/velociraptor/assets/10826865/8e7081c2-80f8-43c6-b4f9-05c4d88d1708)

Do you know what might be causing this issue? If you need me to make any test let me know.

Thank you!

**Comment by scudette** [comment]
Are the clients also running at the same version as the server?

**Comment by gammore** [comment]
Hi!

Just tested now, deleted the old writeback file and tested again, same result. With this VM i've been testing how the new version operates with the clients on 0.6.4 (to see how urgently we need to update them), maybe there are some files left behind?  All tests described on this issue have been tested with client 0.6.8.
 
In this screenshot you can see the Collected artifacts screen, almost empty:
![Screenshot_20230608_172837](https://github.com/Velocidex/velociraptor/assets/10826865/f3b1dc82-ec10-476c-b432-ad39fb7cb767)
 

The client is running version 0.6.8:
```
PS C:\Users\Test\Desktop\velociraptor> .\velociraptor-0.6.8.exe --config .\test-client.config.yaml client -v
[INFO] 2023-06-08T17:15:47+02:00  _    __     __           _                  __
[INFO] 2023-06-08T17:15:47+02:00 | |  / /__  / /___  _____(_)________ _____  / /_____  _____
[INFO] 2023-06-08T17:15:47+02:00 | | / / _ \/ / __ \/ ___/ / ___/ __ `/ __ \/ __/ __ \/ ___/
[INFO] 2023-06-08T17:15:47+02:00 | |/ /  __/ / /_/ / /__/ / /  / /_/ / /_/ / /_/ /_/ / /
[INFO] 2023-06-08T17:15:47+02:00 |___/\___/_/\____/\___/_/_/   \__,_/ .___/\__/\____/_/
[INFO] 2023-06-08T17:15:47+02:00                                   /_/
[INFO] 2023-06-08T17:15:47+02:00 Digging deeper!                  https://www.velocidex.com
[INFO] 2023-06-08T17:15:47+02:00 This is Velociraptor 0.6.8-2 built on 2023-03-27T02:34:10Z (02edb7d9)
[INFO] 2023-06-08T17:15:47+02:00 Loading config from file .\test-client.config.yaml
[INFO] 2023-06-08T17:15:47+02:00 Loading writeback from C:\velcoiraptor\velociraptor.writeback.yaml
(after this, it connects to the server fine)
```

The server is also runnign version 0.6.8:
```
{
"name":"velociraptor"
"version":"0.6.8-2"
"commit":"02edb7d"
"build_time":"2023-03-27T02:28:58Z"
"ci_build_url":"https://github.com/Velocidex/velociraptor/actions/runs/4528050753"
"compiler":"go1.20.2"
}
```


> Do you still see the issue with a completely new client id? Move the writeback file out of the way temporarily and restart the client to get a new client id. Maybe it is a compatibility issue with the older data files. 0.6.8 got a new faster VFS implementation (which is faster again in 0.6.9)
That might have something to do. This clients were on versions 0.6.4 and we did a big step jumping to 0.6.8. Maybe there has to be some cleaning somewhere.

I appreciate the help, thanks!

**Comment by gammore** [comment]
Hi!

Well, I've opened the VM again to test what you asked me and it worked. I don't know why or how.

I've tested again to remove the client, remove the writeback file and test again and it works... The only different thing I did was to try and connect with a different browser than firefox (edge), but  I then returned to firefox to test it and it still works.

Do you think this could be related to the browser? It seems very strange.

Thanks for the help. Do you mind if we keep this issue open for a few days?

**Comment by scudette** [comment]
Sure - I think there was some weirdness around the GUI at some stage where it did not pick up the new information automatically when the collection was done. If the user closed and opened the folder a few times it initiated a refresh request to the server that would populate the tree view.

**Comment by gammore** [comment]
I was never able to reproduce this with a new installation so I must assume is something to do with our server. Having both side to side I can see some minor changes (like the theme, the old one doesn't update until you change it) and that may have something to do with it.

Opening a new browser solved the issue, but we're still in the dark as to why is happening this. I have a theory that i could not prove: It's related to the NFS server that holds de /velociraptor directory. The filesystem is not very fast and that could cause the issues, but i have no way of testing the same deployment without it.

For someone that arrives here seeking for answers and might be interested.

Thank you for your help @scudette , much appreciated.
