### ISSUE TITLE
Binary Parser: pass bitfield types to an Enumeration or Flag

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#2744]
When using the binary parser We may want to use bitfield to extract a value and pass to an Emumeration or a Flag value.

Currently we need to implement via a Value type and use VQL but it would be much nicer to specifically use a Bitfield type in an Enumeration or Flag.

For example: Here we pass an empty dict but if we allow use provided type options then we can pass a bitfield type directly to enumeration 
https://github.com/Velocidex/vtypes/blob/master/enumeration.go#L27

**Comment by scudette** [comment]
Fixed by: #3098
