### ISSUE TITLE
Start Velociraptor service after ClientSysVRPM install

### ISSUE THREAD

**Issue by bhutch** [Velocidex/velociraptor#2751]
Hello!

Is it possible to start the Velociraptor service after ClientSysVRPM install? It will start on (re)boot, but not after RPM installation.

Is this intentional? The service is started on all other platforms I've tested after package installation.

Adding ```/sbin/service velociraptor start``` to ```r.AddPostin``` in ```rpm.go``` should do the trick.

It's currently:
```
584         r.AddPostin("/sbin/chkconfig --add velociraptor")
```

Thanks!

**Comment by scudette** [comment]
Sure. If you can test this works and send a PR it would help :-)

**Comment by scudette** [comment]
This was actually a bug - the installer runs `service velociraptor condstart` but according to this

https://www.linuxquestions.org/questions/linux-general-1/condrestart-531071/

> The condrestart (conditional restart) option only starts the daemon if it is currently running.
> This option is useful for scripts, because it does not start the daemon if it is not running.

Since we just stopped the service it wont be started. Changing to just service start there should be what we want
