### ISSUE TITLE
Users assigned as Org Admin in the Root org are unable to see & manage all orgs created by other users

### ISSUE THREAD

**Issue by CyberKaizen** [Velocidex/velociraptor#2752]
Two users both with the same roles on root:
![image](https://github.com/Velocidex/velociraptor/assets/78124503/19da6a44-4b93-4cd8-9fe5-c25481286559)

User MT makes a new org:
![image](https://github.com/Velocidex/velociraptor/assets/78124503/f2b49eb7-1cfa-4908-9549-af4e60071bb3)

User Admin logs in and only sees the org root on the home page:
![image](https://github.com/Velocidex/velociraptor/assets/78124503/211ec60b-7086-4a12-8461-e96214fb4942)

User Admin runs the list org artifact to get all Orgs created on the server, and does not see User MT's new org that was created:
![image](https://github.com/Velocidex/velociraptor/assets/78124503/3accd7d1-1c57-4269-84b1-ff528ebe6ebc)

The only place where User Admin can see the new org created by User MT is on the Users page: 
![image](https://github.com/Velocidex/velociraptor/assets/78124503/a0d437b1-78cb-4627-8230-61f7af39ff22)

User Admin, tries to add itself to User MT's org in the hopes that they can see and manage this new org while User MT is out on vacation. Unfortunately, User Admin cannot add themselves to the org created by User MT, even when they have the same roles and permissions on the root org:
![image](https://github.com/Velocidex/velociraptor/assets/78124503/2a522531-f4e9-4b80-9d58-a369352661f2)

**Comment by scudette** [comment]
Thanks for reporting this. What was happening here is that listing the orgs in the system filters the list so only those orgs that the user has at least read permission on are shown. This is usually what we want for regular users as they need to see the orgs that they can realistically change to.

I added a PR to make an exception for the org admin so they can see all orgs including the ones that they have no permission in. This allows the org admin to add users to orgs even if they have no permissions on it.

An unwanted side effect of this is that the org switcher GUI now also shows all orgs for the org admin, but switching to the org does not actually work, as the user immediately is redirected to the root org. So the org switcher is showing an org that can not actually be used. However the org admin can always just add themselves to that org anyway so it is not a security boundary but it might be a bit surprising.

**Comment by CyberKaizen** [comment]
@scudette I went ahead and tested the new build (https://github.com/Velocidex/velociraptor/actions/runs/5270364236) by using Wes's container and then uploading the Velociraptor binary to it. The new binary with the commits seems to still have the same issues even though I can see in CI pipeline your changes passed.

**Comment by scudette** [comment]
In the new binary you should be able to see all orgs when logged in as an org admin.

Can you please verify that:

1. The user you are logged in as has org admin permission in the root org. I think being an org admin in a non root org is actually not meaningful at all (we need to hide that option to avoid confusion)

2. you can see all orgs in the org switcher, even though the logged in org admin has no read permissions in the org.

3. The org admin can see all orgs in the dashboard

4. The commit hash in the version block in the dashboard is after the commit that introduced the fix.

**Comment by CyberKaizen** [comment]
@scudette I got it to work! When I went to step 4. The commit hash was still the old one.

It was a user error. I forgot to change @weslambert's Dockerfile from https://github.com/weslambert/velociraptor-docker/blob/master/Dockerfile so that the latest releases git clone does not overwrite the dev build binary I copied in.



Dockerfile (changes made to Wes's original are bolded):
`FROM ubuntu:20.04
LABEL version="Velociraptor v0.6.9"
LABEL description="Velociraptor server in a Docker container"
LABEL maintainer="Wes Lambert, @therealwlambert"
COPY ./entrypoint .
RUN chmod +x entrypoint && \
    apt-get update && \
    apt-get install -y curl wget jq rsync && \
    # Create dirs for Velo binaries
    mkdir -p /opt/velociraptor && \
    for i in linux mac windows; do mkdir -p /opt/velociraptor/$i; done && \
    # Get Velox binaries
    WINDOWS_EXE=$(curl -s https://api.github.com/repos/velocidex/velociraptor/releases/latest | jq -r 'limit(1 ; ( .assets[].browser_download_url | select ( contains("windows-amd64.exe") )))')  && \
    WINDOWS_MSI=$(curl -s https://api.github.com/repos/velocidex/velociraptor/releases/latest | jq -r 'limit(1 ; ( .assets[].browser_download_url | select ( contains("windows-amd64.msi") )))') && \
    **#**LINUX_BIN=$(curl -s https://api.github.com/repos/velocidex/velociraptor/releases/latest | jq -r 'limit(1 ; ( .assets[].browser_download_url | select ( contains("linux-amd64") )))') && \
    MAC_BIN=$(curl -s https://api.github.com/repos/velocidex/velociraptor/releases/latest | jq -r 'limit(1 ; ( .assets[].browser_download_url | select ( contains("darwin-amd64") )))') && \
    **#**wget -O /opt/velociraptor/linux/velociraptor "$LINUX_BIN" && \
    wget -O /opt/velociraptor/mac/velociraptor_client "$MAC_BIN" && \
    wget -O /opt/velociraptor/windows/velociraptor_client.exe "$WINDOWS_EXE" && \
    wget -O /opt/velociraptor/windows/velociraptor_client.msi "$WINDOWS_MSI" && \
    # Clean up 
    apt-get remove -y --purge curl wget jq && \
    apt-get clean
**COPY ./velociraptor /opt/velociraptor/linux/velociraptor**
WORKDIR /velociraptor 
CMD ["/entrypoint"]`

Docker-Compose (line changes made to Wes's original are bolded):
`version: '2'
services:
  velociraptor:
    container_name: velociraptor
    **#image: wlambert/velociraptor**
    **build:
      context: ./
      dockerfile: Dockerfile**
    volumes:
      - ./velocidata:/velociraptor/:rw
    environment:
      - VELOX_USER=${VELOX_USER}
      - VELOX_PASSWORD=${VELOX_PASSWORD}
      - VELOX_ROLE=${VELOX_ROLE}
      - VELOX_SERVER_URL=${VELOX_SERVER_URL}
      - VELOX_FRONTEND_HOSTNAME=${VELOX_FRONTEND_HOSTNAME}
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8889:8889"
    restart: unless-stopped`

**Comment by scudette** [comment]
Cool! We can close this issue then. Thanks for verifying it
