### ISSUE TITLE
S3 Upload - Collector Log Not Properly Uploaded

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#2756]
Example:
`upload_S3: Unable to open Collector_velociraptor-v0.6.8-2-windows-amd64.exe.log: open \\.\Collector_velociraptor-v0.6.8-2-windows-amd64.exe.log: The system cannot find the file specified`

There is a discrepancy between the name of the log file that is expected to be uploaded to the cloud when using a collector binary.

It is expected that the log file be based on the collector binary name, but it is created with the collection name instead.

This does not affect the collection itself.

**Comment by scudette** [comment]
Fixed by #2834
