### ISSUE TITLE
AddCertificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by kaovd** [Velocidex/velociraptor#2765]
Hello!

I am running a self signed configuration with a few machines with version 0.6.9

For sanity I enabled use_plain_http to make sure the certificates where being passed through properly 

I have followed the general self signed documentation and generated a config using the wizard, entering my domain (velociraptor.myinternal.net) and then enabling plain http.

I have one client in working order:

```
Received PEM for VelociraptorServer from http://velociraptor.myinternal.net:443
Connected to http://velociraptor.myinternal.net:443/reader after waiting for limiter for 0s
```

However from my other systems I end up with ```AddCertificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Velociraptor CA")```

When using curl I get the expected result

```
 curl.exe  http://velociraptor.myinternal.net:443/server.pem
-----BEGIN CERTIFICATE-----
MI...
```

It looks fine to me:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7c:a5:9c:b0:39:57:d0:87:c4:cd:eb:ef:a8:30:9f:9e
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = Velociraptor CA
        Validity
            Not Before: Jun 20 20:48:26 2023 GMT
            Not After : Jun 19 20:48:26 2024 GMT
        Subject: O = Velociraptor, CN = VelociraptorServer
```

Not too sure how to debug this one without ripping through a go trace - unsure if a policy configuration could cause this?

**Comment by scudette** [comment]
Make sure both client config have the same cert ca. The client verifies the server certificate using that embedded ca cert in the config file.

**Comment by kaovd** [comment]
Hello,

For some reason it differed. Given I used the same installer I've no idea how that managed to happen but can work around it. Unsure if should be investigated into? 

Thanks!
