### ISSUE TITLE
SPARSE files like USNJRNL not correctly read

### ISSUE THREAD

**Issue by ydkhatri** [Velocidex/velociraptor#2785]
Sparse data streams such as the $USNJRNL:$J are not correctly read due to a bug in the underlying go-ntfs library. 

The issue is that go-ntfs treats SPARSE streams as (SPARSE + ENCRYPTED). This causes incorrect/incomplete sectors to be returned. A simple fix has been made available [here](https://github.com/Velocidex/go-ntfs/pull/79/commits/d96be33f04e971a4dd4ca285daf0def8a070cca2).

Just putting this up here to track it in this project as well.

**Comment by scudette** [comment]
Fixed by https://github.com/Velocidex/go-ntfs/commit/d91ecfd72ff90a598c0490671ff280975584e0da
