### ISSUE TITLE
Add release binaries for Linux/arm64

### ISSUE THREAD

**Issue by tstromberg** [Velocidex/velociraptor#2792]
Our environment is mostly Cloud-hosted arm64 environments. It'd be nice to have binaries available so that I don't have to script out the build process myself.

I'd be happy to contribute a PR if you could point me to which files I should change. Taking a Naive look at it, it seems like all I would need to do is modify the magefile & Github Actions YAML.

**Comment by scudette** [comment]
If you wanted to include the C code we need a C compiler for the arm platform. I think you will need to build on an actual ARM container in the github matrix (unless you can figure out how to install ARM cross compilers for GCC):

https://github.com/Velocidex/velociraptor/blob/00e3a0aebb7422419a3a49ae0dd52f0b73d50029/.github/workflows/go.yml#L15

Currently the arm64 target turns CGO off and so it is missing some things like sqlite, yara and libmagic:
https://github.com/Velocidex/velociraptor/blob/00e3a0aebb7422419a3a49ae0dd52f0b73d50029/magefile.go#L359

If you can build it on the correct container you can just copy paste that target and turn cgo back on.
