### ISSUE TITLE
velociraptor-v0.3.1-linux-amd64 failed custom artifacts want start service

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#28]
Hi,

velociraptor-v0.3.1-linux-amd64 want start artifacts crated in velociraptor-v0.3.0-linux-amd64. It fail on first artifact. 

[ERROR] 2019-07-16T12:42:26Z Failed starting services: Unknown artifact Windows.Events.Sysmon.SymonStatus 
[INFO] 2019-07-16T12:42:26Z Server is shutting down... 
[INFO] 2019-07-16T12:42:26Z Server stopped 

I have definition in directory
velociraptor/artifact_definitions/custom/Windows/Events/Sysmon

**Comment by Idriel** [comment]
```
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/4624_Logon_Type_2.yaml: Artifact type invalid. 
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/Sysmon/CreateRemoteThread.yaml: Artifact type invalid. 
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/Sysmon/FileCreate.yaml: Artifact type invalid. 
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/Sysmon/NetworkConnect.yaml: Artifact type invalid. 
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/Sysmon/ProcessCreate.yaml: Artifact type invalid. 
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/Sysmon/ProcessTerminate.yaml: Artifact type invalid. 
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/Sysmon/RegistryEvent.yaml: Artifact type invalid. 
[INFO] 2019-07-16T13:01:20Z Unable to load custom artifact artifact_definitions/custom/Windows/Events/Sysmon/SymonStatus.yaml: Artifact type invalid. 

```

**Comment by Idriel** [comment]
Found it. Change was it artifact definition:  `type: EVENT` to `type: CLIENT_EVENT`

**Comment by scudette** [comment]
I think this is because it is trying to start the server artifact service
and load the artifact. In the latestb custom artifacts miss start with the
name custom.

I would remove the file in the config directory of the file store and then
add the custom artifacts with the GUI again. Also make sure the custom
artifacts name starts with "Custom."

**Comment by scudette** [comment]
Ah good catch! Yeah now there is client event and server event as different
artifact types.
