### ISSUE TITLE
Improve Windows.Forensic.Timeline with additional fields

### ISSUE THREAD

**Issue by DavidSanchezGracia** [Velocidex/velociraptor#2807]
Hi!

I have realized that the artifact "Windows.Forensics.Timeline" which parse "Windows 10 Timeline" could increment the data it gathers from "ActivitiesCache.db".

At this moment the artefact gather the following fields: 
- Application
- User
- Last modified time
- Last execution TS

While the SQL database contains additional fields as: 
- Start time (timestamp)
- Activity Type
- Display Text
- Clipboard Payload
- Content Info

Would it be possible to update the artifact so that it also gather that info? 

Thanks in advance and kind regards!

**Comment by scudette** [comment]
The activities cache is an sqlite database and it is better parsed with SQLiteHunter https://github.com/Velocidex/SQLiteHunter/blob/main/definitions/Windows_ActivitiesCache.yaml which will become a standard artifact in 0.7.0

In current and previous versions we have https://docs.velociraptor.app/artifact_references/pages/generic.collectors.sqlecmd/ which also covers the same.

Eventually we aim to remove all the individual sqlite parsing artifacts in favor of this one single one.

**Comment by DavidSanchezGracia** [comment]
Amazing, I didnt know that one. Thanks a lot!
