### ISSUE TITLE
Boolean artifact parameters are not checked when their default state is true

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#2811]
Artifacts with a parameter definition like [this](https://github.com/Velocidex/velociraptor/blob/363b597b9f5300428a4a78a0f785abcc3ca530c5/artifacts/definitions/Server/Alerts/TheHive/Alert.yaml#L23),
```yaml
parameters:
  - name: DisableSSLVerify
    type: bool
    default: True
```
, produce a checkbox in the web interface with an unchecked (false) state instead of checked (true). Other controls appear to have their default values correctly set. The [Demo.Plugins.GUI ](https://github.com/Velocidex/velociraptor/blob/363b597b9f5300428a4a78a0f785abcc3ca530c5/artifacts/definitions/Demo/Plugins/GUI.yaml#L40) uses the default value "Y", which results in a checked check box. Other boolish values like, "True", "true" and 1 do not.

I would expect at least the string "true" to be parsed as a true value, like "Y".

**Comment by scudette** [comment]
As you can see the GUI interprets and sets Y/N for boolean values

https://github.com/Velocidex/velociraptor/blob/363b597b9f5300428a4a78a0f785abcc3ca530c5/gui/velociraptor/src/components/forms/form.jsx#L572

Although the VQL compiler will generate code that can handler any of those forms `'^(Y|TRUE|YES|OK)$' `
https://github.com/Velocidex/velociraptor/blob/363b597b9f5300428a4a78a0f785abcc3ca530c5/services/launcher/compiler.go#L175

Perhaps we need to update the GUI to support all those forms.

**Comment by misje** [comment]
I couldn't find allowed values in the documentation (although I know that it isn't complete). I already saw submitted artifacts with the same mistake, so I believe accepting other truthly values would be beneficial. Especially since the other values are interpreted by VQL, leaving the GUI with a checkbox in an incorrect state.
