### ISSUE TITLE
[Feature Request] Specify Minimum TLS Level in Server Config

### ISSUE THREAD

**Issue by nullifysecurity** [Velocidex/velociraptor#2815]
## Details

As discussed on Discord, can you please implement the ability to specify the minimum TLS version in the server configuration for the frontend? This is currently hardcoded at TLS 1.3 (as per [builder.go](https://github.com/Velocidex/velociraptor/blob/85e0bb28d5adaec7829356c60eac58163f4fb9a2/api/builder.go#L744)).

This will allow older technologies without support for TLS 1.3 the ability to communicate with the Velociraptor frontend, such as the default .NET version on Windows 10 used by PowerShell to make web requests.

Thank you!

[Discord Reference](https://discord.com/channels/624244632552734750/624244632552734752/1130678230286868530)

**Comment by scudette** [comment]
You can now specify the config option `allow_weak_tls_server` which will use default settings (allowing TLS 1.2)

https://github.com/Velocidex/velociraptor/blob/eff645275d27c51ad54591ae3581df1ff0f9466d/config/proto/config.proto#L1068

**Comment by Felix83000** [comment]
Hi,

Same problem here with my **GCP Application Load Balancer** which uses **TLS 1.2** from the **load balancer to the VM**.
**Do you have the same problem ?**

While waiting for 0.7.0 I am trying to configure the load balancer to use TLS 1.3 for the backend, hopefully 0.7.0 will be released soon.

Thanks

**Comment by scudette** [comment]
If you are using a load balancer, it seems pointless to use TLS to connect to the server because it will still use encryption anyway. Don't you want to use plain http to remove the encryption load?

**Comment by Felix83000** [comment]
Do you confirm that even when not using HTTPS between the loadbalancer and the VM, Velociraptor will still encrypting all data? (I would prefer to also encrypt traffic inside GCP also.)
If yes, I will use plain http, can you give me the settings to enable it in Velociraptor?

Thanks!

**Comment by scudette** [comment]
Velociraptor has two layers of encryption. The custom encrypted packets that are sent between client and server are encrypted and signed. Then there is a TLS layer on top of that.

If you use plain http between alb and frontend that removes the TLS layer but you can not remove the custom crypto which is always present.

Here is more information about the encryption protocols

https://docs.velociraptor.app/blog/2020/2020-09-28-velociraptor-network-communications-30568624043a/

**Comment by Felix83000** [comment]
Ok thank you. All endpoints will have encrypted communication anyway, but if I log into the admin GUI from the load balancer, the communication will be in the clear within the GCP network.

**Comment by scudette** [comment]
Yes this is true but the number of connections for the GUI are very small compared to client connections. Maybe keep the GUI over TLS then and only use http for the alb. You can set these parameters independently

**Comment by scudette** [comment]
Hopefully in the next few days :-)

**Comment by Felix83000** [comment]
Thanks for your work! 
Everything is working great now :)

ps: All in HTTPS
