### ISSUE TITLE
no space left on device issue. 

### ISSUE THREAD

**Issue by bijuvp** [Velocidex/velociraptor#2817]
I am getting the following error "Error: mkdir /opt/velociraptor/clients/C.f11ea91fd11f6077/collections/F.CIRD0B3FJLLS0: no space left on device"

There is plenty of space on the drive.

**Comment by scudette** [comment]
This error is coming from the os. Are you sure the partition that contains the data store is not full?

**Comment by bijuvp** [comment]
Its a windows 10 device. there ia bout 100GB free space left on the device.

**Comment by scudette** [comment]
in #2887 we introduced a check for low disk space which blocks writes when the disk is too low.

The server here ran out of disk space (it is an ubuntu system because the data store is in /opt/ )
