### ISSUE TITLE
Amcache not parsing correctly

### ISSUE THREAD

**Issue by mtreanor-r7** [Velocidex/velociraptor#2831]
Hi,

We are running 0.6.8 and Windows.Detection.Amcache is not parsing correctly but Windows.System.Amcache is only parsing Windows.System.Amcache/InventoryApplicationFile and not Windows.System.Amcache/File

I've verified the assets have a hive with data processed in other tooling. 

I've tested on 0.6.9 and have the same outcomes.

**Comment by scudette** [comment]
There was a fix to the default glob here
https://github.com/Velocidex/velociraptor/commit/2b6f5354a18c44b161a556601a669cbea34a1196

You can just update it when you launch the artifact in the guI

**Comment by mtreanor-r7** [comment]
Great thank you, I can see data but not the SHA1 values

**Comment by mtreanor-r7** [comment]
My mistake, the SHA1 values are now coming in
