### ISSUE TITLE
New Collection: Specify Resources - input validation and conflicting hints

### ISSUE THREAD

**Issue by Bloggzy** [Velocidex/velociraptor#2835]
As ever, VR is awesome, but highlighting something to (hopefully) make it even better.

### Input Validation

When selecting artefacts for a new collection / hunt I've noticed the following with the "**Specify Resources**" panel.

The input field hints suggest things like "100%" or "600s" or "1 Gb", but if you actually enter those values, the validation doesn't let you continue (by greying out the "Select Artifacts | Configure Parameters | Specify Resources | Review | Launch" options at the bottom).

Initially I wasn't sure what was causing the options to be greyed out, and it took me a moment to figure out what was happening, as there isn't any indication of what field / value is causing the issue (a suggestion for a later enhancement maybe?).

The issue is that if you enter the data as the hint suggests (including a "%" or "s" or "Gb"), then it won't work/validate. In fact you need to specify the values without any non-numeric characters. i.e. "100", "600", or "1".

### Conflicting Hints

The other part of this, is that the "Max Mb Uploaded" field appears to conflict with the hint in the input field, which reads "1 Gb", is it Mb or Gb / MB or GB?

![image](https://github.com/Velocidex/velociraptor/assets/46377651/1ffb1814-e642-4278-9b1a-487f7de059d4)

**Comment by scudette** [comment]
This was actually a CSS bug - the invalid input boxes are meant to go red when invalid. 

Fixed by #3331
