### ISSUE TITLE
Not able to get the Agent Name in version 0.6.9

### ISSUE THREAD

**Issue by Aarav786** [Velocidex/velociraptor#2836]
Hi, I am a newbie for Velociraptor and I am following some training stuff based on previous versions, right now I am doing my hands-on with version 0.6.9 and in this I am not able to figure-out the agent-name. Kindly please help me on this. Thanks

![AgentName Issue Ver-0 6 9](https://github.com/Velocidex/velociraptor/assets/115832883/fc40c50b-b6c1-491c-a395-683b5576ddb2)

**Comment by scudette** [comment]
What do you mean by agent name? Are you asking about the hostname? It's shown at the top on the host overview.

**Comment by Aarav786** [comment]
I am also co-relating the Agent Name with Host Name but i am not sure as in version 0.6.0 Agent Name is there, refer the attachment. 

![IR371-12](https://github.com/Velocidex/velociraptor/assets/115832883/c593201b-7edb-48e2-ab6f-203bc068710c)

**Comment by scudette** [comment]
The agent name is one of the fields in the version structure but it's always the same so we don't bother reporting it anymore. A very long time ago velociraptor was interoperable with grr so that field has some meaning but it's not relevant any more.

**Comment by Aarav786** [comment]
Ok Thanks, for your explanation now i can complete my assignment with valid reason.
