### ISSUE TITLE
Option to download files into a password protected zip using VFS

### ISSUE THREAD

**Issue by delujsecurity** [Velocidex/velociraptor#2858]
In most use cases of Velociraptor, the analyst or user will often be deploying the agent on systems of interest that performed suspicious or malicious activity. If an analyst identifies a suspicious file and needs to download the file for further analysis by using the VFS, this should have the option to download the file into a password protected zip archive. Either allowing the user to supply a custom password, or utilizing the standard password of "infected". This will allow an analyst to safely collect the suspicious file and move the file to a separate system for further analysis, decreasing the chances of accidental execution or endpoint alerts.

**Comment by scudette** [comment]
Fixed by #3057
