### ISSUE TITLE
Clients sometimes have flows that don't timeout

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#2860]
Have seen this quite a lot, but have not good a good idea as to why this occurs.

![image](https://github.com/Velocidex/velociraptor/assets/1241363/a537baf9-d0c4-4f53-a01a-726ca8d2f8af)

This is a client running 0.6.8-2 (server 0.6.9). It can receive flows no problem at the moment, and is currently connected.
It has a few flows that are just sitting there in running and arent active. There is on that was active, returned 1000 rows and the last log entry (>1 day ago) was "waiting for rows".

I think there's an edge condition (maybe the system going offline?) that causes it the client to drop its list of flows, and then it can't report them back to the server. Ideally the server does some funky math and says "hey the client has been online for longer than the timeout, I'm going to mark this as timed out" or even better, it gives the client a bit of a kick and reissues the flow without the user having to do anything (understand why this may not be the case).

**Comment by scudette** [comment]
Nope - the server does not do any such math. If the client dies during the flow (eg rebooted or crashed) the flow will just not be updated. In 0.6.9 clients we write a checkpoint by default when we start running the flow then when we restart (after reboot or crash) we let the server know we crashed.

this is what it looks like (I killed it mid collection with task manager)
![image](https://github.com/Velocidex/velociraptor/assets/3856546/dc5588e8-2338-4b6d-86e2-bdcd47719a0d)

Of course we dont know why it crashed just that it did and we can only send the message when we come back online. So there is a chance that it still ends up looking stuck but in most cases it should report the crash.

**Comment by randomaccess3** [comment]
Yeah I don't mind if it's gone offline during the flow - it'll report as running, but the host will be offline and that's explainable.
Where it's problematic is when the client is actively connected, and has "running" flows, but they arent actually running
In some cases, I've seen the client not even able to accept new flows until some action is taken. Sometimes that action was stopping everything, running killkillkill and it would come good. This week i had one where i collected a profile and it instantly finalised a running flow (but not the earlier ones that the server remembered but the client had forgotten about)

**Comment by scudette** [comment]
Maybe we need an active feedback mechanism where the server can say to the client - i know you are running these 5 flows hows it going? and the client can say - i have no idea what you are talkking about so we can update the state of those flows in the GUI. This can not happen automatically all the time due to load, but may be user initiated in the GUI somehow.

At least this might confirm that the client is still working on the flow or totally forgot them (due to restart) or the flows are queued but waiting to run because they are behind other slow flows etc

**Comment by randomaccess3** [comment]
I have a profile for a similar client. 
It's basically had nothing run on it successfully. It's had a bunch of new hunts queued up, but it is stuck. So it wont accept anything new until the other stuff all expires (possibly tomorrow), but almost nothing has returned a result even though it's connected.
If i ran collect profile, urgently, it worked.

**Comment by scudette** [comment]
can you share the goroutines dump?

**Comment by randomaccess3** [comment]
Yep, will send it to you

**Comment by balasub** [comment]
Any recent updates on this issue? We have seen similar issues with flows when we use the Python interface.

**Comment by scudette** [comment]
This should be addressed in the upcoming 0.73 where flows are actively monitored by the server. If a client disappears (reboots) the flows will be errored out when the client returns.
