### ISSUE TITLE
Labels issue

### ISSUE THREAD

**Issue by AVE-Stoik** [Velocidex/velociraptor#2863]
Hello,

I was trying to use labels to automate the artifact results zip upload to S3 and then fetched by my timesketch instance (https://github.com/ReconInfoSec/velociraptor-to-timesketch)
The results zip name is supposed to be built using the client hostname and labels, however whenever I set labels they're not added in the zip results name.
<img width="661" alt="label3" src="https://github.com/Velocidex/velociraptor/assets/127731526/cebeb399-6dc8-43a4-bad2-3ff84421ef3d">

I also noticed that on the VQL export, the "labels" column was empty whereas the client shows with the labels I added, and I can also search by label in velociraptor server to find these clients.
<img width="815" alt="label1" src="https://github.com/Velocidex/velociraptor/assets/127731526/408e8109-27ba-41f6-9e4f-4515c13f0404">
<img width="1133" alt="label2" src="https://github.com/Velocidex/velociraptor/assets/127731526/6c9f0261-312f-4e83-968a-033676e1d49d">

**Comment by scudette** [comment]
The export name is currently not user configurable and doesn't include the labels.

Are you suggesting we should also export the labels when we export a collection? 

You can dump out the labels for the client using vql but it's not automatically exported with each collection.

Something like

Select client_id, labels from clients()

**Comment by AVE-Stoik** [comment]
My goal is to be able to export in one sketch multiple artifact results, if you check this code from velociraptor-to-timesketch [they claim that you already do it.](https://github.com/ReconInfoSec/velociraptor-to-timesketch/blob/main/bash/watch-to-timesketch.sh#L10C6-L10C6)
cf _"Velociraptor artifact inserts `_$label` to the zip (ex: exchangesrv_ir-1) so we can use the label "ir-1" as the sketch name, and have multiple timelines for an IR under a single sketch"_

Is this a mistake from their side ? Is there any other way to reach our goal of merging multiple result zips into a single identifiable "group" ?

**Comment by AVE-Stoik** [comment]
Nevermind, I just noticed it is handled in their custom server artifact module : https://github.com/ReconInfoSec/velociraptor-to-timesketch/blob/main/velociraptor/Custom.Server.Utils.KAPEtoS3

All good then, I'll handle it there :)
