### ISSUE TITLE
Deaddisk mode searches for files on host system

### ISSUE THREAD

**Issue by ydkhatri** [Velocidex/velociraptor#2870]
Running velociraptor over an image in deaddisk remap mode sometimes looks for files outside on the host system and not in the disk image. This is tested and observed in **0.6.9** and also in the latest **0.7.0-rc1**.

An example of this is running the `Windows.Search.Yara` artifact.
```
velociraptor-v0.6.9-windows-amd64.exe artifacts collect -v --remap="C:\temp\vr\testbed run\test_outputs\remapping_disk.yaml" --logfile="C:\temp\vr\log.log Windows.Search.Yara
```
The logfile (and console if verbose output is used) has several entries like this, showing errors trying to open files:
```
{"level":"info","msg":"Directly scanning file \\\\.\\C:\\Users\\Training\\AppData\\Local\\Microsoft\\Edge\\User Data\\Speech Recognition\\1.15.0.1\\Microsoft.CognitiveServices.Speech.core.dll failed, will use accessor\n","time":"2023-08-08T08:51:49Z"}
{"level":"info","msg":"yara: Failed to open \\\\.\\C:\\Users\\Training\\AppData\\Local\\Microsoft\\Edge\\User Data\\Speech Recognition\\1.15.0.1\\Microsoft.CognitiveServices.Speech.core.dll with accessor : file does not exist\n","time":"2023-08-08T08:51:49Z"}
{"level":"info","msg":"Directly scanning file \\\\.\\C:\\Users\\Training\\AppData\\Local\\Microsoft\\Edge\\User Data\\edge_shutdown_ms.txt failed, will use accessor\n","time":"2023-08-08T08:51:49Z"}
{"level":"info","msg":"yara: Failed to open \\\\.\\C:\\Users\\Training\\AppData\\Local\\Microsoft\\Edge\\User Data\\edge_shutdown_ms.txt with accessor : file does not exist\n","time":"2023-08-08T08:51:49Z"}
```
The files all exist on the disk image, however VR seems to be looking at the host system instead of the disk image. See screenshot of ProcMon below which shows the calls made by VR to read these files. The entire "C:\Users\Training\" folder does not exist on the host and is only in the image.

<img width="960" alt="image" src="https://github.com/Velocidex/velociraptor/assets/13247440/91b4def7-a457-4e16-8431-8174c3feb76d">

While I have not tried to debug this, it would appear that certain code paths (for assessors?) aren't mapping correctly back to the disk image.

**Comment by scudette** [comment]
Can you share your remapping config? When Yara scanning specially we pass
the path to the Yara library itself when using the file accessor and so it
will be trying to open the files by itself

We probably shouldn't because the file accessor may not be really that when
remapping so I think this is a bug.

However if it failed to open the file the plugin should fall back to using
the accessor which should honour the remapping

This is probably an edge case of remapping and the Yara plugin. We should
file a bug to make sure it's handled correctly.

Thanks
Mike

**Comment by ydkhatri** [comment]
Sure, the mapping file is attached here: [remapping_disk.yaml.zip](https://github.com/Velocidex/velociraptor/files/12297062/remapping_disk.yaml.zip). 

Created as 
`velociraptor-v0.6.9-windows-amd64.exe -v deaddisk --add_windows_disk H:\PhysicalDrive1 C:\temp\vr\remapping_disk.yaml`

**Comment by scudette** [comment]
This issue actually affects a number of plugins that require the file on disk to call a library on it:
- yara
- sqlite
- localdb
