### ISSUE TITLE
Bug - Creating Hunts through VQL

### ISSUE THREAD

**Issue by Jbhoohe** [Velocidex/velociraptor#2871]
SELECT hunt(
    description="TESTS3",
    artifacts=('Windows.System.PowerShell','Windows.Detection.EnvironmentVariables'),
    spec=dict(`Windows.System.PowerShell`=dict(Command ='whoami'), `Windows.Detection.EnvironmentVariables`=dict(EnvironmentVariableRegex ='VELOCIRAPTOR_API_FILE')),
    expires=now() + 18000),
    org_id='your org id'
FROM scope()

Throws this.
Symbol org_id not found. Current Scope is: [NULL], [_SessionId, $cache, $device_manager, config, $acl, $uploader, Artifact, $root], [NotebookId], [$Query], []
Query Stats: {"RowsScanned":1,"PluginsCalled":1,"FunctionsCalled":5,"ProtocolSearch":0,"ScopeCopy":3} 

and starts the hunt for all tenants. I'm seeing that the symbol isn't being found.

**Comment by Jbhoohe** [comment]
Didn't add the description. But essentially when creating hunts this does not when specifying the org id. It defaults to the root or all tenants and is fairly buggy.

**Comment by scudette** [comment]
This works fine - your VQL syntax is wrong though. Try something like this:

```sql
SELECT hunt(
  description="TESTS3",
  artifacts=['Windows.System.PowerShell','Windows.Detection.EnvironmentVariables'],
  spec=dict(
    `Windows.System.PowerShell`=dict(Command ='whoami'), 
    `Windows.Detection.EnvironmentVariables`=dict(EnvironmentVariableRegex='VELOCIRAPTOR_API_FILE')),
  expires=now() + 18000,
  org_id='O123')
FROM scope()
```
