### ISSUE TITLE
[Feature Request] Add FlowStartedTime in Hunt Results

### ISSUE THREAD

**Issue by teddy-ROxPin** [Velocidex/velociraptor#2873]
Would you please add a column for the FlowStartedTime in the Hunt Results? If I execute a Hunt in the environment on Monday, then check results on Tuesday, it can be challenging to then check again on Thursday but only review the results that've populated since I last checked on Tuesday. If there were a FlowStartedTime, it would be easy to filter these results.

**Comment by scudette** [comment]
You can always just add this information to your own notebook. For example:

```sql
SELECT *, {
    SELECT timestamp(epoch= start_time)
    FROM flows(client_id=ClientId, flow_id=FlowId)
} AS FlowInfo
FROM source(artifact="Generic.Client.Info/BasicInformation")
LIMIT 50
```
