### ISSUE TITLE
[Feature Request] Edit / create artifact from previous collection

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#2874]
Often we run interesting yara or VQL filters and want to create a new artifact and or slightly modify the VQL for ease of use.

It would save a lot of time to have a "create artifact from collection" button that would take the collection parameters and push us to an edit artifact view to modify and save as required.

A good example of use would be a large yara rule, where we also want to edit the underlying VQL for presentation, currently we need to mess with formatting etc, which makes this process prohibitive. It would be much easier to validate, then pivot to edit from previous collection.

**Comment by scudette** [comment]
Is that different from the favorite process?

Ideally we dont want to end up with hundreds of similar but slightly different custom artifacts - like a full artifact for each yara variation?

**Comment by mgreen27** [comment]
The use case that springs to mind is CVE/Emerging threat coverage and generating a sharable artifact but I do see your point with people adding "lets add a calculator" content even more than now :)

Yara is notoriously bad when trying to add a large rule and testing, before getting an error and needing to try again, not necessarily a favorite. Often its difficult to write an artifact with a super large yara rule. I have gotten around this with a script though.
