### ISSUE TITLE
Quarantine Artifact is not returning rows or logs

### ISSUE THREAD

**Issue by Jbhoohe** [Velocidex/velociraptor#2881]
Essentially while the quarantine object is successfully executed and the client sends the amount of rows there are, the server never receives (or at the very least displays) the rows or logs.

**Comment by scudette** [comment]
I can not replicate specifically with the Quarantine artifact

![image](https://github.com/Velocidex/velociraptor/assets/3856546/319e48ed-6cbf-4eaf-b1da-ad779f88c15a)


But this may be a different effect - the client now reports how many rows it actually sent but then sends the rows separately. It may be that the actual rows were not uploaded correctly but the stats are telling us that there are more rows.
