### ISSUE TITLE
[Feature Request] label host by hostname ,fqdn or os version  

### ISSUE THREAD

**Issue by Ron-Nefyodov** [Velocidex/velociraptor#2889]
label host by hostname ,fqdn or os version  (I install several time per client so I get a lot of client id per host)

**Comment by scudette** [comment]
You can apply labels based on any criteria you want.

For example https://docs.velociraptor.app/knowledge_base/tips/huntlabel/ 

Or you can use the clients() plugin to gather client information (like is fqdn etc)
