### ISSUE TITLE
MacOS unsigned collector

### ISSUE THREAD

**Issue by Zawadidone** [Velocidex/velociraptor#2915]
As of version 0.7.0 the Velociraptor Mac OS collector by default needs a embed config file to be executed. But there are situations (EDR, etc) where it is preferred to execute a single executable without an additional configuration file on a Mac OS system to collect data. 

```bash
xattr -d com.apple.quarantine Collector_velociraptor-v0.7.0-rc1-darwin-arm64
./Collector_velociraptor-v0.7.0-rc1-darwin-arm64
[...]
```

Could a second option be added for the target operating system `Mac OS Unsigned` which still embeds the config file in the executable.

**Comment by scudette** [comment]
Unfortunately not. It seems to be impossible to modify the binary after the compile step on macos.

There seems to be some kind of hash that covers the binary so we can not modify it.

**Comment by scudette** [comment]
Looking more closely at this it seems to affect the arm64 binaries but does not affect the amd64 binaries which can still be repacked:

```
./velociraptor-v0.7.0-darwin-arm64 config generate > server.config.yaml
./velociraptor-v0.7.0-darwin-arm64 config repack server.config.yaml repacked.bin
./repacked.bin
Killed: 9
```

This sequence will work on an amd64 mac.

**Comment by scudette** [comment]
As I mentioned above this works for amd64 binaries but not for arm64.

**Comment by Zawadidone** [comment]
@scudette this also works for arm64 see the commands below.

```bash
MACOS_URL=$(curl -s https://api.github.com/repos/velocidex/velociraptor/releases/tags/v0.7.0| jq -r '[.assets | sort_by(.created_at) | reverse | .[] | .browser_download_url | select(test("darwin-amd64$"))][0]')
wget -q $MACOS_URL -O velociraptor
chmod +x velociraptor

# Collect the tools
./velociraptor config generate > server.config.yaml
./velociraptor --config server.config.yaml artifacts collect Server.Internal.ToolDependencies

./velociraptor --config server.config.yaml artifacts collect Server.Utils.CreateCollector \
  --args OS=MacOS \
  --args artifacts='["Generic.Collectors.File"]' \
  --args parameters='{"Generic.Collectors.File":{"Root":"/","collectionSpec":"Glob\netc/hosts\n"}}' \
  --output macos.zip

unzip macos.zip -d macos
cp macos/uploads/*/Collector_* velociraptor-macos-config

# Adjust to darwin-amd64 for Intel
MACOS_URL=$(curl -s https://api.github.com/repos/velocidex/velociraptor/releases/tags/v0.7.0| jq -r '[.assets | sort_by(.created_at) | reverse | .[] | .browser_download_url | select(test("darwin-arm64$"))][0]')
wget -q $MACOS_URL -O velociraptor-macos

./velociraptor config show --embedded_config velociraptor-macos-config > config.yaml
./velociraptor config repack --exe velociraptor-macos config.yaml new_collector

mv new_collector velociraptor-macos-arm

file velociraptor-macos
velociraptor-macos: Mach-O 64-bit executable arm64
```

Could the option be added to specify specific `TargetOS` to the artifact `Server.Utils.CreateCollector`:

* `Windows`
* `Windows_x86`
* `Linux`
* `LinuxARM` - new repack, if possible musl arm64 
* `MacOS`
* `MacOSARM` - new repack
* `Generic Collector` - the option explained in https://docs.velociraptor.app/blog/2023/2023-07-27-release-notes-0.7.0/#the-offline-collector

**Comment by scudette** [comment]
Can you verify that you can actually execute the modified arm64 binary?

**Comment by scudette** [comment]
Can you verify that you can actually collect though?

**Comment by Zawadidone** [comment]
Due to privacy reasons I cannot execute the collect method on the laptop.

**Comment by scudette** [comment]
ok - so try to run something that will take a sec: `./velociraptor-macos -v query "SELECT sleep(time=1) FROM scope()"` 

In my experience the OS will kill the process once it verifies the hashes so running just `version` will be too fast for it.

**Comment by Zawadidone** [comment]
My bad the process got killed. I thought why not give it a try.
