### ISSUE TITLE
Older Linux distribution version support? - version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by juju4** [Velocidex/velociraptor#2925]
While updating ansible role to setup velociraptor to v0.7.0, I got glibc errors on all my test distributions except for current latest ubuntu-22.04 and rockylinux-9.
is this intended? v0.6.9 as last version for older ones?
or maybe result of golang toolchain version?

https://github.com/juju4/ansible_velociraptor/actions/runs/6058762509/job/16441210163#step:7:2750 (20.04 bare)
```
     "stdout_lines": [
        "/opt/velociraptor/velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/velociraptor/velociraptor)",
        "/opt/velociraptor/velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/velociraptor/velociraptor)",
        "/opt/velociraptor/velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/velociraptor/velociraptor)"
```

https://github.com/juju4/ansible_velociraptor/actions/runs/6058762507/job/16441210398#step:6:362 (via docker)

Thanks

**Comment by scudette** [comment]
https://docs.velociraptor.app/knowledge_base/tips/glibc_errors/

**Comment by juju4** [comment]
Sorry, I searched the github repo but missed the docs.
Thanks!
