### ISSUE TITLE
version `GLIBC_2.33' not found (required by velociraptor)

### ISSUE THREAD

**Issue by leetn00b** [Velocidex/velociraptor#2929]
When attempting to run the latest 0.7.0 velociraptor binary on Ubuntu 20.04 I am encountering the following error:

```
velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by velociraptor)
velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by velociraptor)
velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by velociraptor)
```

**Comment by scudette** [comment]
0.7.0 was built in Ubuntu 22.04, you can use the musl build for older Ubuntu.

I think we might rebuild with 20.04 because a few people are having this issue.

**Comment by Newtt** [comment]
I have the same issue. Our cloud provider do not offer 22.04 yet. I might need to change the whole automation code to use the musl version instead... please let us know if you will revert back so we don't need to change everything yet :)

**Comment by jofrep** [comment]
I have the same issue with Debian 11.7:

`
/usr/local/bin/velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by /usr/local/bin/velociraptor)
/usr/local/bin/velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by /usr/local/bin/velociraptor)
/usr/local/bin/velociraptor: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by /usr/local/bin/velociraptor)
`

current version:
`libc6 is already the newest version (2.31-13+deb11u6).`

**Comment by scudette** [comment]
Just use the musl build if you have an older system

https://github.com/Velocidex/velociraptor/releases/download/v0.7.0/velociraptor-v0.7.0-linux-amd64-musl

**Comment by jofrep** [comment]
Thanks, I confirm this works in Debian 11.7

**Comment by scudette** [comment]
I just uploaded a 0.7.0-2 linux build on Ubuntu 20.04 - you can use that as an alternative
