### ISSUE TITLE
yara: Failed to open errors with artifact Windows.Detection.Yara.Process

### ISSUE THREAD

**Issue by tuttimann** [Velocidex/velociraptor#2934]
I am running velociraptor on a machine and used the artifact Windows.Detection.Yara.Process, but in the log I get many error messages like `yara: Failed to open /4 with accessor process: OpenProcess for pid 4: Access is denied.`
This is not only for pid 4 but also for many other pids.

**Comment by scudette** [comment]
This is expected - pid 4 is the System process so we can not open it for reading. Other processes are protected by windows so we can not open them either. Without a kernel driver we are unable to bypass windows OS protections so can not read memory of protected processes.
