### ISSUE TITLE
[Feature Request] - watch_etw kernel providers

### ISSUE THREAD

**Issue by zaneGittins** [Velocidex/velociraptor#2944]
Currently watch_etw only supports user providers, it would be a great addition to also support kernel providers for additional telemetry. Implement similar functionality to SilkETW: `.\SilkETW.exe -t kernel -kk FileIOInit`

I believe would need to change the EnableFlags for pProperties that is passed to `C.StartTraceW` for kernel providers.

**Comment by bmcder02** [comment]
Hey @zaneGittins. Sorry about the delay getting back to you, are you still experiencing the issue? Velociraptor does have support for kernel providers, do you have a copy of the VQL you were using?

**Comment by zaneGittins** [comment]
Hi @bmcder02 - I don't have any VQL, I was initially trying to use `watch_etw`. I did create a pull request for Velociraptor's etw library to add this functionality https://github.com/Velocidex/etw/pull/2 but was struggling with the CLA.

**Comment by bmcder02** [comment]
Hey @zaneGittins , I just responded on that thread as well, but I'm currently working on a PR that will add the ability to query multiple providers in a single artifact. That was you can create your own Kernel Tracer with additional flexibility.
