### ISSUE TITLE
ACL Does not work with SAML Authentication

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#295]
Authorization failed. You are not registered on this system as my_username. Contact your system administrator to get an account, then try again. 

Logs
[ERROR] 2020-04-01T18:44:34Z User rejected by GUI {"method":"GET","remote":"ip_address:port","user":"my_username"}

my_username from SAML is the same as in User_Folder and ACL.

**Comment by scudette** [comment]
Did you grant the user at least a reader role?

**Comment by Idriel** [comment]
Hi, Yes. administrator role for that Username. 
I upgragrade from v0.3.9 to 0.4.1. Till that everything worked just fine. 
Local accounts (test env) working just fine after granting permissions, SAML not.

**Comment by scudette** [comment]
I replicated the setup described in https://github.com/Velocidex/velociraptor/tree/master/docs/saml#setting-up-testing-environment

and it worked when I granted the full user account (including the email):
![image](https://user-images.githubusercontent.com/3856546/78193117-151bb600-74bd-11ea-8f8d-84ab260842e0.png)

**Comment by Idriel** [comment]
No luck :(
I tried to create user like in screenshoot with mail-address. 
Changed in configuration to use emailAddress and not upn. Same error.

**Comment by scudette** [comment]
Can you see the policy object?
![image](https://user-images.githubusercontent.com/3856546/78215600-326f7500-74fb-11ea-9c35-e5661670be0d.png)

**Comment by Idriel** [comment]
![image](https://user-images.githubusercontent.com/4640885/78215942-0fbc6c80-74b9-11ea-80fd-c9e6656100b7.png)

**Comment by scudette** [comment]
Is the username exactly the same everywhere?

**Comment by Idriel** [comment]
Yes. All this worked on v0.3.9. Same configuration, same SAML/ADFS, ... I just changed binary to v0.4.1

**Comment by scudette** [comment]
0.3.9 did not have any ACL enforcement so this is where it is failing.

This is the relevant code:
https://github.com/Velocidex/velociraptor/blob/master/api/saml.go#L93

and you can see the log message has the username which is the same username which is being checked against the ACLs. The only way to trigger this error is if the ACL does not exist, the username is not the same as the one in the users directory or there is some error in accessing any of those (e.g. permission error). Is the frontend running as root? are there permission problems?

**Comment by Idriel** [comment]
Looks like it was permission error. 
I have server inside DockerFile and then persistant data mapped on host. 
I chmod-ed all for test on 777 and now is working normal.

Thanks

**Comment by scudette** [comment]
Ah wonderful! Thanks for debugging this.
