### ISSUE TITLE
Bug - Launching artifact that calls other artifact fails silently if other artifact misspelt/non-existent

### ISSUE THREAD

**Issue by wobodow** [Velocidex/velociraptor#2952]
When launching Artifact-A as a hunt, if A calls `SELECT * FROM Artifact.ArtifactB()` it will fail silently if ArtifactB does not exist (or is misspelt). Clicking launch hunt appears to succeeed but no new hunt is created. The way I figured this out is to run Artifact-A as a single flow/collection on a single endpoint and review the logs for that as it does run there and fail there.

**Comment by scudette** [comment]
If the hunt is not created then it failed to compile. It should have an error message in the little snack bar (black box on the bottom to right).

We do check this when compiling the artifact and will return an error so I don't think the hunt will be created at all. The question is if the error is obviously enough reported to the user.

**Comment by wobodow** [comment]
Yeah I see nothing popping up / snack bar launching a hunt with 
```
name: AAA.NoSnacks
description: |
   This is the human readable description of the artifact.

# Can be CLIENT, CLIENT_EVENT, SERVER, SERVER_EVENT
type: CLIENT

sources:
  - precondition:
      SELECT OS From info() where OS = 'windows' OR OS = 'linux' OR OS = 'darwin'

    query: |
      
      LET x = SELECT * FROM Artifact.Fake()
      SELECT *,
      {SELECT * FROM x}
      FROM info()
      LIMIT 10

```
