### ISSUE TITLE
Duplicate Clients

### ISSUE THREAD

**Issue by zaneGittins** [Velocidex/velociraptor#2955]
Seeing many duplicate clients across multiple systems. This is a nuisance as the new clients lose their tags and clutters up the GUI.

Here is an example of the first/last seen dates for one of the systems that is having duplicate issues:

1. Original Velociraptor install on 2023-09-14
```
Client ID: C.00fb0088ad89f50c
Agent Version: 0.7.0
Agent Build Time: 2023-08-28T02:38:17Z
First Seen At: 2023-09-14T14:36:39Z
Last Seen At: 2023-09-17T01:20:27Z
```

2. First duplicate
```
Client ID: C.703ce0643d031d83
Agent Version: 0.7.0
Agent Build Time: 2023-08-28T02:38:17Z
First Seen At: 2023-09-18T16:10:21Z
Last Seen At: 2023-09-18T18:02:25Z
```

3. Second duplicate.
```
Client ID: C.5e7aeca8ba91a45f
Agent Version: 0.7.0
Agent Build Time: 2023-08-28T02:38:17Z
First Seen At: 2023-09-18T18:08:19Z
Last Seen At: 2023-09-18T18:26:36Z
```

I attempted to see what was overwriting `velociraptor.writeback.yaml` using Sysmon. I saw event ID 11's for Velociraptor.exe at the time (2023-09-18T18:08:19Z) the second duplicate was created (`C.5e7aeca8ba91a45f`). 

|   |   |   |   |   |   |   |
|---|---|---|---|---|---|---|
|winlog.event_id|winlog.computer_name|winlog.event_data.Image|winlog.event_data.TargetFilename|winlog.event_data.UtcTime|winlog.event_data.CreationUtcTime|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|
|11|test.redacted.com|C:\Program Files\Velociraptor\Velociraptor.exe|C:\Program Files\Velociraptor\velociraptor.writeback.yaml|9/18/23 18:08|9/14/23 14:36|

However, if you check the InstallDate via WMIC for Velociraptor, it still shows the original date of 2023-09-14. 
`wmic product get "name,installdate"` gives "20230914 Velociraptor"

My theory is that sometimes velociraptor.writeback.yaml is getting corrupted, maybe when the client monitoring table is updated, causing it to be regenerated the next time the service starts up which generates a new client id.

Perhaps the client_id should be moved into the Windows registry, or a separate file?

**Comment by zaneGittins** [comment]
If velociraptor.writeback.yaml is corrupted while the agent is running, the client id and key, are not written back to the file.

Steps to reproduce:
1. Start Velociraptor service on Windows (v0.6.9+).
2. Overwrite velociraptor.writeback.yaml with junk data.
3. Update client monitoring table in server GUI.
4. Inspect writeback yaml on client.

In my case the writeback contained the following data:
```yaml
install_time: 1695155176
event_queries:
  event:
  - query_id: 1
    total_queries: 5
    precondition: |2
<--SNIP-->
```
Notably missing is the private_key and client_id.

Potential solutions:
* Ensure client_id and private_key are written back to the writeback file at all times.
* Split into multiple files and save static information in a separate file.

**Comment by LPT6166676c** [comment]
Thanks for raising this as an issue, was having the same issue myself of constant duplicate hosts showing, one online the rest offline with different client ID's. I was not able to recreate the issue so great you have been able to.

For reference the server and agent version I was using was 0.6.9, then upgraded the server to 0.7.0 with the issue still persisting.

**Comment by zaneGittins** [comment]
Thanks for sharing! I'm seeing the same too - issue on 0.6.9 and 0.7.0

**Comment by misje** [comment]
I'm experiencing the same issue. I've been investigating Linux clients so far, and I have full history of the writeback file since it happens to be in /etc and etckeeper is installed on the computers in question. I can't see any corruption of the file in any updates. I also have cases of fresh installs of 0.6.9 on Ubuntu where the client exists with two duplicates in the 0.7.0-2 server, with no evidence whatsoever that the client has been upgraded or reinstalled, but the auto-commited git log of the writeback file shows that the install_time and private_key has been replaced/updated.

**Comment by scudette** [comment]
#2966 now allows settings to be stored in the registry on windows. 

![image](https://github.com/Velocidex/velociraptor/assets/3856546/2a675994-d443-41af-bd15-92b068551325)

Just set the writeback to start with HKLM

```yaml
  writeback_windows: HKLM\SOFTWARE\Velocidex\Velociraptor
```

That PR also introduces two separate writeback files - the first only stores the client id, install time and the private key while the second stores that in addition to the other fields. If the primary file is corrupted the client will restore the values from the secondary file, if the secondary file is corrupted the client will restore the data from the server anyway but will keep the same client id.

**Comment by scudette** [comment]
Unfortunately this is a client side fix so will require pushing new clients. We can release a patch binary this week or wait for the next release depending how urgent this issue is for you.

**Comment by zaneGittins** [comment]
That's awesome, thank you!! I don't mind deploying new binaries if there is a patch.

**Comment by LPT6166676c** [comment]
Great thank you, what would be the time difference in getting a patch or waiting for the new release? Ideally for myself we are going through a roll out and the duplicate clients is causing some issues so the sooner the better would be amazing if possible.

**Comment by mcohen-r7** [comment]
Lets aim to get a patch out the end of this week?

**Comment by LPT6166676c** [comment]
That would be great if possible thank you very much

**Comment by LPT6166676c** [comment]
@mcohen-r7 was a patch released for this issue? having this issue on more than one server now
Thank you

**Comment by h-adwan** [comment]
I have this issue too, and i notice it is also filling the disk space on the server on /opt/clients folder
it will take a while to fill it, but eventually i had /opt/clients folder taking up to 29GB of space, had to delete it to restore operation on velo server
as it was not showing any info in the home page, also not been able to do hunts

just want to mention to notice for /opt/clients folder issue

**Comment by scudette** [comment]
This is likely because the new client ids will pick up any outstanding hunts and re-collect the same hunt under the new client id.

**Comment by scudette** [comment]
Please test the 0.7.0-3 release which should address this problem by making writeback manipulation more robust.

from the release notes:
> Release 0.7.0-3 is a bugfix release primarily for issue https://github.com/Velocidex/velociraptor/issues/2955 . If you are experiencing this issue (many duplicate clients) please test upgrading the clients to 0.7.0-3. This release also adds the ability for the writeback file to be stored in the registry instead of the filesystem on windows - simply modify the writeback_windows value in the config file to something that starts with HKLM (for example HKLM\SOFTWARE\Velocidex\Velociraptor ) this should improve stability in writing the writeback on the client and prevent potential writeback file corruptions which may have previously lead to clients recreating the writeback file with a new client id.

Additionally you can add a new value to the client config `Client.level2_writeback_suffix` (for example the value `l2`). This will create a second level 2 writeback file with a second copy of the client id (and keys). If either writeback files are corrupted the client will recover the client id from the backup file.

If you are upgrading an existing deployment I would suggest to set the `level2_writeback` value to e.g. l2 and not switch to registry based writeback yet. Switching to registry based writeback will recreate all client ids where continuing with file based writebacks will migrate to the level2 writeback if possible maintaining client ids.

Please provide feedback if this solves the issue you are seeing. If not we need to investigate further.

**Comment by zaneGittins** [comment]
Thanks! I am beginning to test 0.7.0-3, I added `level2_writeback_suffix: l2` to the Client section of the client.config.yaml but am not seeing a second writeback file yet on upgraded clients.

**Comment by zaneGittins** [comment]
I've only been running 0.7.0-3 for ~2days using the level2_writeback_suffix, but so far looking very promising. I haven't run into a duplicated client yet, even on systems that were experiencing heavy duplicates. I will update again once some more time has passed.

**Comment by LPT6166676c** [comment]
@zaneGittins I have a question for you if thats alright. How are you generating the new MSI once you have edited the client config? recently I have been using the server to do so but I am unsure how to do this with an edited client config, did you use wix to create the agent file? thank you

**Comment by scudette** [comment]
## Using the GUI

1. Edit your server.config.yaml to add the new option in the Client section.
2. Upgrade the server to 0.7.0-3 by creating a new deb and installing it
3. Collect Server.Utils.CreateMSI as described here https://docs.velociraptor.app/docs/deployment/clients/#official-release-msi

The new MSI will be created 

## Using the command line 

Update the client config yaml 

```
velociraptor-v0.7.0-3-windows-amd64.exe  config repack --msi velociraptor-v0.7.0-3-windows-amd64.msi client.config.yaml velociraptor-v0.7.0-3-repack.msi
```

**Comment by LPT6166676c** [comment]
Understood, thank you Mike will try this later today

**Comment by lnn2204** [comment]
Hi, looks like this issue also is going on Linux/MacOS, 
![image](https://github.com/Velocidex/velociraptor/assets/46069059/10ea33be-ffe7-40fd-a4a9-59c08995dcd8)

**Comment by scudette** [comment]
Did you verify that 0.7.0-3 fixes that issue?
