### ISSUE TITLE
API User Existence Discrepancy: Backend Records not Reflected

### ISSUE THREAD

**Issue by anmol1115** [Velocidex/velociraptor#2965]
### Issue
Im encountering difficulty in using the API. Using [this](https://docs.velociraptor.app/docs/server_automation/server_api/) documentation im able to generate a user and config yaml in backend, which I can confirm using the "acl show" command. But when I try this user config to make an api request I get "User not found" error

## Additional Notes
Earlier I had a version 0.6.8-2 setup of velociraptor, where when I used to create an API user from the backend it used to reflect on the web ui under the user tab, but that as well isnt working right now

**Comment by scudette** [comment]
Make sure you are running as the velociraptor user (with `sudo -u velociraptor bash`) when interacting with the server. Sometimes the created user records are created under the wrong user account. You can verify the permissions and ownerships of the user file and the acl files under `<filestore>/users/`
