### ISSUE TITLE
Config generator missing option to specify port for SSO

### ISSUE THREAD

**Issue by LordPhwa** [Velocidex/velociraptor#2976]
Hi, i was wondering if it was possible to specify a custom port for the frontend, and/or the gui when using sso.

In my case specifically, i wanted to host an on-prem instance, do oauth via azure, and also dont configure dns (even though that would be advantageous, yes) and instead go ip-based.

When going through the wizard, i wasnt asked which ports i would with the gui_port_question (https://github.com/Velocidex/velociraptor/blob/master/bin/config_interactive.go#L69), like as in https://github.com/Velocidex/velociraptor/blob/master/bin/config_interactive.go#L473C32-L473C32

I am not an expert in oauth, and am not quite sure if thats possible, but according to the [documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url) by microsoft it is definitely possible to have a port in the reply-url.

Again, im really sorry if my understanding is limited, and does not allow for that, but i also dont want to use 443 for my gui.
Also i dont seem to find out why i cant specify the port for the grpc api when going the sso route.

**Comment by scudette** [comment]
The config wizard is supposed to be easy to use for the most common use cases. Anything more sophisticated is supposed to be edited from the initial basic config that is produced. You can see a full reference of the config file here 

https://docs.velociraptor.app/docs/deployment/references/

You can change the ports for the GUI by editing the produced config file under GUI.bind_port
