### ISSUE TITLE
Restricting  GUI acecss

### ISSUE THREAD

**Issue by DM15-3T3RNAL** [Velocidex/velociraptor#2979]
Hi 
So i just deployed velociraptor using a domain name and Azure SSO
I was wondering how can i block public GUI access
I cannot simple block port 443 because as of my understanding, when using SSO (letsencrypt) agents will also use port 443.
Basically what i want is that you can only access the WebGUI if you are connected to company VPN
Any help would be much appreciated

Thanks

**Comment by scudette** [comment]
If you are using lets encrypt then the server must be listening on port 80 and 443 for cert renewal. In that case we automatically put the GUI (that connects to the admin console) **and** the frontend (that connects to the clients) on the same port 443.

As of release 0.7.0 you can additionally place an IP allow list on the GUI application using the following config variables
https://docs.velociraptor.app/docs/deployment/references/#GUI.allowed_cidr

This will block off access to the GUI handlers from those CIDR ranges you specify but will allow the frontend handlers to receive connections from all IP addresses (for client connections).
