### ISSUE TITLE
GUI bug while displaying file contents in 0.6.9

### ISSUE THREAD

**Issue by ydkhatri** [Velocidex/velociraptor#2997]
When viewing the output of a hunt such as _Windows.Search.FileFinder_ with upload file enabled, the correct files are identified and uploaded (confirmed via Download Results). However the GUI returns an error while displaying the last element/file.

The GUI error message is: 
<img width="537" alt="image" src="https://github.com/Velocidex/velociraptor/assets/13247440/66e4b729-cf04-4cbd-b90d-73b3b289c2fc">

The full error message copied out is:

> Error: open /opt/velociraptor/clients/**C.0410875d43f7e1e9**/collections/F.CKFN6MFD1N2U8.H/uploads/auto/C%3A/Users/xxxxxxxxxxxx/AppData/Local/Temppatient_hub/runtime-config.js: no such file or directory

It is trying to look for the correct file path, but in the wrong host (ClientId). See screenshot below, which shows that the correct host for that file would have been **C.598a12ff6579459e**.

![image](https://github.com/Velocidex/velociraptor/assets/13247440/603a75d3-d6e3-4a9e-a278-88aa544ff66b)

Velociraptor version = 0.6.9

**Comment by scudette** [comment]
Fixed by #3059
