### ISSUE TITLE
Feature request: improved object management in WebUI

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#30]
I would like to raise a feature request for object management workflow in the GUI

Im finding in my webUI workflow, there is lots of missed collections and other objects like machines or hunts I dont want hanging around longer term. I know I can clean these on the back end via cli but I would love the ability to do this in the GUI.

Some examples:
Write a bad VQL and deploy it. ABle to delete the hunt or collection flow fromt he GUI.
Remove machines from the GUI (and all their previous flows / downloaded data).

**Comment by scudette** [comment]
Fixed by #68
