### ISSUE TITLE
parse_csv() with separator=\x00 results in a the client spinning

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3000]
The following VQL makes velociraptor spin, outputting the error message "parse_csv: csv: invalid field or comment delimiter" continuously:

```
select * from parse_csv(filename='a', accessor='data', separator='\x00', columns=['a'])
```

`columns` is apparently important to trigger this issue. The input can be anything. The artifact timeout limitation does not appear to be honoured. The GUI says that the collection is aborted, but the console output and resources used (> 100 % CPU) suggests otherwise.

Tested in `velociraptor gui` version 0.7.0-2.

**Comment by scudette** [comment]
Fixed by #3058
