### ISSUE TITLE
Let split() optionally discard empty items

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3001]
split() splits a string into an array. Sometimes one wants to ignore the empty fields. Right now that requires additional processing every time split() is used. It would be nice if split() could have a function parameter that ignores empty parts, much like split() in some other libraries.

Example:

`split(sep_string=',', string='1,2,,3', skip_empty=true)` should return '[0: "1", 1: "2", 2: "3"]' and not '[0: "1", 1: "2", 2: "", 3: "3"]'

**Comment by scudette** [comment]
You can filter the list using the filter() function
```sql
SELECT filter(list=split(sep_string=',', string='1,2,,3'), regex=".+")
FROM scope()
```

**Comment by misje** [comment]
That is what I'm doing, but it feels cumbersome and reduces readability. Feel free to close the issue if you don't find it worthwhile.

**Comment by scudette** [comment]
It is better to leave functions short and concise with small number of args. I dont think this is a strong enough reason to introduce an additional parameter when the alternative is almost as short anyway.
