### ISSUE TITLE
CPU limit for offline collection does not seem to be working

### ISSUE THREAD

**Issue by NoelNW** [Velocidex/velociraptor#3002]
When creating an offline collector, inputting a CPU % limit does not seem to actually limit the CPU usage. I tested it on version 0.7.0, with CPU limits of 1%, 5% and 10%, the process for an offline collection of the KapeFiles.Targets artifact seems to hover around 40-60% for the entire duration of the collection.

In my use-case i'm trying to collect a custom artifact. This artifact can be limited as expected when executing it as a hunt. When i try to collect the same artifact using the offline collector the CPU usage hovers between 60-80% for the entire duration of the collect.

**Comment by scudette** [comment]
Fixed by: #3003

**Comment by DavidSanchezGracia** [comment]
Hi! 

It seems like in version 0.7.0-4 this continues to happens. I have created a series of offline collectors, limited to 15-20% CPU but are actually consuming all available resources on the host setting it to 100% CPU utilization.

Artifacts used:

- Windows.EventLogs.Evtx
- Windows.NTFS.MFT

Kind regards

**Comment by scudette** [comment]
this is what it looks like for me
![image](https://github.com/Velocidex/velociraptor/assets/3856546/be89f745-189d-447a-8486-8fd570ca1089)

As indicated above - this was fixed on Oct 7 which was after the release of 0.7.0 so it is in 0.7.1
https://github.com/Velocidex/velociraptor/pull/3003/commits/ac7e765e8fcab4fc72bf6dc00700496e7000e85d

**Comment by DavidSanchezGracia** [comment]
My fault, I thought I had updated the server but I actually didnt! 

Thank you a lot!
