### ISSUE TITLE
Built in support for Sigma 

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#3010]
We should support Sigma rules natively. It should be possible to apply Sigma rules to event plugins so we can write client monitoring queries with Sigma

**Comment by mgreen27** [comment]
logsource guide:  https://github.com/SigmaHQ/sigma/tree/master/documentation/logsource-guides

logsource in each rule: 
![image](https://github.com/Velocidex/velociraptor/assets/13081800/b3997c40-f7e8-4d0b-9b6f-114e433127b5)

**Comment by predictiple** [comment]
https://github.com/NextronSystems/thor-manual/blob/master/usage/custom-signatures.rst#sigma-rules

Florian Roth's THOR tool consumes Sigma format natively and is written in Go, but it's not open source AFAIK. However there might be some value in considering how they have implemented it (from a black box perspective).

**Comment by scudette** [comment]
The traditional sigma implementation is ok but I'm really looking to extending sigma to support more endpoint specific data sources. 

Traditional sigma works on the events from the event log and is primarily intended for siem systems. In that context it doesn't really add much value over eg eql IMHO. But I think there is an opportunity to extend sigma to support endpoint capabilities beyond just event logs.

**Comment by mgreen27** [comment]
That may have been true for the SIMGA ingesting tools that focus on EVTX but checkout the Aurora agent.
https://www.nextron-systems.com/aurora/

**Comment by predictiple** [comment]
Something like:

`SELECT * FROM Artifact.Windows.EventLogs.Evtx() WHERE sigma(rules=rules)`

Or, if you just want rules and don't need associated rule metadata:

`SELECT * FROM Artifact.Windows.EventLogs.Evtx() WHERE eql(rules=rules)`

The Sigma metadata is mostly about source targeting and enrichment (like for example having tags that could be attached to rule matches).

The meat in the Sigma rule container is in the Detections key. The rest is a really awkward and inflexible taxonomy that really isn't very well-defined beyond the Windows event logs category.

In my opinion the Endgame EQL rule container is much more pleasant, as is the rule syntax:
https://github.com/endgameinc/eqllib/blob/master/eqllib/analytics/credential-access/T1003-ntdsutil-dump-ntds.toml

**Comment by scudette** [comment]
Initial implementation here https://github.com/Velocidex/velociraptor/blob/3ab4ffaac894215f60b49003ee23f0a6c2f1fa13/artifacts/definitions/Windows/Sigma/EventLogs.yaml#L18

**Comment by scudette** [comment]
This is now implemented in the `Windows.Sigma.EventLogs` artifact
