### ISSUE TITLE
Issues with access GUI going through Application Load Balancer

### ISSUE THREAD

**Issue by dgilmore82** [Velocidex/velociraptor#3025]
Hello 

I was able to containerize Velociraptor so we can deploy it to an ECS cluster with an application load balancer. The first issue we ran into was a 400 error when we tried to access the GUI. After looking at the [proxy_header ](https://docs.velociraptor.app/docs/deployment/references/#:~:text=of%20the%20server.-,proxy_header,-X%2DForwarded%2DFor) parameter  I set the value to "X-REAL-IP" and "X-FORWARD-FOR". With both configuration we got a 502 error but in the logs I saw we were getting a TLS handshake error saying the client offered only unsupported versions. That's I came across this parameter  [allow_weak_tls_server](https://docs.velociraptor.app/docs/deployment/references/#:~:text=allow_weak_tls_server) assuming if it was set to false it would allow Velociraptor to talk to the ALB. I got the following error when i added it to my server config file and tried to deploy:

**field allow_weak_tls_server not found in type proto.ClientConfig**

Is there a way to access Velociraptor's GUI going through an Application Load  Balancer?

**Comment by scudette** [comment]
That error indicates that you placed the option in the client section of the config but if you look at the reference page you can see it needs to be in Client.Crypto section

How to you know that TLS is your issue? What is the error in the logs? You should go through the trouble shooting steps to understand what the server is actually seeing and any errors reported https://docs.velociraptor.app/docs/deployment/troubleshooting/

In particular you will see errors along the lines of TLS errors when the client attempt to connect.

If you are trying to do TLS offloading using the ALB then instructions are here https://docs.velociraptor.app/blog/2020/2020-09-28-velociraptor-network-communications-30568624043a/#ssl-offloading

**Comment by dgilmore82** [comment]
Setting the parameters _**use_plain_http: true**_ and _**use_self_signed_ssl: false**_, it allowed us to access the Velociraptor GUI. When we are using HTTPS for Velociraptor and the ALB to communicate with each other, this is the error messaged I get in the logs:

`[INFO] 2023-10-13T15:26:45Z http: TLS handshake error from {host}:{port}: tls: client offered only unsupported versions: [303 302 301]`

I tried to set do something like this in the client block but that wasn't correct:
![image](https://github.com/Velocidex/velociraptor/assets/104925486/7aa20ce5-0c63-4fe2-9499-405dbeadfc4c)

What is the correct syntax for the _**Crypto**_ parameter within the client block? Also, is this even the correct course of action to take based off of the TLS handshake error we are getting?

**Comment by scudette** [comment]
If you want to use older TLS versions you need to set that both in the server and the client config and restart the server.

**Comment by dgilmore82** [comment]
Ah understood. Could you let me know how to set the **_allow_weak_tls_server_** parameter? I keep getting errors when I tried to configure it.

**Comment by dgilmore82** [comment]
Could you let me know how to set the _**allow_weak_tls_server**_ parameter? I keep getting errors trying to set it.

**Comment by dgilmore82** [comment]
Also, is it even possible to have Velociraptor communicate with a ALB in AWS? It looks like it is failing the health check:

`Task failed ELB health checks in (target-group arn:aws:elasticloadbalancing:us-east-1:111111111111:targetgroup/aws-targetgroup/123456789)`

**Comment by scudette** [comment]
You need to configure the alb to call /healthz
