### ISSUE TITLE
Allow Enter to close the column regex text field

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3027]
![2023-10-14_14-25](https://github.com/Velocidex/velociraptor/assets/4006538/f9164132-c684-444d-ab4c-d1fa89b86967)

In order to perform the search with the regex filter in a column header, the filter button needs to be clicked. It is a bit frustrating that the Enter key cannot be used for this.

**Comment by scudette** [comment]
Fixed by #3087
