### ISSUE TITLE
GUI gets irresponsive 

### ISSUE THREAD

**Issue by DM15-3T3RNAL** [Velocidex/velociraptor#3031]
Hi
I facing a wierd issue
My GUI is working fine. I have enabled SSO with AZURE and everything works fine.
Now I wanted to write a script to use velociraptor API. I changed the 127.0.0.1 to 0.0.0.0 under the API section in the server.conf file.
As soon as i change the 127.0.0.1 to 0.0.0.0 the GUI is not responding anymore
I changed back the 0.0.0.0 to 127.0.0.1 and restarted the Velociraptor GUI and everything worked fine
Can you please help me with this issue

![image](https://github.com/Velocidex/velociraptor/assets/58237490/ddb8cf8e-9ce1-41b5-96c0-adb5f774f183)

**Comment by scudette** [comment]
Make sure you don't have iptable rules that block the API connections on the public interface

**Comment by DM15-3T3RNAL** [comment]
let me check with the network team

**Comment by DM15-3T3RNAL** [comment]
Hi,
Weird thing is that i can use API from command line as you can see

![image](https://github.com/Velocidex/velociraptor/assets/58237490/b886f9b5-40e0-4067-afa4-658828cab86b)


its the GUI which is timing out

![image](https://github.com/Velocidex/velociraptor/assets/58237490/5143cecb-3320-4db0-848f-2f81059b5fc7)

**Comment by scudette** [comment]
This is not likely to be an issue with Velociraptor - it is probably a networking issue.
