### ISSUE TITLE
Windows config generator log path has wrong slash

### ISSUE THREAD

**Issue by mpilking** [Velocidex/velociraptor#305]
When running `velociraptor-v0.4.1-windows-amd64.exe config generate -i` on Windows, the default log path has a forward slash before the logs directory rather than a backslash.  

![image](https://user-images.githubusercontent.com/5453480/78727254-bf4e7000-78f9-11ea-83e9-79d2aea97975.png)

![image](https://user-images.githubusercontent.com/5453480/78727310-eb69f100-78f9-11ea-97b5-b220cb67eab5.png)

Apparently it's only cosmetic though, because the server still launches and logs are created in the proper path:

![image](https://user-images.githubusercontent.com/5453480/78738302-20d10780-7917-11ea-8b3c-e4d188b6c555.png)

**Comment by scudette** [comment]
Yep - this is only cosmetic - Windows supports either forward or backward slashes in path names. It is only the cmd.exe shell that is annoying to use, even powershell supports both.

**Comment by mpilking** [comment]
Cool, I didn't realize that Powershell (and elsewhere in Windows) could use both slashes.  I'm just in the habit of always using backslashes.  I guess no fix needed.  Thanks for the knowledge :)

**Comment by scudette** [comment]
You can also use either separator in artifacts and elsewhere in the gui. Using forward slashes makes it easier to use because you do not need to quote escape the backslash:

```
SELECT FullPath from glob(globs='C:\\Windows\\System32\\**')
```
vs
```
SELECT FullPath from glob(globs='C:/Windows/System32/**')
```

The only place where you **MUST** use a backslash is in device names like VSC:
```
SELECT FullPath from glob(globs='\\.\C:\Windows/System32/**', accessor='ntfs')
```

**Comment by scudette** [comment]
Also running the server on windows is kind of supported in the sense that we will fix any bugs if they crop up but it is definitely not as well used or tested :-). YMMV

**Comment by mpilking** [comment]
> Also running the server on windows is kind of supported in the sense that we will fix any bugs if they crop up but it is definitely not as well used or tested :-). YMMV

Ok, good to know. I'm working on a single-host demo setup (and a student lab exercise) where the server and client are running together on a Windows VM.  I assume that should work fine (so far it is).   Thanks again.

**Comment by scudette** [comment]
Yep we use that setup for conference workshops etc - very easy to get setup and a good demo. I wouldn't run 10k hosts on it but it should be fine for a few :-).
