### ISSUE TITLE
GUI: Make it possible to append rows to csv-type artifact parameters

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3053]
![2023-10-26_11-47](https://github.com/Velocidex/velociraptor/assets/4006538/35554917-e702-4aad-9b47-70165fd46986)

Currently, there is no way to add a new line to the end of the table in an artifact parameter of type CSV. Pressing the plus button at the last entry inserts a new line before the last entry. Pressing the plus button at the header inserts a line at the beginning.

Suggestion: Make the button at the at the header append a new line. Pressing the plus button at the first line still inserts a line at the beginning.

Fixing this will make the table GUI a lot more user-friendly when order of lines actually matter. Especially because there is seemingly no way to append a row. The current workaround is cut-pasting entries every time when there is a need to add a row to the end.

**Comment by scudette** [comment]
Fixed by #3054
