### ISSUE TITLE
Windows.PersistenceSniper fatal error: out of memory

### ISSUE THREAD

**Issue by gdms04** [Velocidex/velociraptor#3080]
When I ran the collection "Windows.PersistenceSniper" downloaded from the below link in either offline/online mode, I encountered the following error:
https://docs.velociraptor.app/exchange/artifacts/pages/windows.persistencesniper/

![image](https://github.com/Velocidex/velociraptor/assets/47113752/dd0723a4-661f-415a-9d61-e8da4e36a1ed)

fatal error: out of memory

runtime stack:
runtime.throw({0x7ff7cf88929f?, 0xc27e3d9000?})
        /usr/local/go/src/runtime/panic.go:1047 +0x65 fp=0x3d405ff938 sp=0x3d405ff908 pc=0x7ff7cd7de865
runtime.sysUsedOS(0xc256782000, 0x2540c0000)
        /usr/local/go/src/runtime/mem_windows.go:83 +0x1c9 fp=0x3d405ff998 sp=0x3d405ff938 pc=0x7ff7cd7ba4a9

I tried to run the command and the script cached to the temp folder and it was successful.
![image](https://github.com/Velocidex/velociraptor/assets/47113752/ecf23553-cdd7-4ced-97a1-07e010ebe84b)

It means that the script itself is fine, wonder if what went wrong when velociraptor executed the exact same command and script. Thanks!

**Comment by scudette** [comment]
It looks like that artifact is piping the output of persistance sniper to memory and then attempting to parse it out of there. This will probably not work too well.

You can try to modify the artfact to write it to disk and parse it off disk instead

**Comment by FabFaeb** [comment]
I just created a PR that should fix this issue: https://github.com/Velocidex/velociraptor-docs/pull/758

**Comment by ablescia** [comment]
Dear @gdms04, you can fix the artifact by simply reduce the buffer dedicated to the stdout.

`SELECT Stdout FROM execve(argv=["Powershell", cmdline], length=10000000000)` to `SELECT Stdout FROM execve(argv=["Powershell", cmdline], length=104857600)`

In this way the vql will dedicate 100MB otherwise 10GB to the stdout that contains the PersistenceSniper output.

**Comment by mgreen27** [comment]
implemented @ablescia's fix here https://github.com/Velocidex/velociraptor-docs/pull/760

100MB is probabbly too big too but is much more reasonable than 10GB!

**Comment by scudette** [comment]
It's probably better to just write to a temporary file?

**Comment by scudette** [comment]
It looks like the output is passed to parse_json_array which will fail anyway if the size is exceeded because the Json array will not fit in the 10mb and when it gets truncated the Json will be invalid.

Perhaps the script can be changed to emit data in a better format like Jsonl?

**Comment by mgreen27** [comment]
I dont think the 10MB limitation will be a problem.

I can quickly modify FabFaeb's version to work and be better output. It writes to a temp file csv and then attempts to use parse_csv()

**Comment by ablescia** [comment]
Dear @scudette and @mgreen27, please see my implementation at [https://github.com/ablescia/Windows.PersistenceSniper/blob/main/Windows.PersistenceSniper.vql](https://github.com/ablescia/Windows.PersistenceSniper/blob/main/Windows.PersistenceSniper.vql). I have integrated the CSV temporary file writing feature and also added support for the 'DiffCSV' argument. This enhancement significantly reduces the number of false positives.

Finally, you can see that I have avoided calling PowerShell twice.

Best regards.

**Comment by mgreen27** [comment]
Cool that works - I will replace the current PR. Do you know if  adding a different csv path still works if someone puts a bad / null baseline csv.

**Comment by mgreen27** [comment]
just checking the code, I would consider using built in http_client() over powershell

**Comment by mgreen27** [comment]
name: Windows.PersistenceSniper
description: PersistenceSniper is a Powershell module that can be used by Blue Teams, Incident Responders and System Administrators to hunt persistences implanted in Windows machines. It is also available on Powershell Gallery and it is digitally signed with a valid code signing certificate. The tool is under active development with new releases coming out regularly, so make sure to use the up-to-date version. https://github.com/last-byte/PersistenceSniper

author: Chris Jones - CPIRT | FabFaeb | Antonio Blescia

parameters:
  - name: DiffCSVUrl
    default: https://raw.githubusercontent.com/ablescia/Windows.PersistenceSniper/main/false_positives.csv
    type: url

tools:
 - name: PSniper
   url: https://github.com/last-byte/PersistenceSniper/releases/download/v1.15.0/PersistenceSniper.zip
   
type: Client

precondition:
    SELECT OS From info() where OS = 'windows'

sources:
 - query: |
        LET TmpDir <= tempdir(remove_last='Y')
        LET Toolzip <= SELECT FullPath FROM Artifact.Generic.Utils.FetchBinary(ToolName="PSniper", IsExecutable=FALSE)
        
        LET _ <= SELECT copy(accessor='data',dest=TmpDir + "\\false_positives.csv",filename=utf16(string=Content)) FROM http_client(method='GET',url=DiffCSVUrl) 
        
        LET _ <= SELECT * FROM unzip(filename=Toolzip.FullPath, output_directory=TmpDir)
        
        LET PSniperLocation <= TmpDir + '\\PersistenceSniper\\PersistenceSniper.psm1'
        LET FalsePositivesFile <= TmpDir+"\\false_positives.csv"
        
        LET CSVFile <= TmpDir + '\\psniper_results.csv'
        
        LET cmdline <= 'import-module '+ '"' + PSniperLocation + '"'+ '; Find-AllPersistence -IncludeHighFalsePositivesChecks -DiffCSV ' + '"' + FalsePositivesFile +'"'+' | ConvertTo-CSV -NoTypeInformation | Out-File -encoding ASCII "' + CSVFile + '"'
        
        LET _ <= SELECT * FROM execve(argv=["powershell",
                "-ExecutionPolicy", "bypass", "-encodedCommand",  base64encode(string=utf16_encode(string=cmdline))
              ])
              
        SELECT * FROM parse_csv(filename=CSVFile)

**Comment by ablescia** [comment]
> https://raw.githubusercontent.com/ablescia/Windows.PersistenceSniper/main/false_positives.csv

PersistenceSniper will still function if you declare the -DiffCSV file, even when an empty DiffCSVUrl is passed.

**Comment by ablescia** [comment]
Dear @mgreen27, here is the updated version. This version does not include the '**encodedcommand**' and now features a variable to select the URL for the **DiffCSV** file. Additionally, it includes the '**IncludeHighFalsePositivesChecks**' argument:
```name: Windows.PersistenceSniper
description: PersistenceSniper is a Powershell module that can be used by Blue Teams, Incident Responders and System Administrators to hunt persistences implanted in Windows machines. It is also available on Powershell Gallery and it is digitally signed with a valid code signing certificate. The tool is under active development with new releases coming out regularly, so make sure to use the up-to-date version. https://github.com/last-byte/PersistenceSniper

author: Chris Jones - CPIRT | FabFaeb | Antonio Blescia

parameters:
  - name: DiffCSVUrl
    default: https://raw.githubusercontent.com/ablescia/Windows.PersistenceSniper/main/false_positives.csv
    type: url
  - name: IncludeHighFalsePositivesChecks
    default: true
    type: boolean

tools:
 - name: PSniper
   url: https://github.com/last-byte/PersistenceSniper/releases/download/v1.15.0/PersistenceSniper.zip
   
type: Client

precondition:
    SELECT OS From info() where OS = 'windows'

sources:
 - name: Result
   query: |
   
        LET TmpDir <= tempdir(remove_last='Y')
        LET Toolzip <= SELECT FullPath FROM Artifact.Generic.Utils.FetchBinary(ToolName="PSniper", IsExecutable=FALSE)
        
        LET _ <= SELECT copy(accessor='data',dest=TmpDir + "\\false_positives.csv",filename=utf16(string=Content)) FROM http_client(method='GET',url=DiffCSVUrl) 
        
        LET _ <= SELECT * FROM unzip(filename=Toolzip.FullPath, output_directory=TmpDir)
        
        LET PSniperLocation <= TmpDir + '\\PersistenceSniper\\PersistenceSniper.psm1'
        LET FalsePositivesFile <= TmpDir+"\\false_positives.csv"
        
        LET CSVFile <= TmpDir + '\\psniper_results.csv'
        LET arg_diffcsv <= if(condition= DiffCSVUrl!="", then=" -DiffCSV " + '"' + FalsePositivesFile +'"', else="")
        LET arg_includehighfalsepositiveschecks <= if(condition= IncludeHighFalsePositivesChecks, then=" -IncludeHighFalsePositivesChecks ", else="")

        LET cmdline <= 'import-module '+ '"' + PSniperLocation + '"'+ '; Find-AllPersistence'+ arg_includehighfalsepositiveschecks + arg_diffcsv + ' | ConvertTo-CSV -NoTypeInformation | Out-File -encoding ASCII "' + CSVFile + '"'
        
        LET _ <= SELECT * FROM execve(argv=["powershell",
                "-ExecutionPolicy", "bypass", "-command",  cmdline
              ])
              
        SELECT * FROM parse_csv(filename=CSVFile)
      
 ```

**Comment by ablescia** [comment]
Dear @mgreen27, I created a new pull request: [https://github.com/Velocidex/velociraptor-docs/pull/767](https://github.com/Velocidex/velociraptor-docs/pull/767)
