### ISSUE TITLE
Add a VQL plugin for ETW Rundowns

### ISSUE THREAD

**Issue by bmcder02** [Velocidex/velociraptor#3083]
Update the ETW library to allow for a plugin that queries the rundown of ETW providers. This would be a client plugin, as the rundown would allow for the immediate collection of data, and closure of the session/provider. This removes the requirement for ETW events to be collected through a CLIENT_EVENT artifact.

**Comment by scudette** [comment]
This is now available using either the stop or timeout parameters to watch_etw().
