### ISSUE TITLE
Link to flow results only returns flow list instead of specific flow results. 

### ISSUE THREAD

**Issue by casey-hillman** [Velocidex/velociraptor#3085]
After upgrading to 0.7.0-3 we are encountering an issue where links to flow results just bring up the flow list for the client and not the individual flow results. 

`https://example.domain.com/app/index.html#/collected/C.aa16e3a18c605ed2/F.CL51FFDC20OHQ` does not go to the flow results for F.CL51FFDC20OHQ but instead just shows the flow list for the client C.aa16e3a18c605ed2.

**Comment by scudette** [comment]
Fixed by #3087
