### ISSUE TITLE
Connectivity Issue

### ISSUE THREAD

**Issue by Sforse12** [Velocidex/velociraptor#3089]
i'm required for a course project to use your tool,
required to setup 3VMS 1 of them is the server where i installed Velociraptor
now i've done that and installed the Velociraptor and accessed gui successfuly in the server VM (Windows) and i specified the front end to be the the server machine ipv4 address in the local network which is 192.168.1.41:8000, now i imported the client file from the server fm to the client VM and changed its name to Velociraptor.config.client and started the MSI, service is running successfuly but the in the GUI there is no conneted user, when monitoring the Velociraptor frontend -v CMD in the server vm  i dont see any connection attempt what so ever, keep in mind that i can ping the server vm from my client vm, which means every vm has it's own ipv4 inside the network and is reachable inside local network never the less the client did not dynamically connect or even tried to initiate a connection.

Please Do Help if you know how to resolve this issue.

**Comment by Sforse12** [comment]
i used self signed cert, iv'e been trying everything i can do just to connect the client vm to the server vm but could not.

**Comment by scudette** [comment]
https://docs.velociraptor.app/docs/deployment/troubleshooting/

Verify you have network comms with curl and that no local firewall is enabled.

**Comment by Sforse12** [comment]
Now i've got a tls handshake error tls: unknown cert
