### ISSUE TITLE
Blockwise yara plugin behavior yields unexpected results with no error messages

### ISSUE THREAD

**Issue by chris-coalitionir** [Velocidex/velociraptor#3094]
The [yara plugin](https://docs.velociraptor.app/vql_reference/plugin/yara/) supports accessor-based processing of remote files, processing files in user-specified `blocksize` chunks.  The notion of an offset within a file, used in various yara rules such as `at` and `in`, doesn't function as expected, as follows:

**zero-offset conditions repeat every block.**  this is most easily reproducible by searching for a negation of a file-header match using `not` or `!=`. 

something like `condition: uint32(0) != 0x04034b50` (looking for files that aren't zips) produces one result _per block_ rather than one result _per file_.  so in the case of a 500 megabyte zip file, the first 1mb block would not hit, but then you'd get ~499 "successful hits" showing no `PK` header at the beginning of each 1mb block of the file (for the vast majority of the blocks where you don't coincidentally align with such a pattern, of course).  this is true regardless of the `number` parameter.  this may be the intended behavior, but if so it's highly counterintuitive and i'd recommend clearly documenting this quirk. this repetition probably repeats with any sub-blocksize offset, though I didn't test that.

incidentally, this repetition continues for the whole file, even if larger than 100mb.  I couldn't actually see in the source where, if anywhere, the `end` parameter is set to the 100mb default noted in the docs, but even if it is, that processing limit is bypassed by this blockwise offset reset.

it may also be that larger-than-blocksize offsets are simply not supported when doing blockwise processing, in which case it'd be good to get an informative error or warning to that effect. this is tricky, though, as the mmap version could fail for whatever reason and still default you back to blockwise: https://github.com/Velocidex/velociraptor/blob/d96afd20412a51b7e406ef67b35364694e070433/vql/common/yara.go#L172-L175

seems like you could carry the latest offsets through, even streamwise, but that's beyond my ken.  hope this is clear enough - if it's user error, happy to hear about it.  thanks!

_reproduced on version 0.7.0-2, server running on ubuntu, hitting clients on various flavors of windows._

**Comment by scudette** [comment]
This is a limitation of the yara library as there is no way to tell it that a block starts at  particular offset. Likely such yara rules are broken and should not be written in this way as they fail block wise scanning.

For the "file" accessor we call the yara plugin with the path of the actual file and this causes it to open the file by itself. So in that case the offset conditions work as expected.

The yara library does not currently have an abstraction that allows us to pass a reader to it so it can treat the entire virtualized file so there is nothing we can do from our end.

i would say that yara rules that look at offsets are probably best to be used with the "file" accessor or not at all. Usually these rules are just looking at headers for magic detection which we can do anyway in VQL so the rules can be easily refactored.

This behavior is already documented here https://docs.velociraptor.app/docs/forensic/searching/ so there is not much for us to do in this issue.
