### ISSUE TITLE
slowing problem

### ISSUE THREAD

**Issue by Cri01IT** [Velocidex/velociraptor#3102]
hello, 
i have some issues on velociraptor.
sometimes i have to run a server artifact that is supposed to collect logs from all the computers that i have registered; it worked fine until 2 month ago (i don't remember wich version of velociraptor i had), when the artifact started not working; for example if there are 100 computers and i start the artifact it goes fine until the first 12, 15, 20 or sometimes more, like 40 pc but every time it stops before the finish, with the error "Query timed out after 600 seconds".
i also noticed a general slowing, running normal client artifacts, so i thought that the two issues can be related.

**Comment by scudette** [comment]
Can you share the artifact? you can increase the timeout when you launch the artifact. 

If you suspect some regression bugs can you please collect a server profile during the time the artifact is running?  For the server collect Server.Monitor.Profile and share it here

https://docs.velociraptor.app/knowledge_base/tips/debugging_clients/

**Comment by Cri01IT** [comment]
Here is the artifact:
```yaml 
name: Custom.Windows.Veeam.Dashboard
description: |
   Analyses last backup log result on clients online in last 5 mins
   and returns a result for ALL clients

type: SERVER

required_permissions:
  - EXECVE
 
sources:
  - query: |
      SELECT * 
      FROM foreach(
        row={
            SELECT 
                client_id, 
                os_info.hostname as host,
                now() - last_seen_at / 1000000 as LastSeen
            FROM clients(search="label:veeam")
            WHERE LastSeen<300  -- clients online in last 5 mins
        },
        query={
            SELECT 
                EventTime,
                Computer,
                EventID,
                EventRecordID,
                Message,
                Source,
                client_id, 
                host,
                if( condition={SELECT Message FROM scope() WHERE Message=~'Success'},
                    then=if(condition={SELECT Elapsed FROM scope() WHERE Elapsed>5}, 
                            then="OLD BACKUP", 
                            else="OK"
                         ), 
                    else="ERROR!"
                ) AS Result
                
            FROM Artifact.Server.Utils.CollectClient(
                ArtifactName='Custom.Windows.Veeam.LastResult',
                Client=client_id)
        })
```
Here is Server.Monitor.Profile result:
[query_1.json](https://github.com/Velocidex/velociraptor/files/13378034/query_1.json)

**Comment by Cri01IT** [comment]
how can i add a sleep in my code? (i tried sleep(15) in every part of the query but the program doesn't let me save because says that is wrong)

**Comment by scudette** [comment]
you can add sleep with an additional WHERE clause:

```sql
WHERE sleep(time=1)
```
will sleep one second between rows.

**Comment by Cri01IT** [comment]
i added: 

async=TRUE,
workers=100

at the end of my query and now it seems is working correctly

**Comment by scudette** [comment]
Sorry I missed you were calling Server.Utils.CollectClient - that artifact waits for the entire collection to finish before returning so if you run it in serial and there is one slow client it can hold up everyone.

While running it in parallel is a possibility - it is really easier to schedule it in a hunt - the collections will all be scheduled asynchronously and results will be combined at a later stage.
