### ISSUE TITLE
remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by NOULeENGINEER** [Velocidex/velociraptor#3103]
I have configured a velociraptor server V0.7.4, generated a client config file for MSI and I get this error.

**Comment by scudette** [comment]
Where do you get this error? what error is it? did you go through the troubleshooting steps?

https://docs.velociraptor.app/docs/deployment/troubleshooting/

**Comment by NOULeENGINEER** [comment]
Hi @scudette 
thank you for your response,
I have noticed the issue when I installed the MSI package and didn't find any host in the GUI dashboard. 
the message, I found in the logs VelociraptorFrontend_info.log 
the certificate is the same for both configuration files, 
I have noticed that the SSL handshake is not complete when I captured the traffic to the fronted port.

**Comment by scudette** [comment]
Please follow the troubleshooting steps and post here the results of curl -v etc

**Comment by NOULeENGINEER** [comment]
I tried to curl https://x.x.x.x:8000/server.pem it has no response, any idea how to reconfigure it? the private key and the CA certificate are still in the server.config.yaml

**Comment by scudette** [comment]
If there is no response it means your firewall is blocking access to that port. Use the -v flag to curl to get more information

**Comment by NOULeENGINEER** [comment]
I was troubleshooting the issue and I have disabled the firewall in a time, but it wasn't working. I'm sure that firewall rules have access to the specific port, I have seen some SYN flags from the client IP to the server in the packet capture. meanwhile, this is the output of the command 
curl -v https://57.128.197.92:8001/server.pem | openssl x509
 -text -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying X.X.X.X:8001...
* Connected to x.x.x.x(57.128.197.92) port 8001 (#0)
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [88 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [223 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
{ [81 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [873 bytes data]
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

**Comment by NOULeENGINEER** [comment]
I was troubleshooting the issue and I have disabled the firewall in a time, but it wasn't working. I'm sure that firewall rules have access to the specific port, I have seen some SYN flags from the client IP to the server in the packet capture. meanwhile, this is the output of the command
curl -v https://X.X.X.X:8001/server.pem | openssl x509
-text
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Trying X.X.X.X:8001...

Connected to x.x.x.x(X.X.X.X) port 8001 (#0)
ALPN: offers h2,http/1.1
} [5 bytes data]
TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
{ [5 bytes data]
TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [88 bytes data]
TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [223 bytes data]
TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
TLSv1.3 (IN), TLS handshake, Request CERT (13):
{ [81 bytes data]
TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [873 bytes data]
TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
SSL certificate problem: unable to get local issuer certificate
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

**Comment by scudette** [comment]
If you use self signed SSL then you need to provide curl with the -k flag to ignore cert checking.

**Comment by NOULeENGINEER** [comment]
eventually it is showing Could not read certificate from <stdin>Unable to load certificate
please find the full output. 


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying X.X.X.X:8001...
* Connected to X.X.X.X (X.X.X.X) port 8001 (#0)
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [88 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [223 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
{ [81 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [873 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
} [8 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: O=Velociraptor; CN=VelociraptorServer
*  start date: Nov 15 00:31:56 2023 GMT
*  expire date: Nov 14 00:31:56 2024 GMT
*  issuer: O=Velociraptor CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
} [5 bytes data]
* using HTTP/2
* getpeername() failed with errno 107: Transport endpoint is not connected
* getpeername() failed with errno 107: Transport endpoint is not connected
* h2h3 [:method: GET]
* h2h3 [:path: /server.pem]
* h2h3 [:scheme: https]
* h2h3 [:authority: X.X.X.X:8001]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x557130bc9fc0)
} [5 bytes data]
* Send failure: Broken pipe
* OpenSSL SSL_write: Broken pipe, errno 32
* Failed sending HTTP request
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host X.X.X.X left intact
curl: (55) getpeername() failed with errno 107: Transport endpoint is not connected
Could not read certificate from <stdin>
Unable to load certificate

**Comment by NOULeENGINEER** [comment]
is there any way to disable SSL for frontend ? any specific command ?

**Comment by scudette** [comment]
Why would you want to do that? You can disable it if you have a tls stripping load balancer in front of it.

It is very strange that you are trying to connect to port 8001 which by default is the API port . Did you change the ports around from the default configuration? Usually the clients connect on port 8000 with self signed configuration and browser over port 8889.

Can you please confirm your ports and URLs are as configured in the client's config `Client.server_urls` section

**Comment by NOULeENGINEER** [comment]
yes I can confirm that the ip, the protocol and the port are the same in the client configuration generated from the server configuration file. I have changed the port from 8000 to 8001. do you think that this is the issue ? I don't have any component in front of it. but maybe do you have any solution for the error that I have shared earlier about the Server.pem file ?

**Comment by scudette** [comment]
Did you also move the API service off of that port to another port?

**Comment by scudette** [comment]
The client does not connect to the API port. Can you run the server with the -v flag and look for these messages
```
[INFO] 2023-11-16T06:49:43Z Starting gRPC API server on 0.0.0.0:8001  
[INFO] 2023-11-16T06:49:43Z Launched Prometheus monitoring server on 127.0.0.1:8003  
[INFO] 2023-11-16T06:49:43Z GUI is ready to handle TLS requests on https://192.168.1.11:8889/ 
[INFO] 2023-11-16T06:49:43Z Frontend is ready to handle client TLS requests at https://192.168.1.11:8000/ 
```

Make sure the ports that it reports listening on are what is expected

**Comment by NOULeENGINEER** [comment]
seems like the issue is resolved when I changed some configuration ports, I can see the the dashboard of Currently Connected Clients went up from 0 to 2, but host information button is disabled in the GUI

**Comment by scudette** [comment]
That button is only enabled once you search and select a client to interact with.

**Comment by NOULeENGINEER** [comment]
perfect, thank you for your support!

**Comment by NOULeENGINEER** [comment]
This issue is resolved
