### ISSUE TITLE
Yara Scanning Physical Drives

### ISSUE THREAD

**Issue by WD-ST** [Velocidex/velociraptor#3105]
Good Afternoon, 

I was wondering, at the moment our artifacts have the drive letters statically set in the artifact, for example

`FROM parse_mft(
 accessor="ntfs",
 filename="C:\\$MFT")`

`LET Root = pathspec(parse="C:", path_type="ntfs")`

Is there way to get the collector to identify physical drives (not network shares) and scan them all, rather than needing multiple artifacts to ensure we scan all the drives?

Thanks

**Comment by mgreen27** [comment]
Check Windows.ntfs.mft AllDrives switch - you should be able to copy this.

I think I added Alldrives to this after I wrote the yara.ntfs artifact.

**Comment by WD-ST** [comment]
Thanks I will have a look

**Comment by WD-ST** [comment]
Thanks I will have a look
