### ISSUE TITLE
User settings are reset when visiting client shell in the GUI

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3107]
When visiting the shell tab in the client web UI, the user settings are sometimes reset. This is obvious if the theme is set to anything but the default, but all the settings are lost / reset to the defaults, including timezone and editor settings. The user.json.db file is probably corrupted and recreated.

I haven't been able to find reproducible steps, and the issue also occurs when visiting other pages in the web interface. It appears that accessing the client shell page triggers this most often.

**Comment by scudette** [comment]
This is fixed by #3117
