### ISSUE TITLE
First test, can't create hunt, CSRF error

### ISSUE THREAD

**Issue by johnpathe** [Velocidex/velociraptor#311]
Hi,
First time Velociraptor user.
Tested it on work environment, standalone on win server 2012
followed this guide:
https://www.velocidex.com/docs/getting-started/stand_alone/

Some bumps during config generation and client install but generally easy enough.
used the MSI to install the client

While trying to create my first - to enumerate chrome extensions, i click next a few times and I get a CSRF token invalid error at the point of trying to submit the request to create the hunt.

I tried to debug a little and noticed the CSRF token being submitted was different to the one initially in 127.0.0.1:8889/app.html#/hunts

I might try and older release or on a Linux device next.

I hope this helps.

-John

**Comment by scudette** [comment]
Make sure to refresh your browser each time the server is restarted. When the server starts it picks a token and the browser must return that token on each request - this is how CSRF protection works.
If you restart your server you need to fully refresh the browser - CSRF protection only applied to POST and not GET messages so it would appear to work for some things but then fail when you do a POST.

**Comment by johnpathe** [comment]
Thanks for the quick response.

I re-started chrome and I still get the issue. Restarted the server and chrome again, same issue.
Also getting 'error undefined' in a few places in the GUI.
also in the console (started server with verbose flag) we see a lot of this, every few seconds.
'
[INFO] 2020-04-16T09:34:50+10:00 Fetching http://127.0.0.1:8003/metrics
[INFO] 2020-04-16T09:34:50+10:00 count: Field X should be a float not {}.
'

What debug information could I provide that might help?

I noticed client version downgrades are not allowed so maybe trying a linux server might be the next step

**Comment by scudette** [comment]
You can open the chrome dev tools (ctrl-shift I)  or from the menu then look at the network tab and see what errors are returned from the server.

**Comment by scudette** [comment]
If you are running the server on windows make sure you allow it to serve with the windows firewall too. Sometimes it does not popup the gui to allow you to open the firewall up but it still block it.

**Comment by johnpathe** [comment]
More csrf issues noticed on our other windows SOE builds. We are looking to try again on Red Hat. closing issue as I wont be investigating further at this stage.

I'm thinking there is some sort of group policy or other rule in our SOE builds which impacts upon Velociraptor POST requests.
