### ISSUE TITLE
Exporting notebook fails: unknown field "TableOptions"

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3114]
Version 0.7.1-rc1. Steps to reproduce:

1. Create a notebook.
2. Copy cell from a flow notebook, in this case Sigma.Windows.Hayabusa.Rules to the notebook created above
3. Export notebook to HTML

This results in 'proto: (line 1:91): unknown field "TableOptions"' for the Rules cell.

**Comment by misje** [comment]
This happens to all cells in notebooks that include tables. Works in 0.7.0-3.

**Comment by scudette** [comment]
Just having trouble to replicate this issue... Can you please ensure your browser cache is flushed? You can do this by opening the developer tools from the chrome menu then select the network tab and check the disable cache then hit reload.

![image](https://github.com/Velocidex/velociraptor/assets/3856546/81909da5-851a-4d3e-9a41-fc9408454b9e)

![image](https://github.com/Velocidex/velociraptor/assets/3856546/a386a265-ff55-4d0b-bb44-1f6f367617d2)

![image](https://github.com/Velocidex/velociraptor/assets/3856546/3bf0e30b-9104-469b-b31a-8f693bd1ec25)

**Comment by scudette** [comment]
Oh ok i think I see what you mean - you are referring to the output inside the actual HTML that is produced.

**Comment by scudette** [comment]
Fixed by #3117
