### ISSUE TITLE
Add an optional description to a collection to help identify why it was initiated

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3130]
In a deployment where velociraptor is very often used to run single-client collections (i.e. not just hunts), it is challenging to remember why a particular collection was run. Especially if it completes days later, and even more so if it was a custom VQL/Powershell/Bash artifact (the Artifact name alone is not useful). This becomes even more challenging if the collection was initiated by another user.

I would really like to be able to fill out a text field when creating the collection that is used to describe the purpose of the collection. This would fit nicely in a column like a recent flow overview like this:

```SQL
LET ColumnTypes = dict(`Client`='url', `Flow`='url')

SELECT *
FROM foreach(
  row={
    SELECT client_id,
           client_info(client_id=client_id).os_info.hostname AS Hostname
    FROM clients()
  },
  query={
    SELECT format(format='[%v](index.html#/host/%v)', args=[Hostname, client_id]) AS Client,
           format(format='[%v](index.html#/collected/%v/%v)', args=[session_id, client_id, session_id]) AS Flow,
           timestamp(epoch=create_time) AS Created,
           timestamp(epoch=active_time) AS LastActive,
           state AS State,
           artifacts_with_results
    FROM flows(client_id=client_id)
    WHERE NOT session_id =~ '.H$'
    ORDER BY Created DESC
    LIMIT 5
  })
  ORDER BY Created DESC
  LIMIT 50
  ```

An external incident response case management tool would obviously help tying collections/flows to cases, but if this relationship isn't created immediately, the context is lost. And not all collections necessarily have a case. A small note part of the flow would really help. In hunts the description is essential to help understand why it was created. Hunts are not suitable for targeted, single-client collections.

I imagine that this description would be returned by `flows()` and can be stored server-side only.

**Comment by scudette** [comment]
This is kind of what 0.7.1 tries to do with the new notebook focus. The workflow is that the global notebook is used to coordinate/plan an incident. When a user manually created a collection from the client, they can go to the notebook tab, update the description there then simply copy into the relevant global notebook - even if the collection is not done yet the description and query will still be copied.

Then the user can look at the global notebook for the full context, hit refresh on the cell to get new data when the collection is done etc.

**Comment by misje** [comment]
I've been playing with the new notebook features, but thanks for pointing out that workflow. I've been mostly testing it for creating templates that I use after running a collection, in which case I miss parameters or tools to help me populate the template or import data. – A workflow reverse to what you described.

I'll see if doing things the intended way helps me.

By the way, is it a completely bonkers idea to have parameters in a notebook that replaces placeholders or fills in variables? That would instantiate an incident template much quicker.

**Comment by scudette** [comment]
We already do this in the template in many places:
```sql
LET Foo = "XXX"
```

And then the user can just set those when editing the notebook.

Internally notebooks actually already have an Environment (and therefore also variables just like artifacts) but we just dont have the GUI to surface those as a form yet. I was planning on this GUI to appear at some point as well.

**Comment by misje** [comment]
The template instantiation UI looks just like the hunt/collection UI, just without parameters, that's why I was wondering. Having variable placeholders in the template is a very unproblematic workaround.

**Comment by scudette** [comment]
Yes we could reuse the same UI for that step but we also need to add a UI for when the cell is recalculated - because often we want to change some things before recalculating the cell.

I am in two minds about it - on the one hand a UI helps to get parameters in the right form (because we can enforce a type) but on the other hand having the parameters in the cell VQL is more obvious to what is happening. For example right now there are Env variables for ClientId, HuntId, FlowId etc but they are invisible and people just need to know they exist.

If we have a UI that shows the form with variable then maybe these can be more discoverable. Also if we change the VQL in the cell to have the declarations as above this might be even more discoverable. 

Maybe the best solution is to use both - have the GUI emit the VQL statements into the cell based on the UI form so users can use the form or the cell interchangeably.
