### ISSUE TITLE
Clients not erroring out properly

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#3131]
On 0.7.0-4, I have some flows that are still marked as running, but the logs say that they're timed out of concurrency control.

![image](https://github.com/Velocidex/velociraptor/assets/1241363/83080900-dcb6-4151-891b-4a35a4a993e3)
![image](https://github.com/Velocidex/velociraptor/assets/1241363/8813e374-e39e-474d-a8ad-6aa25cd87091)

Although from this is looks like they never started.
![image](https://github.com/Velocidex/velociraptor/assets/1241363/0e480b36-90ad-4e4b-a3a5-c777b2334e39)

**Comment by bmcder02** [comment]
Hey @randomaccess3 , 

Just to reiterate our private chat, really appreciate you submitting this issue. I'll close the ticket, as you mentioned this server is no longer available. 

We these kind of client side issues, it can be really useful if client side logging can be collected. This can be done in one of two ways: 

1. Collecting a profile from the client using an urgent priority should give a nice snapshot of what's happening at the time. This will hopefully help us narrow down if it's a client side issue or if it's having trouble getting back to the server. https://docs.velociraptor.app/knowledge_base/tips/debugging_clients/

2. Alternatively, as of 0.7.1, we now have client side logging. If your team is willing to enable this, even at just 50mb, this will give us really good context of what's happening when the client is just sitting there. https://docs.velociraptor.app/blog/2023/2023-11-15-release-notes-0.7.1/#local-encrypted-storage-for-clients

If you encounter this again in the future, please make another ticket with the client side logging. 

Thanks again!
