### ISSUE TITLE
Feature Request: Addition of Server/Client Monitoring State VQL plugins

### ISSUE THREAD

**Issue by mlucas300** [Velocidex/velociraptor#314]
It would be useful for me if we could have VQL plugins added that provide functionality equivalent to the following API messages:

    GetServerMonitoringState
    SetServerMonitoringState
    GetClientMonitoringState
    SetClientMonitoringState

This would allow me to everything that I require using the Query message for the API.

Thanks,
Martin.

**Comment by scudette** [comment]
Just pushed #316 , please test with the latest CI build.

**Comment by mlucas300** [comment]
Tested and confirmed to be working as expected. Thanks for implementing it so quickly :-)
