### ISSUE TITLE
Generic.Forensic.SQLiteHunter problem with parsing Firefox data

### ISSUE THREAD

**Issue by sec-hbaer** [Velocidex/velociraptor#3144]
while playing with the artifact "Generic.Forensic.SQLiteHunter", I noticed that no data for "places" (the sqlite database containing much of the browsing information for firefox) was outputed.

While testing, I stumbled over following messages in the Velo log:
`{"_ts":1701769628,"client_time":1701769628,"level":"DEFAULT","message":"Starting collection of Generic.Forensic.SQLiteHunter/Firefox Places_History\n"}
{"_ts":1701769628,"client_time":1701769628,"level":"DEFAULT","message":"sql: no such column: moz_places.types\n"}`

I investigated the sqlite database "places.sqlite" on my Windows machine. Following layout is given for the table "moz_places":
![image](https://github.com/Velocidex/velociraptor/assets/150132280/6738c895-f731-4b58-aab2-2f00901e135e)
As visible, there is no column "types", but a column "typed".

As a quick check, I changed the velo artifact to use use "moz_places.typed". The modified artifact now returns data from the "places" sqlite database.

I am unsure, where the difference between the database on my system and the settings in the velo artifact comes from.
Furthermore, I do not know, which side effects come from my change in the velo artifact (e. g. if other parts or following code have to be changed too).

Tested with `velociraptor-v0.7.1-rc1-windows-amd64.exe` on Windows 10.0.19043 Build 19043 against Firefox 120.0.1 (64-bit)

**Comment by scudette** [comment]
Thanks for spotting this typo. This should now be fixed in the latest
