### ISSUE TITLE
Small error in blog post (acl ALL_QUERY should be ANY_QUERY)

### ISSUE THREAD

**Issue by PeterWagenaarNW** [Velocidex/velociraptor#315]
[This]()https://www.velocidex.com/blog/medium/2020-03-06-velociraptor-post-processing-with-jupyter-notebook-and-pandas-8a344d05ee8c/) blog post shows a screenshot of someone granting the API user the "ALL_QUERY" permission, which from the error I get in jupyter should be "ANY_QUERY".

**Comment by scudette** [comment]
Thanks for noticing! At the time the post was written, the permission model was not developed - it was either ALL_QUERY or nothing :-). Since 0.4.1 this needs to be ANY_QUERY.

I will revise that post ...

**Comment by scudette** [comment]
Permissions are now done through roles anyway - so you need to provide the api role.
