### ISSUE TITLE
Add follow symlinks to MacOS glob

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#3170]
It looks like there may be issues with the MacOS client using glob() in some conditions.

I have tried to glob the path `/var/protected/xprotect/*` which has (-rw------- permissions) as part of extracting the XProtect database and looks like it returns 0 rows.

Interestingly stat() works targeting a file directly.
Full Disk Access appears to be enabled.

This issue impacts my ability to collect this artifact in a bulk collection tool I use which relies on glob(). FileFinder and any other artifacts tha leverages glob to enumerate target files will likley also be impacted (probabbly most of them).

![image](https://github.com/Velocidex/velociraptor/assets/13081800/f6b1f2c6-3924-4482-b4de-b860dcebcb94)
![image](https://github.com/Velocidex/velociraptor/assets/13081800/4f01a346-bc2b-49ff-ba1d-a1a7975e4bd7)

**Comment by scudette** [comment]
For safety `glob()` does not follow symlinks. On my system /var -> private/var so you need to glob `/private/var/protected/xprotect/*`

Following symlinks is dangerous because we can end up in a cycle and it is difficult to detect that.

**Comment by mgreen27** [comment]
I think we need to fix the MacOS.Search.FileFinder.
This fails on both selecting this tickbox and unselecting which was my validation.

**Comment by scudette** [comment]
Fixed by #3173
