### ISSUE TITLE
import_collection() does not add entry to the flow_index when a collection for a client already exists. 

### ISSUE THREAD

**Issue by BowenMarmot** [Velocidex/velociraptor#3192]
I am updating all our offline collectors and trying out the import_collection() functionality.   If I import and provide an existing client_id, the import_collection() succeeds but the resulting collection never appears under the existing client in the gui.  I can still get to the data if I use the source() function in VQL in a notebook but must recreate each of the artifacts in the collection. 

When I review the datastore of my velociraptor instance, I see that all the directories and files for the imported collection exist under the client directory ( ..\velociraptor\clients\C.<EXISTINGCLIENTID>) but the flow_index.json file is not updated.  If I manually add an entry to the flow_index.json with the flow id, it shows up in the GUI under that client.  

If the import _collection is run without an existing client_id to generate a new client, the flow_index.json file for that new client is created with the correct entry and the import shows up under the new client in the gui.  

This behaviour is the same, not surprisingly, if I manually create VQL and call import_collection(), or if I use the Server.Utils.ImportCollection artifact. 

This is all done with a local install of version 0.7.1 on Windows 10.

**Comment by BowenMarmot** [comment]
Clarification after further testing.  The failure occurs when the client already has a collection associated with it.   If there is no collection associated with a client (such as when a new client is created during the import) the display of the collection succeeds. 

After a failed import, if the existing collection is deleted, the "failed" collection shows up.  I can only assume that the "flow_index" is recalculated during a delete.

**Comment by 0xDeadcell** [comment]
Any updates on this?

**Comment by scudette** [comment]
I verified this bug - It occurs because the flows index is not being updated which the flow is written to the data store.
