### ISSUE TITLE
Offline collector creation fails with Windows Sigma rules

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3194]
With the Windows Sigma rules artifact the CreateCollector flow completes immediately without errors but does not produce the repacked executable.

![Screenshot from 2023-12-29 17-08-12](https://github.com/Velocidex/velociraptor/assets/9843422/e9055f4d-b7e9-4803-8916-94dfbd433928)

![Screenshot from 2023-12-29 16-48-52](https://github.com/Velocidex/velociraptor/assets/9843422/d1e25b02-2e52-4c8c-872b-fb6298fcf7b4)

By contrast, creating an offline collector with the Linux Sigma rules (which are much smaller) succeeds as expected.

version: 0.7.1-1
commit: 2d7d6cf
build_time: "2023-12-27T09:46:06Z"
ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/7337099705
compiler: go1.21.5

**Comment by scudette** [comment]
We probably don't want to increase the embedding size too large.

 It should work with the generic collector option and we can make the generic collector as large as we want.

Maybe we just need an error message here to indicate that the generic collector should be used

**Comment by predictiple** [comment]
I'm not sure if it is hitting the embedding size limit although it does seem likely. If it is then shouldn't we be triggering this error:
https://github.com/Velocidex/velociraptor/blob/e8ba235fc97e44d44d86b3f85924292c3d377c09/vql/tools/repack.go#L130

I agree about not increasing the embedding size and the generic collector option is a reasonable workaround. The issue is really that the artifact run appears to have succeeded when it has actually failed without errors.

**Comment by predictiple** [comment]
Unfortunately the generic collector option also applies a size limit and therefore does not generate any output.
