### ISSUE TITLE
duplicate mac addresses in v0.7.1

### ISSUE THREAD

**Issue by pmoody-** [Velocidex/velociraptor#3199]
I just upgraded the server and the fleet from v0.7.0-2 to v0.7.1

server

```
[
  {
    "Version": {
      "name": "velociraptor",
      "version": "0.7.1",
      "commit": "0746831",
      "build_time": "2023-12-13T10:45:43Z",
      "ci_build_url": "https://github.com/Velocidex/velociraptor/actions/runs/7194076107",
      "compiler": "go1.21.4"
    }
  }
]
```

sample client

Agent Version: 0.7.1

![Screenshot 2024-01-04 at 16 05 49](https://github.com/Velocidex/velociraptor/assets/6351633/90314ff2-e460-4aa9-831e-7d993548f9ae)

```
$ cat ~/tmp/foo | sort | wc -l
     280
$ cat ~/tmp/foo | sort | uniq | wc -l
      14
```

note, if I hit 'interrogate' on the host in the ui, the server de-duplicates the mac addresses. but this doesn't appear to be happening automatically.

**Comment by scudette** [comment]
This seems like a very old bug we had a lot time ago. Can you verify that the server itself is also running version 0.7.1?

**Comment by pmoody-** [comment]
this was a freshly upgraded server. the backing ebs was all created by 0.7.0-2, but it's running 0.7.1 now.

```
[
  {
    "Version": {
      "name": "velociraptor",
      "version": "0.7.1",
      "commit": "0746831",
      "build_time": "2023-12-13T10:45:43Z",
      "ci_build_url": "https://github.com/Velocidex/velociraptor/actions/runs/7194076107",
      "compiler": "go1.21.4"
    }
  }
]
```

**Comment by pmoody-** [comment]
running generic.client.info hunt looks to have fixed it. thanks!
