### ISSUE TITLE
Can't create or view notebooks ("no workers available")

### ISSUE THREAD

**Issue by chris-coalitionir** [Velocidex/velociraptor#3201]
This intermittent, but we've reproduced it on both Linux and Windows Velociraptor servers, and with both an installed server and running _ad hoc_ with `velociraptor gui`:

One scenario is to attempt to create a notebook in the notebooks section.  On submission, you see this error, presumably generated [here](https://github.com/Velocidex/velociraptor/blob/e8ba235fc97e44d44d86b3f85924292c3d377c09/services/scheduler/scheduler.go#L152):

<img width="323" alt="image" src="https://github.com/Velocidex/velociraptor/assets/83465802/9713b478-aa92-4979-a193-79877ab91728">

This will also happen when clicking to the Notebook tab of a collected artifact or hunt.  It does not happen all the time.  A reload of the page does not address the issue. 

Restarting the server _will_ allow you to create a new notebook on the notebooks tab, but interestingly: all the failed creations tried when there were no workers will then show up in the UI, but _without any actual notebook content_:

<img width="277" alt="image" src="https://github.com/Velocidex/velociraptor/assets/83465802/54a1e777-acf3-4a0e-91a2-71c5548e1b45">

For each of these, if you click them, you get a blank placeholder:

<img width="453" alt="image" src="https://github.com/Velocidex/velociraptor/assets/83465802/e6e2a527-07ee-4a4d-854a-95260d0f4e12">

This is also true if you got the error when trying to view a notebook inside the collected artifact UI: if you got the no workers available error, you can no longer view the notebook for that artifact.  That is, the error is weirdly persistent.

Reproduced in v0.7.1 - attempting to re-create in v0.7.1.1-1, but not clear how to force the issue except to wait. Apologies if this is fixed in that version, it wasn't clear in the release notes and I didn't see a matching issue, so thought I'd risk a duplicate! Thanks so much.

**Comment by scudette** [comment]
You can increase the number of workers available if you need it. 

Also you can run the profile artifact to see what workrs are actually doing and how many are available

You can also run with the --debug flag and point your browser to port 6060 to see all the debug info about workers

**Comment by chris-coalitionir** [comment]
Thank you for the context and workaround, sir - is there a recommended worker count to provision, a safe number that could avoid this while it's being looked at?  It shows up even with a single user on a local `velociraptor gui` instance, not under any particularly large workload, so it'd be good to know a better default for all our updated servers.

This is significant for us in that 1) it's new behavior: we'd never run into the need to tweak worker numbers (or even really be aware of them as an implementation detail), and 2) it leaves a persistent impact: if you don't know what's happening, you can click to various collection and hunt notebooks and all of them will then show blank perpetually, which can wipe out important analytical work.  I'm not sure if the edits are actually lost, or if it's just a UI issue, but the practical effect is the same.

Our preference would be for gracefully degraded performance and a possible solution in the error message, rather than failing in this persistent way.

Thanks again for your responsiveness, as always, please let me know if there's anything else I can provide to clarify or help diagnose.

**Comment by scudette** [comment]
Can you help by shedding light on what the workers are actually doing? - by default we have 5 workers available so we dont expect to run out usually.

Workers typically just calculate the VQL cell and then go back to the pool so the limitation of number of workers is used to ensure server stability. You can check this dynamically by starting the server with --debug flag. This will start the local debug server. You can then see real time information about different aspects

![image](https://github.com/Velocidex/velociraptor/assets/3856546/75fa7650-2f1c-40f6-8525-34c2f63467e7)

In this example I write  query that would take a long time into the cell `SELECT sleep(time=1000) FROM scope()` you can see that worker is busy running that query but the other workers are free

![image](https://github.com/Velocidex/velociraptor/assets/3856546/1c642647-d5cb-475f-a51b-90f5a6b35b55)

You can also sort and filter this view in the GUI.

**Comment by casey-hillman** [comment]
We are encountering this issue as well after upgrading to 0.7.1-1 . Never had any issues before. Will try to look at the debug data and see what we can find.

**Comment by scudette** [comment]
You can increase the number of workers as needed https://docs.velociraptor.app/docs/deployment/references/#defaults.notebook_number_of_local_workers

**Comment by scudette** [comment]
I managed to replicate using this query:

```sql
SELECT sleep(time=1), now() AS Now
FROM range(end=10)
```

Hitting refresh and waiting a few sec then clicking cancel will leave an orphaned worker in the busy state. After a few times workers will be exhausted.

I think the bug was  that the worker was not properly returned to the pool if the query was cancelled (or maybe due to timeout as well).

**Comment by scudette** [comment]
This should be fixed with 0.7.1-2 which is out now - feel free to reopen this issue if you still find issues with 0.7.1-2
