### ISSUE TITLE
Unknown parameter TemporaryOnly provided to artifact Generic.Utils.FetchBinary

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3202]
The TemporaryOnly parameter makes sense for connected clients when you want to ensure that certain tools don't lay around cached on the endpoint. However artifacts that use Generic.Utils.FetchBinary with this parameter fail when used in offline collector mode.

The error is:
`Unknown parameter TemporaryOnly provided to artifact Generic.Utils.FetchBinary`
and then
`shell: exec: "Null": executable file not found in %PATH%`

TemporaryOnly parameter is not needed for offline clients because they don't cache their tools but that means maintaining an alternative "offline version" of any artifact which does need to use it.

Tested with:
version: 0.7.1-1
commit: 2d7d6cf
Server Ubuntu 22.04 and Windows 11 amd64 client.

**Comment by predictiple** [comment]
Same issue with the Version parameter:
`Unknown parameter Version provided to artifact Generic.Utils.FetchBinary`

**Comment by scudette** [comment]
Fixed by #3209
