### ISSUE TITLE
Exceptionally high storage used by monitoring_logs for Windows.Sysinternals.SysmonLogForward if watch_etw session fails on client

### ISSUE THREAD

**Issue by rob-wilco** [Velocidex/velociraptor#3206]
Issue Summary:

Under specific conditions, a Velociraptor client running Windows with Windows.Sysinternals.SysmonLogForward enabled may encounter a situation where an excessive amount of logs, amounting to many gigabytes (50GB+ a day in some cases), is generated on the Velociraptor Server file system. In cases where the ETW provider cannot be successfully added to the Velociraptor session, the system will make further attempts to perform the action. If these attempts persistently fail, it results in the creation of a substantial log on the Velociraptor Server file system.

Path: clients/_ClientID_/monitoring_logs/Windows.Sysinternals.SysmonLogForward/_date_.json

Example Log Entries:

{"client_time":1704499195,"level":"DEFAULT","message":"watch_etw: ETW session interrupted, will retry again.\n"}

{"client_time":1704294102,"level":"DEFAULT","message":"etw: Can not add provider to session Velociraptor: EVENT_CONTROL_CODE_ENABLE_PROVIDER failed; Insufficient system resources exist to complete the requested service.\n"}

![Screenshot 2024-01-09 at 09 14 57](https://github.com/Velocidex/velociraptor/assets/140673290/3b365734-3ca7-4bea-b684-c7916d81397a)

**Comment by mgreen27** [comment]
thank you @rob-wilco can you share what version  both the impacted clients and server is?

@bmcder02 added ETW Multiplexing in 0.7.1 and wondering what your running/if there is a version mismatch.
https://docs.velociraptor.app/blog/2023/2023-11-15-release-notes-0.7.1/#etw-multiplexing

**Comment by rob-wilco** [comment]
0.7.1-1 on both client and server in each observed case.

**Comment by bmcder02** [comment]
Okay, we might have to put a sleep in before the retries and maybe quit after a dozen tries. If it hasn't made a session by then, it probably won't ever. 

I'd be interested to see what is causing the insufficient resources that you can't create a session though. I'm wondering if that's caused because the max etw sessions was hit, or another reason. Is this only happening on a single host in your network?

**Comment by rob-wilco** [comment]
> Okay, we might have to put a sleep in before the retries and maybe quit after a dozen tries. If it hasn't made a session by then, it probably won't ever.
> 
> I'd be interested to see what is causing the insufficient resources that you can't create a session though. I'm wondering if that's caused because the max etw sessions was hit, or another reason. Is this only happening on a single host in your network?

This has happened on 4 systems in total out of about 4,000. The pattern I can find so far is that each system has had an uptime of greater than one month, some had Windows updates pending.

**Comment by scudette** [comment]
Fixed by #3207
