### ISSUE TITLE
Regression in offline collection with upload

### ISSUE THREAD

**Issue by heck-gd** [Velocidex/velociraptor#3222]
We're using Velociraptor as an offline collector with automatic upload to WebDAV.

The query roughly looks like this (`webdav_url` and `filename` are parameters defined beforehand - an example value for `filename` would be `Collection.zip`):
```
SELECT upload_webdav(file=Container, url=webdav_url, name=filename) AS Uploaded FROM collect(....., output=filename)
```

In 0.6.8, the `file` parameter was changed to be of type `OSPath`. However, `Container` returned by `collect()` is just a copy of the filename string given as input. This leads to Velociraptor now treating the filename as device path, i.e. `\\.\namehere`, which obviously won't work.

We'd still like to be able to place the collection in the current working dir without having to come up with an absolute path beforehand. This feels like a bug since it's an undocumented breaking change for existing queries/artifacts, but if there's a way to construct an `OSPath` relative to CWD, that'd be workable - skimming the docs, I couldn't find an obvious way to do so.

**Comment by scudette** [comment]
I dont think we support upload to webdav out of the box? Did you customize this artifact ? Perhaps we should add webdav as another upload method 

As you can see the other uploaders are working the same way https://github.com/Velocidex/velociraptor/blob/8471312a434dff5f4505b26d310c03fd12c0bbc2/artifacts/definitions/Server/Utils/CreateCollector.yaml#L309

I am not sure why the filename input to the collect() plugin will be an NTFS style path ? It is normally a file path on the disk so it should be e.g. `c:\Windows\Temp\XXX.zip`

**Comment by heck-gd** [comment]
You can find the webdav functionality here: https://github.com/Velocidex/velociraptor/blob/master/vql/tools/webdav_upload.go
I contributed it 4 years ago.

The input to `collect()` is not an NTFS style path. It's a plain relative filename so that the collection is stored next to Velociraptor's binary. What breaks is the automatic conversion to OSPath (it was changed in 49c8ad82924d8e755ee30c2a7f47ee8d8876b90c). The accessor assumes that a path with one component [must be a device path](https://github.com/Velocidex/velociraptor/blob/99b00b1d63effb230da9657e97cc07f0b065fba5/accessors/file/os_windows.go#L283) and prepends `\\.\`.

We explicitly would not like to store the collection in a Temp dir or similar.

**Comment by scudette** [comment]
This is maybe the issue - we never use relative paths because they are unpredictable - it really depends where the user started the program from (they could download it and start it from anywhere and the current working directory could be anywhere including the windows directory - which happens for elevated cmd shell - so we dont want to start writing on random directories)

Therefore it we just do not support parsing relative paths at all - we always use absolute paths.

If you really wanted to use the current working directory for something you could do something like this to get a relative path:

```
LET Info <= SELECT * FROM info()

SELECT pathspec(parse=Info[0].CWD, path_type=Info[0].OS) + "Foobar"
FROM scope()
```

**Comment by heck-gd** [comment]
Thanks Mike, that's what I was looking for. Works like a charm.
