### ISSUE TITLE
Issue running proc_yara() plugin in 0.7.1

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#3225]
Im getting a repeatable exception running proc_yara() plugin in 0.7.1.

![image](https://github.com/Velocidex/velociraptor/assets/13081800/64513c3e-aa77-4204-9271-a8c47baf716f)

replicate with in artifact or notebook: `SELECT * FROM proc_yara(pid=TargetPid,rules=YaraRule)`

Im testing this plugin as the standard yara(accessor='process'...) is causing some false negatives in some advanced rules due to block scanning and I want to test this older plugin performs as expected. We can then update Windows.Detection.Yara.Process and other artifacts as needed.

**Comment by mgreen27** [comment]
This issue appears to be resolved in https://github.com/Velocidex/velociraptor/pull/3226
Will keep the issue open until I update Windows.Detection.Yara.Process

**Comment by mgreen27** [comment]
Windows.Detection.Yara.Process - https://github.com/Velocidex/velociraptor/pull/3233

Testing proc_yara under linux seems to error out with: `proc_yara: pid 0: could not attach to process`

**Comment by scudette** [comment]
That is expected there is no pid 0

**Comment by mgreen27** [comment]
I thought this may be a generic error  in linux as I specified a pid (and a name regex).

**Comment by scudette** [comment]
This works for me
```diff
--- a/artifacts/definitions/Linux/Detection/Yara/Process.yaml
+++ b/artifacts/definitions/Linux/Detection/Yara/Process.yaml
@@ -92,13 +92,13 @@ sources:
                     file='String.Data',
                     name=format(format="%v-%v_%v_%v",
                     args=[ ProcessName, Pid, String.Offset, ContextBytes ]
                         )) as HitContext
-             FROM yara(files=format(format="/%d", args=Pid),
-                       accessor='process',rules=yara_rules,
+             FROM proc_yara(pid=Pid,
+                       rules=yara_rules,
                        context=ContextBytes, number=NumberOfHits )
           })

```

Write `secret` in vi and check the pid

```
velociraptor-v0.7.1-1-linux-amd64 -v artifacts collect Linux.Detection.Yara.Process --args PidRegex=3145944 --args YaraRule="ascii wide: secret"
```

**Comment by mgreen27** [comment]
this makes sense as in my artifact I was running int(int=Pid) - if this has failed it would explain why the 0 was being scanned.

**Comment by scudette** [comment]
Interesting - running explain on the query shows
```
[DEBUG] 2024-01-22T06:29:47Z   arg parsing: &functions.IntArgs{Int: int32(3145944)}
```
So maybe int() function is not handling int32 properly

**Comment by mgreen27** [comment]
Confirmed working in head release - thank you!
