### ISSUE TITLE
FR: proc_yara() for MacOS

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#3239]
MacOS process scanning can be a bit hit and miss but it is probably worthwhile to look at this capability to round out our coverage.

Yara itself allows for scanning of a pid in MacOS although there is some limitations on access.

**Comment by scudette** [comment]
We also need to implement a process accessor for MacOS to make this work. The yara code is a good guide of the APIs needed

**Comment by scudette** [comment]
Fixed by #3312
