### ISSUE TITLE
Possible bug in the glob plugin related to its handling of short name representations

### ISSUE THREAD

**Issue by ablescia** [Velocidex/velociraptor#3241]
Dear Velociraptor Team,

I attempted to utilize the glob plugin by setting the 'globs' argument to point to the temporary directory declared with the 'tempdir' function.
I believe there is an issue with the path that uses the '\~' character in the long name convention.

Please analyze the following VQL query:
```vql
LET TmpDir <= tempdir(remove_last=true)
LET WithoutTempDir = Select OSPath FROM glob(
  globs=['C:\\Users\\**\\AppData\\Local\\Temp\\gui_datastore\\temp\\*\\Assessor\\reports\\*.html'])
LET WithTempDir = Select OSPath FROM glob(
  globs=[TmpDir + '\\Assessor\\reports\\*.html'])
  
SELECT TmpDir, WithoutTempDir, WithTempDir from scope()
```
That returns the following results set:
![image](https://github.com/Velocidex/velociraptor/assets/90195154/5e814354-e1fa-401f-a12b-3f47cada55f8)

As you can see, the 'TmpDir' variable includes the '\~' character in the username string, specifically as **AUTHOR\~1**.
When I use the glob plugin with the 'TmpDir' variable, I do not receive any entries. 

Could this be a bug? If not, how can I point to a path that contains the short folders/filenames standard?

Thanks.

**Comment by scudette** [comment]
This is what the root parameter to the glob() plugin is for. The root path is interpreted literally so glob character dont mean anything in it.

**Comment by ablescia** [comment]
I will try it, thanks!
