### ISSUE TITLE
Add labels during installation

### ISSUE THREAD

**Issue by 0x6a0x6f0x6e0x610x730x640x6c0x6d** [Velocidex/velociraptor#3245]
I would be nice if you could add custom tags or labels to a host during the installation of the MSI, like with the installatiof of Rapid7 Agent.
Something like `msiexec /i velociraptor.msi CUSTOMATTRIBUTES="Windows,Server2022,TestServer,TeamNaam" /quiet`. During the installation this labels will be added to the client in Velociraptor Web GUI. Later you can use these labels to start a hunt.

**Comment by scudette** [comment]
You can include labels in the config file that you can repack into the MSI 
https://docs.velociraptor.app/docs/gui/clients/#built-in-labels
