### ISSUE TITLE
OIDC Authenticator missing forward-proxy configuration

### ISSUE THREAD

**Issue by Niicolaa** [Velocidex/velociraptor#3265]
There is no is specific option to configure a forward-proxy for the oidc authenticator configuration.

It seems that the https://github.com/Velocidex/velociraptor/blob/master/docs/references/server.config.yaml#L558 configuration doesn't work, thus I added it as "Environment" Var in the systemd service config.. It works like this, but (if possible) I'd like to use the standard systemd service config which gets generated by the velociraptor server command. 

Input from Mike Cohen (scudette) from Discord:
i think the issue is that we dont even configure the http connection when we call into the oidc library
so an env var works because it affects all http connections but we dont configure the oidc library specifically

**Comment by scudette** [comment]
This should be fixed with 0.7.1-2 which is out now
