### ISSUE TITLE
Add option in humanize function to convert to kiB, MiB, GiB instead of kB, MB, GB

### ISSUE THREAD

**Issue by cybiosity-syn** [Velocidex/velociraptor#3266]
The `humanize` function converts bytes to **kB, MB, GB**, etc... which are the number of bytes divided by 1000 (a certain number of times).

It would be cool if there was a parameter to the `humanize` function to convert to **kiB, MiB, GiB** instead (divided by 1024 a certain number of times).

**Comment by scudette** [comment]
This is already available since today I submitted #3258 

https://github.com/Velocidex/velociraptor/blob/4a705e2bf87974b299eff44b5c0e004ec92bcf3f/vql/functions/humanize.go#L32
