### ISSUE TITLE
Better alerting on timeout of prepare download

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#3275]
It would be great if there was better visibility in the "Available downloads" section when something timed out when zipping. 

It's not something that happens often, but when it does, someone will absolutely miss this - it would be good if it said "600 (Request timeout) etc like it does for other times a timeout occurs.
![image](https://github.com/Velocidex/velociraptor/assets/1241363/013ac387-bb98-4bac-b5de-b39c9c5d9f41)

Extending the timeout in the config is a workaround at least :)

**Comment by scudette** [comment]
Fixed by #3315
