### ISSUE TITLE
path_join does not clean result

### ISSUE THREAD

**Issue by djoreilly** [Velocidex/velociraptor#3278]
I have a couple of problems with linux paths when trying to use the audit plugin

1. `path_join(components=["/tmp", "../tmp"], path_type="linux")` returns `/tmp/tmp` and not `/tmp`
2. functions like hash don't work when there are `..` in the path, e.g. `hash(path="/tmp/../tmp/test")` tries to work on `/tmp/tmp/test` and not `/tmp/test`

It would be nice if path_join cleaned the result like [filepath.Join](https://pkg.go.dev/path/filepath#Join) 

```
# auditctl -w /tmp -pw -k vrr_tmp

LET audit_events = SELECT
	*,
	if(condition=File.Path=~"^/", then=File.Path,
	   else=path_join(components=[Process.CWD, File.Path], path_type="linux")) AS FullPath
  FROM audit()
  WHERE "vrr_tmp" IN Tags

SELECT File.Path, Process.CWD, FullPath, hash(path=FullPath).SHA1 AS SHA1 FROM audit_events


# touch /tmp/test1
 {
  "File.Path": "/tmp/test1",
  "Process.CWD": "/root",
  "FullPath": "/tmp/test1",
  "SHA1": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
 }

# cd /tmp; touch test2
 {
  "File.Path": "test2",
  "Process.CWD": "/tmp",
  "FullPath": "/tmp/test2",
  "SHA1": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
 }

 # cd /tmp; touch ./test3
 {
  "File.Path": "./test3",
  "Process.CWD": "/tmp",
  "FullPath": "/tmp/test3",
  "SHA1": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
 }

# cd /root; touch /tmp/../tmp/test4
 {
  "File.Path": "/tmp/../tmp/test4",
  "Process.CWD": "/root",
  "FullPath": "/tmp/../tmp/test4",
  "SHA1": null
 }

# cd /root; touch ../tmp/test5
 {
  "File.Path": "../tmp/test5",
  "Process.CWD": "/root",
  "FullPath": "/root/tmp/test5",
  "SHA1": null
 }
```

**Comment by scudette** [comment]
Note that paths in Velociraptor are handled extremely accurately and conservatively. We do not support .. directory traversal at all.

See this https://docs.velociraptor.app/blog/2022/2022-03-21-paths/ to understand how paths are handled.

**Comment by djoreilly** [comment]
Okay thanks. I found VQL has a `relpath` function which calls https://pkg.go.dev/path/filepath#Rel which cleans the result. I was able to use it to create a `clean_path` function to solve the problem of paths with `..` coming from the audit plugin.

LET clean_path(path) = "/" + relpath(path=path, base="/")
