### ISSUE TITLE
I can't create "large" offline collectors

### ISSUE THREAD

**Issue by dinosaurlover12** [Velocidex/velociraptor#3283]
I tried creating an offline collector using 20 artifacts, and it didn't create it, I had to mix&match artifacts and split it into 5 different collectors in order to make it work
I saw someone already encountered this problem, and apparently its a problem with the config file?

![image](https://github.com/Velocidex/velociraptor/assets/153808011/aa0ceb56-367a-4ebf-8bd0-edc188ed861d)

so maybe removing the config file limit will fix the situation, this process is tedious to go through every time I want to create an offline collector

**Comment by predictiple** [comment]
This was fixed by #3209 

If you need it urgently you can get the binaries from the CI pipeline or compile from source.

**Comment by scudette** [comment]
This should be fixed with 0.7.1-2 which is out now
