### ISSUE TITLE
adding product and fileversion to windows binaries as part of the build

### ISSUE THREAD

**Issue by ghals13** [Velocidex/velociraptor#3352]
at the moment they're hardcoded to v0.0.0.0 for FileVersion and ProductVersion is not at all set. 
It would be helpful if it was set to reflect the actual version as could be useful for inventory or detection rule purposes and upgrades in deployment 

While you can query msi product ids [different each release] or get product by name for installed apps and then query version but it can be a bit of a pain compared to the service exe. 

![image (15)](https://github.com/Velocidex/velociraptor/assets/158580423/459c5db9-044d-47cd-b998-4fd79b9c9a34)
![image (16)](https://github.com/Velocidex/velociraptor/assets/158580423/87578c07-d14c-44c1-9d4d-977437c344e5)

**Comment by scudette** [comment]
Fixed by #3353
