### ISSUE TITLE
Unable to fetch a file via "Collect from the Client"

### ISSUE THREAD

**Issue by denizciftci-sec** [Velocidex/velociraptor#3363]
Hi Team,

As I have upgraded from 0.6.9 to 0.7.1 version, I am not able to click "Collect from the Client" icon for any file in File Sytsem.
Simply the button is irresponsive and I have tested the fetch different files from Windows and Linux clients.
Is there a workaround for that? I already upgraded client agent version to 0.7.1 ( the same version as server) and restart/stopped/started services couple of times. 
I am not sure how to generate error logs for debugging?

+ Tried Export VFS Files > but it only fetches the metadata information of the files. The real files are not downloaded.
+ Tried different browsers - did not help
+ Update > I upgraded the server to newest pre-release 0.72 and able to fetch the files from a client which 0.7.1 agent is running. Still I am not able to get any files from clients which has 0.6.9 installed.

**Comment by scudette** [comment]
Cant reproduce. Please reopen if needed.
