### ISSUE TITLE
GUI does not display anything when click `Modify Hunt` without selecting a `Hunt ID`

### ISSUE THREAD

**Issue by fukusuket** [Velocidex/velociraptor#3369]
Hello :)
I would like to report a minor issue I found on the `Hunt Manager`.

**Describe the issue**
Nothing is displayed on the screen when click `Modify Hunt` without selecting a `Hunt ID`.

**Step to Reproduce**
1. Download Release 0.72 RC1 (or 0.7.1) 
2. `./velociraptor-v0.72-rc1-darwin-arm64 gui`
3. Click `Hunt Manager` -> `Modify Hunt`
<img width="700" alt="スクリーンショット 2024-03-24 15 45 55" src="https://github.com/Velocidex/velociraptor/assets/41001169/96eb6cfa-681a-4507-b8b6-e016354d37fa">

**Expected behavior**
GUI remains displayed.

**Actual behavior**
The following screen is displayed.
<img width="1440" alt="スクリーンショット 2024-03-24 15 47 40" src="https://github.com/Velocidex/velociraptor/assets/41001169/c75edff5-e7f7-48ab-8d30-d5989f5cf276">

**Environment**
- OS(Server): Ubuntu 22.04 LTS
- Velociraptor: 0.72 RC1 / 0.7.1
- Google Chrome: 123.0.6312.59（Official Build） （arm64）

**Additional information**
I confirmed that this issue occurs in both versions 0.72.0 RC1 and 0.7.1.

Thank you for your time.

**Comment by scudette** [comment]
Fixed by #3370 - modify button is disabled unless a hunt is selected.
