### ISSUE TITLE
The time string in the dashboard remains unaffected by changes in time zones.

### ISSUE THREAD

**Issue by Dev0ke** [Velocidex/velociraptor#3374]
**Describe the issue**
The time string in the dashboard remains unaffected by changes in time zones.

**Version**
Latestd build from [Linux Build Musl Static](https://github.com/Velocidex/velociraptor/actions/runs/8413816164).

**Step to Reproduce**
1. Run command `./velociraptor-v0.72-rc1-linux-amd64-musl gui`
2. Open the dashboard `https://127.0.0.1:8889/app/index.html#/dashboard`
3. Change `Display timezone` in `User Setting` to any other.
![image](https://github.com/Velocidex/velociraptor/assets/59955386/9f96161a-87ec-4882-8d72-a98e638198df)

**Result**
- Before change
![image](https://github.com/Velocidex/velociraptor/assets/59955386/5e82a538-82cc-42e5-8fde-96ba30df0945)

- After change
![image](https://github.com/Velocidex/velociraptor/assets/59955386/a50f9ee5-8a8b-456a-bbd4-ae80c73f3b53)

**Comment by scudette** [comment]
Fixec by #3375
