### ISSUE TITLE
No Filesystem access

### ISSUE THREAD

**Issue by RSOCKS** [Velocidex/velociraptor#3378]
Hello!

I am running 0.7.0-4, server on Ubuntu and 0.7.0-4 client on a Windows domain controller.

I am connected to the endpoint.  I can run shell commands.  No hunts will function, it's as if the server cannot see the file system.  I am connected to another endpoint within the same network with full visibility and hunt functionality.  

I've uninstalled and re-installed via a repackaged .msi file with the custom client.config.yaml.

I've also executed velociraptor via the command line '--config client.config.yaml client', we receive a connection but again, no filesystem visibility.

I looked through previous issues, I didn't see one that matches this scenario.

Thanks for your help!

**Comment by predictiple** [comment]
Try adding `-v` to your client (admin privilege) command line. Keep an eye out for any warnings or errors, especially when you try the next step...

Then on the server try to browse the client's filesystem in the VFS browser view. This will create collections associated with the System.VFS.ListDirectory artifact and you can see these in the client's Collections view. If you select one and then go to it's Log tab you can review the log for any issues.

If no issues are evident from the above steps then you can follow the guide here to collect more detailed diagnostic data: https://docs.velociraptor.app/docs/deployment/troubleshooting/#debugging-a-remote-client

**Comment by scudette** [comment]
Can not replicate - closing
