### ISSUE TITLE
Escaped quotes is causing problems with Windows.System.CmdShell

### ISSUE THREAD

**Issue by mpilking** [Velocidex/velociraptor#339]
On Windows clients, I'm unable to list paths with spaces using Windows.System.CmdShell artifact, and with the interactive shell too, which appears to behave the same way.

Please see the following 2 screenshots showing the issue.  I think the simple solution is to force the user to add the backslash escapes when necessary and we just document it appropriately.  

1st attempt without quotes on the path is problematic for the `dir` command:

![image](https://user-images.githubusercontent.com/5453480/80718814-3c67a200-8ac0-11ea-952e-cc0c496729cd.png)

2nd attempt with including quotes on the path.  I believe this would work as expected if the backslashes were not automatically included.

![image](https://user-images.githubusercontent.com/5453480/80718829-412c5600-8ac0-11ea-82e3-16c955b32141.png)

**Comment by scudette** [comment]
Sadly cmd.exe has some very interesting quote escaping rules - you actually need to escape it 3 times inside a string (quotes are escaped with quotes not backslash):

![image](https://user-images.githubusercontent.com/3856546/80726534-dd4d7000-8b47-11ea-9083-2a6cf75dadab.png)

I would suggest to just use the powershell variant - Powershell seems to have more sane string escape semantics and also you can use forward slash (so you dont have to worry about escaping). Finally with the powershell artifact we encode the command in base64 so really do not need to worry about escaping anything.

![image](https://user-images.githubusercontent.com/3856546/80726768-2dc4cd80-8b48-11ea-80db-3f6c6ba254e4.png)
![image](https://user-images.githubusercontent.com/3856546/80726803-3c12e980-8b48-11ea-8abd-fe1475090257.png)

**Comment by mpilking** [comment]
Good idea on Powershell for the artifact.  It even works for the interactive shell:

![image](https://user-images.githubusercontent.com/5453480/80731535-adaf5100-8ad0-11ea-8dfe-ed2804cea78b.png)

However, back to the cmd option, I think the problem is that Velociraptor is forcing the addition of the backslash escape.  So even with the triple quotes, it's still fails because each quote gets escaped and that doesn't work with cmd.  What if you just disabled the auto-escape and left it up to the user?

![image](https://user-images.githubusercontent.com/5453480/80731766-f535dd00-8ad0-11ea-82b9-d565ddc7b144.png)

**Comment by scudette** [comment]
We actually dont do any escaping at all we rely on the underlying Go language to build the command line - you can read more about the problem here https://github.com/golang/go/issues/15566 . The main issue is that unlike Unix, processes on windows do not receive an array of arguments, but a single text command line. So every program on windows does its own splitting of the command line into arguments and cmd.exe does its own thing which is inconsistent with the standard c library (on windows). So it is difficult to know how to build such a command line reliably for all potential edge cases.

cmd.exe command line parsing is a complete mess and has been for decades - it is best to just avoid it altogether.  You can choose to run through powershell with the --type flag (perhaps we should made that the default)

![image](https://user-images.githubusercontent.com/3856546/80734619-c7917800-8b52-11ea-8037-234b23a8ea25.png)

**Comment by mpilking** [comment]
w00t!  This is essentially what I was trying to accomplish...not just list the files in a directory that has a space in the path, but also run a program with parameters, which also may have spaces.  Finally got it to work!

![image](https://user-images.githubusercontent.com/5453480/80782143-89885a00-8b3a-11ea-96bb-c211b1dd76eb.png)

Thanks for the tips Mike! I think we can close this one.

**Comment by scudette** [comment]
Can we change the artifact to work like that? Maybe it can save the next
user some head scratching?

**Comment by mpilking** [comment]
Hmm, I'm not sure about changing the artifact.  What you have is bare bones and maybe better.  It seems like if you change it, there could be unintended consequences and other edge cases we're not aware of yet, and then we start chasing our tail a bit.  Also, I like that the artifact essentially mirrors the interactive shell behavior (as far as I can tell).

I think documenting the behavior might be the way to go.  Maybe just update the description on this **Windows.System.CmdShell** artifact to warn users that the CMD shell can be problematic with quotes and spaces and that the **Windows.System.PowerShell** is generally more reliable.  Then on the **Windows.System.PowerShell** artifact, we add a bit more to the description and even an example of running more advanced commands such as executing processes with spaces and parameters.

Let me know what you think.  I'd be happy to test more and/or suggest updates to the descriptions/documentation.

**Comment by scudette** [comment]
Yeah I agree documentation would help. I think the main source of confusion here is that this is not a regular shell you would get e.g. with ssh - It is an execve shell so there is no state carried from one command to the other (e.g. cd dirname is useless). These quote issues are also another manifestation of this distinction.

Maybe we need a real shell with a pty or console attached.

Or maybe we dont need anything that fancy? We can certainly do everything we need with this execve shell.

**Comment by mpilking** [comment]
Well, I would hate to turn down cool new features :)  That said, I'm not sure it's worth the effort for a full-fledged shell.  I think the most important thing is simply that any process or script can be initiated and we can audit what was run.  From what I know so far, I think we can do what we need from the current implementation.  

As far as documentation, I think a nice start would be to add a little more detail to the existing descriptions.  I would add something like this  as a note at the end of the **Windows.System.CmdShell** artifact description:

> Note there are some limitations with passing commands to the cmd.exe shell, such as when specifying quoted paths or command-line arguments with special characters.  Using Windows.System.PowerShell artifact is likely a better option in these cases.

And then I would add something along these lines to the end of the **Windows.System.PowerShell** artifact description:

> Note that in addition to running PowerShell cmdlets and scripts, the Windows.System.PowerShell artifact can also be used to launch Windows command-line executables with their parameters.  This can be difficult to achieve with the Windows.System.CmdShell artifact due to complications with spaces in paths and other special character issues.  This PowerShell artifact is able to avoid most of these problems by encoding the command in Base64.  
>
> As an example, the following command initiates a Windows Defender AV quick-scan from the default location, which includes a path with spaces in it:
>
> `& 'C:\Program Files\Windows Defender\MpCmdRun.exe' -Scan -ScanType 1`

(Extra Note: Type 1 is a quick scan which should finish within the default 10 minute VQL timeout period.  If doing a type 2 full-system scan, the analyst will need to extend the timeout period.) 

![image](https://user-images.githubusercontent.com/5453480/80855236-27e0f200-8c05-11ea-81cb-373c60576dd0.png)

These are just some suggestions :) 

Thanks!

**Comment by scudette** [comment]
I added these documentation changes. Thanks for working out solutions to these quoting issues.  There is nothing much for us to do here any more so I am closing this.
