### ISSUE TITLE
[feature request] Add unique ID to offline collections to identify client

### ISSUE THREAD

**Issue by certrik** [Velocidex/velociraptor#3393]
At the moment you have to add a hostname to clients manually when importing offline collections. Furthermore the ClientID does not stay the same if adding offline collections for the same host afterwards. This doesn't allow importing multiple offline collections from the same host afterwards.
The hostname and a unique ID can be derived from the Generic.Client.Info artifact and can be used to generate the same ClientID in velo to also be able to stack offline collections for the same host.

Request: Add Generic.Client.Info as a default artifact (opt-out) to offline collectors and derive the hostname and ClientID from this artifact so that if Server.Utils.ImportCollection is used the hostname is populated automatically and the ClientID is derived from HostID (which is unique per host).

This will allow a consistent experience in regard to collected artifacts when using the offline collector.

**Comment by scudette** [comment]
Fixed in #3718
