### ISSUE TITLE
Add offline support to USN path reconstruction

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#3407]
Looks like we will need to do some refactor to support offline path reconstruction by mocking MFT + USN path.
https://github.com/Velocidex/velociraptor/blob/62e5c7cdc5cfa69663ca51322bbffefb21809fb8/vql/parsers/usn/usn.go#L59

This might not be trivial so creating an issue as a reminder.

**Comment by scudette** [comment]
This is related to #3519

**Comment by scudette** [comment]
Fixed by #3652
