### ISSUE TITLE
Bug: Notebook env doesn't seem to work

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3447]
```sql
SELECT 
       notebook_create(
         name="notebook2",
         artifacts=["Notebooks.VQLx2"],
         env=dict(mystring="hello"))
FROM scope()
```
But then in the notebook2 notebook `SELECT mystring FROM SCOPE()` errors with "Symbol mystring not found. Current Scope is..."

Tested with version:
version: 0.72.0
commit: f72e911
build_time: "2024-04-23T15:37:26Z"

**Comment by scudette** [comment]
Fixed by #3741
