### ISSUE TITLE
Feature Req: Add Parameters to Global Notebooks ( just like Parameters switch in artifact_xyz.yaml)

### ISSUE THREAD

**Issue by Gaffx** [Velocidex/velociraptor#3465]
A useful feature for Velociraptor would be the addition of a "**_Parameters_**" switch to global notebook templates. This would simplify the process by allowing users to fill out specific parameters during deployment, either through the deploying template wizard or after calculating results. This feature would save time and improve efficiency, particularly for those who are new to using Velociraptor.

**Comment by scudette** [comment]
This feature is now in 0.73
