### ISSUE TITLE
GUI - Option to output server artifacts in CSV or JSON

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#348]
the recent change to JSONL output means that some artifacts are needed to be post processed adding an extra step to the analysts workflow

Would be good to have a UI option to allow for the data to be converted to JSON using the command
mlr --ijson --ocsv cat

May not be perfect for every artifact, but would be useful for some of them and allow the analyst to dump certain data quickly for review

**Comment by scudette** [comment]
fixed by #353  - we now just output both because why not
