### ISSUE TITLE
Bug: Artifact aliases should not be delete-able

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3484]
In the GUI Artifacts view an artifact with aliases is represented as multiple artifacts. When one of the aliases is selected, attempting to delete it results in the error:
"Error: remove /datastore/artifact_definitions/Windows/Detection/VelociraptorInception.yaml: no such file or directory".

When an alias is selected the delete button should actually be unavailable/greyed out, as it is for built-in artifacts.

**Comment by scudette** [comment]
Fixed by #3716
