### ISSUE TITLE
Symbol user_create not found

### ISSUE THREAD

**Issue by hoce247** [Velocidex/velociraptor#3487]
Hello Everyone, 

I've been trying to deploy Velociraptor having the datastore offloaded to a SMB share (changed the corresponding paths in server.config.yml and adjusted the necessary permissions on the SMB share. Velociraptor starts and runs smoothly but I can't create new users, orgs or start any hunts because I always receive an error containing "Symbol XXX not found" (as seen in the picture).

What could be the reason for this?

Thank you
![image](https://github.com/Velocidex/velociraptor/assets/116655121/6f004da8-c7a0-4b02-ae52-784b6a37f600)

**Comment by scudette** [comment]
https://docs.velociraptor.app/knowledge_base/tips/plugin_not_found/

If you use SMB you probably should also enable the memcache filestore to compensate for the slow filesystem
https://docs.velociraptor.app/docs/deployment/cloud/multifrontend/
