### ISSUE TITLE
GUI bug - Notebook bottom pane does not refresh when you delete a notebook

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#349]
If you have a notebook selected and you delete it, the contents of said notebook will still appear in the bottom pane. This allows you to continue editing it but then if you refresh the page you'll "lose" your data.

Would also be useful to have a "trash" button within the UI that lets you recover deleted notebooks, should you accidentally delete one.

And or a check when you hit trash that if the notebook has content, then the user has to acknowledge with a dialog box that they want to delete the notebook.

**Comment by scudette** [comment]
fixed by #353
