### ISSUE TITLE
Artifact MacOS.System.Wifi Outputs Errors On macOS Ventura 13.6.7 Test System

### ISSUE THREAD

**Issue by rob-wilco** [Velocidex/velociraptor#3502]
Test operating system:
macOS Ventura 13.6.7 (Intel)
Velociraptor version: velociraptor-v0.72.1-darwin-amd64
Artifact: macOS.System.Wifi
Preconditions: Full disk access granted to compiled binary.

Error output:
Symbol OSPath not found. Current Scope is [NULL], [_SessionId, $responder, WifiGlob, $device_manager, config, $acl, $uploader, Artifact, $repository, $root], [precondition_MacOS_System_Wifi_0], [WifiPlist], [KnownNetworks], [EachNetwork], [MacOS_System_Wifi_0_3], [$Query], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [Version, Counter, DeviceUUID, PreferredOrder], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [Version, Counter, DeviceUUID, PreferredOrder], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [Version, Counter, DeviceUUID, PreferredOrder], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Version, Counter, DeviceUUID, PreferredOrder], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [Version, Counter, DeviceUUID, PreferredOrder], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [DeviceUUID, PreferredOrder, Version, Counter], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [PreferredOrder, Version, Counter, DeviceUUID], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Counter, DeviceUUID, PreferredOrder, Version], [Name, OSPath, Mtime, Atime, Ctime, Btime, Size, Mode, IsDir, IsLink, Data, Globs] 

When concatenating /Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist with elevated privileges the following output is produced:

<plist version="1.0">
<dict>
    <key>Counter</key>
    <integer>2</integer>
    <key>DeviceUUID</key>
    <string>844A8A08-022E-4A49-B5D0-2726F4589D95</string>
    <key>PreferredOrder</key>
    <array/>
    <key>Version</key>
    <integer>5000</integer>
</dict>
</plist>

**Comment by scudette** [comment]
Fixed by #3505
