### ISSUE TITLE
Client crashes - reoccurring problem

### ISSUE THREAD

**Issue by yarox24** [Velocidex/velociraptor#3503]
We are using Velociraptor with custom "complex" VQL plugins over 2 years.
Target machines: Windows
Velociraptor version (current): 0.7.1-2

But often we observe client crashes (Agent version = same as server):

Target OS: Windows Server 2019
![image](https://github.com/Velocidex/velociraptor/assets/18016218/f1eac10f-d9b8-4404-a109-c793903d7751)

Target OS: Windows Server 2008 R2
![image](https://github.com/Velocidex/velociraptor/assets/18016218/2f91bb99-4db3-4ae1-b96c-d0141526f964)

Our observations:
- More plugins executed (withing single large VQL we call profile) better chance of crash
- Some crashes may be related to file collections (Using KapeFiles plugins underneath)
- Crashes are not replicable on clean Windows OS, it's always production OS
- Due to production system crashes we don't have "tracebacks" as we don't turn on "Tracing" beforehand

We can share our VQL "profiles" but prefer to do so in private way.

**Comment by scudette** [comment]
With 0.72 we have some additional settings that might help to debug this:
- Setting client.panic in the config file will maintain a client side panic file which will show any tracebacks  in case of an actual crash see https://docs.velociraptor.app/docs/deployment/references/#Client.panic
- It is possible now to write client side encrypted logs that can be reviewed later https://docs.velociraptor.app/docs/deployment/references/#Client.logfile_name

**Comment by scudette** [comment]
Closing due to staleness - if you see this issue in 0.73.2 please reopen.

**Comment by casey-hillman** [comment]
seeing similar crashes with 0.72.4; was something fixed in 0.73.2 that should address this?

**Comment by scudette** [comment]
Hard to tell since there is not a lot of information in the issue but the latest release is 0.73.3 and you can run a trace during the artifact collection to get more information of what's happening.
