### ISSUE TITLE
help wanted: build linux386 

### ISSUE THREAD

**Issue by pasqueque** [Velocidex/velociraptor#3510]
Good Day. Сan anyone help with compiling  LinuxMusl386?
Got error while running `go run make.go -v LinuxMusl386`
```
Build Environment: {"CC":"musl-gcc","CGO_ENABLED":"0","GOARCH":"386","GOOS":"linux"}
exec: go "build" "-o" "output/velociraptor-v0.72.3-linux-386-nocgo-musl" "-tags" " server_vql extras  release yara disable_gui " "-ldflags= -w -s -linkmode external -extldflags \"-static\" -X \"www.velocidex.com/golang/velociraptor/config.build_time=2024-05-22                          T17:25:16+03:00\" -X \"www.velocidex.com/golang/velociraptor/config.commit_hash=3a14fd9a\"" "./bin/"
# www.velocidex.com/golang/velociraptor/bin
loadinternal: cannot find runtime/cgo
```
Set CGO_ENABLED=1 do not work.

18.04.1-Ubuntu i686
go version go1.20.1 linux/386
musl-1.1.23

**Comment by scudette** [comment]
Looks like the musl build required cgo to enable but this breaks other modules like sqlite. Why do you need specifically a musl build? can you build a regular 386 build on the target platform?

**Comment by scudette** [comment]
Feel free to reopen if a regular build is not working for you
