### ISSUE TITLE
EncryptedPass no longer in Base64 format since v0.72.0

### ISSUE THREAD

**Issue by OlafHaalstra** [Velocidex/velociraptor#3512]
When using a X509 certificate to encrypt the offline collector zip asymmetrically the EncryptedPass field inside `metadata.json` is no longer in Base64 format.

Also the output contains non UTF-8 / ASCII characters so I'm unsure how to proceed with the decryption.

**Comment by scudette** [comment]
It should not actually matter though - does it fail to decrypt the file correctly?

**Comment by OlafHaalstra** [comment]
Tested with 0.72.3 and it is fixed indeed
