### ISSUE TITLE
Error to download autorun

### ISSUE THREAD

**Issue by sebdraven** [Velocidex/velociraptor#3513]
Hi,

with the last version stable, I try use Windows.system.autorun

and I've this issue

![image](https://github.com/Velocidex/velociraptor/assets/1478484/737e6034-58f4-4cfd-91e2-7d476b23e02d)

I've no issue with other hunting operation

My server hasn't not dns name Velociraptor server and I've change correctly this setting in the yaml files

**Comment by sebdraven** [comment]
Thanks for your reply I'll check that but it seems I have already done.

**Comment by scudette** [comment]
Feel free to reopen if the issue persists
