### ISSUE TITLE
Windows.KapeFiles.Targets _BasicCollection hangs

### ISSUE THREAD

**Issue by nikitah4x** [Velocidex/velociraptor#3515]
Hey,
I'm testing the velociraptor and for some reason, all hunts are working except the Windows.KapeFiles.Targets.
It seems to work but then it just hangs.
![image](https://github.com/Velocidex/velociraptor/assets/58976181/30a95755-3c7d-46e0-a670-1b1f4cbbcadb)

![image](https://github.com/Velocidex/velociraptor/assets/58976181/f5e8a9ff-7140-48a4-ab20-da0b16b4a56c)

**Comment by scudette** [comment]
Can you please collect profiles and maybe turn on the trace function as described here https://docs.velociraptor.app/docs/deployment/troubleshooting/#debugging-a-remote-client

What version are you running?

**Comment by ioscanner** [comment]
I have the same issue. All other artifacts work just fine. I just get:

Windows.KapeFiles.Targets/All File Metadata: Time XXX: : Waiting for rows.

It worked in the past versions with no issues.  I noticed after the update and just didn't have time to post, it never completes before it times out.

I am running:
"name":"velociraptor"
"version":"0.7.1-1"
"commit":"2d7d6cf"
"build_time":"2023-12-27T09:45:45Z"
"ci_build_url":"https://github.com/Velocidex/velociraptor/actions/runs/7337099704"
"compiler":"go1.21.5"

**Comment by scudette** [comment]
This should be fixed in 0.72.3 can you please test that version?

**Comment by scudette** [comment]
Please reopen if you still have issued with 0.72.3
