### ISSUE TITLE
Stacking links do not always work as expected

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3520]
Given this very simple example query:

```SQL
LET Data <= 'foo,1
bar,1
baz,2
qux,2
quux,1
corge,2'
SELECT * FROM parse_csv(columns=['Foo', 'Bar'], accessor='data', filename=Data)
```

![2024-05-28_19-38](https://github.com/Velocidex/velociraptor/assets/4006538/9331d3e7-183a-45fc-9a96-88825a935459)

Sorting on Bar and selecting *stacking* gives the following expected results:

![2024-05-28_19-38_1](https://github.com/Velocidex/velociraptor/assets/4006538/e473d180-7fdc-44dd-bc98-da7407d40131)

Clicking on the second link, for Bar == 1 results in the following, as expected:

![2024-05-28_19-39](https://github.com/Velocidex/velociraptor/assets/4006538/4ad399dc-2a7f-4419-bb19-53a250167b8a)

However, clicking on the first link returns the following (not expected):

![2024-05-28_19-39_1](https://github.com/Velocidex/velociraptor/assets/4006538/e5ac3a99-1d07-4e71-b70a-1fed9dd55b97)

The expected result would be just corge, qux, baz.

**Comment by scudette** [comment]
That seems correct. The first link should take you to the part of the table where bar = 2. There seems to be 3 rows like that and that's what the table is showing.

**Comment by scudette** [comment]
That is not what the links do - they seek into the sorted table to the place where the primary sort key is equal to the specified value.

**Comment by scudette** [comment]
I was debating if to implement the feature as you suggest and only show the rows where the value is equal but decided this was actually not ideal as you would normally want to review similar values to the sort key immediately after the value of interest instead of clicking back and forth to the next batch

**Comment by misje** [comment]
Right. That makes much more sense.

I have used the link feature before without thinking about this. The behaviour then felt natural. It was some time later when I had a dataset that only contained two distinct values where I was led to believe that something felt wrong.
