### ISSUE TITLE
Windows service commands should not all require a config

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3524]
On Windows the `service` commands always require a client config. That makes sense for the `install` subcommand but not for start/stop/pause/continue.
![VirtualBox_WinDev2311Eval_30_05_2024_10_34_39](https://github.com/Velocidex/velociraptor/assets/9843422/d12c56c6-f865-4ab1-8790-84a9ae9112f9)

Just noticed this while playing around. It's not too important and doesn't prevent accomplishing the goals but it could be improved.

Of course it's also not the recommended way to install the client and for service operations one could also use `sc`.

**Comment by scudette** [comment]
We actually do need the config to know what the name of the service is. 

Probably in practice we would use sc.exe to control the service anyway.
