### ISSUE TITLE
Artifact parameters should be unset when string is set to empty

### ISSUE THREAD

**Issue by Zyrenica** [Velocidex/velociraptor#3526]
Currently an artifact parameter when blanked after setting to a value passes the empty string to the artifact instead of the default value.
Hunt Overview does not display this parameter which leads you to believe it is unset and passing the default value.

This should revert the parameter to use the default value instead, or blank if there is no default value.

Example:

```
  - name: FileSize
    description: The maximum file size to pass through the entropy algorithm. Default = 2MB.
    type: int
    default: "2000000"
```

Parameter is used as such, but works the same for any parameter with a default value:

```
SELECT basename(path=OSPath) AS Filename,
  Ctime AS Created,
  Mtime AS Modified,
  Atime AS LastAccessed,
  Size,
  OSPath AS SourceFile
FROM glob(globs=specs.Glob, nosymlink=TRUE, one_filesystem=TRUE)
WHERE NOT IsDir
  AND Mode.IsRegular
  AND Size < FileSize
```

- Parameter was tested with a much lower value to ensure it was working, the hunt was then copied and the value removed.
- Further testing returned 0 results, even though the overview for the hunt did not list that parameter as set leading to belief that the parameter was back to its default value.
- Viewing the request is the only way to see that the key value is missing when the value is blanked.

**Comment by scudette** [comment]
Fixed by #3741
