### ISSUE TITLE
Windows.Sys.AllUsers fails to return the "roaming_users"

### ISSUE THREAD

**Issue by jonas-koeritz** [Velocidex/velociraptor#3533]
While trying out this artifact and comparing the results to the `Windows.Sys.Users` artifact I wasn't able to reproduce the results I expected. I experimented with the VQL and determined that the `memoize()` around the `roaming_users` query seems to break this.
My best guess is that `chain()` doesn't allow for chaining a dict (which is the result of the memoize call as far as I understand) and a query (which `local_users_with_mtime` is).
My familiarity with VQL is severely lacking so I would like to have someone more advanced look into this.

**Comment by scudette** [comment]
This should be fixed now. You can copy the artifact definition from master branch to test if you like.
