### ISSUE TITLE
process_tracker_updates() returns weird timestamps for NULL values

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3541]
[This](https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/Events/TrackProcesses.yaml) artifact has started producing the timestamps "0001-01-01T00:53:28+00:53" (this exact value) in pstree. I don't think the issue lies in the artifact, since I get the same result in other custom event artifacts. It appears that when either the timestamp fields start_time or end_time, or the corresponding StartTime and EndTime in the data dict is NULL, `process_tracker_updates()` returns these invalid timestamps. In the event viewer, the timestamps from `process_tracker_updates()` are "0001-01-01T00:00:00Z". Valid timestamp strings or timestamps passed to the fields work as expected. This happens in version 0.72.3.

**Comment by scudette** [comment]
Just trying to replicate this in `velociraptor gui` on windows

I enabled AlsoForwardUpdates so I can see the updates from the actual queries. This shows the sync query (from pslist) and the start row from sysmon:

![image](https://github.com/Velocidex/velociraptor/assets/3856546/8dc037f2-445c-4e22-bdc6-29375282769c)

and the sync query is 

![image](https://github.com/Velocidex/velociraptor/assets/3856546/21b1eccc-816a-43e7-ace2-5bb4406d309b)

I then start notepad exit it and start it again

![image](https://github.com/Velocidex/velociraptor/assets/3856546/0c5839da-5c2d-4f5e-aa72-a1708be2d182)

So this shows one live notepad and one exited one. The exit time looks accurate.

**Comment by misje** [comment]
I see, so these timestamps are meant to look like this. I see that it's been like this for years from screenshots in the documentation. May I ask why these timestamps are created like this instead of being NULL?

**Comment by scudette** [comment]
The field type is Go time.Time so it has a zero value like `0001-01-01T00:00:00Z` This is how Go represents an unset (zero value) time.

**Comment by scudette** [comment]
Looking at the value you get ` "0001-01-01T00:53:28+00:53" ` looks like the zero time in a weird 53 minute timezone
