### ISSUE TITLE
FR: Modify Offline Collectors easier

### ISSUE THREAD

**Issue by DavidSanchezGracia** [Velocidex/velociraptor#3556]
Hi everyone,

I have realized that whenever you build a new Offline Collector, it is possible to select that flow on the "Server Artifacts" tab and copy the collection but modifying that Offline Collector to add new artifacts or change parameters is not really intuitive, because you have to do it all from the Configure Parameters phase in JSON format. 

I feel like it would be easier that when you click on "copy the collection" of an Offline Collector it populates the "Offline collector builder" with all that you set up previously so that the user can easily add/remove artifacts and configure their parameters without needing to edit it on JSON. 

Hopefully this would make easier to edit Offline Collectors, specially when you have large collections with many artifacts and parameters.

**Comment by scudette** [comment]
This is a good suggestion I think - we should special case the Server.Utils.CreateCollector artifact to bring up the offline collector GUI for editing instead of the default artifact editing one.

**Comment by DavidSanchezGracia** [comment]
Exactly, that would be great

**Comment by scudette** [comment]
Fixed by #3577
