### ISSUE TITLE
Error encountered when using client remap via SSH accessor

### ISSUE THREAD

**Issue by gdms04** [Velocidex/velociraptor#3562]
I successfully used the SSH accessor to remap a Linux client to my Velociraptor server as “RemoteSSH” using velociraptor-v0.72.0-linux-amd64. I was able to run some basic artifacts like Linux.Sys.LogHunter, System.VFS.ListDirectory, etc.

However, when I ran Exchange.Generic.Collection.UAC, it was unable to successfully create a tempdir. The user I used is root, so it should have sufficient privileges to create a directory.
![remotessh](https://github.com/Velocidex/velociraptor/assets/47113752/429077c0-3d03-417b-9534-fce3116586b6)

I tried using a standard client on the same artifact and it was successful.
![standard_client](https://github.com/Velocidex/velociraptor/assets/47113752/11f6e6ba-5d03-42c9-a539-0bb5c9b44274)

I’m wondering if I missed anything when I set up the client remapping. Thanks!

**Comment by scudette** [comment]
The ssh accessor is used to read remote files - it can not execute arbitrary tools on the endpoint - UAC collector is a shell script which is pushed to the endpoint normally so it can not be used via the ssh accessor.

**Comment by gdms04** [comment]
ohh i see, thx!
