### ISSUE TITLE
"auto" accessor doesn't work as expected on Windows x86

### ISSUE THREAD

**Issue by hunt3vil** [Velocidex/velociraptor#3600]
We use an offline collector with the KapeFiles artifact. With default configuration the collector uses lazy_ntfs for registry hives and does not pull Windows\System32\config\SOFTWARE for example. However, when I changed the accessor to ntfs the collector correctly pulled the SOFTWARE registry hive file.

**Comment by scudette** [comment]
This is interesting as the `lazy_ntfs` is just an alias to the regular `ntfs` accessor these days (they used to be different in the distant past).

https://github.com/Velocidex/velociraptor/blob/5cc893a3e507a271037f7ff32e095a4025ce8af6/accessors/ntfs/ntfs_accessor_windows.go#L184

**Comment by hunt3vil** [comment]
OK. So my report is incorrect because inside the KapeFile artifact it is the "auto" accessor that is used by default for everything set to "lazy_ntfs". Updated the issue title

**Comment by scudette** [comment]
I can not really replicate this issue - are you sure that you were not using the x96 binary on a 64 bit OS? This wont work because of WoW rewriting and would result in what you observed.

Please reopen the issue if you still see it with the x86 binary running on actually 32 bit system.
