### ISSUE TITLE
Potetial issue in yara.pe module

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#3602]
Processing open source yara repos I hit several errors when processing PE module - pe.number_of_signatures that was fairly common for checking compromised certs. Although we can check for this easily in Velociraptor using the Authenticode function, it might be worthwhile fixing for cases where users just want to copy and paste rules.

I suspect this may be related to no ssl in VR yara but raising this issue to document. The issue also likley also impacts pe.number_of_certificates and other modules that rely on ssl.

To replicate: run yara on the velociraptor windows binary using the following yara rules:
```
import "pe"
rule TestIssuer {
    condition:
        for any i in (0..pe.number_of_signatures) : ( pe.signatures[i].issuer contains "DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1" )
}
rule TestPE {
    condition:
        pe.is_pe
}
```

We should get 2 hits. TestIssuer and TestPE.
Current velociraptor throws an error on pe.number_of_signatures

**Comment by scudette** [comment]
See this comment 
https://github.com/VirusTotal/yara/blob/6fe197e1bca069d1e79c68fecc46619e788829e6/libyara/modules/pe/pe.c#L1723

We dont enable openssl so we can not support these kinds of signature checks.

**Comment by scudette** [comment]
Just submitted a yara_lint() VQL function in #3649 - you should be able to use that to automatically remove any yara rules that are not supported. This allows us to just throw a large set of rules, filter it to remove unsupported rules and use the other ones.

You can run this function on the server to produce a smaller rule set (removing the metadata etc). Alternatively you can modify the yara artifacts to prefilter the rules with it before loading into the yara() plugin.
