### ISSUE TITLE
Wine build of MSI

### ISSUE THREAD

**Issue by freeload101** [Velocidex/velociraptor#3604]
Following this guide:
https://www.youtube.com/watch?v=2kgC9Ushk9g&t=79s

would be nice to have a way to run it without building MSI ? it works fine in windows 11 with the same exact files ...

when I run this in windows I get no output:

```velociraptor.exe --config client.config.yaml client -v --debug```

Also what is the differnece between  [velociraptor-v0.6.4-windows-amd64.exe](https://github.com/Velocidex/velociraptor/releases/download/v0.6.4-2/velociraptor-v0.6.4-windows-amd64.exe) and  [velociraptor-v0.6.4-2-windows-amd64.exe](https://github.com/Velocidex/velociraptor/releases/download/v0.6.4-2/velociraptor-v0.6.4-2-windows-amd64.exe) ?

Wine error: 
```
Z:\root\Downloads\W\wix>"c:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" velociraptor_amd64.wixob

j -ext "c:\Program Files (x86)\WiX Toolset v3.11\bin\WixUtilExtension.dll"[K[?25h[?25l[K[1C[?25h

0248:fixme:mscoree:parse_startup useLegacyV2RuntimeActivationPolicy=L"true" not implemented
0248:fixme:mscoree:parse_startup useLegacyV2RuntimeActivationPolicy=L"true" not implemented
0248:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
[?25lWindows Installer XML Toolset Linker version[K

Copyright (c) .NET Foundation and contributors. All rights reserved.



[?25h0248:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0050E988, 0035E930, 0050E98C, 0050E980
0248:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0050E988, 0035E930, 0050E98C, 0050E980
0248:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0050E988, 0035E930, 0050E98C, 0050E980
0248:fixme:file:NtLockFile I/O completion on lock not implemented yet
0248:fixme:file:CopyFileExW cancel_ptr is not supported
0248:fixme:msi:MsiGetLastErrorRecord
0248:err:msidb:msi_commit_streams failed to write stream L"\430b\4131\4735\443e\4336\41ac\47a8\43e7\482f" (hr = 0x80030102)
0248:err:msi:MsiDatabaseCommit Failed to commit streams!
0248:fixme:msi:MsiGetLastErrorRecord
0248:fixme:msi:MsiGetLastErrorRecord
[?25llight.exe : error LGHT0216 : An unexpected Win32 exception with error code 0x65B occurred: Function failed
```

**Comment by scudette** [comment]
You can run it like you did as outlined in the troubleshooting guide https://docs.velociraptor.app/docs/deployment/troubleshooting/#debugging-client-communications

I'm not sure if running wix in wine is supported - we certainly dont use it like that but I think there some docker containers that do make it work. The wine issue is probably outside the scope of this project - you should just use a Windows system to build the MSI if you need to. These days this is fairly rare because you can now use the official MSI to repack the config in.

**Comment by freeload101** [comment]
Ohhh that's great! Ill check out the prebuild MSI route . Maybe I can get it to work in wine :P thanks!
