### ISSUE TITLE
Column names prefixed by underscores are no longer hidden by default

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3605]
I don't know exactly when this behaviour changed, but I am pretty sure that column names prefixed by underscores were hidden by default. It would be nice to either get this behaviour back, alternatively how do I hide columns by default in artifacts now?

**Comment by misje** [comment]
My bad, this works as expected in notebooks, just not in "Results". I am not sure this was ever possible in the Results tab. However, it would be nice if the same feature is available in Results as in notebooks.

**Comment by scudette** [comment]
The way it works is:

1. If there are regular columns but some of them have a leading _ then those ones are hidden
2. If all the columns have a leading _ then we show them all (otherwise we would show an empty table)

**Comment by misje** [comment]
Your description matches my expectations, but in the latest release (0.72.4/d568709), I get some inconsistent results. Here is an example from the artifact in my recent pull request (#3612):

![2024-07-12_22-24](https://github.com/user-attachments/assets/73338f0a-9cc0-4898-92a8-b009754fe684)

![2024-07-12_22-24_1](https://github.com/user-attachments/assets/aea991a8-b70e-4bfb-abc6-9de7e8be4f2d)

**Comment by mgreen27** [comment]
I noticed this too when doing some customisation on the sinkhole artifact that calls another artifact with `Artifact.Windows...` and shows the _Source field. I cant remember if this used to be hidden by default but may not have been when calling another artifact scope.
![image](https://github.com/user-attachments/assets/a2a9e821-7f2a-4e4f-b8d5-4bbb9d09f495)

**Comment by misje** [comment]
In my NM.Connections artifact I typically end up with all columns visible (in the previous example, some, but not necessarily all hidden columns were visible):

![2024-07-13_10-07](https://github.com/user-attachments/assets/3cfe187d-87df-4a49-810b-c704489a00dd)

As in the previous example, the behaviour in Results and Notebook are different. In this case, all columns are hidden as expected in the notebook:

![2024-07-13_10-09](https://github.com/user-attachments/assets/1e428b64-bd68-4faf-8d74-e192e0768554)

**Comment by scudette** [comment]
Im not really able to reproduce this - the code that sets up the initial toggle states is here
https://github.com/Velocidex/velociraptor/blob/765259943bca03f143b1376d3c2619108286c65a/gui/velociraptor/src/components/core/paged-table.jsx#L490

and it depends on the columns that are reported from the server from the GetTable call.

Is it possible that the table columns are not consistent? Ie the first page has different set of tables from the second page?

Can you filter the api call in the dev console to check on the columns that are reported?
![image](https://github.com/user-attachments/assets/c307a620-2c8a-46ec-96c1-2973fcce751b)

**Comment by misje** [comment]
I get the same response as you, even though they are visible:

![2024-07-14_13-55](https://github.com/user-attachments/assets/5fea856e-99db-4abf-98c1-de97bb5311c3)

In this artifact query the columns are all stable.

**Comment by predictiple** [comment]
In case it helps, it works correctly for me using yesterday's CI build: cd6bcf5.

In both Results and Notebook views the underscore columns are hidden.

![Screenshot from 2024-07-14 14-15-04](https://github.com/user-attachments/assets/5b1b4c0f-464f-4a44-8e24-68ab50dc81f9)

**Comment by misje** [comment]
Tried that build. Fresh datastore, private windows, doesn't work for me. Neither in Firefox nor Chrome.

**Comment by scudette** [comment]
Is this maybe related to the custom column types? Can you try to remove that in your artifact definition and see if it helps?

**Comment by scudette** [comment]
should be fixed by #3614
