### ISSUE TITLE
Saving a favourite flow for server artifacts do not show up and instead end up in client artifacts

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3618]
The ability to save a flow as a favourite is a useful feature to save parameter values, as well as pre-selecting a number of artifacts. This feature is available in both client and server artifacts, but when saving a flow as a favourite in the "Server artifacts" view, it is not made available when creating a new collection. It is, however, available in client collections instead.

**Comment by scudette** [comment]
Fixed in #3636
