### ISSUE TITLE
Linux.Forensics.Journal not working on recent Linux systems

### ISSUE THREAD

**Issue by ant1** [Velocidex/velociraptor#3622]
On recent linux systems (ubuntu 24.04 for instance),  Linux.Forensics.Journal doesn't seem to work:
- the journal files are located in  `/var/log/journal/*/*.journal` ,  not  `/run/log/journal/*/*.journal`
- the files are zstd compressed so the binary parser doesn't work

**Comment by scudette** [comment]
This is now fixed by #3632 and #3633
