### ISSUE TITLE
KapeFiles regex entries break with Windows.Kapefiles.Targets

### ISSUE THREAD

**Issue by hunt3vil** [Velocidex/velociraptor#3630]
Just though I'd mention that some artifacts in KapeFiles are defined using regexes. Those entries do not work with the current conversion script as that simply leaves the keyword `regex` in the path. Some of the regular expressions could be programmatically converted to glob pattern but others no.

Example from Bitdefender.tkape:

```
Name: Bitdefender SQLite DB Files
Category: Antivirus
Path: C:\Program Files*\Bitdefender*\
Recursive: true
FileMask: regex:*.+\.(db|db-wal|db-shm)
Comment: "Bitdefender SQLite databases"
```

**Comment by scudette** [comment]
Yeah good catch! This should be fixed with #3631
