### ISSUE TITLE
Implement a watch_journal() event plugin

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3632]
journald has replaced syslog fils on Debian systems, at least starting on Debian Bookworm. syslog, kernel, auth and other log files are no longer produced. Therefore, `watch_syslog()` is no longer useful (unless the package "rsyslog" is installed as a workaround).

There is already an artifact that implements the binary format of journal files. It seems to work well, except when there is a need to retrieve logs from a specific time period, and not parse all available data before looking at timestamps. If the journal is flushed in valid objects with complete headers, I suppose implementing a plugin shouldn't be too much work.

The use cases are many, but the one I have in mind right now is the ability to implement real-time sigma client event artifacts also for Linux, using the chopchopgo rules (already included).

**Comment by scudette** [comment]
The current parser is fairly inefficient as it does not actually use the indexes inside the file but rather parses all objects from start to end. The file format is actually designed to support efficient tailing but we dont support it using the binary parser.

It will be a lot more efficient to use `journalctl -f` to follow the logs i think

**Comment by scudette** [comment]
If we are going to write a plugin in go we could use something like this
https://github.com/coreos/go-systemd/blob/b14d3eb023cc860c82b1bb143bb98122d3c40224/sdjournal/journal_test.go#L33

**Comment by misje** [comment]
> It will be a lot more efficient to use journalctl -f to follow the logs i think

I have noticed that velociraptor aims to do as much as possible natively, which is why I was wondering whether there was interest in implementing this as well. However, since this is for live OSes only, not dead-disk analysis, avoiding the complexity of implementing this makes a lot more sense. I will go for shelling out.

**Comment by scudette** [comment]
The more I think about this the more interesting this possibility is... I think it is a good idea actually. Binding to systemd is not ideal as then we will need to be running on linux and it is not portable. It also wont be possible to parse journal files from dead disk images.

The format is actually very simple so it is easy to implement a parser for it.

**Comment by misje** [comment]
Parsing journal files, yes definitely. However, specifically watching a journal log stream is only ever needed on a live system. If journalctl exists, run it, if not, then just use `watch_syslog()`?

**Comment by djoreilly** [comment]
The SUSE fork has a `watch_journal` plugin
https://github.com/SUSE/linux-security-sensor/commit/f7c12e4e3d5dc0a00f42e7c5de9a39162c8179e7

It has copied code from github.com/coreos/go-systemd/journal instead of just using it - I'm not sure why yet.

**Comment by scudette** [comment]
Thanks for the pointer - I was not aware of that fork since it was not sent upstream. 

I think the problem with that is that it must be built on Linux and links to the systemd runtime on Linux. This makes it hard to use on other systems (which might be needed eg when doing dead disk forensics etc).

The new journal support in #3634  is native Go so it works on all OSs.

**Comment by scudette** [comment]
Fixed by #3634
