### ISSUE TITLE
unable to create a correct deadisk remap file with the latest version

### ISSUE THREAD

**Issue by secufred** [Velocidex/velociraptor#3646]
With the version 0.6.9 it was possible to remap a local disk attached to a linux device by doing the following code : 
( assuming that the partition containing the /windows folder was on a partition on the /dev/sdb drive : 

./velociraptor-v0.6.9-linux-amd64-musl -v deaddisk --add_windows_disk /dev/sdb remap.yaml 

sed -i 's/"file"/"raw_file"/' remap.yaml 

./velociraptor-v0.6.9-linux-amd64-musl -c client4.config.yaml --remap=remap.yaml client -v 

with the latest version it's not creating a valid remap file as it is crashing with an error : read_file: /dev/sdb: Only regular files supported (not /dev/sdb)

The issue could be linked to "https://github.com/Velocidex/velociraptor/blob/master/bin%2Fdeaddisk.go#L275" ( thanks to @scudette )

if in the 'fix' we could also help the user to not have to make that rewrite on the remap.yaml file it would even be easier.

**Comment by scudette** [comment]
Fixed in #3649
