### ISSUE TITLE
feature - request - password protect feature suggestion for ease of use and avoiding human error

### ISSUE THREAD

**Issue by ghals13** [Velocidex/velociraptor#3673]
**essentially there's several problems with the current implementation of the password protect in our opinion:**
1. [it's not on by default and also there's a bug] we keep setting the password for each user and it keeps disappearing randomly (eg I set in one tab 5 mins ago, then open another tab and it says 'please set the password' 🤔   - this is repro on other people's pcs/macs and firefox/chrome )
2. vfs downloads are by default not protected / same with flow uploads since it directly calls vfs download  and vfs is too convenient not to use the dl from there 😄
3. people have to explicitly select hunt results or collection results, and make sure it's locked lock and password is set to dl pw protected zip.

Is there any chance you'd be willing to implement something 'on by default' and covering VFS/uploads section (so basically uniform and always on) e.g to avoid human error/so you don't have to think about what's protected what's not protected etc - just everything gives you zipped with password files for download e.g:

1. can we make it an instance wide admin setting with password infected
2. if it's set, hunt result downloads are auto protected
3. if it's set, VFS result downloads are auto wrapped in a password protected zip .

**Comment by scudette** [comment]
This is now in place at #3679 . If you want to enforce that zip password is set you can use the new user_option() VQL function in a monitoring artifact or a periodic artifact to set the password on all users (introduced in #3680.
