### ISSUE TITLE
[feature req] splunk_upload (plugin) - setting per event sourcetype and perhaps source to a field value inside the event?

### ISSUE THREAD

**Issue by ghals13** [Velocidex/velociraptor#3678]
Hi there, 

I understand there is a way to convert Artifact to sourcetype using step 4 to achieve this . 
https://docs.velociraptor.app/exchange/artifacts/pages/splunk.events.clients/ To set up (i.e. sourcetype='vql'  in splunk with the transform details there  `Configure your Splunk props.conf and tranforms.conf`

However, perhaps we could request being able to set it by nominating the sourcetype as an event field name similar to what you do with timestamp or hostname i.e. here:

in send_to_splunk 
https://github.com/Velocidex/velociraptor/blob/d075118f9ec3a83ba9e5f185c426810aa1f0c122/vql/server/splunk.go#L214

That would make it a lot easier for people who want minimal changes on the splunk end (not setting up the transform/ ingest time eval) but enough flexibility to easily filter or monitor what's ingested from VRR by metadata field (combinations or host,index,sourcetype,source https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Event_metadata )

**Comment by scudette** [comment]
This should be fixed now
