### ISSUE TITLE
FR: Artifact parameters should have a boolean 'required' property

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3695]
Some artifacts work in unexpected ways if a parameter is not specified. For example Generic.Utils.FetchBinary has:

```yaml
- name: ToolInfo
  type: hidden
  description: A dict containing the tool information.
```
without which it doesn't function correctly, yet it will still run without it and then it behaves unexpectedly by falling back to tool definitions in the dummy inventory.

Many existing artifacts could benefit by requiring that certain parameters be explicitly specified by the user. Currently those artifacts work around the problem by having sensible defaults or implementing checking logic in VQL. Being able to make certain parameters mandatory would allow those artifacts VQL to be simplified.

In terms of user experience, an artifact that lacks mandatory parameters should refuse to be collected.

For backward compatibility, the 'required' property would obviously be False if not specified.

**Comment by scudette** [comment]
Artifacts are called both from the GUI and from VQL. What should happen if a parameter is required but not specified?

Clearly in the GUI it will stop the user from launching the collection. That can be useful but it does add friction to launching collections . Having a sensible default is much nicer experience.

In VQL will it just refuse to run it? That is how plugins work right now.

The default mechanism can be used right now to detect the user did not specify anything and fail. This can be done in VQL already by guarding the query with a check for set parameters. This does not solve the GUI issue which still allows launching such artifacts but it will help ensure they dont do unexpected things.

Generically the required attribute is a best effort and artifacts should be written to not do crazy stuff when a parameter is not set properly. It should be harmless if unexpected.

**Comment by predictiple** [comment]
Yes, I was imagining that it would fail the same way as a missing plugin. The idea being that if the collection is errored then it draws the user's attention. This is preferable to having a collection that seems successful but contains whacky results.

Having the GUI prevent launching would be a bonus feature, but less important. In the GUI we can already do validating regex to draw the user's attention but it only triggers after something is typed into the form field. But it is a partial solution.

I think you're right: it's really an artifact design issue. Authors should think about the effects of missing parameters and do parameter checks in VQL if necessary.

If anyone raises the issue in future we can point them to here.
