### ISSUE TITLE
Bug: Download CSV button in VFS viewer results in "invalid request"

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#3697]
version: 0.73.0-rc1
commit: cd69c3e
build_time: "2024-08-19T02:58:30Z"

![Screenshot from 2024-08-20 12-12-51](https://github.com/user-attachments/assets/cf5e2f24-b738-4059-b183-da87f76b0575)

![Screenshot from 2024-08-20 12-17-21](https://github.com/user-attachments/assets/1c75d38b-ae49-47c5-a770-e4f981b6963a)

**Comment by scudette** [comment]
fixed by #3713
