### ISSUE TITLE
Error thrown on Collect Artifacts

### ISSUE THREAD

**Issue by joshlemon** [Velocidex/velociraptor#37]
The following error is produced on the console when attempting to use any of the "_Collect Artifacts_" with a Windows system.

```
Can't start flow ArtifactCollector:
Some artifacts to run are required.
```

Prior to this _Interrogate_ is run along with collecting the virtual file system.

**Comment by scudette** [comment]
When selecting the artifacts to run in the GUI you need to actually add
some before proceeding by clicking the add button.
