### ISSUE TITLE
Seg fault when trying to access Client Monitoring Table

### ISSUE THREAD

**Issue by mlucas300** [Velocidex/velociraptor#370]
Today I started using the latest version (0.4.3) and when I try and click on the Client Monitoring icon (Binoculars) I get a crash in the server:

[INFO] 2020-05-18T16:46:44+09:30  {"method":"GET","remote":"127.0.0.1:43222","status":200,"url":"/api/v1/GetClient/C.a099e977b5da68d6","user":"ubuntu","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9f4d1e]

goroutine 906 [running]:
www.velocidex.com/golang/velociraptor/file_store/api.(*FileStoreFileInfo).IsDir(0xc001526960, 0xc001526960)
	<autogenerated>:1 +0x2e
www.velocidex.com/golang/velociraptor/api.(*ApiServer).ListAvailableEventResults.func1(0xc0020afad0, 0x26, 0x1cfe8a0, 0xc001526960, 0x1cc2fa0, 0xc001526930, 0x0, 0x0)
	/home/mic/projects/velociraptor/api/artifacts.go:250 +0x5b
www.velocidex.com/golang/velociraptor/file_store/directory.(*DirectoryFileStore).Walk.func1(0xc0020afa40, 0x2e, 0x0, 0x0, 0x1cc2fa0, 0xc001526930, 0xc001014ae0, 0xc001014b00)
	/home/mic/projects/velociraptor/file_store/directory/directory.go:244 +0x128
path/filepath.Walk(0xc0020afa40, 0x2e, 0xc000db19b8, 0xc0020afa40, 0x2e)
	/home/mic/go/src/path/filepath/path.go:402 +0x6a
www.velocidex.com/golang/velociraptor/file_store/directory.(*DirectoryFileStore).Walk(0xc00077f8f8, 0xc0020afa10, 0x26, 0xc00030e2c0, 0x0, 0x0)
	/home/mic/projects/velociraptor/file_store/directory/directory.go:238 +0x96
www.velocidex.com/golang/velociraptor/api.(*ApiServer).ListAvailableEventResults(0xc0009c5c80, 0x1cf15a0, 0xc001526810, 0xc001526840, 0xc0009c5c80, 0xc001526810, 0xc0010e7b40)
	/home/mic/projects/velociraptor/api/artifacts.go:248 +0x279
www.velocidex.com/golang/velociraptor/api/proto._API_ListAvailableEventResults_Handler(0x1924c60, 0xc0009c5c80, 0x1cf15a0, 0xc001526810, 0xc000095c80, 0x0, 0x1cf15a0, 0xc001526810, 0xc0006700a0, 0x14)
	/home/mic/projects/velociraptor/api/proto/api.pb.go:1841 +0x21a
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0010ba000, 0x1d07720, 0xc001085e00, 0xc001670a00, 0xc0009c5d10, 0x2ab5410, 0x0, 0x0, 0x0)
	/home/mic/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:1082 +0x4fd
google.golang.org/grpc.(*Server).handleStream(0xc0010ba000, 0x1d07720, 0xc001085e00, 0xc001670a00, 0x0)
	/home/mic/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:1405 +0xd23
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0014665b0, 0xc0010ba000, 0x1d07720, 0xc001085e00, 0xc001670a00)
	/home/mic/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:746 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/mic/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:744 +0xa1

**Comment by scudette** [comment]
Thanks so much for reporting this!

**Comment by scudette** [comment]
This should be fixed in 0.4.4
