### ISSUE TITLE
Cursor No Longer Automatically Populates "Search for Artifacts..." Field in 0.7.3-rc1

### ISSUE THREAD

**Issue by rob-wilco** [Velocidex/velociraptor#3712]
As of version 0.7.3-rc1, the cursor no longer automatically focuses on the "Search for Artifacts..." field when selecting artifacts to collect. Instead, manual movement of the cursor and selection of the field are necessary before the user can begin filtering.

In contrast, testing in versions 0.7.1.x and 0.7.2.x shows the correct behavior: the cursor automatically focuses on the "Search for Artifacts..." field, allowing the user to start typing the desired artifact name and begin filtering as soon as the Select Artifacts page appears.

This functionality saves time in workflows.

**Comment by scudette** [comment]
Fixed by #3713
