### ISSUE TITLE
access a registry that has two types a of regs with the same path 

### ISSUE THREAD

**Issue by Ron-Nefyodov** [Velocidex/velociraptor#3719]
example:
![image](https://github.com/user-attachments/assets/9d4a2632-9413-4484-9f44-dff8ace3c6b7)
Access two keys  in registry that has the same path using glob,
it cannot be done it gives only one of the values

**Comment by predictiple** [comment]
I believe this is the same issue that was just fixed here:
https://github.com/Velocidex/velociraptor/pull/3713

**Comment by scudette** [comment]
Thank you very much for reporting this bug and documenting the screenshot above! 

This bug was indeed fixed at that commit but it is good to have the issue anyway. The fix will go out in the upcoming release.
