### ISSUE TITLE
Velociraptor ingesting .yaml artifacts but not .yml artifacts

### ISSUE THREAD

**Issue by FormindALH** [Velocidex/velociraptor#3727]
Hi, just had a bit of a facepalm problem : 

Was trying to work on our automated deployment of Velociraptor and one of the thing we wanted to do is clone one of our github repos containing hunts and ingest them into velociraptor on install through the artifact_definitions_directories option in the config file.

However when doing so not all hunts were ingested, and within a bit too much time I found the issue, some of them had the .yaml extension and others the .yml extension.

Fixed the problem by changing all problematic file extensions, however I was wondering if that was intended behaviour?

If not maybe .yml extensions support could be added to prevent this issue in the future ?

**Comment by scudette** [comment]
Fixed by #3730
