### ISSUE TITLE
Japanese characters in Uploaded folder/file names are URL encoded

### ISSUE THREAD

**Issue by Tako060** [Velocidex/velociraptor#3734]
This issue is similar to [#2454](https://github.com/Velocidex/velociraptor/issues/2454), but while #2454 involved the offline collector, this time it concerns the upload function/plugin.
When using the upload function/plugin to upload files/folders that contain Japanese characters, the characters are URL-encoded (e.g. あ → %E3%81%82) and stored on the server. This sometimes results in file paths that are too long to be saved. 
Is it possible to store files/folders on the server without URL encoding?

**Comment by scudette** [comment]
This is a very good question. The reason file names are url encoded is to avoid any special characters from appearing in file names (for example there are a bunch of illegal characters for windows filesystems).

Also the encoding ensures we can run on filesystems that do not support Unicode. 

But according to your example this can expand the length of the filename by 9 times. It looks like on Linux the maximum length of a file is 255 chars. If we didn't url encode the file name it might be only expanded by 3 times.

**Comment by Tako060** [comment]
I understand that URL encoding is important for handling special characters, but from 28 to 84 chars is big for me. 
Also, when the file name is too long and it can't be saved, sometimes the uploading process gets stuck. So, it makes me feel more secure if the limit could be expanded further.
Is it possible to handle this, like in the previous issue?

**Comment by scudette** [comment]
I just submitted #3736 which solves the issue but allowing arbitrarily long filenames in the filestore. Hopefully this happens rarely but we can handle this case when it occurs.

**Comment by scudette** [comment]
Please  test to see if it fixes the immediate issue. We can discuss if to escape UTF8 or not for aesthetic reasons.

The issue is that if the filename does not consist of valid utf8 characters it might result in a corrupted file name by the underlying file system (On linux this does not seem to be the case but maybe Windows will substitute an invalid code point for the binary data).

**Comment by Tako060** [comment]
I successfully retrieved all the files that I couldn't obtain before. And the Japanese characters in the files/folders downloaded from the server was correctly restored.
I am very pleased with the outcome!　Thank you so much for your help.

**Comment by scudette** [comment]
Ok thank you for confirming and thanks again for reporting the issue!
