### ISSUE TITLE
Velociraptor ignoring custom artifact directory

### ISSUE THREAD

**Issue by ruzzle** [Velocidex/velociraptor#3750]
Since https://github.com/Velocidex/velociraptor/commit/643a199c4757450e8e8c835051d72939986294e9, the custom artifact directory specified in the config seems to be ignored, i.o.w. the following config does not seem to let velociraptor import artifacts residing in /path/to/artifacts/ anymore

```
defaults:
  artifact_definitions_directories:
  - /path/to/artifacts/
```

For context, I am running velociraptor standalone using the `query` subcommand to run my custom artifacts

**Comment by scudette** [comment]
This should be fixed in 0.73-rc1
