### ISSUE TITLE
Honour user timezone preference in timeline UI

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3760]
If I set a timezone other than UTC in velociraptor, all timestamps are converted into my local timezone. I find this very useful.

However, the timeline browser, the timestamps are all UTC – except for the data timestamps. See this screenshot for a demonstration:

![2024-09-16_17-19](https://github.com/user-attachments/assets/50440503-8cfe-43f0-93ab-714e165ef59c)

It would be great if this could be fixed in the next release, which brings a lot of attention to timelines.

**Comment by scudette** [comment]
Fixed by #3804
