### ISSUE TITLE
multiple velociraptor server installation with the same configs

### ISSUE THREAD

**Issue by colangiuli** [Velocidex/velociraptor#3763]
Hi, i'm trying velociraptor, i want to install it on different servers using docker but i want to be sure that each installation has the same configs including tools and custom artifact.

i will deploy with the docker compose from here:
https://github.com/weslambert/velociraptor-docker
this docker compose bind mounts the entire velociraptor folder.

My idea is to do a local installation of velociraptor, install all the required parts and copy its content to all the new installation.

if i need to add something i will do it on the local installation and copy again the entire velociraptor folder to the other servers.
Maybe i can version this folder with git in order to keep track of configuration changes.

Those velociraptor servers will be used only to generate offline collectors so i don't care if i overwrite their internal data.

Do you see anything wrong with this approach or can you suggest me a better one?

Are there any folder that is better to exclude from the copy?
i've identified those ones for now:
velociraptor/logs 
velociraptor/server_artifact_logs
velociraptor/server_artifacts
velociraptor/temp
velociraptor/public

**Comment by scudette** [comment]
There isnt really anything to fix here so closing.
