### ISSUE TITLE
MSI for v0.4.3

### ISSUE THREAD

**Issue by Idriel** [Velocidex/velociraptor#377]
Hi,
can you please add .MSI package. 
tnx.

**Comment by scudette** [comment]
Just a quick question. Do you really find msi packages useful?

Given it's very easy to generate your own and when you make your own, you can include the config in the package for easier deployment, how useful is the msi we generate is?

You can build your own msi using the instruction on https://github.com/Velocidex/velociraptor/blob/master/docs/wix/README.md

**Comment by Idriel** [comment]
Hi, 
will do own msi then. :)
it's very useful to us as we deploy it though SCCM and then we have versioning in place (automatic deploy of latest version)
