### ISSUE TITLE
Issue with Special Characters Sanitization in Filenames

### ISSUE THREAD

**Issue by Tako060** [Velocidex/velociraptor#3783]
Hello Velociraptor Team,

I would like to report a bug that occurs in rare situations.

When uploading files from a macOS/Linux client to a Windows server, using like MacOS.Search.FileFinder, the following conditions cause issues:
- The filename contains " or \\.
- The output of glob() expands to more than 1000 rows and is stored in a JSON tempfile.

In this scenario, the filename is sanitized twice (once during glob() and once when stored in the tempfile) but is only de-sanitized once during upload(). This results in the filenames being altered, causing upload() to overlook them. The table below illustrates this issue:

| Original filename |    | Sanitized after glob() |    | Sanitized on json tempfile |    | Filename upload() reads from tempfile |
|-------------------|----|------------------------|----|----------------------------|----|--------------------------------------|
| aaa"bbb.txt       | → | "aaa""bbb.txt"         | → | """aaa""""bbb.txt"""       | → | "aaa""bbb.txt"                       |
| aaa\bbb.txt       | → | "aaa\bbb.txt"          | → | """aaa\bbb.txt"""          | → | "aaa\bbb.txt"                        |

I am not currently facing any issues due to this bug, but I wanted to inform you about it.

**Comment by scudette** [comment]
Thanks for your comment. If you want to read more about how filenames are handled in velociraptor check out this link

https://docs.velociraptor.app/docs/forensic/filesystem/paths/

You should be able to upload any file from the endpoints regardless of any special character.

Are you saying that creating such a file on the endpoint makes it impossible to upload?

**Comment by scudette** [comment]
Can you also please clarify what you mean by tempfile? The artifact here https://docs.velociraptor.app/artifact_references/pages/linux.search.filefinder/ should not use a tempfile at all. 

Is there an easily reproducible way we can replicate this issue? for example creating more than 1000 files in a directory?

**Comment by Tako060** [comment]
Sorry, actually macOS/Linux.Search.FileFinder doesn't cause this issue. Cloud you use Generic.Collectors.File and collect more than 1000 files? I hope you'll see this kind of logs:

> Materialize of LET all_results: Expand larger than 1000 rows, VQL will switch to tempfile backing on /tmp/VQL_all_results_.jsonl1343434737 which will be much slower.

> upload: Unable to open /Users/Shared/"""aaa""""bbb.pdf""": lstat /Users/Shared/"aaa""bbb.pdf": no such file or directory
> upload: Unable to open /Users/Shared/"""aaa\bbb.pdf""": lstat /Users/Shared/"aaa\bbb.pdf": no such file or directory
