### ISSUE TITLE
Add 24 hour time picker

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3794]
For those who us who use 24-hour formats exclusively, having to use an AM/PM time picker is a nuisance. Being able to set my time format in user settings and get a 24-hour UI in every datetime widget would be such an improvement in daily usage.

**Comment by scudette** [comment]
You are absolutely right -the current time/date widget is not very user friendly. We need something that 

1. Ideally can just paste or type an RFC3339 time which can be copied from elsewhere in the GUI
2. Bring up the calendar on demand
3. Can automatically convert from UTC to another timezone 

I think the current widget is too complicated and fiddly to use efficiently. We need a much simpler one

**Comment by misje** [comment]
Even better. Great suggestions.

**Comment by misje** [comment]
Implemented in 299792d63..224e5318.
