### ISSUE TITLE
Add time constraint support to parse_journald()

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3796]
The native journal parser is great. However, if I only want logs within a given time frame (say, the last 24 hours), I still have to parse the whole journal and then filter on time. Simply changing the artifact to

```SQL
   SELECT *
   FROM foreach(
     row={
       SELECT OSPath
       FROM glob(globs=JournalGlob)
     },
     query={
       SELECT *
       FROM parse_journald(filename=OSPath)
       WHERE if(
         condition=DateAfter,
         then=System.Timestamp > DateAfter,
         else=true)
        AND if(
              condition=DateBefore,
              then=System.Timestamp < DateBefore,
              else=true)
     })
```
works, as in limiting the number of rows uploaded, but it is very slow. I would like to replace Exchange.Linux.Sys.JournalCtl as soon as this parse_journald() supports something à la journalctl's --since and --after.

Will this be a lot of work to implement in go, resulting in faster searches? If it is not realistic to implement before the release, I'd still like to add the time constraint parameters in time for the release, even if the solution is not ideal. I'll create a pull request with adjusted tests, if so.

**Comment by scudette** [comment]
The journald file format is designed for fast searching by building indexes into the file. We currently do not support parsing those indexes so we just enumerate all the objects in the file. The journalctl command supports looking at those indexes.

I am not sure it should be that slow tbh - what kind of performance impacts are you seeing? how large is the file? how many objects/messages in it?

BTW as an aside following the log is very cheap as we just look at the last sequence number 
https://github.com/Velocidex/go-journalctl/blob/96e2f85c55304795e2d2c5c43e9b6ad6a6c91152/parser/open.go#L52

This means we can avoid parsing objects before the sequence number - but this is not really corresponding to a time as such.

We have two options - 
1. Support walking the time index - just like journalctl
2. We may be able to prioritize parsing the object to get the timestamp first, then we can skip it earlier and avoid parsing the whole object.

It really depends how slow the journal parsing is in reality

**Comment by mgreen27** [comment]
I wonder if performance is impacted by the amount of rows and if() function.

@misje you can mess around with how we approached the MFT artifact and have different streams for added filter
https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/NTFS/MFT.yaml#L212-L233

**Comment by scudette** [comment]
I dont have a journald file that is large enough to see any noticabe performance delays but I just added some time boxing around the `Linux.Forensics.Journal` artifact - can you please check that artifact in the latest build on one of your larger log files?

**Comment by misje** [comment]
Your changes made the artifact return my search in five seconds as opposed to minutes (I cancelled it before it finished), so this is a huge improvement!

On a typical system I'm inspecting, there are system journals ranging around 20–120 MB in size, depending on auditd configuration and activity. I see logs back two months, and the total size of the directory is about 3.6 GB in this very example I'm looking at.

This is a true gift for those of us extracting data within time frames as opposed to uploading everything first. Thanks a lot for the quick implementation!
