### ISSUE TITLE
Vfs path is too short - Version 0.73.0

### ISSUE THREAD

**Issue by migr19** [Velocidex/velociraptor#3797]
Started Velociraptor Server with velociraptor-v0.73.0-rc1-linux-amd64 and the config from Version 0.72.0.
After creating a new msi with version 0.73.0 for Windows can't download it, get message Vfs path is too short
Also for older created msi Version 0.72.0 i get the message, when i try to download, but it worked in version 0.72.0.
Any ideas?

**Comment by scudette** [comment]
Can you provide more details? This might have been fixed as part of the 0.73 release cycle so maybe also test the latest build

https://github.com/Velocidex/velociraptor?tab=readme-ov-file#getting-the-latest-version

**Comment by migr19** [comment]
Sry for late response, have done downgrade, will test to upgrade later on and let you know.

**Comment by scudette** [comment]
I assume this is fixed in 0.73.2 - please reopen if the issue still persists
