### ISSUE TITLE
CPU & Memory and connected client graphs timeframes don't match

### ISSUE THREAD

**Issue by lukerosser** [Velocidex/velociraptor#3801]
When selecting any period other than "Last hour" the X axis on the two homepage graphs don't match

Example:

![Screenshot 2024-10-04 at 08 56 38](https://github.com/user-attachments/assets/29942614-928b-4656-9e23-8fe8c0e85f65)

CPU and Memory ends on 2024-10-03 and clients ends on 2024-10-04

**Comment by scudette** [comment]
Thanks for reporting this - it should be fixed by #3802
