### ISSUE TITLE
Offset/paging is not reset when changing source

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3821]
When I change the source in the collection results, and the next source has fewer pages than the page I was on in the previous artifact, the table is empty, because the state is not updated. This led me to believe that a bunch of results were empty before I realised what was going on. These two screenshots should hopefully demonstrate the issue:

![2024-10-13_12-36](https://github.com/user-attachments/assets/01a7a339-2318-419e-bb7e-02aaa70fa314)
![2024-10-13_12-36_1](https://github.com/user-attachments/assets/674b384a-ed9f-4b74-8628-51f627a44663)

Reproduce by

1. Collect at least two artifacts, one you expect to return lots of results, and another that you expect to return far fewer results (but not none)
2. Navigate to the end (or near it) of the source providing many results
3. Change source
4. The table now appears empty unless you navigate to a different page/offset

**Comment by scudette** [comment]
Thanks for reporting this - it was probably there for a while. Fixed by #3822
