### ISSUE TITLE
Hunt condition - exclude/include 

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#383]
It would be good to have an "exclude" option in the hunt conditions

Useful to exclude things like test boxes, or when you have to hunt across groups at a time before expanding to the entire network.

**Comment by mgreen27** [comment]
This may be a separate request but I think implementing this would also be helpful for deployment scenarios where using a <= parameter to ensure no download race condition, downloads the binary for machines not in the chosen hunt group.

**Comment by scudette** [comment]
Live in head.
