### ISSUE TITLE
Using the auto-format button on an artifact with a "notebook" section in source invalidates the yaml

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3834]
This is best demonstrated with the following screenshots:

![2024-10-15_17-48](https://github.com/user-attachments/assets/b4370a44-82a6-4054-869c-c27fb835a7e8)

![2024-10-15_17-48_1](https://github.com/user-attachments/assets/15f1cf70-85ac-4250-8dcf-426f69fc8c38)

**Comment by scudette** [comment]
Fixed in 0.73.2
