### ISSUE TITLE
Timeline Notebook - White Screen

### ISSUE THREAD

**Issue by mtreanor-r7** [Velocidex/velociraptor#3848]
Following the instructions here https://docs.velociraptor.app/blog/2024/2024-09-12-timelines/ for creating a global notebook using Notebooks.Timelines on 0.73.1 results in a white screen.

I can refresh the window and quickly navigate out to continue using VR but the white screen only appears when I try to access the notebook timeline.

Unsure if this is important but I'm using VR locally via 'velociraptor-v0.73.1-windows-amd64.exe gui'

**Comment by scudette** [comment]
I think the current release is 0.73.2

**Comment by misje** [comment]
Sounds like #3832, which has since been fixed.

**Comment by mtreanor-r7** [comment]
Confirming this is resolved in 0.73.2, didn't see the update got pushed out, is it possible to put the latest release version at the top of the release page instead of needing to scroll down?

**Comment by scudette** [comment]
Indeed it is already pointed to from the download page https://docs.velociraptor.app/downloads/

**Comment by mtreanor-r7** [comment]
Noted thank you, bookmarked for future checking, I was referring to here which you may not have much control of how it's listed https://github.com/Velocidex/velociraptor/releases
