### ISSUE TITLE
Enhancement - Windows.sys.users type change and SAM parsing

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#385]
API calls on domain controllers return users as local users when this is not necessarily the case.

suggestion would be to have three separate types
1. API - list users based on API calls
2. SAM - parse the SAM hive for local users, these can be called local
3. Profilelist - parse the SOFTWARE hive for roaming users, these can be called local

There will definitely be duplication across this however it will also provide a bit more context for DCs as an unexpected local user on a DC can be identified quicker.

**Comment by scudette** [comment]
It now also shows the profile last load time and unload time which are very useful in establishing timelines
![image](https://user-images.githubusercontent.com/3856546/174697903-05beb538-a1cc-49e8-8305-52e52314c9b9.png)
