### ISSUE TITLE
source() without an end_time argument no longer works in event artifact notebooks

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3851]
In the latest build/release, simply running `SELECT * FROM source()` in an event artifact notebook no longer works (I get no results). It works if I add `end_time`, say `source(end_time=now())`.

**Comment by scudette** [comment]
If you don't provide an end time it uses the EndTime variable from the environment. This used to be set to the current time by default but it is now set to the end of the viewer range when making the notebook the first time.

I think the idea was to zoom out to include the whole range then create the notebook to view only the range of interest. But this is not ideal because the notebook once created has the end time fixed in it and doesn't really change when the timeline viewer is updated.

**Comment by misje** [comment]
I do see the benefits of getting a nice time-constrained default out of the box when creating a notebook in the event interface. However, when `select * from souce()` doesn't work, that just causes a lot of head-scratching. Especially if one fires up the notebook intending to work on all the data, removing the default variables and arguments. Additionally, new cells and vql_suggestions from notebooks now have to add a end_time argument that is not used, but has to be there, with a distant-future timestamp.

I'm note sure if this new feature helps that much in the end. And it is confusing for the user. What about removing surprises (including the use of these env.vars.), keeping it simple, awaiting a larger redesign? The default can still be two LET expressions and the use of start_time and end_time to reduce boilerplate for the user (although myself I almost always remove these in my use cases), but don't rely on "hidden" behaviour of these variables are not specified. Just return it all.

**Comment by predictiple** [comment]
This might indicate a broader design issue. It might be better to have a session-based global timeframe selection in the UI. I've seen this feature in other products.

Usually while investigating the user is focusing on a specific timeframe at each point in the investigation. Currently if they are looking at results from a specific artifact and have filtered their view to the timeframe of interest and then navigate to a different artifact then they have to manually repeat the time selection. And then they need to keep doing that everywhere they go. It would be much better if a timeframe can be selected globally and then wherever the users goes they only see records associated with that timeframe, in a similar way to how the timezone preference is currently applied wherever one goes.

That might obviate the need for specifying start/end times in VQL. With timelines there would probably need to be additional filtering based on zoom level.

**Comment by scudette** [comment]
The timeline viewer is used for quick preview but in the notebooks we want to have a feature that we can use to update parameters. 

So for this use case we will have start time and end time as time selector parameters the user would edit the cell as usual but be able to specify the time graphically. 

At the moment the time viewer does not actually show as part of the notebook at all so it's really not related. I think that's ok to have a different UI for the notebook and the result viewer. Maybe we can add a link from the time selector to the time line (like a button to update it from there)

**Comment by misje** [comment]
What is the quick fix or workaround for this at the moment? For writing vql_suggesstions, for instance. Do I just add an end_time with a random future timestamp to get anything to show up? A notebook vql_suggestion cannot know the values of these env.vars? Or can I access them?

**Comment by scudette** [comment]
It is working as intended for this release  - we are discussing how to fix the user interface for the next release.

The env variables should be visible in your VQL as they are set by the GUI when the notebook is created. You can also override them in your VQL suggestion (set to NULL or "2100-01-01T00:00:00Z" for example )

**Comment by misje** [comment]
I'm a bit slow; I found the variables. That solves my issue for now, although I still think `SELECT * FROM source()` possibly returning nothing will be confusing for users and might raise bug reports in the future. I'm closing this issue. The larger design discussion deserves a new issue. There is probably more input on this as the new release, with its new timeline improvements, is used by more users.
