### ISSUE TITLE
Wrong download / href URLs at buttons, base_path of server.config.yaml not reflected at URLs

### ISSUE THREAD

**Issue by WickedJack99** [Velocidex/velociraptor#3859]
At version change from 0.72 to 0.73 I ran into an issue with the GUI base_path at server.config.yaml .

I'm using:
..
BASE_PATH="/ecto"
..
"GUI": {
            "base_path": "'$BASE_PATH'",
..

When trying to download any file from https://172.0.0.1/ecto/... it works but I figured out, that buttons hrefs, which allow to download CSVs are pointing to https://172.0.0.1/... where /ecto is missing.

Here you see I'm accessing the GUI at https://192.168.0.189:8889/ecto/... but the URL for the download has no /ecto in it.
![Screenshot 2024-10-28 083519](https://github.com/user-attachments/assets/742c2a38-248b-48d4-9fbc-656b8e3d97ef)

#bug

**Comment by scudette** [comment]
should be fixed by #3862
