### ISSUE TITLE
WIX client.config issue

### ISSUE THREAD

**Issue by mirwitch** [Velocidex/velociraptor#3863]
The WIX configurations for both x86 (`velociraptor/docs/wix/velociraptor_X86.xml`) and x64 (`velociraptor/docs/wix/velociraptor_amd64.xml`) agents have the following configuration line in the ServiceInstall element:
```
Arguments=' --config "[INSTALLDIR]/client.config.yaml" service run '
```
This will result to the following log when installing with `msiexec /i velociraptor-v0.73.1-windows-amd64.msi /L*V "velo.log"`:

```
MSI (s) (D8:5C) [10:36:40:227]: Executing op: ServiceInstall(Name=Velociraptor,DisplayName=Velociraptor Service,ImagePath="C:\Program Files\Velociraptor\Velociraptor.exe"  --config "C:\Program Files\Velociraptor\/client.config.yaml" service run ,ServiceType=16,StartType=2,ErrorControl=32769,,Dependencies=[~],,StartName=LocalSystem,Password=**********,Description=Velociraptor Service,,)
```
The resulting config path is `C:\Program Files\Velociraptor\/client.config.yaml` which should be  `C:\Program Files\Velociraptor\client.config.yaml`.

I don't know if this issue as any impacts on the service installation for some specific systems.

**Comment by scudette** [comment]
Are you saying this is broken? Velociraptor (and Windows) will accept either / or \ for path separators so this should not be an issue.

**Comment by mirwitch** [comment]
Further investigations showed that was not the problem. 
Closing the issue for now.
