### ISSUE TITLE
Server.Utils.CreateMSI artifact requires internet connection

### ISSUE THREAD

**Issue by amoser-lw** [Velocidex/velociraptor#3891]
Hello there,

The Server.Utils.CreateMSI artifact requires an internet connection, while our requirement is to isolate the system from the internet in an IR case.
Would it be possible to add a feature, where we specify lets say an option at the server.config.yaml to search locally for the MSI to repack with the client.config.yaml?

That would be very nice :)

![image](https://github.com/user-attachments/assets/d1149212-0bb8-452a-96c9-d619397f2511)

**Comment by scudette** [comment]
It does not - you can manually upload the MSI to the tools setup configuration as required . This is described here

https://docs.velociraptor.app/docs/extending_vql/#the-autoruns-artifact

If you need to maintain an air gaped server you might find the following artifact useful - it allows you to sync all the tools in one operation

https://docs.velociraptor.app/artifact_references/pages/server.utils.uploadtools/

**Comment by predictiple** [comment]
You can also repack the MSI on the command line:

`velociraptor config repack --msi velociraptor-v0.73.3-windows-amd64.msi client.config.yaml win_agent.msi`

**Comment by amoser-lw** [comment]
Thanks for these suggestions, I think I will use the command line approach, since I use some custom scripting and it is fitting in perfectly, thanks! 🙏
