### ISSUE TITLE
URI used to download files from parameter type upload is incorrect

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3909]
When the client attempts to fetch the uploaded file, it's clear from the log that the wrong URI is used. The Client::server_urls is not used. I expected "wss://10.0.2.2:8000", but "https://localhost:8000" is used instead. The former is the server_url configured in the client, and the latter is the server_url in the server config.

Probably related: #3581

**Comment by scudette** [comment]
wss is not a protocol that can be used for downloads. The client will use https instead to fetch the file.

We kind of assume the client config is in sync with the server config - the server calculates the URL that should be used by the client based on its own config.

Usually the client config is derived from the server config using `velociraptor --config server.config.yaml config client` so if you need to change the client's config you need to also sync the server's config or just change the server config and re-derive the client config.

**Comment by misje** [comment]
OK, so if the server URL differs depending on client, this simply will not work and is not supported.
