### ISSUE TITLE
Linux version numbering for 4.3.3

### ISSUE THREAD

**Issue by PeterWagenaarNW** [Velocidex/velociraptor#392]
It seems as though something went wrong with the version numbering of the latest linux release:

![image](https://user-images.githubusercontent.com/44571193/83156605-e6a80900-a102-11ea-949f-6e57e3603ad1.png)

As far as I can see, the .3 at the end should be a lot closer to the v0.4.3 earlier in the file name :)

**Comment by scudette** [comment]
Yeah this release had some bugs and we had to re-release it. We normally only have 3 numbers.

**Comment by PeterWagenaarNW** [comment]
No, I mean, specifically the linux release; it has a .3 at the end instead of in the version number....

**Comment by PeterWagenaarNW** [comment]
Fixed with release of 0.4.4
