### ISSUE TITLE
Allow the shell UI to use overridden shell artifacts

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#3923]
As opposed to interrogation, which picks a Custom override artifact when the button is clicked, there is no way to use a custom override for the shell artifacts (BashShell, PowerShell, CmdShell) in the shell web interface. Using a custom artifact, if available, would be very useful if, for instance, I want all my shell flows to fail if my command returns a non-zero return code.

**Comment by scudette** [comment]
You actually can override built in artifacts by specifying them in the config file or using the --definitions flag . Specifying such artifacts is considered "built in" in that they are allowed to override or mask artifacts that are compiled in.

So you can easily customize those artifacts by overriding them in the config

**Comment by misje** [comment]
Thanks for the tip, that certainly works! I just figured there was meant to be a similar mechanism to interrogation.
