### ISSUE TITLE
Running with Velociraptor executable and yaml config not collecting Event Logs

### ISSUE THREAD

**Issue by ericp502** [Velocidex/velociraptor#3933]
I'm having an issue with the ability to collect Event logs using the signed "Rapid7 LLC" (Using the velociraptor-v0.73-3-windows-amd64.exe" executable) when using a yaml file for the config.

I can create an offline collector and it works just fine. It will collect the Event Logs and all other files configured in the "Windows.KapeFiles.Targets".  If I export this offline config with the "config save" and run the signed executable with the yaml file the "Event Logs" are not collected for some reason.

The reason I want to run this with a yaml config instead of the offline collector is to reduce the likelihood that Anti-virus/EDR will block the executable. With the signed executable it is not being blocked by behavior analysis as often.

In the Yaml file under "Windows.KapeFiles.Targets" I have both "_KapeTriage" and "EventLogs" configured.  I've tried disabling each of these with the same results.

"_KapeTriage": "Y"
"EventsLogs": "Y"

The offline collector DOES collect the Event Logs but when the "veleociraptor-v0.73.3-windows-amd64.exe" executable is run with the yaml file it DOES NOT collect the Event Logs.

Any ideas?  I've tried this with other VR executables with the same result.

**Comment by scudette** [comment]
You need to use the generic collector as described here 

https://docs.velociraptor.app/docs/offline_triage/#the-generic-offline-collector

**Comment by ericp502** [comment]
Thank you.  Giving that method a try now.

**Comment by ericp502** [comment]
Unfortunately I'm having the same issue with the generic collector instead of the yaml file.  Collects everything except the Event Logs.  If I run the offline collector itself works just fine.  When I use the "velociraptor-v0.73-3-windows-amd64.exe" executable with the yaml config or the generic collector the Event Logs are not collected.

**Comment by ericp502** [comment]
I've tried the "Windows.KapeFiles.Targets with  "_KapeTriage", "_SANS_Triage" and just "EventLogs" with the offline collector executable, yaml config file (config save from offline collector) and I've tried the Generic Collector and using just the "--embedded_config".  

Offline collector executable is the only one that works.  The yaml file and generic collector doesn't collect the EventLogs and nothing in the logs about it.

**Comment by scudette** [comment]
This sounds a lot like what happens when you run the 32 bit binary on a 64 bit system. 

Can you confirm you're using the correct binary on the correct platform? 

If you attach some of the output in the issue we can look at it. Or even attach the actual generic collector you generated (it's usually very small)

**Comment by ericp502** [comment]
I can confirm that the Windows executable that is running the generic collector or yaml file is "velociraptor-v0.73.3-windows-amd64.exe".  The Velociraptor server that created the generic collector and offline collectors are running: "velociraptor-v0.73.1-linux-amd64-musl".

The offline collector runs fine and collects the Event Logs correctly as expected.  It is only when running the Windows VR executable (velociraptor-v0.73.3-windows-amd64.exe) uses the yaml config or the generic collector that it doesn't collect the Event Logs.  

[generic_collector_12022024.zip](https://github.com/user-attachments/files/17984986/generic_collector_12022024.zip)

**Comment by ericp502** [comment]
scudette, I was wrong in the post above. I double checked and the Windows version of VR I'm running on Windows is 32 bit.  I had this executable embedded into a script and thought I used the 64 bit version.  Changing it out now and I'll re-test.  Thank you for your help.

**Comment by ericp502** [comment]
That was it.  As soon as I replaced the 32-bit VR executable with the 64-bit it worked.  Sorry to bother you but thank you for the help.

**Comment by scudette** [comment]
No problem - this is a common gotcha because Windows uses WOW64 to virtualize the file system so to a 32 bit binary files appear in the wrong locations.
