### ISSUE TITLE
How do I get a list of hunts across multiple organizations?

### ISSUE THREAD

**Issue by CyberKaizen** [Velocidex/velociraptor#3944]
Looking for a way to generate user metrics across the entire server (like Hunts run per user). I don't see a way to do that outside of each individual org - is this a technical limitation or something that can be done via a hunt?

**Comment by scudette** [comment]
Orgs are separated out so when you run a query you are running that query within the context of the org. You can switch org contexts using the `query()` plugin

https://docs.velociraptor.app/vql_reference/misc/query/

So for example to see all hunts in all orgs:

```sql
SELECT * FROM foreach(
  row={
    SELECT OrgId
    FROM orgs()
  },
  query={
    SELECT *
    FROM query(query={
      SELECT * FROM hunts()
    }, org_id=OrgId)
  })
```

This query iterates over all the orgs, then runs the `SELECT * FROM hunts()` query within the org context. 

Of course your user account must have access to the orgs. Each org has a separate ACL for each user, so your user needs to have at least the READ_RESULTS permission to be able to see the org.

Some plugins (e.g. hunt() ) support orgs directly for convenience but generally you should use the above approach. This will also remind you that each such query is running in a separate org context and therefore can not see other data at the same time.

**Comment by CyberKaizen** [comment]
Thank you @scudette! I appreciate this!
