### ISSUE TITLE
Artifact bugs in 0.4.3

### ISSUE THREAD

**Issue by nixg** [Velocidex/velociraptor#398]
When trying to run `velociraptor.exe -v artifacts collect "Windows.Registry.NTUser.Upload" --output test.zip` from the command line, an error is thrown for every ntuser.dat file: `Velociraptor: scope.go:360: upload: Unable to open  C:\Users\Administrator\ntuser.dat: Invalid fixup`. This same collection works fine in 0.4.2

**Comment by scudette** [comment]
This error seems to come from the ntfs parser here https://github.com/Velocidex/go-ntfs/blob/master/parser/boot.go#L35 and is generated when the fixup array is empty.

I can't think of why 0.4.2 would not generate those errors - that code has not changed for a while.

I am not actually sure if it is possible to have no fixeups anyway? I mean fixups are a relic of the 80s when hard disks could have bit errors but this is not even possible these days so maybe Microsoft is dropping the whole thing? in that case it may be a valid possibility that the fixup array be of 0 length.

I think we should rework the code to allow for an empty fixup array.

**Comment by scudette** [comment]
This should be fixed in 0.4.4 can you please check?

**Comment by scudette** [comment]
We ignore fixup errors now. Maybe this is more robust.
