### ISSUE TITLE
Feature request: Alert examiner to flow timeout in the hunt manager

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#408]
If a flow times out during a hunt it should be clearly alerted within the hunt manager.
It's obvious if you go to the host and you can see the alert, but as you have larger hunts, this becomes difficult/time consuming

**Comment by scudette** [comment]
You can see flow results now in the stats tab.

**Comment by scudette** [comment]
This should be visible in the clients tab
