### ISSUE TITLE
Feature request: Timestamp mods

### ISSUE THREAD

**Issue by randomaccess3** [Velocidex/velociraptor#433]
It would be amazing to have a function within Timestamp that allows the examiner to optionally transform the timestamp into a specific timezone

This may not be used during an analysis as much, but preparing data for presentation to a non-technical user (that typically dont want to understand UTC and just operate in local) would be amazingly useful.

example
timestamp(epoch=ctime, tz=Australia/Sydney)
where that process reads the ctime and correctly applies AEST or AEDT.

As it's optional it shouldn't alter existing artifacts, but alllows the user a bit more manoeuvrability.

**Comment by scudette** [comment]
This is now implemented in head. Rendering the JSON timestamps takes into account the VQL "TZ" variable. Once you set this in a notebook cell all VQL in that cell will be serialized using that timezone.

![image](https://user-images.githubusercontent.com/3856546/88496122-7bde5580-cfff-11ea-89d5-66a1cf7f3cb8.png)
