### ISSUE TITLE
"Certificate is valid for VelociraptorServer" issue

### ISSUE THREAD

**Issue by mrezqi** [Velocidex/velociraptor#441]
Hi guys,

I just run the velociraptor server and deployed the client (both 0.4.5), but got this error:
```
While getting https://mysubdomain.mydomain.com:8000/: Get "https://mysubdomain.mydomain.com:8000/server.pem": x509: certificate is valid for VelociraptorServer, not mysubdomain.mydomain.com
Waiting for a reachable server: 1m10s
```

This is the only mention of Velociraptor on both config file:
`pinned_server_name: VelociraptorServer`

Still doesn't work even after removing this line. Kindly advise.

**Comment by scudette** [comment]
It looks like you server is operating in self signed mode but your client thinks it should be in autocert mode.

Have you generated client and server config files using the wizard?

You are missing the use_self_signed_ssl: true in the client config.

**Comment by mrezqi** [comment]
Thanks, that is indeed the issue. I did not generate the config with the wizard.
