### ISSUE TITLE
Allow artifact_definitions to display all artifacts

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#444]
It would be great for the `artifact_definitions` plugin to be able to return a list of all of the available default + custom artifacts (without having to specify artifact names).

Either through a generic query showing all (then filtering via the optional args, as necessary):

Ex. `select * from artifact_definitions()`

Or through the use of something like regex.

**Comment by scudette** [comment]
Providing no args now returns all definitions. You can further filter that with VQL.

**Comment by weslambert** [comment]
Thanks, Mike!
