### ISSUE TITLE
Add mmap feature to yara plugin

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#448]
Yara exe mmaps a file whilst the Velociraptor yara plugin uses a blocksize (1MB by default), then applies the yara rule to the block. This means the yara rule may fail is the signature is split across the block boundary.

We can currently choose block size as a workaround, but I think a good request would be a plugin option to also allow an mmap to provide simlar capability to yara exe.

**Comment by scudette** [comment]
This should be fixed by #461
