### ISSUE TITLE
Pseudo command shell interface on a host drill-down

### ISSUE THREAD

**Issue by ecapuano** [Velocidex/velociraptor#452]
As discussed in Discord, would be awesome if a hunter could isolate a host and type powershell commands directly into a pseudo shell presented in the web UI. This would speed up many initial response triage actions.

**Comment by sjosz** [comment]
This would be a great feature!

**Comment by scudette** [comment]
![image](https://user-images.githubusercontent.com/3856546/88082193-c5c0d900-cbc4-11ea-8c33-4600085b9cda.png)

**Comment by sjosz** [comment]
New Velociraptor features are released with the speed of light traveling to the sun - I love it! Thanks for this awesome feature, will try it when I have a chance.
