### ISSUE TITLE
Windows.Sysinternals.Autoruns artifact default config returns only system-wide results

### ISSUE THREAD

**Issue by chris-counteractive** [Velocidex/velociraptor#470]
**Description:** In the `Windows.Sysinternals.Autoruns` artifact, a newline is present in the default value of the `AutorunsArgs` parameter, which does not cause an error but **does** cause the results to only contain system-wide entries (that is, it omits autoruns entries from individual profiles).

This newline appears to suppress the meaning of the final `*` in the default command line arguments to `autorunsc` (which indicates "[all profiles](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns#autorunsc-usage)").  Rather than producing an error, `autorunsc` dutifully reports only the system-wide entries (presumably because velociraptor runs `autorunsc` as `SYSTEM`).  Once you remove the newline, entries from all profiles are returned, as described below.

This is notable because it doesn't cause errors: it can lead users to think they have all results when they're missing important entries.

**Fix:** ensure there's no newline in the default `AutorunsArgs` parameter in [the artifact definition](https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/Sysinternals/Autoruns.yaml), either by deleting it in the UI before launching (temporary) or removing it from the artifact definition (preferred).  We did this by removing the multiline-style string and replacing it with a standard string:

```yaml
# from
parameters:
  - name: AutorunArgs
    default: |
      -nobanner -accepteula -t -a * -c *
# to
    default: '-nobanner -accepteula -t -a * -c *'
```

There may be another root cause in the yaml parsing, but this does fix the issue.

**Steps to reproduce:**
1. Create an autorun in a user's profile to run an easily-findable script (e.g., a run-key `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` to run `c:\tmp\step1.ps1`)
1. Create a system-wide autorun to run a second easily-finable script (e.g., a task scheduler job to run `c:\tmp\step2.ps1`)
1. Run the `Windows.Sysinternals.Autoruns` artifact with no modifications.  Note that when you put your cursor in the edit text box for `AutorunsArgs` there is a newline after the default value `-nobanner -accepteula -t -a* -c *`:
![image](https://user-images.githubusercontent.com/48190665/86280169-e76c0900-bba0-11ea-81a0-2ce3b01a3a4c.png)
1. Download and review the results, and note you only see the system-wide test case (`step2.ps1`).  In fact, you'll see no other profiles except "System-wide".
1. Repeat these steps, but delete the newline.
1. Download and review the results, and note you see both test cases.  Note you also see entries from all other profiles on the system, including `NT AUTHORITY\LOCAL SERVICE` and `NT AUTHORITY\NETWORK SERVICE`, all suppressed in the previous output.

**Version:** 0.4.5, server running on Ubuntu, client on Windows (various versions)

As always, huge fans, love the work.

**Comment by mgreen27** [comment]
@chris-counteractive if it helps, I have been assuming autoruns is system only and using
 Windows.Registry.NTUser() artefact to ensure I get user hive keys. This method guarantees to hit all user hives on the system.

**Comment by scudette** [comment]
This is very cool analysis and the change seems reasonable. Can you prepare a quick PR to fix?

Thanks again!

**Comment by chris-counteractive** [comment]
@scudette glad to, sir - submitted #471. please let me know if you need anything else.

@mgreen27 yes indeed, that's what made this tricky, it silently gave a "reasonable" response.  we've just been using `autorunsc` for a while and knew it supported all profiles.  still no idea why it behaved like that (ignoring the final `*`), it was certainly the right inclusive default argument list, if not for that odd newline-induced behavior. in any case, glad we could collaborate on solving a problem, and help you remove those extraneous `Windows.Registry.NTUser` calls!

**Comment by scudette** [comment]
Thanks! This is now merged.
