### ISSUE TITLE
Bug: Embedded config and Windows Service mode

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#472]
@scudette 

I found a bug with the 0.4.5 agent deployed in a custom MSI: the MSI simply installs a bundled embedded config agent to a custom folder path.

After troubleshooting the embedded agent running: "AGENT.exe service run" could not use the embedded config as it is specifically looking for AGENT.client.config.yaml in the path.

To resolve the issue, I needed to either:
1. export the config out 
AGENT config show > AGENT.client.config.yaml
and ensure to AGENT.client.config.yaml in the agent path folder so the agent picks it up.
2. change the service to run in client mode "AGENT.exe client" (i.e not use the service run method).

Looking in the commit history I noticed a issue in this PR although I dont think it resolves the issue: https://github.com/Velocidex/velociraptor/pull/438/commits/36adcceb4d27d6ad23f13d930101771ee67651d8

Matt

**Comment by scudette** [comment]
Yeah that commit adds support for embedding the config in the windows service.

It sounds like you embed your config in the client then are using the velociraptor.xml file to create the msi? The custom.xml file requires packaging an actual config file with the msi.

Have you tried with a client built after that commit?

**Comment by mgreen27** [comment]
yep - I use a custom WIX config for the MSI.
I just tested with the binaries after that commit and it is working as expected.

Thank you.
