### ISSUE TITLE
Error running installer on UTF-16 Windows 7 64 bit

### ISSUE THREAD

**Issue by Oddy9923857** [Velocidex/velociraptor#475]
Error message provided my installer was the service could not be installed. The installer then rolls back. Have tried running the executable as a client but no connection initiated. User has administration rights. Not sure what the issue is, the machine is localised for Thailand. Installs have worked on many other machines on the same network. Can run tests and provide output if required.

**Comment by scudette** [comment]
What seems to be the issue with running it manually? The output of

```
Velociraptor.exe --config client.config.yml client -v
```

**Comment by Oddy9923857** [comment]
Running the client manually with the -v option there is an error message displayed : 

"Velociraptor.exe is not a valid Win32 Application"

It should be noted that the default backslash symbol is a 'yen' symbol on this machine. Not sure if that makes a difference.

**Comment by scudette** [comment]
Is this an amd64 machine or an itanium based Windows? The binary seems to not work at all. Can you even get the help with the -h flag?

**Comment by Oddy9923857** [comment]
Not sure about the -h, I'll request this is tried. I can confirm it is an Xeon cpu so that probably explains it; is there a build for ia64?

**Comment by scudette** [comment]
Sorry we cant support ia64 - Go wont compile on it. The closest comment I can see from 2015 is 
https://go-review.googlesource.com/c/go/+/9644/3/src/go/build/syslist.go#8

```
I wouldn't bother with Itanium.  It's basically a dead architecture. 
Plus, it's so hard to write a compiler for it that I really can't see it happening except 
as a labor of love, and nobody loves the Itanium.
```

So I think there is no planned support for this platform.

**Comment by Oddy9923857** [comment]
Ok, no problem. Thanks for confirming.
