### ISSUE TITLE
"Download files in this folder and below" does not do as it says

### ISSUE THREAD

**Issue by ecapuano** [Velocidex/velociraptor#478]
v0.4.4

I've tried to use this feature a few times on Windows/Linux systems and every time, it simply returns an empty ZIP. Retrieving individual files in these locations works fine, but not the entire directory.

![image](https://user-images.githubusercontent.com/4219694/86957875-f6af0180-c120-11ea-8bc8-fb6f9ea6e856.png)

**Comment by ecapuano** [comment]
We're on 0.4.4 because of https://github.com/Velocidex/velociraptor/issues/469

**Comment by scudette** [comment]
Just to be clear, this feature only download the files already downloaded into the vfs using the collect button in the vfs. It is not that useful in practice so we never really use it.

If you want to download all the files from the client you are better off with the file finder artifact to collect the file then download the results.
