### ISSUE TITLE
Custom Base Path

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#484]
It would be great if we could specify a custom base path, for example, for use with a proxy fronting multiple apps/paths.

It may be possible to do something like the following:

http://www.verdantrefuge.com/writing/2013/angularjs-changing-app-path-base-element/

.. in conjunction with setting the path for the cookie:

https://github.com/Velocidex/velociraptor/blob/master/api/oauth.go#L84

**Comment by scudette** [comment]
Can you please test the latest CI build? You should be able to specify a base_path in the GUI config.

**Comment by weslambert** [comment]
Yep, will do so as soon as I can. Thanks, Mike!

**Comment by weslambert** [comment]
Looks good from my testing so far! 👍

**Comment by scudette** [comment]
Available in 0.4.9
