### ISSUE TITLE
Request - ability to customise service description

### ISSUE THREAD

**Issue by SekDev** [Velocidex/velociraptor#5]
Hi, is it possible to add a paramater to the client config to specify a custom service description ?

I'm trying to ensure adversary wont as easily detect the client during a hunt operation. Cheers

eg. client.conf.yaml

  windows_installer:
     install_path: $ProgramFiles\blah\Velociraptor.exe
     service_name: Velociraptor
>> service_description: Velociraptor service name

**Comment by scudette** [comment]
Should be possible now 179db9ab488cd039ea67afa5af6e975b7e89dcd4
