### ISSUE TITLE
Feature request: Linux Process Artifact

### ISSUE THREAD

**Issue by mlucas300** [Velocidex/velociraptor#503]
It would to be great to be able to have a Linux equivalent of the Windows.System.Pslist artifact.

**Comment by scudette** [comment]
Did you need some more features in Linux.Sys.Pslist?

**Comment by mlucas300** [comment]
Hi Mike, 

I think I must have not seen Linux.Sys.Pslist, so I'll just close this issue. In fact we were surprised to find out that Linux.Sys.Pslist also works on Windows which is nice :-)

Regards,
Martin.
