### ISSUE TITLE
SSL/TLS Offloading for GUI

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#508]
It appears we can now offload TLS for the Frontend (https://github.com/Velocidex/velociraptor/issues/483), which is great (thank you! 🙏 ), however, it would be even better if we had the ability to offload for the GUI as well, so that we could have something like nginx provide TLS for us for both the Frontend and the GUI.

**Comment by scudette** [comment]
This is now implemented in head - you can download all binaries from the actions tab on github.

NOTE: https://github.com/Velocidex/velociraptor/blob/master/config/proto/config.proto#L281
```
    // Allows the GUI to start with no encryption - **WARNING** This
    // only makes sense if you have TLS proxy in front. In fact the
    // GUI **will not work** without a TLS proxy because the csrf
    // cookie is set to secure only.
```
