### ISSUE TITLE
Bash option for GUI shell does not work

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#524]
As discussed previously, it appears the Bash option for the shell in the GUI does not work as intended.  There is no output returned to the GUI when executing commands via the `Bash` shell option as opposed to the` Cmd`, or `Powershell` options.

**Comment by scudette** [comment]
This should have been fixed with the 0.4.7-1 bugfix. Did it not?

**Comment by weslambert** [comment]
Whoops...I actually have not had a chance to test that...wasn't aware it would be in there...let me confirm. 😄

**Comment by weslambert** [comment]
Okay, so it does look like it works for 0.4.7-1 for `Bash`.  Although, it looks like there is no 0.4.7-1 for the darwin -- is that intentional?  Also, it may be good to have a kill switch, or mechanism to kill the command initiated by the shell if possible, because if you run something like `ping` on linux without any terminator or limit on the number of pings, then it will run indefinitely.  I could put in a separate issue for something like that, if needed, or if you feel that is something that should be considered.

**Comment by kerbalette** [comment]
It will run as SYSTEM account. Need to elevate up to kill it.  Is this a
server side fix or do agents need the new binary?

**Comment by scudette** [comment]
There should be a 10 min query limit by default. You should be able to cancel the query from the collected artifacts screen and this should in theory kill the child process (can you confirm?)

Maybe we need a shortcut key in the shell GUI to do the same?

**Comment by weslambert** [comment]
Seems like even if I kill it on the collected artifacts page, the spinning icon still shows in the shell UI.

![image](https://user-images.githubusercontent.com/16829864/89091156-5772d800-d375-11ea-8398-8b438c9a8ca3.png)


![image](https://user-images.githubusercontent.com/16829864/89091146-432edb00-d375-11ea-96a2-1daf5137dd7a.png)

I think from a UX perspective, it would be great to have a shortcut in the shell GUI to do something like that(maybe next to `Load Output`, or something similar).

**Comment by scudette** [comment]
Yeah totally! We need to add a cancel button to the GUI in case the command over ran itself.

**Comment by weslambert** [comment]
👍  Okay, I will close this issue and create a new one to reference the cancellation of commands via the GUI.
