### ISSUE TITLE
Consistent Version Tagging

### ISSUE THREAD

**Issue by clong** [Velocidex/velociraptor#528]
Hello, huge fan of the project! I use a script to determine the latest tagged release of Velociraptor to dynamically determine the download URL, but unfortunately in the latest release there's a mix of "v0.4.7" and "v0.4.7-1". This causes the script to fail 😞

In future releases, would it be possible to keep the versioning consistent on the releases page?

![image](https://user-images.githubusercontent.com/5092699/89133803-f877a500-d4d3-11ea-98c0-297fcdbb5766.png)

**Comment by scudette** [comment]
Hi - yeah I had to push out a 0.4.7-1 release to fix a couple of GUI issues (and a file upload issue) that crept into the release.

The versioning on the releases page is not relevant - you can always get the latest release asset by simply asking Github for it. For example:

```
curl https://api.github.com/repos/velocidex/velociraptor/releases/latest | jq 'limit(1 ; ( .assets[].browser_download_url | select ( contains("windows-amd64.exe") )))' 
```

Shows the latest URL for the latest windows amd64 binary release (you can also write this in python or maybe even use grep :-).

**Comment by clong** [comment]
Ah, that's a nice little snippet! The script is powershell, so time to see if it natively supports JSON parsing. I'll figure it out, thanks! 🙂

**Comment by scudette** [comment]
There is nothing for us to do here ...
