### ISSUE TITLE
When KapeRules are specified, output is empty

### ISSUE THREAD

**Issue by op7ic** [Velocidex/velociraptor#536]
Hi Team, 

I can use following config to capture whole bunch of good things from the system:

```
autoexec:
  argv: ["artifacts", "collect", "-v", "Windows.KapeFiles.Targets",
         "--output", "collection_$COMPUTERNAME.zip",
         "--args", "WebBrowsers=Y",
         "--args", "_BasicCollection=Y",
         "--args", "EventLogs=Y"]
```

However, if I add KapeRules so the config is as follows, nothing gets captured and resulting ZIP file is empty:

```
autoexec:
  argv: ["artifacts", "collect", "-v", "Windows.KapeFiles.Targets",
         "--output", "collection_$COMPUTERNAME.zip",
         "--args", "WebBrowsers=Y",
         "--args", "_BasicCollection=Y",
         "--args", "KapeRules=Y",
         "--args", "EventLogs=Y"]
```

In both cases above I execute following command to generate my own collector and collector without KapeRules runs just fine.

```
velociraptor-v0.4.7-windows-386.exe config repack myconfig.txt mycapture.exe
```

Here is output from failed execution when "KapeRules" is specified :

```
> mycapture.exe
[INFO] 2020-08-04T18:19:50+03:00 Loaded embedded config
[INFO] 2020-08-04T18:19:50+03:00 Autoexec with parameters: [artifacts collect -v Windows.KapeFiles.Targets --output collection_XXXX.zip --args WebBrowsers=Y --args _BasicCollection=Y --args EventLogs=Y --args KapeRules=Y]
[INFO] 2020-08-04T18:19:50+03:00 Loaded embedded config
[INFO] 2020-08-04T18:19:50+03:00 Loaded 169 built in artifacts in 52.1875ms
[INFO] 2020-08-04T18:19:50+03:00  Will create container at collection_XXXX.zip
[INFO] 2020-08-04T18:19:51+03:00 Compiled all artifacts.
[INFO] 2020-08-04T18:19:51+03:00  Collected Windows.KapeFiles.Targets/All File Metadata
[INFO] 2020-08-04T18:19:51+03:00  Collected Windows.KapeFiles.Targets/Uploads
[
 {
  "Container": "collection_XXXX.zip",
  "Report": ""
 }
][INFO] 2020-08-04T18:19:51+03:00 Collection completed in 1 Seconds
```

Version:
```
velociraptor-v0.4.7-windows-386 
```

**Comment by scudette** [comment]
KapeRules are the rules that we compile from the KapeFiles repository - it is very unlikely you will want to override them and if you do this is not the format you should use:

https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/KapeFiles/Targets.yaml#L408

By specifying them in the --args you are overriding the parameter which might make sense in limited situations but probably not what you intended - instead it breaks the VQL :-).

**Comment by op7ic** [comment]
yep figured it would normally pick them up but I think it would be great if there would be some error that alerts users - otherwise you might end up with a lot of empty files ;)

**Comment by scudette** [comment]
There is no error because the parameter is valid but probably not quite what you meant :-). It expects a CSV and you provided "Y" which is also a valid CSV file (with one column called Y and no rows). Therefore it parsed it and found no rules and therefore skipped everything and produced no results.

In the GUI the parameter is hidden which discourages people from messing with it but on the commandline you can do anything :-).

**Comment by op7ic** [comment]
make sense I guess. I`ll close this issue in this case.
