### ISSUE TITLE
Improve Quarantine feature

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#544]
We want to improve the Quarantine feature.

1. Add view Quarantine status content
2. Add gui option to quarantine and view quarantine status

**Comment by yampelo** [comment]
You can do the first one with the new `client_set_metadata` function which would show up here:

![image](https://user-images.githubusercontent.com/6065272/94097914-729e1900-fdf5-11ea-9dad-22792d919d53.png)

**Comment by scudette** [comment]
This is now in 0.6.1
