### ISSUE TITLE
Allow setting download format (json/csv) in config

### ISSUE THREAD

**Issue by CR-OmerYampel** [Velocidex/velociraptor#555]
Is it possible to allow us to define the output formats we want in the downloaded zips in a config entry? I have cases where the download is ~500mb because it contains a csv with 150mb and a json with 350mb where i only use the csv.

**Comment by scudette** [comment]
Just checking - are you specifically talking about the combined hunt results csv/json? Or the download flow button?

**Comment by scudette** [comment]
Available in 0.4.8
