### ISSUE TITLE
3rd party tools editing capability

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#572]
I have been working in an environment where I am an administrator in the GUI but have no access to the back end.
Currently using notebook to edit and add to the 3rd party tools infrastructure and its working well but overall a bit clunky.

What I would love to see from a UX perspective is a simple upload and edit box configuration capability (similar to offline collector). I think this would help user experience significantly.

Matt

**Comment by scudette** [comment]
Check out the latest commit:

![image](https://user-images.githubusercontent.com/3856546/90715620-1b84c000-e2ee-11ea-833f-256323205ece.png)

![image](https://user-images.githubusercontent.com/3856546/90715645-36573480-e2ee-11ea-87a2-85a03f97d14c.png)

Please test and provide feedback...

**Comment by scudette** [comment]
Available in 0.4.9
