### ISSUE TITLE
Velo /tmp file output filled my disk - is there a more optimal way to log failed events to disk?

### ISSUE THREAD

**Issue by SekDev** [Velocidex/velociraptor#6]
Hi, i've been testing the Velo server on a Ubuntu host, with 2 clients (1x win7, 1x ubuntu).

I had some tasks sent to my clients and one was failing, I forgot about it and left the server running for what seems like a week, then i noticed my Ubuntu host was saying the disk was full, I seemed to have tens of millions of .db files in my /tmp folder, if my analysis is correct - Velo seems to create a .db file in /tmp for each failed Flow ArtifactCollector log ? 

I only noticed this because when I rebooted - the sheer amount of files caused Ubuntu to fail to boot, or at least it was taking forever to boot, maybe trying to do a /tmp purge, I gave up and eventually had to manually clear out the /tmp folder using a Live CD.

So this leads me to some questions, 

- is it necessary to create what seems like a separate .db file for each ArtifactCollector failure, not just a .log file ?
- i assume its stored in /tmp due to default "DataStore" config, but is there a reason these errors werent being committed to a log outside of /tmp ?
- should there be a default timeout enforced in all artifact collection tasks to prevent this type of thing happening ? admittedly i dont really know why it was failing but an idiot proof timeout might prevent this type of thing.

---------------------------------------------------------------------------------------------------------
$sudo ls /tmp/velo/users/test-user/notifications/pending

[example /tmp directory listing]

```
1549419092985746.db  1549537163181385.db  1549698847410046.db  
1549924433119874.db  1550206872154305.db  1549419095623858.db  
1549537163184089.db  1549698847413535.db  1549924433134528.db  
1550206874124526.db  1549419095625958.db  1549537165717240.db  
1549698847415650.db  1549924433142233.db  1550206874125264.db
1549419095628052.db  1549537165717921.db  1549698847423309.db  
1549924438316875.db  1550206874125922.db ^Z
```
-----------------------------------------------------------------------------------------------------

[example .db file content]

$ sudo cat 1549537163184089.db

<blah> .... Flow ArtifactCollector failed!.2""

**Comment by scudette** [comment]
These are the user notifications. In a recent change they were refactored to write a (single) user notification log file:
https://github.com/Velocidex/velociraptor/blame/master/users/notifications.go#L77

Are you running a recent server version?

Do the corresponding flows show as finished or still running in the GUI?

**Comment by SekDev** [comment]
The flow state was RUNNING with notifications still being logged, not sure which artifact is causing the error as I ran a bunch together. Possibly ProcessCreation, if the # 2 in the log [Flow ArtifactCollector failed!.2] corresponds to the artifact number ?
 	
Artifact context
-------------------------------------
Generic.Client.Stats
Windows.Events.ProcessCreation
Windows.Events.ServiceCreation
Windows.Sys.StartupItems
Windows.Sys.Programs
Windows.Sys.AppcompatShims
Windows.Packs.Autoexec

----------------------------------------------------------------------------------------------------------------
I can try the next binary release package once it becomes available to see if that helps.

build_time: "2018-12-28T18:07:03+10:00"
commit: 5bc335e
name: velociraptor
version: 0.2.7

**Comment by scudette** [comment]
The current release is 0.2.8 which should solve the logging issue. 

This brings another interesting issue which is that collecting Windows.Events.ProcessCreation artifact does not make sense because it will never terminate. It is an event collection artifact and it is  used within the Event Monitoring framework:

https://docs.velociraptor.velocidex.com/blog/html/2018/12/09/more_on_client_event_collection.html

We should probably reject such artifacts from the Artifact collector flow?

**Comment by scudette** [comment]
Argh sorry my mistake - I prepared the 0.2.8 release a couple weeks back but had not realized it was still a draft on GH so it never shows it.

**Comment by SekDev** [comment]
Sounds fair to me, I think filtering out monitoring queries from the collect would be a good way to reduce potential log noise that I came up against. 

On that note, maybe an alternate query to only collect currently running process list then exit, would be a valid replacement collector, if its not already captured by one of the other collectors you have built.

Cheers

**Comment by scudette** [comment]
We now filter out monitoring artifacts as well as timeout queries. This should assist in now letting a user select monitoring artifacts in the first place and if they do the artifact will timeout after 600 seconds by default. 

There is now a simple Windows.System.Pslist artifact for simple single use process list collection.
