### ISSUE TITLE
Help for Install on Ubuntu 18.04

### ISSUE THREAD

**Issue by yazarneon** [Velocidex/velociraptor#621]
Hi,

Have you any setup video or step by step a text for install. I tryed Everythings but I cound not install this tool. I could not start gui.
 
I tryed everthings on this title. "Building from source"

I need setup this tool.

Thank You

**Comment by scudette** [comment]
You probably dont need to build from source - just grab the release binary.

We have a youtube channel https://www.youtube.com/channel/UCT0g9A7Jf1rcpUcvWR0ycng/playlists

This one helps you install it https://youtu.be/l1_sKDmNWS4
