### ISSUE TITLE
Be able to import VQL functions 

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#625]
Since VQL functions appeared we can write some useful reusable code. But there is no way currently to share that between different artifacts. We need a way to import functions from another artifact without importing the actual queries.

**Comment by CR-OmerYampel** [comment]
It might also be useful to allow us to define globals. Similar to how the tools are a global that is injected into every VQL. A use case of this may be an S3 key, or a specified output path, instead of having to define it in each sub-vql

**Comment by scudette** [comment]
That's the same thing since you can always define global in vql:

```sql
LET Foo = "some string"
```

As long as we can import that then it will be defined in the scope.

The question is more about do we want to also allow parameters to be imported (so the GUI can offer to change them)

I tend to think not otherwise it would explode the number of form parameters making the GUI more complex and possibly adding un needed parameters by way of an import.

**Comment by scudette** [comment]
This is now available in 0.6.0 rc1
