### ISSUE TITLE
Feature request: scrollable artifacts without search keywords

### ISSUE THREAD

**Issue by h4sh5** [Velocidex/velociraptor#627]
Hi, I'd like to request a quick UX improvement regarding adding hunts.
During artifact selection for a hunt, it would be great if the interface displays all loaded artifacts in the window (screenshot below) so that users can start off choosing from them instead of manually lookup up / through the artifacts list. 

It could be as simple as handling term=* or term= (nothing) queries, just to create an impression that they are there.

![image](https://user-images.githubusercontent.com/38898566/92511510-bf5bee80-f250-11ea-8059-a62e8fd3012e.png)

**Comment by scudette** [comment]
This is the way it is in the new GUI redesign.
