### ISSUE TITLE
Issue with event log ID filtering in 033

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#63]
Im testing some IOCs in new 0.33 and notice my eventID filter is not working in the latest.

Looks like the data is there as running the query without a filter I can find the relevant event but I cant seem to filter.

I tried filtering on the integer directly (as what works in 032) and using atoi() same results.

Expected results in 0.3.2

Matt

        SELECT *
        FROM foreach(
          row=files,
          query={
            SELECT timestamp(epoch=System.TimeCreated.SystemTime) As EventTime,
              System.EventID.Value as EventID,
              System.Computer as Computer,
              System.Security.UserID as SecurityID,
              EventData.AccountName as ServiceAccount,
              EventData.ServiceName as ServiceName,
              EventData.ImagePath as ImagePath,
              EventData.ServiceType as ServiceType,
              EventData.StartType as StartType,
              System.EventRecordID as EventRecordID,
              System.Level as Level,
              System.Opcode as Opcode,
              System.Task as Task
            FROM parse_evtx(filename=FullPath, accessor=accessor)
            WHERE System.EventID.Value = 7045
        })

**Comment by mgreen27** [comment]
I think this is related to integer type as changing the filter to be a floating point works as expected.
e.g WHERE System.EventID.Value = 7045.00

Returns expected results in both 033 and 032.

**Comment by scudette** [comment]
Yep this is a problem with VQL numeric comparisons. Probably introduced when we added various int types as native to VQL (https://github.com/Velocidex/velocifilter/commit/099a571effd4f0098cd3af0d8812ab1c5e10aac4).

Thanks for reporting :-). I also added a test to ensure it wont regress. You can grab the latest HEAD build from https://ci.appveyor.com/project/scudette/velociraptor-ialou/builds/27259110

**Comment by mgreen27** [comment]
thanks mike!
