### ISSUE TITLE
Delete button doesn't work on errored artifacts

### ISSUE THREAD

**Issue by chris-counteractive** [Velocidex/velociraptor#636]
Version: 0.4.9 on Windows 10, tested in Chrome, new Edge, and Firefox

Steps to reproduce:

1. Start the gui using `velociraptor gui`
1. Run a collection that errors out due to size (e.g., a KapeFiles collection that exceeds the byte count).  Let this run until it errors, displaying a "!" in the collected artifacts list:
![image](https://user-images.githubusercontent.com/48190665/93120692-5aa5f700-f689-11ea-9854-cbd19a3ae2bd.png)
1. Try to delete the collection using the trashcan button:
![image](https://user-images.githubusercontent.com/48190665/93120834-8de88600-f689-11ea-87ef-42593f670d5b.png)
1. Observe that nothing happens 😃 

Notes:

1. Deleting successfully completed collected artifacts appears to work fine (those with a check mark ✔️).
1. If you add a few successful artifacts after the errored one (say, a few ListDirectory items from the VFS browser), then try to delete it, it jumps to the top of the list, apparently "refreshed" in the index to appear newer in the sort order.
1. Did not test with "normal" installation, just under the `gui` command.
1. No errors show in the JS console; looks like that functionality is implemented with a post to the `ArchiveFlow` API with the client ID and flow ID, not sure the best way to see debugging info from those calls ... happy to help with more info if pointed in the right direction.
1. It seems to be the error state, not the specific artifact, that matters.  You can repro with a simpler, smaller artifact like `PsList` and limit the row constraint to something smaller than the normal result set (100 worked in testing).

Apologies if this is a known issue, couldn't find reference to it in the issues list or discord.  Thanks!

**Comment by scudette** [comment]
I wonder if this seems to be as a result of the ui not refreshing the new flow list? if you navigate away from the flows screen and back or hit refresh does it properly update the list?

**Comment by chris-counteractive** [comment]
Thanks for looking into it.  It doesn't appear to be a UI refresh issue: deleting/archiving completed flows works instantly, and refreshing or navigating away has no affect on the errored flow(s).

**Comment by scudette** [comment]
The new GUI has real delete - i.e. the data is really nuked from disk. It should work.
