### ISSUE TITLE
Feature request: calculate Import Hash (ImpHash)

### ISSUE THREAD

**Issue by e-kriz** [Velocidex/velociraptor#641]
Hi. It would be great to have a feature that allows to calculate the Import Hash (ImpHash) from a binary. It can be a handy tool to find and identify malware binaries in a network belonging the same family.

**Comment by scudette** [comment]
Implementation here https://github.com/erocarrera/pefile/blob/master/pefile.py#L3922

**Comment by scudette** [comment]
Fixed with 0.5.5 release
