### ISSUE TITLE
Add admin privilege check to client command

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#656]
The recently added `--require_admin` switch on the `artifacts collect` command invokes the [CheckAdmin function](https://github.com/Velocidex/velociraptor/blob/1fa4f5e1a77272db976ee214a8dd7d6b10378158/bin/artifacts.go#L128). The primary use case for this is as an `autoexec` switch in offline collectors where VR will exit if the collector is run without admin privileges, thus avoiding an incomplete collection when certain embedded artifacts require admin privilege.

Because VR can also be used as a non-installed `client` for triage purposes, we could also avoid unexpected incomplete collections by ensuring that the client is run with admin privilege. This could be done by adding the same `--require_admin` flag to the `client` command to invoke the CheckAdmin function.

**Comment by scudette** [comment]
Fixed by #1989
