### ISSUE TITLE
Allow CheckAdmin function to be called from artifacts

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#657]
The recently added `--require_admin` switch on the `artifacts collect` command invokes the [CheckAdmin function](https://github.com/Velocidex/velociraptor/blob/1fa4f5e1a77272db976ee214a8dd7d6b10378158/bin/artifacts.go#L128). The primary use case for this is as an `autoexec` switch in offline collectors where VR will exit if the collector is run without admin privileges, thus avoiding an incomplete collection when certain embedded artifacts require admin privilege.

When collecting from multiple artifacts, not all of them may need admin privilege. If the CheckAdmin function can be called from within artifacts then each artifact can adjust it's collection logic based on the result, or a standalone `check_admin` artifact could be used in an artifact chain, or the standalone artifact could be used simply to verify that the client is running with admin privilege before proceeding with further investigation work on that endpoint.

**Comment by scudette** [comment]
This can already be done using the tokens() plugin right? If the velociraptor process has the system token or elevated token then it can be read the raw disk.

**Comment by predictiple** [comment]
wow, I learn something new every day! If that's the case then this feature request can be closed.

**Comment by predictiple** [comment]
The argument against using token() is is that it's Windows-specific while CheckAdmin is cross-platform.

**Comment by scudette** [comment]
But artifacts are rarely cross platform? most artifacts apply to one platform only and if there is a sensible fallback then it can use the correct platform check. I am actually not convinced that we should fallback if not running with the right permissions - if an artifact can not get the desired data would you rather partial results (which might be confused with no data at all) or a failure in a clear way that it can not run?

I would rather put these kinds of checks in VQL - this allows them to be very refined. For example it might be more about file permissions not just running as admin. Sometimes you actually need to run as non-admin - for example to access network resources typically a domain user is more powerful than system.

**Comment by predictiple** [comment]
Good points and I agree mostly but perhaps I am imagining a use case that is less idealistic: We are often relying on untrained people - sometimes even non-IT people - to run the client. I know of organisations in my region where the staff barely know how to use a mouse and they are sometimes too shy to admit that don't know what "run as administrator" means. To be fair, that person may be the company accountant. Then we run a triage collection and stuff fails and we then have to spend an hour on the phone talking them through How-To-Windows... that's _if_ the aren't travelling IT support people who have already left their remote site and flown back to head office.

So what I'm envisaging for the CheckAdmin artifact is more like a remote "is the client running as admin?" ping. If no then we have a list of machines where there will potentially be problems during collection or when running tools.

I thought it might make sense to leverage the already-existing and compartmentalised functionality, rather than reproduce a more nuanced version of it in VQL. Having a basic check would not preclude anyone from writing a more advanced check. 

Personally I rank this enhancement idea as far less important/useful than my other request to have CheckAdmin added to the client command because that will obviate the need for this in my use case. If there was really a need for this in artifacts then I'm sure you would have heard it requested by someone else by now.

**Comment by predictiple** [comment]
As an alternative to this maybe the info() plugin could report back the CheckAdmin result as an additional field?

**Comment by scudette** [comment]
Added an IsAdmin field to the info() plugin.
