### ISSUE TITLE
Question on "Windows.Packs.Autoexec" output

### ISSUE THREAD

**Issue by mrezqi** [Velocidex/velociraptor#666]
Hi,

I ran a flow for autoexec items today and got the below result on quite a lot of machine:
"Name" : "@"
"Path" : ""

Could somebody tell me what does the @ symbol there mean?

**Comment by scudette** [comment]
That artifact is an old artifact that basically calls `Windows.Sys.StartupItems` - you should try to collect that one to get more information but I assume that is finds some values with the default value (@) in the registry Run keys.

You are probably better off to run the sysinternals autoruns artifact as it is more complete.

**Comment by mrezqi** [comment]
Aha, thanks for the explanation. Still I'd like to understand what is causing this @ thing.
I checked the machine in question and in the registry there is indeed this (Default) key with (value not set):
![image](https://user-images.githubusercontent.com/2455832/94917760-7561d380-04b1-11eb-827d-704b34e8612d.png)

So I guess this is probably the cause?

**Comment by scudette** [comment]
Can you see the same result when collecting the Windows.Sys.StartupItems?

**Comment by mrezqi** [comment]
Yes, you are right. Let me close this issue. Thanks so much 👍
