### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#680]
This is an issue where we can add suggestions to the new GUI. At this stage I don't want to make large changes but small things that make the experience better.

# hotkey navigation. 
- [x] top level navigation to open sidebar
- [x] hotkey for starting collection, copy collection when in collection view, new notebook when in notebook view etc.
- [x] hotkey to focus search for client

# extra functions
- [ ] make hunt from flow button
- [x] in vfs recursively download directory should actually download files from host.

**Comment by scudette** [comment]
Release checklist for GUI functionality
- [ ] Upload artifact pack
- [ ] flow overview - prepare download and report
- [ ] notebooks - export notebook
- [ ] add cell from hunt/flow/artifact
- [ ] create artifact from VQL cell
- [ ] host view interrogate button
- [ ] automatically hide columns starting with _

**Comment by scudette** [comment]
- [ ] Add delete client button
- [ ] Have a UI to edit hunt descriptions

**Comment by randomaccess3** [comment]
- [ ] Option to edit the description in the hunt manager to allow users to provide further details - particularly useful when a hunt has partially completed, or is being "managed" (strategically turned on and off)
- [ ] Clarify whether ctime displayed in the UI in VFS is created time or change time. It's not obvious
- [ ] When a file has been collected in VFS, calculate and display its hash in the file properties. Useful for malware investigations!

**Comment by scudette** [comment]
- [ ] be able to serve from a different base path

**Comment by scudette** [comment]
- [ ] Copy hunt to rerun the same hunt again.

**Comment by scudette** [comment]
- [ ] Timestamps should have a tooltip of how long ago it was (makes it easier to see e.g. last week, 3 days ago etc).

**Comment by scudette** [comment]
- [ ] Add a close mark to label selection in remove label button.

**Comment by weslambert** [comment]
- [ ] allow client search by last seen ip
- [ ] allow client search by label

**Comment by scudette** [comment]
> * [ ]  allow client search by last seen ip (ex. `ip:192.168.1.101`)
> * [ ]  allow client search by label/metadata (ex. `label:group1`)

We already allow label search like that. For ip based search it is more complicated because in many environments IP addresses are reused or shared with many hosts (e.g. NAT) so an IP based search is not that useful - just because the client had that IP in the past does not mean it has it now. This can probably be enhanced with #701 though we probably can not actually create an index here.

**Comment by weslambert** [comment]
> > * [ ]   allow client search by last seen ip (ex. `ip:192.168.1.101`)
> > * [ ]   allow client search by label/metadata (ex. `label:group1`)
> 
> We already allow label search like that. For ip based search it is more complicated because in many environments IP addresses are reused or shared with many hosts (e.g. NAT) so an IP based search is not that useful - just because the client had that IP in the past does not mean it has it now. This can probably be enhanced with #701 though we probably can not actually create an index here.

Thanks, Mike! Is there an example of how we might perform the label/metadata search?  I just tried with the key:value set for some arbitrary metadata, and it didn't seem to find the intended client.  With regard to IP address, I certainly realize the complications and caveats when searching by IP, but would still think at least having the option would be better than not, presuming it wouldn't be too much extra work on the backend.

**Comment by scudette** [comment]
You can search by label by just typing "label:mylabel" in the search bar because labels are indexed. We do not index the metadata though so you can not directly search by this.

For all your other search needs as you highlighted you can run a VQL query which will basically scan all the clients but filter by arbitrary conditions (if you have a lot of clients say > 10k, it may take a couple min). If you think you will need that same search again you can just apply a label on that VQL and then search by that label in the GUI.

**Comment by scudette** [comment]
Should be fixed in 0.5.3
