### ISSUE TITLE
Windows.Memory.Acquisition - Failed Error

### ISSUE THREAD

**Issue by prats84** [Velocidex/velociraptor#70]
In my test setup I tried to acquired memory from Windows using Windows.Memory.Acquisition. However, i receive the below error on failure/termination. 

```
1568376511898144 | 2019-09-13 12:08:31 +0000 UTC | vql: scope.go:313: Symbol binaryURL not found. Current Scope is: [NULL, __destructors], [Artifact], [$responder, $uploader, config, $cache], [$throttle], [Windows_Memory_Acquisition_0_0]
-- | -- | --
1568376511917875 | 2019-09-13 12:08:31 +0000 UTC | vql: scope.go:313: http_client: parse [https://<FQDN>:8443/public/inventory.csv]: first path segment in URL cannot contain colon
1568376511917875 | 2019-09-13 12:08:31 +0000 UTC | Time 0: Windows.Memory.Acquisition: Sending response part 0 2 B (0 rows).
```
I am a newbie to Velociraptor as such I might have had some configuration errors. 

Thanks.

**Comment by scudette** [comment]
This artifact is using the upcoming VQL plugin feature. It is not well documented yet but basically it works by sending a binary to the endpoint (in this case WinPmem) to do the actual acquisition and then uploads the image to the server. To make it work you need to:

1. Ensure there is a public_path set in the config file (new config files generated will include it already):
```
Frontend:
  public_path: /var/tmp/velociraptor/public/
```

2. Click the server artifacts and run the `Windows.Utils.DownloadBinaries` artifact. This artifact will download the required binaries to the server and generate the inventory file (which contains hashes). You can run this artifact (or a copy of it) any time you want to refresh the binaries you want to expose (e.g. if you want to have your own VQL plugins).

After doing this, when you run the `Windows.Memory.Acquisition` artifact the endpoint will download winpmem from the server and store it locally and then use that to acquire memory, once that is done it will upload the image to the server and remove it from the endpoint.

I hope to document this mechanism better in the near future.

**Comment by prats84** [comment]
Thanks for the update. 

In my Server config file I had the public_path setup as below, and I ran the ```Windows.Utils.DownloadBinaries ```. However, the executed flow terminated and nothing was populated in the server public_path folder and no logs are created in the UI for this terminated flow. 

```
Frontend:
  public_path: /mnt/velociraptor_datastore/public/
``` 

I than proceeded to download the binaries manually into the  server public_path and manually created the inventory.csv :

```
Tool,Type,URL,ExpectedHash

Autorun,amd64,autorunsc64.exe,bea5da8b6487dac6e0c7ab5a4c6f0dc0c2b89d6870199dc6f75ae425bde896a6
Autorun,x86,autorunsc.exe,083d7eee4ed40a3e5a35675503b0b6be0cb627b4cb1009d185a558a805f64153
WinPmem,.,winpmem_v3.3.rc2.exe,6ca71c13f98eeed8ffc0a9edb8eea787624b90018bd4f64672439af35c3ec820
Sysmon,amd64,sysmon64.exe,4a5c255abe9af16eecc16e81413b150c997632fe4d82eb6d8ccf255be6e5152c
Sysmon,x86,sysmon.exe,ba0b8fabcc0e067184d4ee53d155d1245a435247539a64dd2a6621729dd24e5b
```

However, the memory acquisition workflow still failed with the below error

```
timestamp,time,message
1568470430008767,2019-09-14 14:13:50 +0000 UTC,"vql: scope.go:313: Symbol binaryURL not found. Current Scope is: [NULL, __destructors], [Artifact], [$responder, $uploader, config, $cache], [$throttle], [Windows_Memory_Acquisition_0_0]
"
1568470430017445,2019-09-14 14:13:50 +0000 UTC,"vql: scope.go:313: http_client: parse [https://<domainName>:8443/public/inventory.csv]: first path segment in URL cannot contain colon
"
1568470430018065,2019-09-14 14:13:50 +0000 UTC,Time 0: Windows.Memory.Acquisition: Sending response part 0 2 B (0 rows).
```

**Comment by scudette** [comment]
First lets work out why `Windows.Utils.DownloadBinaries` did not work - do you have any info in the server logs? When you run the frontend with -v flag I can see (removing irrelevant lines):
```
[INFO] 2019-09-14T14:45:55Z Fetching https://live.sysinternals.com/tools/autorunsc64.exe
[INFO] 2019-09-14T14:45:57Z http_client: Downloading https://live.sysinternals.com/tools/autorunsc64.exe into /tmp/tmp918237183.exe
[INFO] 2019-09-14T14:45:58Z copy: Copying file from /tmp/tmp918237183.exe into /var/tmp/velociraptor/public//autorunsc64.exe
```

The error message `parse [https://<domainName>:8443/public/inventory.csv]: first path segment in URL cannot contain colon` means that http_client receives literally '[https:// ...]' which is not a valid URL. Maybe the server urls are misconfigured? It seems to be passed a list instead of a string for some reason?

On my machine the following connects to the correct url:

```
F:\>velociraptor.exe -v --config my_client_config.yaml query "SELECT * FROM  http_client(url=get(item=config.ServerUrls, member='0') + 'public/') "
[INFO] 2019-09-14T15:04:37Z Loaded 139 built in artifacts
velociraptor: scope.go:315: Fetching https://192.168.0.6:8000/public/
velociraptor: scope.go:315: Shutting down due to interrupt.
```

Where my client config file contains:
```
Client:
  server_urls:
  - https://192.168.0.6:8000/
  - https://192.168.0.6:8000/
```

**Comment by prats84** [comment]
* On the server running with -v and exeucting ```Windows.Utils.DownloadBinaries```, the servers indicate that the inventory file cannot be opened. 
 `Logs`
```
[INFO] 2019-09-15T01:05:56Z LaunchFlow {"client":"server","details":"creator:\"admin\" client_id:\"server\" flow_name:\"ArtifactCollector\" start_time:1568509556726975 args:\u003ctype_url:\"type.googleapis.com/proto.ArtifactCollectorArgs\" value:\"\\n \\n\\036Windows.Utils.DownloadBinaries*\\366\\002\\032\\363\\002\\n\\nbinaryList\\022\\344\\002Tool,Type,URL\\nAutorun,amd64,https://live.sysinternals.com/tools/autorunsc64.exe\\nAutorun,x86,https://live.sysinternals.com/tools/autorunsc.exe\\nWinPmem,.,https://github.com/Velocidex/c-aff4/releases/download/v3.3.rc2/winpmem_v3.3.rc2.exe\\nSysmon,amd64,https://live.sysinternals.com/tools/sysmon64.exe\\nSysmon,x86,https://live.sysinternals.com/tools/sysmon.exe\\n8\\330\\004\" \u003e ","flow_id":"aff4:/clients/server/flows/F.BLUOST48NB248","user":"admin"}

```

`Followed by the below error`:

```
[INFO] 2019-09-15T01:05:56Z write_csv: Unable to open file [/mnt/velociraptor_datastore/public/inventory.csv]: open [/mnt/velociraptor_datastore/public/inventory.csv]: no such file or directory 
```

`Verified that that the path has inventory file(manually created by me)`:

```
 ls /mnt/velociraptor_datastore/public/
autorunsc64.exe  autorunsc.exe  inventory.csv  inventory.csv.bak  sysmon64.exe  sysmon.exe  winpmem_v3.3.rc2.exe

```

* On the client side executed ```velociraptor.exe -v --config Velociraptor.config.yaml query "SELECT * FROM  http_client(url=get(item=config.ServerUrls, member='0') + 'public/') "```

`Response`
```

[INFO] 2019-09-15T01:16:19Z Loaded 138 built in artifacts
velociraptor: scope.go:313: Fetching https://[DomainName]:8443/public/
[
 {
  "Content": "\u003cpre\u003e\n\u003ca href=\"autorunsc.exe\"\u003eautorunsc.exe\u003c/a\u003e\n\u003ca href=\"autorunsc64.exe\"\u003eautorunsc64.exe\u003c/a\u003e\n\u003ca href=\"inventory.csv\"\u003einventory.csv\u003c/a\u003e\n\u003ca href=\"inventory.csv.bak\"\u003einventory.csv.bak\u003c/a\u003e\n\u003ca href=\"sysmon.exe\"\u003esysmon.exe\u003c/a\u003e\n\u003ca href=\"sysmon64.exe\"\u003esysmon64.exe\u003c/a\u003e\n\u003ca href=\"winpmem_v3.3.rc2.exe\"\u003ewinpmem_v3.3.rc2.exe\u003c/a\u003e\n\u003c/pre\u003e\n",
  "Response": 200,
  "Url": "https://[DomainName]:8443/public/"
 }
]
```

The domain name is correct.

**Comment by scudette** [comment]
This is very strange - it seems like it is trying to open an array instead of the filename. There was a change https://github.com/Velocidex/velocifilter/commit/24eb23ea486a189194ca260f5adbf459248ee0b6c 27 days ago to support using the first element of the array if a string arg is given a list of exactly one. For example the following queries:

```
$ velociraptor query "SELECT * FROM write_csv(filename=['/tmp/test.csv'],query={SELECT * from info()  })"
[
 {
  "Architecture": "amd64",
  "BootTime": 1567888130,
  "Fqdn": "DevBox",
  "HostID": "b62d7e6c-32d3-4b41-857a-68abf1bdcf24",
  "Hostname": "DevBox",
  "KernelVersion": "4.15.0-1035-oem",
  "OS": "linux",
  "Platform": "ubuntu",
  "PlatformFamily": "debian",
  "PlatformVersion": "19.04",
  "Procs": 388,
  "Uptime": 650494,
  "VirtualizationRole": "",
  "VirtualizationSystem": ""
 }
]
$ ls -l /tmp/test.csv
-rwx------ 1 mic mic 279 Sep 15 19:10 /tmp/test.csv
```

But an array of more than 1 should not work:
```
$ velociraptor query "SELECT * FROM write_csv(filename=['/tmp/test.csv', 'foo'],query={SELECT * from info()  })"
velociraptor: scope.go:315: write_csv: Unable to open file [/tmp/test.csv foo]: open [/tmp/test.csv foo]: no such file or directory
```
You see how it writes the filename with "[" before and after it.

The issue is with https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/Utils/DownloadBinaries.yaml#L36

The query runs `LET binpath <= SELECT server_config.Frontend.public_path AS Path FROM scope()` which should be a list of exactly one row with the public directory. Then we do:

```
SELECT * FROM write_csv(
          filename=binpath.Path + "/" + "inventory.csv",
```

Which would expand to a single list of one value and that should be taken as a single string. On my system the following query returns:
```
$ velociraptor --config ~/server.config.yaml query "SELECT server_config.Frontend.public_path AS Path FROM scope()"
[
 {
  "Path": "/var/tmp/velociraptor/public/"
 }
]
```

Is this what is happening on your system? Which version are you using exactly? (the output from `velociraptor version`)

Perhaps special casing the conversion from a list of one parameter to a string is not worth it - in this case you could change the code to:
```
SELECT * FROM write_csv(
          filename=get(item=binpath.Path, member="0") + "/" + "inventory.csv",
```

**Comment by prats84** [comment]
Using the Change, I was able to get the `Windows.Utils.DownloadBinaries` working and create the inventory.csv.  Thanks for your help. T


The Memory Acquisition is still failing, due to the `Windows.Utils.FetchBinary` 

Version
```
velociraptor version
name: velociraptor
version: 0.3.3
commit: 009b182
build_time: "2019-09-06T10:37:05+10:00"
```

**Comment by prats84** [comment]
Haven't had much luck in getting the FetchBinary fixed.

**Comment by scudette** [comment]
Are you able to please test one of the latest builds? You can get the windows binary built at head from the CI pipeline:

https://ci.appveyor.com/project/scudette/velociraptor-ialou 

Click the artifacts tab and find velociraptor.exe.

I have a strong suspicion this is fixed at head. If it still does not work we can work around the issue by fixing the artifact itself (basically adding an explicit get() for each array).

**Comment by prats84** [comment]
Hi, 

Thanks for the latest binary. It seems to have fixed the issue. 

I could verify on the endpoint that winpmem process was `running` and storing the memory into `C:\Windows\Temp\`. Additionally, the artifacts ```Results``` seems to give progress on the capture. I did not finish the capture as was testing this on a high memory capacity machine. But I believe that once completed, I should be able to access via the portal. 


I will test this further, but thank you for the quick fix update. 


```Logs:```


```

timestamp | time | message
-- | -- | --
1568814390569783 | 2019-09-18 13:46:30 +0000 UTC | vql: scope.go:315: Symbol binaryURL not found. Current Scope is: [NULL, __destructors], [Artifact], [$responder, $uploader, config, $cache], [$throttle], [Windows_Memory_Acquisition_0_0]
1568814390579930 | 2019-09-18 13:46:30 +0000 UTC | vql: scope.go:315: Fetching https://<DomainName>:8443/public/inventory.csv
1568814390636412 | 2019-09-18 13:46:30 +0000 UTC | vql: scope.go:315: Fetching https://<DomainName>:8443/public/winpmem_v3.3.rc2.exe
1568814390637510 | 2019-09-18 13:46:30 +0000 UTC | vql: scope.go:315: http_client: Downloading https://<DomainName>:8443/public/winpmem_v3.3.rc2.exe into C:\Windows\TEMP\tmp483898613.exe
1568814390670591 | 2019-09-18 13:46:30 +0000 UTC | vql: scope.go:315: copy: Copying file from C:\Windows\TEMP\tmp483898613.exe into C:/Program Files/Velociraptor/winpmem_v3.3.rc2.exe
1568814390674549 | 2019-09-18 13:46:30 +0000 UTC | vql: scope.go:315: shell: Running external command [C:/Program Files/Velociraptor/winpmem_v3.3.rc2.exe -dd -o C:\Windows\TEMP\tmp739919312.aff4 -t -c snappy]
1568814490558638 | 2019-09-18 13:48:10 +0000 UTC | Time 99: Windows.Memory.Acquisition: Sending response part 0 20 kB (164 rows).
1568814590554453 | 2019-09-18 13:49:50 +0000 UTC | Time 199: Windows.Memory.Acquisition: Sending response part 1 16 kB (122 rows).
......
```


Results: 

```
Stdout | Stderr | Upload
-- | -- | --
  | 2019-09-18 14:46:30 I Setting compression snappy |  
  | 2019-09-18 14:46:30 I This is The WinPmem memory imager. version 3.3rc2 |  
  | 2019-09-18 14:46:30 I Extracted 45368 bytes into C:\Windows\TEMP\pmeBF55.tmp |  

```

**Comment by scudette** [comment]
Great! I submitted some more fixes for the binary fetch artifacts which do not rely on this behavior. We are now explicitly dereferencing the 1st element of the list.

I hope to document this a bit better for the next release. Thanks for your patience.
