### ISSUE TITLE
Allow capitals and other valid characters in DNS name for config files

### ISSUE THREAD

**Issue by mlucas300** [Velocidex/velociraptor#702]
Version 0.5.0 allowed mixed case DNS names in the "config generate -i" process, but 0.5.1 will only allow only lower case names. It would be great to change it to be the same as in version 0.5.0 and also add support for any other valid characters for DNS names, if not already catered for.

**Comment by scudette** [comment]
This should be fixed in head.

**Comment by mlucas300** [comment]
I just ran our tool with version 0.5.3 and it would only accept lowercase DNS names.

**Comment by scudette** [comment]
hostname validation occurs with this regex
https://github.com/Velocidex/velociraptor/blob/a12d6867f693d81d985f6ee53249b47bcfe43a50/bin/config_interactive.go#L68

What did you enter as the name that was rejected?

**Comment by mlucas300** [comment]
VelociraptorServer, when I changed to velociraptorserver it was accepted.

**Comment by scudette** [comment]
Ah I see, the regex is wrong - it should be `a-z0-9.A-Z`.

**Comment by scudette** [comment]
Should be fixed in 0.5.4

**Comment by mlucas300** [comment]
Thanks very much :-)
