### ISSUE TITLE
Supporting building Windows binary on MacOS computer

### ISSUE THREAD

**Issue by aspir** [Velocidex/velociraptor#703]
In order to build Velociraptor for Windows platforms on MacOS machines there should be a change in 'magefile.go' file, line 96 to:
if (runtime.GOOS == "linux" **|| runtime.GOOS == "darwin")** && self.goos == "windows" {

Can you please change the above line? THX

**Comment by scudette** [comment]
This change will require the mingw cross compilers to be present. Are these commonly installed on darwin?

Is it possible to build a windows binary without CGO_ENABLED?

**Comment by aspir** [comment]
In order to cross compile on darwin you have to install mingw(probably should be mention in the documentation),
It is possible to build windows binary without CGO_ENABLED(I ran `go run make.go -v WindowsTest` which disables cgo), however if I will do it, things that need to compile like "crypto.go" won't work. Disclaimer: I didn't test yet if every feature in Windows cross compiled binary worked

**Comment by scudette** [comment]
Windows uses cgo heavily and so building without a c compiler will result in much fewer features (for example wmi eventing, process information etc). If you have valid mingw compilers though it should work fine (I typically build the release windows binaries on a linux machine).

It is probably not a great idea to build windows binaries on MacOS anyway - we dont really test this combination but YMMV. I submitted the change requested earlier so maybe you can test with HEAD?

**Comment by aspir** [comment]
Yes. Are there any tests that I can run?

**Comment by scudette** [comment]
Our CI pipeline uses windows built binaries  

https://github.com/Velocidex/velociraptor/blob/master/.github/workflows/windows.yml

but it currently relies on the windows VM a bit as well so it is not easy to just run it on a different machine.

There aren't that many plugins that require cgo: on windows currently only:

- WMI event
- yara
- dns
- certificates
- vad, handles
- proc_dump
- authenticode

So a quick smoke test should be fine. I think if it compiles it should be fine.

I was specifically referring to the dlv issue you files earlier. I think it was a dependency problem with gopsutil?

**Comment by scudette** [comment]
I think this project https://github.com/karalabe/xgo should work. We used to use it in the past but now build with VMs instead. It should install all the required compilers by itself
