### ISSUE TITLE
Selecting Server Monitoring Events Changes Date Selection to Previous Day

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#706]
When selecting a server monitoring event in the GUI, it appears that date selection gets changed to the previous day.

![image](https://user-images.githubusercontent.com/16829864/97796370-28236f80-1bdf-11eb-9855-dbfcb9d71e8a.png)

to

![image](https://user-images.githubusercontent.com/16829864/97796374-3a9da900-1bdf-11eb-992c-a4690b47580c.png)

**Comment by scudette** [comment]
The date will be changed to the latest day with results. Do you have results in the current day?

Also be aware that velociraptor always treats times as utc so the date is shown as utc not local time. Depending on your timezone it may appear to be before or after the current day.

The date shown is also the start of the day - it will show events from the first second of that day to the last which may span the current time but appear to be the day before.

**Comment by weslambert** [comment]
Yes, I have results for the current day, and none for the previous, so I have to go select the current day again (11/1) after selecting the artifact.

The UTC date was still the current day (11/1) at the time this was noticed.

**Comment by weslambert** [comment]
This is resolved in head release
