### ISSUE TITLE
Making dlv work on macos

### ISSUE THREAD

**Issue by aspir** [Velocidex/velociraptor#707]
tld;r: Please upgrade the 'gopsutil' package in "go.mod" file in order for running dlv on macOS.

When trying to run `dlv debug --wd=. --build-flags="-tags 'server_vql extras'" ./bin/ -- frontend -v --debug`
I got this error:
`../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:67:51: cannot use stat.Mntfromname[:] (type []byte) as type []int8 in argument to common.IntToString
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:68:49: cannot use stat.Mntonname[:] (type []byte) as type []int8 in argument to common.IntToString
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:69:50: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:85:43: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
exit status 2`

After searching the web, I found this issue: [https://github.com/shirou/gopsutil/issues/853](https://github.com/shirou/gopsutil/issues/853).
When I upgraded the 'gopsutil' package to 'v3.20.10' in go.mod file, I successfully ran dlv on MacOS.
I am not sure if this is only a MacOS issue, and if there is another issue regarding updating this package.

**Comment by scudette** [comment]
I tried to run dlv on catalina with the latest HEAD (after updating gopsutil) but it seems dlv is anyway broken on macos. I get this error:

```
bash-5.0$ dlv debug --wd=. --build-flags="-tags 'server_vql extras'" ./bin/ -- frontend -v
could not launch process: stub exited while waiting for connection: exit status 0
bash-5.0$
```

So it builds but it cant actually run the debugger. I quickly googled for the issue but was only able to find this issue
https://github.com/go-delve/delve/issues/1016

which suggests to use the native debugger but I think that one is not really supported any more:
```
bash-5.0$ dlv debug --backend native --wd=. --build-flags="-tags 'server_vql extras'" ./bin/ -- frontend -v 
could not launch process: native backend disabled during compilation
```

This seems to be a dlv issue now...

**Comment by scudette** [comment]
Please reopen if updating gopsutil does not fix it.
