### ISSUE TITLE
GUI new collection wizard DatePickers don't reflect artifact defaults specified in ISO 8601 format

### ISSUE THREAD

**Issue by chris-counteractive** [Velocidex/velociraptor#717]
**summary:** GUI new collection wizard `DatePicker` components don't reflect artifact defaults specified in ISO 8601 format

_note_: reporting this as a bug because it just seems like a counterintuitive choice, but it might be functioning as designed.  see analysis below.

**environment:**

- Microsoft Windows [Version 10.0.19041.572] (though this is a GUI bug, so should be server-OS-agnostic)
- velociraptor v0.5.1-1, latest windows release
- Latest Chrome, Edge, and Firefox

**steps to reproduce:**

1. run velociraptor gui on a windows machine
1. select an artifact that has a parameter with type `timestamp` (e.g., `Windows.Forensics.Prefetch`)
1. customize the artifact to add a default in ISO 8601 format, like so:
    ```yaml
    parameters:
        - name: prefetchGlobs
          default: C:\Windows\Prefetch\*.pf
        - name: dateAfter
          description: "search for events after this date. YYYY-MM-DDTmm:hh:ssZ"
          type: timestamp
          default: 2019-01-01T00:00:00Z # with or without quotes, same result
    ```
    ... and save it.
1. navigate to your host and start the "new collection" wizard for your recently-customized artifact.  notice the default shows up (it's just a string at this point):
    | ![image](https://user-images.githubusercontent.com/48190665/98296136-198ade80-1f78-11eb-9e3d-186d8f17b55c.png) |
    | :---: |
    | _default parameter_ |
1. navigate to the "Configure Parameters" tab and notice the default is not reflected in the date picker:
    | ![image](https://user-images.githubusercontent.com/48190665/98296449-8aca9180-1f78-11eb-995a-ea662825ab9f.png) |
    | :---: |
    | _date picker with erroneous value_ |
1. incidentally, if you specify an appropriate integer value (as a string) it'll work, because the DatePicker creates its date by parsing the default as a seconds-past-epoch string.  See analysis.
1. also, "resources" is still misspelled in a couple places (https://github.com/Velocidex/velociraptor/search?q=resorces, see #696): 

**analysis**

root cause seems to be the new collection wizard passing the parsed artifact details, including its defaults, to the `VeloForm` component: https://github.com/Velocidex/velociraptor/blob/f167373ada393ff5c53726634f380a227d0d41dc/gui/velociraptor/src/components/flows/new-collection.js#L295-L302 

... and when the form creates a `DatePicker` for `timestamp` types, the `DatePicker` expects `timestamp`s to be seconds-past-epoch strings rather than ISO 8601 strings: https://github.com/Velocidex/velociraptor/blob/ea9b953110f1750d39414f2a31c9f3e0d886b482/gui/velociraptor/src/components/forms/form.js#L103-L107

this could be fixed using js `Date` constructor or `Date.parse` to parse the ISO string, or something more feature-rich like [`date-fns.parseISO`](https://date-fns.org/v2.16.1/docs/parseISO) (recommended by MDN).

```javascript
date = new Date( this.props.value ) // constructor
date = new Date( Date.parse( this.props.value ) ) // so odd that Date.parse doesn't return a Date ...
```

Or you could parse ISO strings into whatever format you prefer when converting the YAML.

One workaround is to specify timestamp defaults as integer strings, but that's not very ergonomic, and doesn't match what you'd expect based on the [yaml spec](https://yaml.org/type/timestamp.html).  Could be there's a reason for it somewhere else in the codebase, but from an artifact author point of view it's a bit awkward ("seconds past epoch? milliseconds? which was it again? did I forget quotes?").  Presumably the VQL `timestamp` function is pretty forgiving in what it accepts.

**impact**

low impact, it just makes specifying default timestamps a little unwieldy when writing custom artifacts, and doesn't align with what I expect in yaml.  when timestamp defaults are easy to specify it makes certain artifact VQL cleaner to write.

As usual, if this is user-error please let me know.  Thanks!

**Comment by scudette** [comment]
So just to explain what it is doing here - artifact parameters are **always** strings because that is how we send the data to the client. It is up to the VQL to parse the string out into something it can use. The type field in the parameter **only** suggests to the GUI how to present the form element to the user. Ultimately the parameter is always a string.

So it is expected that the value will be a stringified version of the epoch seconds. Then the VQL can simply use it like `timestamp(epoch=NameOfParameter)`. The GUI therefore used to writes the selected date as an epoch number.

Saying that, for quite some time the VQL `timestamp()` function has been much more forgiving and also accepts a string ISO date instead as the epoch parameter - actually it tries to guess something sensible out of the parameter if it is a string.

So since VQL doesnt really mind passing an iso date as the parameter default it makes sense that the GUI also supports reading the parameter as an ISO date and also writing an ISO date to the parameter. The slight benefit is that the request becomes a bit more readable:

![image](https://user-images.githubusercontent.com/3856546/98374830-fc93ff80-208c-11eb-8189-ddadf4b038ba.png)

**Comment by chris-counteractive** [comment]
Thanks for the details, sir, and for the quick update!  I noted up top that this might be intended behavior, but I appreciate the improvement to reading and writing timestamps in artifact defaults.  And the increased readability of the request is nice too.

I think the main goal of the report was to note the deviation from expectation: when I see "timestamp" in yaml, I think ISO 8601 (and in [json too](https://stackoverflow.com/questions/10286204/what-is-the-right-json-date-format), FWIW) ... how the system chooses to use that (as a string, epoch int, epoch int-as-a-string, etc.) is up to the system.  In any case, for anyone whose mind works like mine, this aligns better to our instincts, so thanks again for working through it! 💯
