### ISSUE TITLE
A way to upload to a bucket the log execution file

### ISSUE THREAD

**Issue by aspir** [Velocidex/velociraptor#723]
I am running a standalone Vraptor client binary which run some artifacts and send the results and the report to S3 bucket. I tried to find a way to upload the log file of the execution to the s3 bucket too.
The only way that I can think of is to repack Vraptor which repack inside another Vraptor with the artifacts, run it, and upload the execution log to the cloud.
Is there a better way to do it?

**Comment by scudette** [comment]
This is a good point. It is currently not possible to send the log file or the report to a cloud target because those are done **after** the artifact is collected.

For the report we probably could fix by uploading it separately. But for the log file we write it on disk asb the process is running, so we can not send it completely until the process terminates. 

Maybe we can send a partial log file, at least up to the point that we are uploading it?

**Comment by aspir** [comment]
Actually The report you can send it to the cloud, like it done in Artifact "CreateCollector", which uploads the report in another 'upload_s3' plugin:

`SELECT upload_s3(file=Container,
          bucket=TargetArgs.bucket,
          name=filename + ".zip",
          credentialskey=TargetArgs.credentialsKey,
          credentialssecret=TargetArgs.credentialsSecret,
          region=TargetArgs.region,
          endpoint=TargetArgs.endpoint,
          noverifycert=TargetArgs.noverifycert) AS Upload,
       upload_s3(file=Report,
          bucket=TargetArgs.bucket,
          name=filename + ".html",
          credentialskey=TargetArgs.credentialsKey,
          credentialssecret=TargetArgs.credentialsSecret,
          region=TargetArgs.region,
          endpoint=TargetArgs.endpoint,
          noverifycert=TargetArgs.noverifycert) AS ReportUpload
      FROM collect(artifacts=Artifacts, report=tempfile(extension=".html"),
          args=Parameters, output=tempfile(extension=".zip"), template=Template,
          password=Password)` 

I can try to add another upload_s3 artifact for the log file, will it work?

**Comment by scudette** [comment]
Yeah exactly we can do that separately into the created artifact.

I wonder if we uploaded the partially written log file at the same time it might be good enough? It obviously won't include the last few messages but it's probably ok

**Comment by aspir** [comment]
IT WORKED! 
if you add another "upload_s3" of the log file, it will send the log and the last log record will be the "upload_S3: Uploading ..."(of the log file)

**Comment by scudette** [comment]
Excellent!

**Comment by scudette** [comment]
This should be default behavior now with 0.5.2
