### ISSUE TITLE
DeleteFlowDialog always shows 0 Mb estimated for recovery when deleting flow

### ISSUE THREAD

**Issue by chris-counteractive** [Velocidex/velociraptor#739]
**summary:** the DeleteFlowDialog component, which shows as part of a modal when deleting a flow, always shows 0 bytes in its estimate for how much space will be recovered ("We expect to free up _ Mb").

**environment:**

- velociraptor v0.5.1 latest CI build at time of report (92228cf)
- Windows 10, though this is likely a GUI/react issue rather than an OS one
- Reproduced on latest chrome, edge, and firefox

**steps to reproduce:**

1. run `velociraptor gui`
1. run an artifact that produces more than a few megabytes of results, say `Windows.EventLogs.Evtx`
1. navigate on the filesystem to the flow results and note the size:
![image](https://user-images.githubusercontent.com/48190665/98853674-1c298000-241f-11eb-86e1-3e4c26914dca.png)
1. navigate to the flow and click the delete flow button:
![image](https://user-images.githubusercontent.com/48190665/98853498-d8cf1180-241e-11eb-9d74-401aae224ee3.png)
1. note that the UI shows an estimate of 0 Mb in the modal popup:
![image](https://user-images.githubusercontent.com/48190665/98853731-36635e00-241f-11eb-9ffd-09700516fc66.png)
1. note further: the delete works, the data gets removed, so this is just a display issue (though it doesn't delete the `flow.json.index` file, which can be a few megs ... not sure there's any reason to keep it without the data).

**impact:** minor - workaround is to use the row count as a decent first-order heuristic of size, and check the filesystem if you're really curious.

**analysis:**

The `DeleteFlowDialog` uses `props.flow.total_uploaded_bytes` to show this number:
https://github.com/Velocidex/velociraptor/blob/0bd0a04db98c2c90a9c10c1aecd4c0dd43eb7de2/gui/velociraptor/src/components/flows/flows-list.js#L55

presumably `flow` is either improperly set, not set, or `total_uploaded_bytes` is improperly set or not set.  In any case, I'm sure you'll diagnose it in 30 seconds 💥 Thanks!

**Comment by scudette** [comment]
There intention here is to allow people to delete a flow that collected a lot of files they didn't want. The estimate is only really concerned with total bytes uploaded rather than the Json files that were collected because the Json is typically pretty small. Although some artifacts like the mft one can actually collect a lot of Json data.

We actually have no record of the size of Json files as well upload them maybe we should maintain that as well?

I guess this is only an estimate so it's more important to report the uploaded bytes.

**Comment by chris-counteractive** [comment]
ah, i see what you mean, makes sense.  yeah, we frequently use MFT and others (e.g., Evtx) that routinely drop hundreds of mb of json per flow, but it's low impact either way - we can still guess their general size via row count.  if it's working as designed, all good, it just felt like a bug based on expectations: I think of flows as both the artifact json and uploaded files.  

i assumed that functionality would stat the file(s), i didn't think about the upload telemetry option, but it's not a big deal at all.  thanks for the info!

**Comment by scudette** [comment]
I changed the message to be more descriptive - we now mention the number of rows and say "bulk data" to indicate files.

![image](https://user-images.githubusercontent.com/3856546/98962060-f8b32200-2551-11eb-9fb9-2e4c63463139.png)
