### ISSUE TITLE
SQLite Plugin Not Working with Darwin Binary

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#750]
Was working with the SQLite plugin with a client running on Mac OSX Catalina, and when attempting to parse a SQLite database, I am receiving the following error.  

`Unable to open sqlite file.....Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub`

Do I need to manually build a Darwin binary to include this?  I would think the `sqlite` plugin would work OOB for all supported archs.

Thanks,
Wes

**Comment by scudette** [comment]
To build the sqlite binary you need a c compiler. The darwin binary build on the CI pipeline is actually built on Linux so we dont have darwin C compilers. The release binary is built on Sierra so should work fine.

If you want to build you own pre-release and you have a mac with xcode installed you can just run `make release` at the toplevel.

**Comment by weslambert** [comment]
Confirmed this works with the official release binary. 👍
