### ISSUE TITLE
Unable to collect to s3

### ISSUE THREAD

**Issue by alecisec** [Velocidex/velociraptor#753]
I'll be honest this is likely a user error but I can't locate the doco to correct what I'm doing wrong here

I'm getting the error
 
 {
   "log(message=\"Aborting collection: Failed to upload to cloud bucket!\")": true
 }

which is self-explanatory but for the life of me I can't see what i'm doing wrong

I'm creating an offline collector on 5.2 and setting the following config

Target OS Windows or Linux
Collection Type AWS Bucket
S3 Bucket XXXXXXXXXX
Credentials Key XXXXXXXXXXXXXXXXXXXXXXXXX
Credentials Secret XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Region ap-southeast-2

and leaving Endpoint blank
obviously my real S3 key/secret and bucket name are in those fields

I've tested the same exact Key/Secret using crossFTP and am able to upload files to the bucket without providing any other info than the Key/Secret

is the "S3 Bucket" field supposed to be in a specific format? I'm just using the actual name of the bucket
are extra permissions required? I've granted the programmatic access account "s3:ListAllMyBuckets" in addition to "s3ListBucket" with the resource ARN for the bucket in question and the bucket itself has a policy to allow "s3:ListBucket" and "s3:GetBucketLocation" as well as "s3:PutObject" with the Principal set to the ARN for the programmatic access account

**Comment by scudette** [comment]
When you run the collection does it show any errors to the screen? A screenshot would help.

**Comment by scudette** [comment]
I think this issue is fixed in CI head right?

**Comment by scudette** [comment]
Should be fixed in 0.5.3
