### ISSUE TITLE
Feature request: notebook per flow

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#759]
We added a great feature on to 0.5.2 head version which is a notebook per hunt, this enables workflow easily for triage of hunt results.

I would like to see a similar feature for each flow on machine view. Currently with the new indexed results screen we dont have a search option to quickly target results of interest. A notebook here would significantly improve workflow.

**Comment by scudette** [comment]
This is now available in CI head - give it a try

**Comment by mgreen27** [comment]
works really well. One of the most productive features yet!
