### ISSUE TITLE
"Include condition - Operating system" when hunting doesn't exclude other operating systems

### ISSUE THREAD

**Issue by daverstephens** [Velocidex/velociraptor#762]
When running a hunt, select "Include condition - Operating System" and set to Linux, the hunt still appears to run on Windows endpoints also.

eg. If you run the 'Linux.Sys.Bashshell' artefact for 'uname -a' you get errors in the log file for Windows endpoints indicating the command wasn't able to be run

[H.be06d320.zip](https://github.com/Velocidex/velociraptor/files/5574047/H.be06d320.zip)

(file produced from test system with 1 Windows client and 1 CentOS client - Both produce results although the hunt is configured to be limited to Linux only. Behaviour works as expected when hunting by "Include condition - Label" having previously labelled each machine accordingly).

Behaviour occurs on 0.5.2 running on Ubuntu 20.04.

**Comment by scudette** [comment]
Should be fixed in 0.5.3
