### ISSUE TITLE
Offline Version of Documentation

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#764]
Would it be possible to bundle the latest version of the documentation within the Velociraptor binary?  This way, users could view the VQL reference, etc without having to leave the server interface/GUI, and would not require internet access.

**Comment by scudette** [comment]
The documentation is actually bundled already - the most important part of the documentation is the list of VQL plugins/functions and their args (and types of args) and all this is already available as part of the command line completion. I guess we could add the extra details behind each plugin/function (currently it has only a one liner).

Which part of the documentation are you specifically referring to? Most of the more interesting articles/documentation is available on the blog but these are larger documents and probably wont make sense to embed in the binary.

Maybe we just need to present the information we already have in a more accessible way? like a search of plugin/function name or something like that?

**Comment by weslambert** [comment]
I'm thinking of the details around parsers/plugins/functions.  I noticed the command-line completion, and do appreciate and utilize it, but sometimes it can be a little vague/difficult to interpret, and I think it would be great to have the extra detail behind each item.  As far as the articles/blog posts, I think it's fine to exclude those.  It's mainly the aforementioned that I would be interested in.  I find myself going to research the online docs quite often to find a little extra detail behind each thing.  Maybe, as you suggested, the information could be presented in another way.

**Comment by scudette** [comment]
The vql.yaml file is now embedded in the server so we can offer suggestions for all platforms - now completions for windows only plugins work on linux etc.
