### ISSUE TITLE
Feature request: Add hunt/flow using the API

### ISSUE THREAD

**Issue by mlucas300** [Velocidex/velociraptor#77]
It would be useful to be to add hunts and flows to the API, so that these can be done remotely. We have a use case to interact with the server completely without the GUI, so this functionality would mean we could use Velociraptor (which is by far the best tool that we have looked at) to do our host monitoring.

**Comment by scudette** [comment]
You actually can use all the methods in the API that the GUI uses directly (i.e. not with VQL) but we just dont advertise it because we want the public API to be simple.

https://github.com/Velocidex/velociraptor/blob/master/api/proto/api.proto

shows all the methods that are available (e.g. ListHunt, CreateHunt etc).

To use them just copy them over to the simple .proto file we provide https://github.com/Velocidex/velociraptor/blob/master/bindings/python/api.proto to add the methods you want then rebuild the proto file to produce the new _pb2.py files. 

Then you can just call CreateHunt() directly.

We should also make this available through VQL but this is a workaround if it makes it easier.

**Comment by mlucas300** [comment]
Hi, thanks for the prompt response :-)

I've merged all of the Hunt definitions into the api.proto in the bindings/python directory but I'm getting a stack of errors when I run make. In each of the proto files there are imports of the form 'import "www.velocidex.com/golang/velociraptor/proto/semantic.proto"', which I assume is some sort of remote import (if there is such a thing). These links give a 404 in the browser and a 301 "Moved permanently" using curl. I had the idea to change these imports to the current locations in github.com, which obviously loads in the browser but with curl I get the same 301 result. 

There are also 'import "google/api/annotations.proto"' statements.

I copied all of the proto files I could find, both from api/proto and places like actions/proto) into the local directory and imported them into api.proto and amywhere else it look like they might be required. When I run make it complains about many messages not being defined, but many of them are in the copied local .proto files though, e.g. ApiFlow in flows.proto, but some are missing e.g. FlowRunnerArgs. These are the missing messages:

ApiClient
*ApiFlow
ApiFlowRequest
ApiFlowRequestDetails
ApiFlowResponse
ApiGrrUser
APIResponse
ArtifactCollectorArgs
ArtifactDescriptors
ArtifactParameter
FlowContext
FlowDescriptor
FlowDescriptors
*FlowRunnerArgs
GetArtifactRequest
GetArtifactResponse
GetArtifactsRequest
GetClientRequest
GetReportRequest
GetReportResponse
GetTableRequest
GetTableResponse
GetUserNotificationsRequest
GetUserNotificationsResponse
GrrMessage
LabelClientsRequest
ListAvailableEventResultsRequest
ListAvailableEventResultsResponse
LogMessage
ObjectReference
SearchClientsRequest
SearchClientsResponse
SetArtifactRequest
Types
UserNotificationCount
VFSListRequest

I've also tried to comment out the imports with the URLs in case they are not required, but this didn't seem to help either.

Do you have any idea what I'm doing wrong as I've tried everything I can think of?? 

TIA,
Martin.

**Comment by scudette** [comment]
You dont have to build the entire protobufs to use the API. If you do that it will try to import a ton of code you dont want or need.  All you need to do is copy the proto definitions you need. As long as you keep the field types and their IDs the same the on wire protobuf will be exactly the same.  

The code uses annotations but you probably dont care about that,  You also dont really need all the fields either, just the ones you care about should be copied into the local proto file.

It might not be worth the effort though - adding a schedule hunt VQL plug is much easier and less code. The main purpose of all the additional gRPC methods is to communicate with the GUI.

**Comment by mlucas300** [comment]
OK, thanks for that, I've gone back and taken an incremental approach, adding each required message definition required by the CreateHunt() functionality. It whinged about '"google.protobuf.Any" is not defined.', so I added import "google/protobuf/any.proto"; and that went away.
Now I have new errors:  Option "(sem_type)" unknown.
Option "(description)" unknown,
Option "(google.api.http)" unknown
and Option "(semantic)" unknown.

I tried grepping and googling but couldn't find anything. The google.api.http reference occurs in CreateHunt()  in the main api.proto so that seems like a bit of a show-stopper:

    rpc CreateHunt(Hunt) returns (StartFlowResponse) {
        option (google.api.http) = {
            post: "/api/v1/CreateHunt",
            body: "*"
        };
    }

I wasn't quite sure what you meant by "It might not be worth the effort though - adding a schedule hunt VQL plug is much easier and less code.", does that mean it is possible for me to code up some VQL that can accomplish the same?

Very sorry to keep hassling you incessantly, but it seems we must be pretty close now.

Thanks...

**Comment by scudette** [comment]
Yeah thats what I mean by annotations - you dont really need the sem type stuff just remove it.

You also do not need the options either - just drop them too - the http option is used for creating the HTTP -> gRPC gateway for the GUI and wont be needed to just call the API directly with gRPC.

**Comment by scudette** [comment]
This is now checked in with https://github.com/Velocidex/velociraptor/commit/202a36ca5e234485b51c744128b4656955fe7d98  

You use it the same way as starting a flow:

```
$ velociraptor --config ~/server.config.yaml query "SELECT hunt(description='My Hunt', artifacts=['Generic.Client.Info']) from scope()"
```

There are currently no hunt conditions - if you need the hunt to only run on a subset of machines just add a condition to the artifact itself. Also the hunt is created already in the running state so does not require a second step of starting it like the GUI

**Comment by mlucas300** [comment]
Wow, that's awesome, thanks very much!!!

**Comment by mlucas300** [comment]
I'm getting the following error:

./velociraptor-v0.3.3-linux-amd64  --config server.config.yaml query "SELECT hunt(description='My Hunt', artifacts=['Generic.Client.Info']) from scope()"
velociraptor: scope.go:313: Symbol hunt not found. Current Scope is: [NULL, __destructors], [Artifact], [config, server_config, $uploader, $cache], [$throttle], []
[
 {
  "hunt(description=\"My Hunt\", artifacts= [\"Generic.Client.Info\"])": null
 }

I've pulled the current version from git and have downloaded the current executables, although I suspect that isn't required. I get the same error when I substitute flow for hunt. I've tested with the previous queries that I've used and they all still work (e.g. "select collect(client_id='C.84ff34f2ada35283', artifacts=['Windows.Analysis.EvidenceOfExecution']) AS FlowId FROM scope()").

**Comment by scudette** [comment]
Sorry I just submitted the pr. you would need to build from source to get
the latest. Just follow the instructions in the readme file

We hope to roll a new release in the coming week

Thanks
Mike

**Comment by scudette** [comment]
FYI I added a linux binary build to appveyor CI pipeline. You can download the linux (and windows) binaries at every commit from there:

https://ci.appveyor.com/project/scudette/velociraptor-ialou

Click on the artifacts tab and find velociraptor_linux.elf

**Comment by scudette** [comment]
This should be in the latest release.
