### ISSUE TITLE
Clients table per hunt export error

### ISSUE THREAD

**Issue by JayJ72** [Velocidex/velociraptor#773]
On Velociraptor v0.5.2
When attempting to export a listing of clients from the client table under a Hunt, the query fails returning 

schema: invalid path "path" 

For example

/api/v1/DownloadTable?download_format=csv&columns=ClientId&columns=FlowId&columns=StartedTime&columns=State&columns=Duration&columns=TotalBytes&columns=TotalRows&hunt_id=H.xxxxxxxx&path=H.xxxxxxxx&type=clients

Modifying the 'path' parameter in this query causes to return a blank CSV

**Comment by scudette** [comment]
Should be fixed in 0.5.3
