### ISSUE TITLE
Velociraptor Agent to run only one instance

### ISSUE THREAD

**Issue by AdmU3** [Velocidex/velociraptor#807]
We tried to use the GPO to deploy the velociraptor in Agentless mode.

We noticed that the GPO was deployed several times and ends up running around 30 instances of Velocirpator on the same machine, which causes the CPU and memory to rise to the max and server crashed.

Can we include a new feature in the executable to check if there is a current running Velcoiraptor process and if its found it won't create another one.

So the executable when deployed will always create only one instance of the service.

**Comment by scudette** [comment]
Are you deploying a client or an offline collector?

**Comment by AdmU3** [comment]
No I deployed a client following this article "https://www.velocidex.com/docs/getting-started/deploying_clients/".
We tried to create the scheduled task GPO to use the agentless mode, but we noticed each time the GPO run it creates new instance of the agent.

**Comment by scudette** [comment]
Interesting - the GPO scheduled task is launching multiple times? tThis guide seems to suggest that it should not be doing that and should teminate the previous process when it starts a new one.

https://4sysops.com/archives/run-powershell-scripts-as-immediate-scheduled-tasks-with-group-policy/

Velociraptor uses the writeback file to know its own client id and crypto keys - the first time it is run on the endpoint it will create this file and rekey itself. The next copy will use the same client id and try to connect to the server. If you have multiple clients running, they should not all be active at the same time (as long as they use the same client id).  The server will detect multiple clients claiming they are the same client id and reject all but the first with a 406 conflict HTTP status - therefore they should not all be working at the same time.

Where are you storing your writeback file? Do you see all the processes working (ie CPU and memory more than normal) at the same time?

I think it makes sense to have some kind of hook at client start that can be used for this purpose - maybe a precondition query that can run to check if the client can be invoked?  A quick check would be something like
```sql
SELECT * FROM pslist() WHERE Name =~ "velociraptor"
```

**Comment by AdmU3** [comment]
I first tried to run the binary using the default client configuration after change the client.config.yaml to velocirpator.config.yaml

But the binary running was failing and error was that the velociraptor directory isn't found in program files.

So I've update the client config file and changed the default locations to windows/temp and installation was successful after doing that.

  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: c:\windows\temp\velociraptor.writeback.yaml <<<<<<<<<<<<<<<<
  tempdir_windows: c:\windows\temp\Tools <<<<<<<<<<<<<<<<<<<<<<<<
  max_poll: 60
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe <<<<<<<<<<<<<<<<<<<<<<<<<
    service_description: Velociraptor service

I deployed the agent using the GPO on one servers and next day I found the server performance severely impacted, when I checked I found the GPO run many instances of the binary file and I found the CPU and memory are utilized to the max level.
When I killed the instances and disabled the GPO we returned to normal behavior.

**Comment by scudette** [comment]
Interesting - i wonder if the temp directory was being cleaned and the new instance started with a different client id - on the server did they all appear as the same client id or different one?

You can actually just run velociraptor with a query and then you can write VQL to only launch the client if no other velociraptor process exists. For example something like this

```
f:\velociraptor.exe query "LET me = SELECT Pid, Exe FROM pslist(pid=getpid()) SELECT * FROM switch(a={SELECT Pid, Name, CommandLine FROM pslist() WHERE Name=~ 'velociraptor' and Pid != me[0].Pid}, b={SELECT * FROM execve(argv=[me[0].Exe, '--config', PathToConfig,  'client']) })"  --env PathToConfig=F:\client.config.yaml
```

Will check that no other process with name Velociraptor exists before launching the client, otherwise it reports the velociraptor processes.  You can modify for your needs from there.

**Comment by AdmU3** [comment]
Thank you 👍 

No, on the server I didn't see duplicate clients only one client appears on the GUI, but several instances on the client running.

I will try to replicate the issue again on a test server this time during the weekend and if it re-appears will provide screenshots and update you.

**Comment by AdmU3** [comment]
Appreciate your Help Mike, I will close this issue thank you
