### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by secusoc** [Velocidex/velociraptor#822]
Hi,

Some artifact need to download third party software before running. (ie: NirsoftBrowsingViewer...).
a) How configure frontend server to use a "proxy with authentication" to download it  ?
b) If not possible: Where store 3rd party software if download manually ?

Kind regards

**Comment by scudette** [comment]
You can configure a proxy easily:

1) When installing the deb you will find the /usr/bin/velociraptor is just a wrapper shell script that sets some environment variables.
2) Just add the HTTPS_PROXY environment variable to that - when the server starts it will be able to use the proxy.

See https://www.golinuxcloud.com/set-up-proxy-http-proxy-environment-variable/ for example

You can upload the binary yourself when you are about to launch it for the first time. Just click the tool setup icon in the Artifact selection box and the manually upload the tool in the browser. Once the tool is uploaded once you dont need to do it each time you want to use the same tool.

![image](https://user-images.githubusercontent.com/3856546/102412377-1e46b600-403f-11eb-93de-d7931eabf9f4.png)

![image](https://user-images.githubusercontent.com/3856546/102412416-2bfc3b80-403f-11eb-8901-04d428e8dfa7.png)

**Comment by secusoc** [comment]
thank you scudette
