### ISSUE TITLE
Execute Velociraptor on Windows Server 2003

### ISSUE THREAD

**Issue by tej7gandhi** [Velocidex/velociraptor#856]
Hello Mike,

Thanks the last update is 0.5.4 seems very good to go,I tried run Velociraptor on Windows Server 2003 ,it does not get installed is there any tweak that will be required for it?

Thanks and Regards
Tej Gandhi

**Comment by scudette** [comment]
Supported platforms are https://github.com/golang/go/wiki/MinimumRequirements 

For Go 1.11 and later: Windows Server 2008R2 and higher or Windows 7 and higher. We test on Windows Server 2008 R2, 2012 R2, and 2016, which are roughly Windows 7, Windows 8, and Windows 10.

Windows server 2003 is not even supported by Microsoft.
