### ISSUE TITLE
`hunt` VQL function doesn't return anything

### ISSUE THREAD

**Issue by CR-OmerYampel** [Velocidex/velociraptor#859]
The `hunt` VQL function doesn't return anything after creating the hunt. I would expect it to return at least the resulting hunt_id, but ideally the same output as ```SELECT * FROM hunts() WHERE hunt_id = <resulting_hunt_id>```

**Comment by scudette** [comment]
This is very interesting - it is certainly supposed to return the hunt_id and the code actually does do this but when you run it in the notebook it always says "Cancelled after ... ms". 

What was happening was that when we launch a hunt we send a notification to all currently connected clients so they can immediately pick up the hunt. When one edits the cell, the cell is listening for interruption on the same notification service (in case the user clicked the stop button in the cell). So the hunt was actually sending a message to cancel the cell which cancelled the query so the results never made it out at all. Very subtle :-).

**Comment by scudette** [comment]
Fixed with 0.5.5 release
