### ISSUE TITLE
`hunts()` vql function doesn't show creator for hunts created via `hunt()` 

### ISSUE THREAD

**Issue by CR-OmerYampel** [Velocidex/velociraptor#860]
The `hunts()` function has an empty value in the creator column for hunts created via vql (`hunt()` function) 
![image](https://user-images.githubusercontent.com/57952597/103936699-be02db80-50f5-11eb-9153-3560ee37cbc3.png)

**Comment by scudette** [comment]
Fixed with 0.5.5 release
