### ISSUE TITLE
Unknown parameter IsExecutable provided to artifact Generic.Utils.FetchBinary

### ISSUE THREAD

**Issue by alecisec** [Velocidex/velociraptor#868]
Example of logs as follows:

[INFO] 2021-01-12T09:27:02+10:30  Collected Generic.Client.Info/Users 
[INFO] 2021-01-12T09:27:02+10:30  upload_S3: Uploading Collection-ubuntu-2021-01-12_09_27_01__1030_ACDT.zip to sag-yara-logs 
[INFO] 2021-01-12T09:27:02+10:30  upload_S3: Uploading Collection-ubuntu-2021-01-12_09_27_01__1030_ACDT.html to sag-yara-logs 
[INFO] 2021-01-12T09:27:02+10:30  upload_S3: Unable to open Collector_velociraptor-v0.5.4-linux-amd64.log: lstat /Collector_velociraptor-v0.5.4-linux-amd64.log: no such file or directory

it seems that the issue where the log file not existing still prevents the execution of the collection in version 5.4

edit: the error seems to be unrelated to the failure to locate the log file, changed the subject accordingly

**Comment by scudette** [comment]
This is strange - in the current version the code does a test upload first and aborts immediately if it can not upload (we do this to make sure creds are good before starting the collection):

https://github.com/Velocidex/velociraptor/blob/865097eecc9a6abf2c5a520f70c07c1a7c49c9ab/artifacts/definitions/Server/Utils/CreateCollector.yaml#L188

But the logs above show it failed to upload at the end of the collection - which means it had to have succeeded at the start?

**Comment by scudette** [comment]
Ah sorry i take that back - the initial test upload is just a string - it is not the log file itself. 

The logs above actually show it worked though no? is it just the .log file that failed to upload?

**Comment by alecisec** [comment]
Seems the error is not what's preventing the execution but the actual error is "Unknown parameter IsExecutable provided to artifact Generic.Utils.FetchBinary" which is being triggered by the Windows.Search.Yara artifact (I believe)

**Comment by scudette** [comment]
Fixed with 0.5.5 release
