### ISSUE TITLE
Hyperlink Artifact Name from Client Collected Overview

### ISSUE THREAD

**Issue by weslambert** [Velocidex/velociraptor#886]
While more active/iterative artifact development is surely intended to be done through the use of a notebook, I think it would be great if the artifact name (much like the Flow ID) displayed in a client's "Collected Flows" view ( `/collected/<clientid>`) were hyperlinked to the equivalent artifacts page ( `/artifacts/<artifact>`).  This might help with not having to go click on the artifact icon the left, search for the artifact, click it, then copy/modify, etc.

**Comment by scudette** [comment]
This is in head
