### ISSUE TITLE
How to pass nested JSON to Args for the collect with multiple artifacts

### ISSUE THREAD

**Issue by bhjella-awake** [Velocidex/velociraptor#896]
Hello,

I have an issue where I tried to pass args to the collect script as such:

```
SELECT * FROM collect(
                    output="test.zip",
                    artifacts=[
                        .....
                        "Custom.Windows.KapeFilesAL2.Targets"
                    ],
                    args={"Prefetch":"N"},
                    format="json",
                    output=tempfile(extension=".zip")
                  )
```

And I get this error:
`collect: Parameter 'args' refers to an unknown artifact. The 'args' parameter should be of the form {"Custom.Artifact.Name":{"arg":"value"}}`

Which is cool that it told me how to do it.  However I am struggling to find the syntax to put in there.  I can use:
`{"Custom.Artifact.Name":{"arg":"value"}}`  as this errors saying: `mapping values are not allowed in this context` 

Then I try `dict("Custom.Windows.KapeFilesAL2.Targets"=dict(...))` and I get `Starting services.: 4:105: unexpected token "(" (expected ")")`

Is there some special way to pass the JSON object to args so I can specify the args for each artifact module?

**Comment by scudette** [comment]
Note that in vql the curly braces represent a sub query so args={...} Does
not make sense

You can build the data either by using a dict or by unserializing a Json
blob


So something like

Args=dict(`cusrom.artifact.name`=dict(foo="bar"))

Note the use of backticks to denote names with spaces or special characters
in them.

You can examples of how the vql is used by looking at the test files. Just
search in the *.in.yaml files for the plugin for want to see an example of
use.

Thanks
Mike

**Comment by bhjella-awake** [comment]
Thanks!

**Comment by bhjella-awake** [comment]
Another question... is there a way to pass the params to a function using parameters.  

For example:
```
parameters:
  - name: collectors


sources:
  - precondition: SELECT OS from info() where OS = 'windows'
    queries:
      - SELECT *
        FROM Artifact.Windows.KapeFiles.Targets(
          {SELECT * from collectors}
        )
```

How could I make this work?
```
FROM collect(
                    output="C:\test.zip",
                    artifacts=[
                        "Custom.Windows.KapeFilesAL2.Targets"
                    ],
                    args=dict(
                      `Custom.Windows.KapeFilesAL2.Targets`=dict(
                        `collectors`=(
                          RegistrNHives="Y",
                          Prefetch="Y"
                        )
                      )
                    )
                 )
```

**Comment by scudette** [comment]
Yeah vql only supports keywords so you have to name all your parameters.

Take a look at the blog for an intro to vql and the workshop slides are currently the best reference. 

Btw why are you calling the collect() plugin? That plugin creates a zip file with other artifacts in it so it is fairly specialized. If you want to collect an existing (or custom) artifact you can just collect it directly with the GUI. Just trying to understand your use case.

**Comment by bhjella-awake** [comment]
We do targeted collections using the stand alone collector (non-server).  I figured out a way to specify the specific collections we want to perform.  Basically we want to create a collection yaml without having to recompile the binary.  The method below will allow us to just repack it.  We use a variety of methods to retrieve these files via ZIP.

```
                 FROM collect(
                    artifacts=[
                        "Windows.KapeFiles.Targets"
                    ],
                    args=dict(
                      `Windows.KapeFiles.Targets`=dict(
                          RegistrNHives="Y",
                          Prefetch="Y"
                      )
                    ),
```

**Comment by scudette** [comment]
Isn't that what the server.utils.createcollector does any way? You might want to take a look at that one too.

Although the offline collector builder is a dedicated GUI it just ends up running a server side artifact that is pretty easy to run independently.
