### ISSUE TITLE
Version 0.5.5-1 of the Offline Collector is not deleting files from the designated Temp directory after completing the collection

### ISSUE THREAD

**Issue by CyberKaizen** [Velocidex/velociraptor#899]
As the title says, after the v05.5-1 release, the offline collector is not deleting temp files after it finishes running.

There are probably workarounds to this, but the Velociraptor server out of box currently pulls down the latest version of the executable at build time (I may be misunderstanding how it works).

An idea for the future would be that, out of the box, only having a matching version pulled and built upon pressing the offline collector and pressing launch.

Here's the proof seen in the end of the logs of v0.5.4 vs v0.5.5-1:
**Version 0.5.4 Log**
`{"level":"info","msg":" tempfile: removing tempfile C:\\Users\\redact\\AppData\\Local\\Temp\\tmp229941833.html\n","time":"2021-01-14T00:29:26Z"}
{"level":"info","msg":" tempfile: removing tempfile C:\\Users\\redact\\AppData\\Local\\Temp\\tmp243285522.zip\n","time":"2021-01-14T00:29:26Z"}
{"level":"info","msg":"Collection completed in 580 Seconds","time":"2021-01-14T00:29:27Z"}`

**Version 0.5.5 Log**
`{"level":"info","msg":" upload_SFTP: Uploading Collection-redact-2021-01-28_00_39_33__0000_GMT.log to redact.redact.com:22\n","time":"2021-01-28T01:03:44Z"}
{"level":"info","msg":"Collection completed in 1454 Seconds","time":"2021-01-28T01:03:46Z"}
{"level":"info","msg":" Query Stats: {\"RowsScanned\":1,\"PluginsCalled\":1,\"FunctionsCalled\":0,\"ProtocolSearch\":0,\"ScopeCopy\":2}\n","time":"2021-01-28T01:03:46Z"}
{"level":"info","msg":"Exiting notification service!","time":"2021-01-28T01:03:46Z"}`

**Files not being deleted after completing collection**
![image](https://user-images.githubusercontent.com/78124503/106079596-26ccea80-60db-11eb-8de3-daaddced3de8.png)

**Comment by scudette** [comment]
It this about removing the zip file after uploading to s3? Isn't the zip file the completed collection?

You can also set the temp folder now to a more convenient location.

You can always override the packaged binary using the tool setup screen.

**Comment by CyberKaizen** [comment]
> It this about removing the zip file after uploading to s3? Isn't the zip file the completed collection?
> 
> You can also set the temp folder now to a more convenient location.
> 
> You can always override the packaged binary using the tool setup screen.

The issue is that after completing the upload to the SFTP server, the previous version's behavior was to delete the temp files including that zip. The new version is not repeating that same behavior.

**Comment by scudette** [comment]
Please test the  latest head build. You will need to override the VelociraptorWindows tool in the Configure Collection screen. Simply upload the latest windows build.

**Comment by CyberKaizen** [comment]
> Please test the latest head build. You will need to override the VelociraptorWindows tool in the Configure Collection screen. Simply upload the latest windows build.

Will do, I will see what it does for me and let you know.

**Comment by scudette** [comment]
Should be fixed in 0.5.6

**Comment by CyberKaizen** [comment]
Sorry I was not able to quickly run the test for you.

I recently used Velociraptor on a couple of things and found things I hope to report at a later date.
________________________________
