### ISSUE TITLE
server install on ubuntu 18.04

### ISSUE THREAD

**Issue by siftuser** [Velocidex/velociraptor#9]
Could you please help with installation instructions ? Thanks!

sudo dpkg -i velociraptor-v0.2.8-linux-amd64
dpkg-deb: error: 'velociraptor-v0.2.8-linux-amd64' is not a Debian format archive

sudo apt-get install  ./velociraptor-v0.2.8-linux-amd64
Reading package lists... Done
E: Unsupported file ./velociraptor-v0.2.8-linux-amd64 given on commandline

**Comment by scudette** [comment]
It is not a debian package - it is a linux executable - just drop it anywhere you want (e.g. /usr/bin) and create a new config file:

```
/usr/bin/velociraptor config generate > /etc/velociraptor.config.yaml
```
Edit the config file to suite your deployment and start the frontend:
```
/usr/bin/velociraptor --config /etc/velociraptor.config.yaml frontend -v
```

If you need to install systemd service file you can use this one (just edit the ExecStart line):
https://github.com/Velocidex/velociraptor/tree/master/debian

The same binary will run on any Linux based OS (even ChromeOS).

**Comment by siftuser** [comment]
Many thanks! that worked :)

Just curious, does it support mac osx clients ? Thanks

**Comment by scudette** [comment]
Yes the OSX clients are on the release page. Same deal - they are just a binary which can run on any version of osx (I think down to 10.6 maybe?). You just install them on endpoint the same way:
```
# velociraptor service install
```

It basically calls launch daemon to install itself:
https://github.com/Velocidex/velociraptor/blob/master/bin/installer_darwin.go#L95

Usually people have sccm with osx so its easy to install

**Comment by siftuser** [comment]
@scudette  Many thanks for your time & patience!

This is what I did 
1. generated client yaml on the server
2. scp'd client yaml to the client
3. downloaded velociraptor pkg for OSX from release page
4. sudo ./velociraptor-v0.2.8-darwin-10.6-amd64 --config client.conf.yaml client

It runs, but I dont see it on the server gui search page

Is there a way to run the client in verbose mode or any other troubleshooting steps ? Thanks again

**Comment by scudette** [comment]
No worries - check out the training material https://docs.velociraptor.velocidex.com/resources/nzitf_velociraptor.pdf around the part that talks about Deployment.

We will be updating this material really soon now too :-).
