### ISSUE TITLE
base64decode produced Null

### ISSUE THREAD

**Issue by bhjella-awake** [Velocidex/velociraptor#906]
Hello, I am doing the following VQL in an Artifact:

```
          SELECT * FROM foreach(
          row={
              SELECT Username FROM UserProfiles
          },
          query={
              SELECT
                ....
                Data.value as raw_reg_data
              FROM Artifact.Windows.Registry.NTUser(userRegex=Username, KeyGlob=compressionHistory7zip)
          })
```

This returns `raw_reg_data` as a base64 string.

When I use the following:
```
          SELECT * FROM foreach(
          row={
              SELECT Username FROM UserProfiles
          },
          query={
              SELECT
                ....
                base64decode(string=Data.value) as raw_reg_data
              FROM Artifact.Windows.Registry.NTUser(userRegex=Username, KeyGlob=compressionHistory7zip)
          })
```

This returns `raw_reg_data` as `null`

I think I am doing this correctly as stated in https://www.velocidex.com/docs/vql_reference/basic/ but maybe I am missing something.

Thanks!

**Comment by scudette** [comment]
Can you please attach the values for compressionHistory7zip ?

If base64decode() is returning Null it means the string is probably not properly encoded in base64. Either the string is in UTF16 or some other problem happened.

You can always add debugging by simply adding a log function to the WHERE clause - log() always returns true but actually prodeces a query logs which helps to see what is going on.

```sql
 SELECT * FROM foreach(
          row={
              SELECT Username FROM UserProfiles
          },
          query={
              SELECT
                ....
                base64decode(string=Data.value) as raw_reg_data
              FROM Artifact.Windows.Registry.NTUser(userRegex=Username, KeyGlob=compressionHistory7zip)
              WHERE log(message=format(format="%v %v", args=[Data, Data.value]))
          })

```

**Comment by bhjella-awake** [comment]
Parameters:
```
parameters:
  - name: compressionHistory7zip
    default: Software\7-Zip\Compression\ArcHistory
  - name: userRegex
    default: .
```

The compressionHistory7zip is just the reg path.

**Comment by scudette** [comment]
It does not look to me that this value is base64 encoded at all - it looks utf16 encoded - can you to use utf16() instead?

![image](https://user-images.githubusercontent.com/3856546/106546478-0aa3d000-6557-11eb-8f1e-cc13a7d394d5.png)

**Comment by scudette** [comment]
Ah I see where the confusion arose - the base64 encoding you see is just an artifact of encoding to JSON - json can not represent binary data and so the GUI converts to base64. But the data inside the VQL is actually binary data (as indicated by the Data.type value)
![image](https://user-images.githubusercontent.com/3856546/106547007-180d8a00-6558-11eb-9b10-ecd563b21094.png)

**Comment by bhjella-awake** [comment]
Ah! Perfect! That was what the problem was.
