### ISSUE TITLE
Feature Request: Update SFTP support

### ISSUE THREAD

**Issue by CdtDelta** [Velocidex/velociraptor#915]
Wanted to see if we could add the capability to supply both a password and a private key for SFTP uploads. We're looking at building an offline collector that would automatically SFTP the results/data to a SFTP server we would set up prior to the engagement. The SFTP servers we're running require both a Private Key (which is already in the SFTP upload code) and a passphrase.

**Comment by clayscode** [comment]
To be clear, you don't mean a password to unlock the private key, but rather you ssh using a private key and then it asks for a password?

**Comment by CdtDelta** [comment]
Correct. So for example if I was connecting from the CLI (on Ubuntu):
sftp -i <private key> user@hostname

And then I get prompted for the SFTP password.

**Comment by scudette** [comment]
Implementing this change is easy, what I am not so sure about is if it is a good idea :-).

We currently use ssh.ParsePrivateKey here
https://github.com/Velocidex/velociraptor/blob/4de33a2f74b1fc84fa6d0878a3466adab01d4d71/vql/tools/sftp_upload.go#L117

All we need to do is to change it to ParsePrivateKeyWithPassphrase https://pkg.go.dev/golang.org/x/crypto/ssh#ParsePrivateKeyWithPassphrase  so it can unlock the private key provided.

Although this is still not secure - anyone can extract the private key with the password that is also embedded in the offline collector. You would need to restrict access on the server side in any case. 

If you are going to create a new key and set its permissions using e.g. https://www.digitalocean.com/community/questions/trying-to-setup-a-sftp-user-with-limited-access then you might as well generate an unlocked private key anyway.  There is no advantage in allowing plain password access either to that user.

**Comment by CdtDelta** [comment]
I don't think the password is to unlock the private key however, and I do know when I do the sftp command on the CLI I have to set the permissions to the private key file to 600.

**Comment by scudette** [comment]
But you want to embed the password in the offline collector right? This means anyone that gets hold of the collector can just look at the password or private key (velociraptor config show) and unless you took extra steps to secure the ssh server, can use those to get shell access to the upload server.

SFTP as an upload method can be used safely but it is not secured by default and I am worried that if we make it really easy to use it might encourage people to open gaping holes in their systems. 

It might be that your server requires password authentication (so not private key auth at all). In that case we need to use this
https://pkg.go.dev/golang.org/x/crypto/ssh#Password instead here
https://github.com/Velocidex/velociraptor/blob/master/vql/tools/sftp_upload.go#L135  - is this what this feature is about? Do we just want to add a new auth method (password) to the VQL plugin?

**Comment by CdtDelta** [comment]
Well in this particular instance, we are controlling the access on the "backend", and the cert and password change each time. So the collector would be customized per use.  Once it's done you just reset the password on the SFTP side.

What we're looking to accomplish is right now the triage runs, and then the end user has to SFTP it up anyway. So instead of having that extra step, when the collection is finished it just uploads. All the end user is doing is running the program.

**Comment by CdtDelta** [comment]
Closing this issue, since an alternative was found (and fixed in https://github.com/Velocidex/velociraptor/issues/950 )
