### ISSUE TITLE
artifact_search_filter hides custom artifacts

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#919]
When `artifact_search_filter` is enabled with `.*` as it's regex value, then all artifacts are shown in the GUI _except_ for custom ones. This means that it's not currently possible to only show custom artifacts, since as soon as `artifact_search_filter` is specified then the custom artifacts are hidden.

Tested with version 0.5.6

**Comment by scudette** [comment]
I cant seem to replicate this. In fact if the parameter is not specified at all it is set to "." - so filtering is always occurring.

To only show Custom artifacts just filter for ^Custom

![image](https://user-images.githubusercontent.com/3856546/107881412-03ee6300-6f30-11eb-8975-493f3da17938.png)
![image](https://user-images.githubusercontent.com/3856546/107881447-1d8faa80-6f30-11eb-8d5b-63d56cbf8623.png)

**Comment by predictiple** [comment]
It seems to be some sort of edge case with `.*` - unquoted in the YAML - in particular. When specified with quotes it works fine. Without quotes it hides all the custom artifacts.

Other regexes such as `^Cust.*` work equally fine with or without quotes.

Thanks for the response Mike. I am happy that it works with ^Custom :smile:
