### ISSUE TITLE
AWS Managed Services SFTP File Upload Failure

### ISSUE THREAD

**Issue by davidjmaria** [Velocidex/velociraptor#921]
The SFTP upload functionality in the offline collector is unable to upload files to AWS managed services SFTP instances. Whenever an upload is attempted, the upload fails with the error:
`upload_SFTP: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)"`

This is a known issue with the SFTP library, as described in [pkg/sftp#305](https://github.com/pkg/sftp/issues/305). The fix for this issue is described in [this comment](https://github.com/pkg/sftp/blob/master/client.go#L202).

**Comment by davidjmaria** [comment]
After some testing I have found some issues with the proposed solution (opening files in write-only mode for uploading). Opening files in write-only mode causes the upload test and the post-upload verification to fail because these processes rely on read permissions. 

To fix these issues, the tests would need to be restructured to work without the read permission, or the files would have to be closed after they are written and re-opened with read-only permissions for the the tests to run successfully. Would the team consider accepting changes implementing either of these solutions, or will AWS Managed Services SFTP uploads remain unsupported for the time being?

**Comment by scudette** [comment]
Sure we would love to have this fixed - lets work through the issues and see if we can make it work.

BTW just out of curiosity - from a practical perspective if one is going to use AWS SFTP what is the reason they would not just use S3 uploads? S3 upload is more secure and already happens in a read only way.  Typically with S3 upload we create a AWS service account with write only permission to a bucket so it is impossible to use those credentials to retrieve the data again.

**Comment by davidjmaria** [comment]
Sounds good, thanks! After taking a closer look at the code I realized the changes needed weren't as drastic as I thought, I have a working fix that I'll be creating a PR for soon. 

From a practical perspective, I agree that it would make more sense to use S3 uploads in this case. Sadly due to certain access limitations that are out of my control I haven't had much getting approval making this happen.
