### ISSUE TITLE
Cannot populate empty lookup table

### ISSUE THREAD

**Issue by ecapuano** [Velocidex/velociraptor#932]
Just realized that if you delete all items from a lookup table when specifying collection parameters, you cannot add anything to the empty table.

![image](https://user-images.githubusercontent.com/4219694/109328337-f930a980-781e-11eb-853e-c65765b55921.png)

Version
--
{"name":"velociraptor""version":"0.5.3""commit":"e957bec""build_time":"2020-12-03T15:33:04+10:00"}

**Comment by scudette** [comment]
Hahah that's a good point! UI fail....

**Comment by scudette** [comment]
Fixed in 0.5.7
