### ISSUE TITLE
[Feature Request] Add "CSV" Output Format

### ISSUE THREAD

**Issue by clong** [Velocidex/velociraptor#934]
When building an offline collector, the options for output format are `JSON` and `JSON + CSV`. It would be nice to have just a `CSV` option as well.

![image](https://user-images.githubusercontent.com/5092699/109358641-f04cd180-7838-11eb-8d56-f3be8cca60e2.png)

**Comment by scudette** [comment]
Internally velociraptor always uses Json to write and read result sets. When we also select csv we write the Json and additionally convert it to csv.

Maybe we can delete the Json and not include it in the collection but this week also

**Comment by scudette** [comment]
I think since preventing the json from being written prevents the collection from being imported later on - it just makes sense to keep it around. Please feel free to reopen if you think of a good reason to omit it from the final file.

**Comment by clong** [comment]
Just for my own reference (and anyone who comes across this), it's super straightforward to convert to CSV using jq:

`cat Generic.Forensic.Timeline.json |  jq -r '[.[]] | @csv' > Generic.Forensic.Timeline.csv`
