### ISSUE TITLE
Reliably support multi server configuration

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#941]
Previously there was an attempt to support multi frontend configurations using the mysql backend but since that did not work out, this issue tracks progress on that front.

Ideally we want to be able to distribute as much work as possible to multiple frontends. 

* Currently the most expensive operation is TLS which can be offloaded but would be nice to be able to handle ourselves. 
* The next issue is syncronization and selecting which microservices can run concurrently and which must maintain a lock. Ideally server event monitoring should be running on each frontend.

The issues are:
1. Shared distributed backends to allow clients to be randomly assigned to a specific frontend.
2. Syncronization of event journaling - do we let multiple server event artifacts to be collected on different frontends? if so how to manage syncronization?

For 1 we could use EFS as a faster and more distributed way to share file storage than mysql.

**Comment by predictiple** [comment]
Please keep in mind containerization and container runtime contracts, for e.g.
https://cloud.google.com/run/docs/reference/container-contract

Ideally the frontends need to be stateless and not initiate any computational work.

Also it would be nice if in a container situation the "node" (brain / datastore) server didn't have to run the frontend services.

**Comment by scudette** [comment]
This is interesting and currently contrary to the execution model of Velociraptor. It is unlikely we can support this anyway due to the following restrictions:

```
Your container instance must send a response within the time specified in the request timeout setting after it receives a request, including the container instance startup time. Otherwise the request is ended and a 504 error is returned.
```
This is contrary to the current always connected communication mode - we can fallback to polling but latency will be much worse.

```
Computation is scoped to a request
After startup, you should only expect to be able to do computation within the scope of a request: a container instance does not have any CPU allocated if it is not processing a request.
```

This is contrary to the current design where the frontend runs queries in the background (e.g. in notebooks). In that case the notebook is managed via REST API but the query keeps running in the background for a significant amount of time. 

What benefit does containerisation bring over straight out VMs?

**Comment by predictiple** [comment]
Ah I see. I thought clients were still polling but maintained a connection while flows were happening.

The idea behind containerisation (via Google Cloud Run) would be that the frontend doesn't actually exist when no clients are calling it. So for example a rollout to 10000 machines might have the 1st client on day two, 5000 clients the next day and then more and more as time goes on. GCR then scales by adding container instances based on client demand and defined thresholds. Since with a VR server the CPU load comes mostly from the TLS, GCR handles that part of the scaling problem. That then allows the "backend" VR server to be relatively constant in terms of resource requirements.

**Comment by predictiple** [comment]
And if the backend supported multi-tenancy then a separate GCR frontend array could be provisioned for each tenant, with the costs then scaling per tenant from zero to whatever is needed based on actual demand.

**Comment by scudette** [comment]
Right but Velociraptor has long running tasks like being able to do post processing and run long running queries. so this does not fit into the model. 

Maybe a hybrid model makes sense - separate the frontend from a worker. Frontend just collects the data and the workers run long lived tasks.

**Comment by predictiple** [comment]
FWIW I tested this not long ago and it appeared to work quite well. GCR handled auto-scaling of the frontend CPU resources and Google Cloud SQL handled auto-scaling of the backend storage. Then the backend server was a little VM running a 'dummy' frontend. With all clients stopped the GCR frontend disappears. If a client is talking and it's frontend instance terminates then it calls again and a new instance picks up.

**Comment by scudette** [comment]
Yes it may be possible to move all long running services to this dummy vm model and use flexible frontends in containers to accept client traffic. It looks like the GCP GUI allows to set a timeout of up to 900 sec which is very reasonable so maybe this is fine.

**Comment by scudette** [comment]
With the current master/minion architecture it might be fine to have a master on vm and minion in a scalable container? There are no long term running tasks on the minion which just accepts client connections and stores them to efs.

**Comment by scudette** [comment]
Closing this issue as multi-frontend is live in 0.5.9
