### ISSUE TITLE
Feature request: Additional info on dashboard

### ISSUE THREAD

**Issue by e-kriz** [Velocidex/velociraptor#946]
It would be handy to have some more information on the dashboard, not only Client ID, Hostname, and OS Version, but also last-connected user, domainname (extracted from registry), internal IP address (queried from registry, fe), last connected IP address + port, public IP address.

![image](https://user-images.githubusercontent.com/11965973/109526521-eb935200-7ab2-11eb-8b19-c20996cf57c0.png)

I've made Notebook query which is able to do some of it, but having this information on the dashboard by-default would be handy.

Just a nice to have - keep up the good work! :)

**Comment by scudette** [comment]
This is the search screen not the dashboard (The dashboard is what you get with the Home icon). The dashboard is just an artifact you can modify yourself to include whatever info you want (just edit Server.Monitor.Health).

The search screen can only show metadata we actually keep on each client.  In the case of Velociraptor, we specifically do not have a data model about the client - so we dont index and maintain any of that information internally. This design choice was made to keep the server light and fast. Of course the information can be collected specifically from the client but we dont want to maintain any specific indexes about it (also it changes a lot).

Remember that there could be a lot of clients. 

You can convert your notebook query into an artifact (there is Server.Information.Clients which is similar)  then the user can prepare a report at any time which is a snapshot in time of this information if they need it.
