### ISSUE TITLE
SFTP Upload with write-only permissions

### ISSUE THREAD

**Issue by davidjmaria** [Velocidex/velociraptor#950]
SFTP uploads made with accounts with write-only permissions currently fail due to a ErrSSHFxPermissionDenied exception being thrown when lstat is called. Would you be willing to accept changes to catch that specific exception on lstat for SFTP uploads? My proposed solution would be to catch that error and warn the user that the size of the uploaded file cannot be verified due to the lack of read permissions. This would allow the upload to finish successfully.

**Comment by scudette** [comment]
Yeah sure this seems reasonable
