### ISSUE TITLE
When I try to run make 

### ISSUE THREAD

**Issue by netzeroo** [Velocidex/velociraptor#951]
![image](https://user-images.githubusercontent.com/60299499/110046481-192e0480-7d1a-11eb-8b11-6a6445099949.png)

❯ make
go run make.go -v autoDev
Running target: AutoDev
exec: fileb0x artifacts/b0x.yaml
exec: go get github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6
exec: fileb0x artifacts/b0x.yaml
Error: failed to run "fileb0x artifacts/b0x.yaml: exec: "fileb0x": executable file not found in $PATH"
exit status 1
make: *** [Makefile:2: all] Error 1
![image](https://user-images.githubusercontent.com/60299499/110046468-14695080-7d1a-11eb-90e3-63c4967876f3.png)

Any ideas on how to build it for linux? The npm or make build for React worked.

**Comment by yampelo** [comment]
This issue comes when your GOPATH isn't properly configured, you need to set it so that whatever folder your GOPATH env variable points to contains the fileb0x executable 

https://golang.org/doc/gopath_code#GOPATH

**Comment by scudette** [comment]
Just add ~/go/bin to your path

**Comment by netzeroo** [comment]
Looking into this, thanks for the advice so far.

**Comment by scudette** [comment]
Feel free to reopen if this is still an issue
