### ISSUE TITLE
Refactor globs to return time.Time

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#956]
Currently Velociraptor uses an internal type called TimeVal to pass file times into the VQL query. While TimeVal looks similar to the more standard time.Time it is not exactly the same and can behave differently in different contexts.

We should remove TimeVal in favor of time.Time everywhere. This might change the VQL interface and some artifacts. It will be interesting to do this change in a backwards compatible way.

**Comment by predictiple** [comment]
I wonder if any artifacts are inadvertently doing lexical date comparisons?

**Comment by scudette** [comment]
Fixed by #979
