### ISSUE TITLE
connection error: desc = "transport: authentication handshake failed: x509: certificate is not valid for any names, but wanted to match VelociraptorServer"

### ISSUE THREAD

**Issue by martinvogel21** [Velocidex/velociraptor#962]
I've deployed velociraptor as a docker container.
I'm using self signed certificates and when i try to open the gui i get the following error message in the main frame:
connection error: desc = "transport: authentication handshake failed: x509: certificate is not valid for any names, but wanted to match VelociraptorServer"

Hostname for the System VelociraptorServer
i've changed the name of the pinned_gw_name: from GRPC_GW to velociraptorserver and switched the certificate, but it didn't solve the issue

the log i find the following:
velociraptor    | [INFO] 2021-03-10T10:49:53Z  {"method":"GET","remote":"xx.x.x.x:50558","status":503,"url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:66.0) Gecko/20100101 Firefox/66.0"}
velociraptor    | [INFO] 2021-03-10T10:49:54Z  {"method":"GET","remote":"xx.x.x.x:50232","status":503,"url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}

how do i fix this?

**Comment by scudette** [comment]
How did you create your config file? You should probably never need to change the GRPC_GW pinned name. This is only used for connecting internally between the gui and the api server.

**Comment by martinvogel21** [comment]
the config was created using this call:
./velociraptor config generate > server.config.yaml --merge '{"Frontend":{"public_path":"'$PUBLIC_PATH'", "hostname":"'$VELOX_FRONTEND_HOSTNAME'"},"API":{"bind_address":"'$BIND_ADDRESS'"},"GUI":{"bind_address":"'$BIND_ADDRESS'"},"Monitoring":{"bind_address":"'$BIND_ADDRESS'"},"Logging":{"output_directory":"'$LOG_DIR'","separate_logs_per_component":true},"Client":{"server_urls":["'$VELOX_SERVER_URL'"],"use_self_signed_ssl":true}, "Datastore":{"location":"'$DATASTORE_LOCATION'", "filestore_directory":"'$FILESTORE_DIRECTORY'"}}'

Using these variables:
VELOX_USER=admin
VELOX_PASSWORD=xxx
VELOX_ROLE=administrator
VELOX_SERVER_URL=https://velociraptorserver:8000/
VELOX_FRONTEND_HOSTNAME=velociraptorserver
BIND_ADDRESS="0.0.0.0"
PUBLIC_PATH="public"
LOG_DIR="."
SERVER_URL="https://VelociraptorServer:8000/"
DATASTORE_LOCATION="./"
FILESTORE_DIRECTORY="./"
CLIENT_DIR="/velociraptor/clients"

i've redeployed it and left the GRPC_GW unchanged this time since it didn't help. problem still exists.

**Comment by martinvogel21** [comment]
I see the following in the logs:

tail VelociraptorGUI_info.log
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:46:59Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:04Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:09Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:14Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:19Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:24Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:29Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:34Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:39Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}
{"level":"info","method":"GET","msg":"","remote":"xxx.x.x.xxx:55480","status":503,"time":"2021-03-10T16:47:44Z","url":"/api/v1/GetUserUITraits","user":"admin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}


tail VelociraptorFrontend_info.log
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56268: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:06Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56272: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:11Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56278: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:16Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56282: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:32Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56298: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:32Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56300: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:32Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56306: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:36Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56317: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:41Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56323: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:46Z"}
{"level":"info","msg":"http: TLS handshake error from xxx.x.x.xxx:56327: remote error: tls: unknown certificate\n","time":"2021-03-11T04:37:51Z"}

**Comment by scudette** [comment]
You should probably start from a know working config as created by the
interactive wizard (ie with the -i flag) and then make sure the merged
config looks the same.
