### ISSUE TITLE
Duration time is not correct

### ISSUE THREAD

**Issue by mnrkbys** [Velocidex/velociraptor#966]
I am testing Velociraptor 0.5.6 on Windows.
The Duration time is not calculated correctly if running a collection with a large number of artifacts specified.
For example, sometimes the elapsed time would increase by 200 seconds while the actual duraition time was about 7 seconds.
As a result, the collection cannot be completed (see the figure below).

![image](https://user-images.githubusercontent.com/26597618/110897666-2e6de900-8341-11eb-9a2c-8170aee36ba1.png)

The artifacts I specified are like below.
I have confirmed each artifacts can be successful if I specify one by one.

```
Windows.EventLogs.ExplicitLogon
Windows.EventLogs.Kerbroasting
Windows.Attack.ParentProcess
Windows.Detection.Mutants
Windows.EventLogs.Modifications
Windows.EventLogs.ScheduledTasks
Windows.EventLogs.ServiceCreationComspec
Windows.EventLogs.Symantec
Windows.Forensics.Bam
Windows.Forensics.CertUtil
Windows.Forensics.Lnk
Windows.Forensics.Prefetch
Windows.Forensics.RecentApps
Windows.Forensics.RecycleBin
Windows.Forensics.SRUM
Windows.Forensics.Timeline
Windows.Forensics.Usn
Windows.Network.ListeningPorts
Windows.Network.NetstatEnriched
Windows.Persistence.PermanentWMIEvents
Windows.Persistence.Debug
Windows.Persistence.PowershellRegistry
Windows.Persistence.Wow64cpu
Windows.Registry.AppCompatCache
Windows.Registry.EnableUnsafeClientMailRules
Windows.Registry.EnabledMacro
Windows.Registry.MountPoints2
Windows.Registry.Sysinternals.Eulacheck
Windows.Registry.UserAssist
Windows.Sys.AppcompatShims
Windows.Sys.FirewallRules
Windows.Sys.Interfaces
Windows.Sys.Programs
Windows.Sys.StartupItems
Windows.Sys.Users
Windows.Sysinternals.Autoruns
Windows.System.Amcache
Windows.System.DLLs
Windows.System.Handles
Windows.System.Pslist
Windows.System.SVCHost
Windows.System.Services
Windows.System.TaskScheduler
Windows.System.UntrustedBinaries
Windows.System.VAD
```

**Comment by scudette** [comment]
When you collect multiple artifacts in the same collection, the Duration applies for the entire collection while the timeout applies to each collection separately. This is why you can have a duration that exceeds the timeout.

Duration is calculated when an error or success is sent (at end of each artifact request)
https://github.com/Velocidex/velociraptor/blob/2ad3c76ca4149e41a23bb3e1895389a082336331/responder/responder.go#L129

Deadline is set for each query collected (essentially each artifact)
https://github.com/Velocidex/velociraptor/blob/2ad3c76ca4149e41a23bb3e1895389a082336331/actions/vql.go#L94

**Comment by scudette** [comment]
The new release clarfies it a bit better 
![image](https://user-images.githubusercontent.com/3856546/111108523-ca4b5f00-85a4-11eb-81ad-e76273f10b02.png)

**Comment by mnrkbys** [comment]
Thanks for your reply and the update.
