### ISSUE TITLE
Be able to filter columns from * column specifier

### ISSUE THREAD

**Issue by scudette** [Velocidex/velociraptor#969]
Currently we can do something like

```sql
Select * from ...
```

But if we wanted all the columns except one we have to add them all in explicitly.

It would be nice to be able to remove some columns. Some syntax suggestions

```sql
Select *, $ as Foo from ...

Select * from column_filter(query={ select * from ... }, exclude="Foo")
```

**Comment by predictiple** [comment]
Maybe something like the Logstash prune filter?
https://www.elastic.co/guide/en/logstash/current/plugins-filters-prune.html

So perhaps `SELECT prune(whitelist=["some-regex", "^key"], blacklist="annoying-fieldX") FROM ...`

The Logstash prune filter's "blacklist_value" / "whitelist_value" doesn't need to be implemented because Veloci has the WHERE clause.

**Comment by mgreen27** [comment]
im a fan of the Splunk fields command. 
e.g:
 ```SELECT * - Field1, Field2 FROM ...```
```SELECT Field* FROM ...```
```SELECT * - Field* FROM ...```
https://docs.splunk.com/Documentation/SCS/current/SearchReference/FieldsCommandExamples

**Comment by scudette** [comment]
Implemented column_filter() plugin in head. I would rather not make this a syntax feature if it can be easily solved with a plugin and not must more complex syntax.

**Comment by predictiple** [comment]
It works well but I still think it would lead to more elegant VQL if it was a function.

```sql
SELECT column_filter(include=["some-regex", "^key"], exclude="annoying-fieldz"), plus, other, fields  FROM plugin()
```
rather than

```sql
SELECT *  FROM column_filter(query= { SELECT * FROM plugin() }, include=["some-regex", "^key", "^plus$", "^other$", "^fields$"], exclude="annoying-fieldz")
```

**Comment by scudette** [comment]
Functions transform one or more values into another single value, so if we had it as you showed, the column_filter() function will produce exactly one column which contains a value (possibly a dict). Also there is no way to pass the entire row into it (you see there is no parameter passed into the function) so there is no way for the function to affect the row itself.

Of course this can be fixed by making special cases in the syntax but I would rather not have special cases or exceptions or the language gets really complicated and hard to reason about. Lets keep the syntax straight forward and simple and put as much functionality as possible into plugins/function as appropriate.

**Comment by scudette** [comment]
This is probably as far as we want to take it - all the original use cases are solved with column_filter().
