### ISSUE TITLE
Markup applied to hunt/collection artifact selection

### ISSUE THREAD

**Issue by mgreen27** [Velocidex/velociraptor#97]
I just noticed markup was not applied to hunt artefact selection.

markup is applied to artefact description and reports so seems like this would be a good idea to apply to here too.

![image](https://user-images.githubusercontent.com/13081800/66021428-47326800-e4da-11e9-879d-93378c6bdbb3.png)
![image](https://user-images.githubusercontent.com/13081800/66021488-734de900-e4da-11e9-994f-539ba7d0ec3d.png)

**Comment by scudette** [comment]
Fixed by #99
