### ISSUE TITLE
Shared environment variables not available to systemd client service

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#981]
The client service which runs as root does not have access to shared environment variables defined in /etc/environment. For a general description of the problem see https://serverfault.com/questions/883636/persist-etc-environment-variables-to-non-interactive-user

The problem can be demonstated by running `env` via Bash in the Velociraptor shell screen.

A solution for this is to add the following line into the Service section of /etc/systemd/system/velociraptor_client.service:

`EnvironmentFile=/etc/environment`

I've tested the above with v0.5.7 on Ubuntu 18.04 and it solves the problem.

**Comment by scudette** [comment]
I think this is dangerous - a common way to backdoor a system is to add say ldpreload to the env or any go environment variables (or even proxy env etc). 

What environment variables do you actually need? usually /etc/environment contains path settings, and best practice is to have an empty search path anyway (so execve must use a full path all the time).

**Comment by predictiple** [comment]
It could be dangerous, but not doing so creates a discrepancy from an artifact perpective when running the client as root manually vs. as a service. So using environ() is not going to give consistent result in artifacts.

**Comment by scudette** [comment]
This is what i am trying to get at - environment variables influencing behavior of a program means that it is not hermetic. If there is such a discrepancy it is a problem anyway (perhaps the artifact is not written correctly).  All execve should specify a full path ideally and not depend on path search order.

Running the client manually as root is not a normal way of operating (people do it e.g. to debug the client) so it is not that important. We can consider the service mode the supported mode anyway.

Of course we can always read /etc/environment - what you are proposing is that we use what is set in there to control the operation of the program.

**Comment by predictiple** [comment]
I'm not proposing that VR should start storing and using settings in /etc/environment. :laughing: 

It's about consistency. If my artifact checks and logs an environment variable, I shouldn't have to take into account how the client was run. The system should present itself to VR the same as it would be if a user had logged on to it.

**Comment by predictiple** [comment]
As a concrete example, imagine a company uses a variable "business_unit" on each machine which their login scripts reference and perhaps do stuff like map certain network shares based on it's value. Now imagine that with VR we want to perform certain checks on machines _if_ they are in a specific business unit.

OS | VR run method | Artifact functions to determine env value
--- | --- | ---
Windows | Command line | environ(var="business_unit")
Windows | Service | environ(var="business_unit")
Linux | Command line | environ(var="business_unit")
Linux | Service | from read_file(filenames="/etc/environment")... parse_lines() ... where

**Comment by scudette** [comment]
I guess it's just a trade off here. For the convenience of sharing environment variables you are proposing to weaken the service security. I am not suggesting that attackers maliciously manipulate the environment file (ideally that file has fairly tight permissions). But if the file extends things like path it opens up the attack surface.

Typically high security programs make sure they wipe the environment before starting (perhaps we should even wipe the path environment variable). See this for an example of how it may be abused https://pure.security/how-i-got-root-with-sudo/

If you have a specific requirement to read environment variables you can still do this via the execve plugin or just parse the file via regex.

**Comment by scudette** [comment]
Just to correct your earlier comment, on windows the service and user have different environments stored in different registry hives (see this https://stackoverflow.com/questions/573817/where-are-environment-variables-stored-in-the-windows-registry )

So this is the same issue. If a user set a special env variable you won't be able to see it as system. Additionally, on windows if a user has mounted remote shares the service can not see them either (due to lack of network credentials)

I guess my point is that the running context of velociraptor is going to be different than the user context anyway in many ways. It is just easier and safer to assume the service shares no context (like env variables) and go from there.

**Comment by predictiple** [comment]
Ok, all fair points. It's not causing any problems for me and if it was then there are alternatives. I created an artifact that checked an env var and was surprised that it didn't work when the client was installed. I guess there's not much point to the environ() function then. In command line mode the client should possibly also wipe the path variable to be consistent.
