### ISSUE TITLE
Option to turn off SSL

### ISSUE THREAD

**Issue by recursionbane** [Velocidex/velociraptor#987]
Is there a way to run the velociraptor agent without requiring SSL, e.g., behind firewalls or on air-gapped networks?

**Comment by scudette** [comment]
Yes, you can disable SSL on either the frontend or GUI. Just add the use_plain_http: true to either the GUI or Frontend section in the config file.

https://github.com/Velocidex/velociraptor/blob/master/config/proto/config.proto#L303

Note that you must have some kind of SSL for the GUI but the frontend can be on plain HTTP - there is still another layer of encryption under the TLS to protect communications with the clients (you can not disable that).

These settings are normally used to enable TLS offloading eg with nginx.

**Comment by recursionbane** [comment]
Thanks for the detail!
